### ISSUE TITLE
symbology

### ISSUE THREAD

**Issue by MannusEtten** [perliedman/leaflet-routing-machine#102]
is it possible to change the symbology of the line and the to-from markers?

i would like to make the line a bit transparent and other color
i would like to make the to-marker red and the from-marker green

or can I just remove the geometries?

**Comment by perliedman** [comment]
You can alter the line style by providing the `lineOptions` option when creating the control:

```
var control = L.Routing.control({
        lineOptions: {
            styles: [
                {color: 'black', opacity: 0.3, weight: 11},
                {color: 'white', opacity: 0.9, weight: 9},
                {color: 'red', opacity: 1, weight: 3}
            ]
        },
       [...]
    });
```

You can alter the markers by providing the `createMarker` options, which overrides the default function to create the waypoint markers:

```
var control = L.Routing.control({
        createMarker: function(waypointIndex, waypoint, numberOfWaypoints) {
            [...]
        };
```

(the function should return the marker to use for the waypoint).

Check the API docs, if you haven't already: http://www.liedman.net/leaflet-routing-machine/api/

It lacks info on the `lineOptions`, but has lot of technical detail on other functions in LRM.

**Comment by MannusEtten** [comment]
thanks for your quick reply!
