### ISSUE TITLE
Replace waypoint by leaflet marker

### ISSUE THREAD

**Issue by thomas-fenoul** [perliedman/leaflet-routing-machine#104]
Hello, first of all : congratulations for this great job!

I just would like to know if it's possible to replace waypoint by existing leaflet markers on the map. And if not, just hide waypoints to only keep plan drawing?

Thank you in advance.

**Comment by perliedman** [comment]
Hi and thanks!

If I understand your question correctly, you're looking for the `createMarker` option (see options for [`L.Routing.Plan`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan)).

This will, for example, disable waypoint markers:

```
L.Routing.control({ createMarker: function() { return null; } });
```

**Comment by thomas-fenoul** [comment]
Ho god, just that.. Thank you very much and all the best !

**Comment by rgdamalerio** [comment]
I spend 12hrs to look for this solution. thanks....

**Comment by PhocaCz** [comment]
Hmm, for me it does not solve the problem :-(
For example:
In my map, I have rendered one marker and I want to make a routing for this marker as "End". "Start" will be set by user. This is commonly used, when you just add your address ("END") and user will find the way to your address by typing "START".

a) If I do it standard way - I get two markers on one place - one created by the standard marker (my address), second created by "End" form field in routing form

![Two Markers](https://i.imgur.com/S88Cscl.png)

b) If I add: 
`createMarker: function() { return null; }`

then I don't get any marker in "START" position :-(

![No Marker in Start](https://i.imgur.com/BnZK86w.png)

**Comment by ujangaripin24** [comment]
@perliedman thx man, you help me a lot
