### ISSUE TITLE
Enable draggable route

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#106]
Hi,

I'm just creating my own website with a interactive map, Adding/removing waypoints by "on-map-click" works pretty well but the feature that another waypoint is added by clicking at the route and drag it should be enabled. Regrettably I don't find this option.

Greetings,
Dominik

**Comment by perliedman** [comment]
It should be enabled by default, see the option `addWaypoints`, which is `true` by default, for [`L.Routing.Plan`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan).

Does clicking the route and dragging work in the examples on the LRM site?

One issue with dragging the route is that it's known to not work very well on mobile devices, where the route's line is too narrow to hit with a finger. It's on my todo to find a workaround for this.

**Comment by dominikbruckner** [comment]
yes, unfortunately it works. For clearness look at this png.
![draggableroute](https://cloud.githubusercontent.com/assets/12047646/7269722/7e0f2980-e8d6-11e4-9253-84acc7365300.png)
I want to enable that the route can be spliced and another waypoint is added. The route should be added to my map and no user interaction with the way should be possible

**Comment by perliedman** [comment]
Ah, ok you want to disable it, not enable it.

Try setting `addWaypoints` to `false` then, also `draggableWaypoints` to `false` if you want to prevent the user from modifying the current waypoints.

**Comment by dominikbruckner** [comment]
oh sorry disable^^ yeah super. works exactly how I wanted. Big thanks
