### ISSUE TITLE
Remove panel with waypoints

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#107]
Hi,

I've finished the tutorial and everything worked pretty well. But after a long internet search (API of L.directions.control, too) I haven't found the way to delete the panel at which the exact route (the white one on the right site saying: 1. street left 2. street right... I think you know what I mean ;-) ) I only find: route.options.show=false; [ route=L.routing.control({  });  ] but a little white square still appears.

Thanks in advance,
Dominik

**Comment by perliedman** [comment]
Yes, that's sort of a compromise now. You can hide it, but the user can still show it again by using the white square.

If you want to really hide the control, without giving the user the opportunity to show it, you can add this CSS rule:

```css
.leaflet-control-container .leaflet-routing-container-hide {
    display: none;
}
```

**Comment by jeangarcia2414** [comment]
I have a Div with CSS styles on one side of the map, I want the itinerary to be painted there but I can not find how to do it, I have searched the documentation and I can not find a solution

**Comment by perliedman** [comment]
@jeangarcia2414 this can't be achieved without hacks at the moment. Your best bet is probably to listen for the `routeselected` event and build the itinerary in your `div` from the instructions in the selected route.
