### ISSUE TITLE
L.routing.control for pedestrians

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#108]
Hi,

I used L.routing.control to displace a route from A to B. It works pretty fine but only for cars. I wanted to create a routing application for pedestrians and/or cyclists. Are there any options which edit the used way of transportation?

Thank you very much for your help,
Dominik

**Comment by perliedman** [comment]
Hi Dominik,
this depends on the OSRM backend that is used. By default, OSRM's demo site is used. The default site only supports car routing.

If you need another configuration, it is pretty easy to set up your own OSRM. Check the docs here: https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM
