### ISSUE TITLE
Routing for Pedestrian

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#109]
Sorry, I refer to #108 which was closed. I don't know whether I could post under this issue beacuse it's closed or not. So my request is about graphhopper routing. I tried to build my own OSRM but unfortunately failed :-( So I tried the graphhopper router by router: L.routing.graphhopper(myApi); and it worked. But by default there's car routing, too. Can I easy change the device of transportation (foot or bike) easiely without setting up my own OSRM? Somethint like:
route=L.routing.control({ waypoints , router: L.routing.graphhopper(myApi , BIKE) });

Thank you very much in advance,
Dominik

**Comment by perliedman** [comment]
Yes, try:

```
route=L.routing.control({
    waypoints: waypoints,
    router: L.routing.graphhopper(myApi , {
        urlParameters: {
            vehicle: 'foot'
        }
    })
});
```

I need to document this better.

(BTW, it's fine to comment a closed issue, I'll see it just fine anyway.)

**Comment by dominikbruckner** [comment]
Super. Worked. For all readers:
L.routing.graphHopper() with great H!
Thanks :-)

**Comment by rossanag** [comment]
Hi, I have similar problem. I want to add bike routing. I tryed the code below, but it works once. The next time, a transparent line is rendered insted.

    L.Routing.OSRM = L.Class.extend({
		options: {			
			serviceUrl: 'http://osrm.mapzen.com/bicycle/viaroute',
			timeout: 30 * 1000
		},

It there letf another for changing the code?. Thanks :)

**Comment by perliedman** [comment]
@rossanag no need to make a new class unless you really want to, and you definitely shouldn't reassign `L.Routing.OSRM`.

This should be fine:

```js
var bikeRouter = L.Routing.osrm({
    serviceUrl: 'http://osrm.mapzen.com/bicycle/viaroute'
});
```

Of course, if you want to create a new class for other reasons than just updating the options, that's perfectly fine. Just don't overwrite `L.Routing.OSRM`, that will only complicate things.

**Comment by rossanag** [comment]
Oh my bad, you were right. Thanks so much.

**Comment by dominikbruckner** [comment]
@rossanag : Does it work? I tried your router at my code, too

**Comment by dominikbruckner** [comment]
Does it work? I tried your router at my code, too. My code:

route = L.Routing.control ({ waypoints, router: L.Routing.osrm({serviceURL: like above})  });

but no route is calculated... Do I need additional libraries or a mapzen key?

And by the way, how do I get the script style like perliedman or you?

**Comment by rossanag** [comment]
@dominikbruckner it doesn't work for all cases. Sometimes it renders the line perfectly and in other cases it renders a transparent straight line which pass over the blocks as if they didn't exist. I think it could has to do with the lack of OpenStreetmap information for bike routes for my location.
I didn't search about the reason yet, if I know something, I'll post it here.

Best!

**Comment by perliedman** [comment]
@dominikbruckner note that your code contains a syntax error - you're missing a key for the waypoints. This is probably what you want:

```
route = L.Routing.control ({ waypoints: waypoints, router: L.Routing.osrm({serviceURL: like above}) });
```

You can get GitHub to format/syntax highlight code by starting a block with three backticks (`), check more info here: https://guides.github.com/features/mastering-markdown/

**Comment by rossanag** [comment]
Is there a reason to get a transparent line between 2 points? Althoug it doesn't happen always It from certain paths. However it doesn't happen when I use the car option. I think it could be the lack of information for bike routes.
Thanks!


      var bikeRouter = L.Routing.osrm({
    serviceUrl: 'http://osrm.mapzen.com/bicycle/viaroute'
    });
        routeControl = L.Routing.control({
        router: bikeroute;  
        plan: L.Routing.plan([], {                      
                geocoder: L.Control.Geocoder.nominatim({
                    geocodingQueryParams: { countrycodes: 'uy'}                
                })
                
            }),
        lineOptions: {    
            styles: 
                [
                    {color: 'black', opacity: 0.15, weight: 9}, //sombra
                    {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                    {color: 'red', opacity: 1, weight: 4}] // Centro
       }, 
      
        summaryTemplate:  '<h2>Trayectoria: {name}</h2><h3>Distancia: {distance}</h3>',   
        language: 'sp',        
        routeWhileDragging: true
    }).addTo(mapa);

**Comment by perliedman** [comment]
@rossanag could you provide a screenshot?

LRM uses a grey/transparent line when the returned route does not start/end exactly at the provided waypoints. The transparent line is used to show that this part of the route isn't included in the itinerary, and/or does not necessarily follow any real roads.

You can change this to automatically move the waypoints to the closest locations actually covered by the returned route, by setting the option `waypointMode` to `snap` (`connect` is the default). As usual, check http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control.

**Comment by dominikbruckner** [comment]
@perliedman just forgot that in the post. In my code there is a key.^^
I get the problem. It's exactly the problem you posted. I set 2 waypoints and first no route is calculated but when I drag the startpoint only a few metres it work. I changed the waypointMode to snap but nothing changed:


route = L.Routing.control ({ 
                waypoints: waypoints, 
                router: L.Routing.osrm({serviceURL: like above}),
                waypointMode: 'snap'
             });

**Comment by rossanag** [comment]
@perliedman thanks! that's make the difference, it works now.

**Comment by dominikbruckner** [comment]
By the way: Does anybody know a good router for pedestrian/bicycle for free with an acceptable amount of routings per day (ca 100000)

**Comment by perliedman** [comment]
@dominikbruckner I've set up my own OSRM for exactly that purpose.

It's not entirely free, I pay $5/month for the smallest Digital Ocean cloud server, and run a bike router on it. Works pretty well. There's even a tutortial how to set it up on Digital Ocean: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04

**Comment by dominikbruckner** [comment]
By the way, is it possible setting the route to invisible at all. just watched the style of rossanag and this came to my mind^^

**Comment by dominikbruckner** [comment]
ok stupid question^^ just set all weights to 0.

**Comment by MrVico** [comment]
Is this  the right code to show a pedestrian route on the leaflet map? Because the console tells me that there's a ')' missing, somewhere around the router.

    L.Routing.control({
        waypoints: [
          L.latLng( latCoord , lngCoord),
          L.latLng( latCoord , lngCoord)],
        router: L.routing.graphHopper( /* graphHopper API KEY */ , {
            urlParameters: {
              vehicle: 'foot'
            }
        })
      }).addTo(map);

**Comment by perliedman** [comment]
If you replace the comment about the API key with an actual API key, it looks like proper javascript.

Please note however that this is not the correct place to ask questions about JavaScript syntax.

**Comment by rossanag** [comment]
Hi, me again. I throws me this error: 
GET http://...... net::ERR_NAME_NOT_RESOLVED.
It is important to have bike and pedestrian service to my project. Any idea? Thanks so much.

```
 var bikeRouter = L.Routing.osrm({
serviceUrl: 'http://osrm.mapzen.com/bicycle/viaroute'
});
    routeControl = L.Routing.control({
    router: bikeRouter,
    plan: L.Routing.plan([], {                      
            geocoder: L.Control.Geocoder.nominatim({
                geocodingQueryParams: { countrycodes: 'uy'}                
            })

        }),
    lineOptions: {    
        styles: 
            [
                {color: 'black', opacity: 0.15, weight: 9}, //sombra
                {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                {color: 'red', opacity: 1, weight: 4}] // Centro
   }, 

    summaryTemplate:  '<h2>Trayectoria: {name}</h2><h3>Distancia: {distance}</h3>',   
    language: 'sp',        
    waypointMode: 'snap',
    collapsible:true
}).addTo(mapa);
```

**Comment by perliedman** [comment]
@rossanag https://mapzen.com/blog/osrm-sunset/

**Comment by rossanag** [comment]
Thank you, I've read before about Vahalla, the issue I think is that there isn't a spanish translatio yet.
Is there a way to use it with your plugin? (i.e: instructions translated)
Just in case, I am up to translate that plugin as well.

Thanks

**Comment by perliedman** [comment]
I'm actually not sure how [lrm-valhalla](https://github.com/mapzen/lrm-mapzen/blob/master/src/L.Routing.Mapzen.js) does instructions, but it looks like they've extended the instructions system, which would probably not make it work with LRM's builtin language support.

**Comment by Ramyapriya24** [comment]
How to change the route line color when it is already added to map?
