### ISSUE TITLE
get coordinates of route-elements

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#110]
To be clear I don't mean the waypoints. Short example:
Route between waypoints [0,0] and [100,100] then the route is represented as line elements e.g.
[0,0] -> [0,100] and [0,100] ->[100,100]. how can I get these coordinates. I tried with
route._line._route.coordinates & route._routes[0].coordinates & tried to write my own getCoordatines-function to leaflet-routing-machine. (route=L.Routing.control({...});)
But route._line & route._routes is undefined and there's no get-function implemented in leaflet routing machine. 
Maybe it would be nice to get this coordinates by a simple function.
Greetings,
Dominik

**Comment by perliedman** [comment]
You can do this in several ways, using events are probably easiest and most reliable.

For example, to get the coordinates of a route every time it's selected by the user or returned from the server:

```js
var control = L.Routing.control({...});

control.on('routeselected', function(e) {
    var route = e.route;
    // Do something with the route here
    console.log(route.coordinates);
});
```

You can do similar things with the `routesfound` event if that suits you better, check the available events for [`L.Routing.Control`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control) and [`L.Routing.Itinerary`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary) (which the control inherits from).
