### ISSUE TITLE
Hide or Roll up Routing side panel

### ISSUE THREAD

**Issue by DaveCoventry** [perliedman/leaflet-routing-machine#111]
I'm implementing the routing machine as follows:

```var routeline=L.Routing.control({
  waypoints: [
    L.latLng(51.58712487851482,0.2217864990234375),
    L.latLng(51.58819143910773,0.27294158935546875)
  ]
}).addTo(map);
var routeToggle=1;```

It works great!

However, it's the default and it renders a panel with a set of directions on how to get from one point to the other.

I would imagine it's quite straightforward to toggle the panel off and on so that the map (and the routing line) can be seen.

Many thanks.

**Comment by perliedman** [comment]
Yes. There are `hide` and `show` methods that you can use.

By default, a hidden control will still show as a small button, to make it possible for the user to show the control again. If you really want to hide it altogether, you can add this CSS rule:

```
.leaflet-control-container .leaflet-routing-container-hide {
    display: none;
}
```

**Comment by jeangarcia2414** [comment]
Is there a way to assign or render the itinerary in a div or panel of my preference?
Type google that allows this:
DirectionsDisplay.setPanel (document.getElementById ("directionsPanel"))

**Comment by perliedman** [comment]
@jeangarcia2414 please see my reply in the other issue you posted about this.

**Comment by russelltrafford** [comment]
For anyone else who was curious which other issue @perliedman mentioned above to jeangarcia, its this one here: https://github.com/perliedman/leaflet-routing-machine/issues/107

Unfortunately, there was not a solution. At least it saves others time looking for the post:

> @jeangarcia2414 this can't be achieved without hacks at the moment. Your best bet is probably to listen for the routeselected event and build the itinerary in your div from the instructions in the selected route.

**Comment by nguyenngocho78** [comment]
i want to hide "leaflet-routing-container ", tell me please

**Comment by nguyenngocho78** [comment]
![untitled](https://user-images.githubusercontent.com/34339402/54006938-12ec0880-4192-11e9-8f92-1354129a5e68.png)
