### ISSUE TITLE
Error thrwon when using L.Routing.osrm()

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#112]
Hi, this is the core of a piece of code that calculates the route between 2 points (latlng).
(Simmilar to the former Interactive example).
    

      waypoints.push({latLng: latA});   
        waypoints.push({latLng: latB});   
        
        var routes = null;
        
        routes = L.Routing.osrm({addWaypoints: false});
        console.log("en la func");
        
         routes.route(waypoints, function(err, routes) { // here the error appears
         if (line) {
             mapa.removeLayer(line);
         }

'
I got this error:   Uncaught TypeError: Cannot read property 'allowUTurn' of undefined     

Thanks!

Ro

**Comment by perliedman** [comment]
Are you using the latest version? This sounds like #88, that was closed by 2dd9d778baae30f0ef7f2d535a9d12ee7283a500. It should be fine as long as your version is 2.2.0 or later.

**Comment by rossanag** [comment]
You are right, it isn't the latest version. I am going to update it, in case the error persist I'll post again.
Regards :)

**Comment by perliedman** [comment]
Ok, let's hope that helps. I'll reopen if the problem persists.
