### ISSUE TITLE
zoom while routing

### ISSUE THREAD

**Issue by dominikbruckner** [perliedman/leaflet-routing-machine#119]
By default it seems that after calculating a route the map is zoomed in. I want to disable this feature. At the documentation I found the RoutingOptions "z" but don't know how to use it. I tried
 route = L.Routing.control({
waypoints:waypoints,
routeLine:myLine,
z:15 
});
But (apart from that that the "z" don't work) the current zoom level should be kept
Thanks in advance

**Comment by perliedman** [comment]
Try setting the option `fitSelectedRoutes` to `false`. It defaults to `smart`, which will fit the route if none of the waypoints are in view, or the route covers a very small part of the screen. Setting it to `true` will always fit the view around a new route, setting it to `false` will never automatically adjust the view.
