### ISSUE TITLE
Feature Request: Add geocoders like Photon or Pelias?

### ISSUE THREAD

**Issue by stephan75** [perliedman/leaflet-routing-machine#125]
Hi,
about the geocoder modules: is it possible at all to include (next to Nominatim and the commercial ones) geocoders like Pelias or Photon?

See http://wiki.openstreetmap.org/wiki/Search_engines for more information and maybe documentation about each one's API.

**Comment by perliedman** [comment]
Yes! You can definitely use any geocoder you want.

Photon is already supported by Leaflet Control Geocoder (https://github.com/perliedman/leaflet-control-geocoder/blob/master/Control.Geocoder.js#L813), although it seems I've forgotten to document it. Sorry about that.

If a provider you like is not already implemented in Leaflet Control Geocoder, you just need to make an implementation that follows this interface: https://github.com/perliedman/leaflet-control-geocoder#igeocoder - I'd suggest looking at one of the already implemented geocoders and go from there, it's pretty straight forward. Bonus points if you contribute the implementation back to Leaflet Control Geocoder, of course.
