### ISSUE TITLE
reverseWaypoints option undocumented

### ISSUE THREAD

**Issue by tmcw** [perliedman/leaflet-routing-machine#126]
Looks like this option (a boolean) is included in releases >2.3.0 but isn't documented in the API docs: http://www.liedman.net/leaflet-routing-machine/api/

**Comment by perliedman** [comment]
:+1: Good catch, will add it.

It's for enabling the "reverse waypoints" button in the UI.

**Comment by perliedman** [comment]
Closed by aa582e75ce3cddc43e56d5a27b84e593584444df.
