### ISSUE TITLE
build.sh no longer functional

### ISSUE THREAD

**Issue by tmcw** [perliedman/leaflet-routing-machine#127]
This script looks for two files that no longer exist:

```
~/src/leaflet-routing-machine〉sh ./build.sh
cat: src/pre.js: No such file or directory
cat: src/post.js: No such file or directory
```

**Comment by perliedman** [comment]
Oh, yes - it's a leftover from when the normal build system didn't work on Windows, but I really had to build on Windows.

It should be removed since builds should work properly on Windows now.
