### ISSUE TITLE
Modify marker?

### ISSUE THREAD

**Issue by cristodcgomez** [perliedman/leaflet-routing-machine#13]
Hi, thank you for developing this usefull addon.

I'm trying to change the marker (using awesome markers) but i can't find a proper way to do it. where can I modify the marker?

I think that is needed a documentation (maybe I'll join to improve this plugin)

Greetings

**Comment by kaio328** [comment]
@cristomc what kind of basemap are you using? It looks pretty damn nice!

**Comment by kaio328** [comment]
Hey again!
Is there any example for how to create a seperate marker for every single waypoint?
I tried some stuff like:

 `var Control = L.Routing.control({
waypoints: [
    dStart,
   dGoal
  ],
   createMarker: function(i, waypoints, n){ 
   return L.marker(Start.latLng, {
					draggable: true,
					bounceOnAdd: true,
					bounceOnAddOptions: {duration: 1000, height: 800, function(){(popup.openOn(map))}}, 
					
icon: redMarker}).bindPopup(poppi).openPopup();
	},`

result: no marker...

Would be thankful for any idea or hint!

**Comment by perliedman** [comment]
@kaio328 looks like you're creating all markers at the same latlng (`dStart.latLng`); you should probably use the functions second argument (which should be `waypoint`, not `waypoints`).

**Comment by kaio328** [comment]
ok tried this:
```
var Control = L.Routing.control({
waypoints: [
    dStart,
   dGoal
  ],
   createMarker: function(i, waypoint, n){ 
   return L.marker(waypoint.latLng, {
					draggable: true,
					bounceOnAdd: true,
					bounceOnAddOptions: {duration: 1000, height: 800, function(){(popup.openOn(map))}}, 
					
icon: redMarker}).bindPopup(poppi).openPopup();
	},
```

 Result: unfortunately two markers are displayed. One for dStart and one for dGoal.

**Comment by perliedman** [comment]
@kaio328 yes, `createMarker` is called for _each_ waypoint in the route. You can return `null` for the waypoint you don't want to show.

**Comment by kaio328** [comment]
@perliedman if i get you corret, its not possible to add _iconA_ for _dStart_ and _iconB_ for _dGoal_, is it?

**Comment by perliedman** [comment]
@kaio328 it's perfectly possible. You can make that function return any marker you want, or no marker. But you have to implement the logic.

The function is passed three arguments:

* `i` - the index of the waypoint to create marker for (0 = start)
* `waypoint` - the actual waypoint to create the waypoint for; contains `name` and `latLng`
* `n` - the total number of waypoints in this route; mostly to be able to tell if `i` is the last waypoint

**Comment by kaio328** [comment]
@perliedman big thanks for your advdice and your patience! As a novice im sadly not able to figure out how to implement this. So i stick with one marker.

**Comment by ktjaco** [comment]
@kaio328 

One possible way around this is to use the Glyph plug-in.

https://github.com/Leaflet/Leaflet.Icon.Glyph

```js
createMarker: function(i, wp) {
				
				return L.marker(wp.latLng, {
					
					draggable: true,
					
					icon: L.icon.glyph({
						
						glyph: String.fromCharCode(65 + i)
						
						})
					
				}).addTo(map);
				
			}
```

**Comment by SravanisupriyaBoda** [comment]
How to return null for the second waypoint?
Can any one explain the two way point code?@perliedman
