### ISSUE TITLE
Disable close button in the route plan.

### ISSUE THREAD

**Issue by fhosen** [perliedman/leaflet-routing-machine#133]
Hi!

I would like to know if there is a way to disable the close button of a waypoint, since I don't want to give the user the possibility to change the waypoints. Also, is there a way to lock the text input?

Thanks!

**Comment by perliedman** [comment]
Currently, no. This is an oversight on my part. You can disable adding new waypoints by setting `addWaypoints` to `false` and prevent modification by setting `draggableWaypoints` to `false`, but you can still change text input, and waypoints can still be removed.

One way to this is to set the `createGeocoder` option (see http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan), and create input elements that are disabled, and return no `closeWaypoint` element. Hope this helps!

**Comment by fhosen** [comment]
Thank you for the quick replay.
For now I will just leave it the way it is, if in the future I change it I will let you know.
