### ISSUE TITLE
mutliple routes

### ISSUE THREAD

**Issue by noerw** [perliedman/leaflet-routing-machine#134]
Is it possible to have multiple independent routes displayed (and edited) within one map at once?

I want to load some routes  into the map which are stored within a DB, but currently I'm only able to show a single route by
```javascript
routeCtrl.setWaypoints(...);
```

**Comment by perliedman** [comment]
You can manually insert each route as an alternative to the control, using the `setAlternatives` method: http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary (look at the methods section).

If you don't have the `IRoute` instances, you will have to query each route by using `L.Routing.OSRM` directly first.

If you just want to display the lines on the map, and don't need the itinerary, you can also use the `L.Routing.Line` class directly - it can be used as a normal Leaflet layer, and you can add multiple lines to the same map; again, you might want to use `L.Routing.OSRM` to get the routes and their geometries, if you don't have them already.
