### ISSUE TITLE
CORS header missing using own GraphHopper Server

### ISSUE THREAD

**Issue by maroo672** [perliedman/leaflet-routing-machine#136]
I prepared simple routing web application based on Leaflet and LRM. First, I took API key to use public graphhopper server and it was working fine. Then I downloaded and ran my own graphhopper server and my requests are blocked with Cross-Origin reasons. Public server gives me "Access-Control-Allow-Origin * " header but my own server not.

My own server works fine, it has built-in web-app which also works properly so both can be as standalone application. Moreover, server sends CORS header to this app, but not to my app.

My connection:

control = L.Routing.control({
        waypoints: [],
        routeWhileDragging: true,
        router: L.Routing.graphHopper('' , {
            serviceUrl: 'http://localhost:8989',
            urlParameters: {
                vehicle: 'foot',
            }
    })
    });

What am I doing wrong? Is there any way to ask server to give me proper header in response?

Graphhopper download source: https://graphhopper.com/#community

**Comment by perliedman** [comment]
Hm, actually not sure - I have to confess I haven't actually run my own GraphHopper server. I would say this is a GraphHopper issue (or rather, question, I guess), more than in LRM.

@karussell do you have any input on this? Any special configuration that needs to be done to set `Access-Control-Allow-Origin: *`.

**Comment by karussell** [comment]
Yes, this can be enabled on server side only, although for some old browser you need to enable this on the cliend side too IMO. By default these options are set from the web module:
https://github.com/graphhopper/graphhopper/blob/master/web/src/main/java/com/graphhopper/http/GHServletModule.java#L55

https://github.com/graphhopper/graphhopper/blob/master/web/src/main/java/com/graphhopper/http/CORSFilter.java

BTW: It is not really cross origin if server+client are on localhost (?)

**Comment by maroo672** [comment]
- BTW: It is not really cross origin if server+client are on localhost (?)

Yes, unfortunately it's still cross origin, because of different port number. My app on 'http://localhost:80' and GraphHopper server on 'http://localhost:8989'

Anyway, thank you for your answers. I have to take a look at the server side.

**Comment by karussell** [comment]
And does [this](https://github.com/graphhopper/graphhopper/blob/master/web/src/main/webapp/js/main.js#L58) help?

**Comment by perliedman** [comment]
Thanks for the input, @karussell!

I'm closing this issue, feel free to add more here if there's anything we can do on the LRM side to make this easier, or just info to help others running into the same problem.

**Comment by maroo672** [comment]
@karussell 
I've tried it before and it doesn't help. As I said, LRM with this simple code (which I attached) is working fine with public GraphHopper server, but not with my private. I've just wanted to make sure that there's nothing more to configure on LRM side.

I would like to find some elegant solution for GraphHopper in particular using config file or cmdArgs. I rather don't want to interfere into GH code. 
Now, I am using release 0.4 from March.  https://graphhopper.com/#community
 When could we expect a new release?

**Comment by karussell** [comment]
Hmmh, on public GraphHopper we have an authentication layer in-between so there could be indeed a problem with CORS for the GraphHopper server somehow. What exactly is the error message you get and does LRM do preflight option queries?

What you could do is to clone the repo add the following to the CORSFilter:
```java
rsp.setHeader("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS");
rsp.setHeader("Access-Control-Allow-Headers", "Origin,Accept,X-Requested-With,"
                + "Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers");
```
then do

```
# force recompiling:
./graphhopper.sh clean
./graphhopper.sh web your.pbf
```

> When could we expect a new release?

Why would be a new release fix your problem? I currently do not know what is causing your problem.

**Comment by maroo672** [comment]
> What exactly is the error message you get and does LRM do preflight option queries?

I get standard Firefox error for CORS missing:
```
11:32:14.079 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8989/?point=53.55275090389169,10.003695487976074&point=53.55040527565132,9.978933334350586&instructions=true&type=json&key=&vehicle=foot. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>
```
LRM request configuration in my first post.


> Why would be a new release fix your problem?

I noticed that my private server works in slightly different way than public, e.g. it gives some different headers in response (in communication between GH and DirectionsAPI). 
And the most important - your public server allows CORS to my own App. I supposed you're serving other release which isn't published on your community. So I thought new release could fix this issue, but if you use some additional intermediate layer this is much complicated.

Also, I was a bit confused why nobody noticed before that own webapp cannot cooperate with own GH server because of lack of CORS (I couldn't find any similar issues) so I suspected my fault somewhere.

Anyway, I'm thankful for you advice, I'll try to modify CORSFilter, doFilter method.  :+1:

**Comment by karussell** [comment]
> And the most important - your public server allows CORS to my own App.

Yes, this might be due to the authentication layer

> Anyway, I'm thankful for you advice, I'll try to modify CORSFilter, doFilter method. :+1: 

If this works then this is indeed missing to the GH service, this is something I use for the authentication layer in between and was the only difference I found. Let me know!

**Comment by maroo672** [comment]
@karussell 
Still the same problem.

Your solution adds these headers but still only for built-in DirectionsAPI:
before:
http://s22.postimg.org/a5440uo9t/image.png
after:
http://s23.postimg.org/o6cgtb60b/image.png

In my App CORS is still missing.
after (My App):
http://s24.postimg.org/hst150591/image.png

Also, request from my app to my own server and public server are the same.
request to public server:
http://s10.postimg.org/g1mmgoc89/image.png

**Comment by karussell** [comment]
Could it be that you just missed the 'route' path somehow? Look at 'localhost:8989?...' vs. 'localhost:8989/route?'

**Comment by maroo672** [comment]
OMG, now it's working..
It was my mistake..

There is only one thing to change in code in my connection I've placed in first post:

```
control = L.Routing.control({
waypoints: [],
routeWhileDragging: true,
router: L.Routing.graphHopper('' , {
serviceUrl: 'http://localhost:8989',
urlParameters: {
vehicle: 'foot',
}
})
});
```

to

```
control = L.Routing.control({
waypoints: [],
routeWhileDragging: true,
router: L.Routing.graphHopper('' , {
serviceUrl: http://localhost:8989/route',      // here
urlParameters: {
vehicle: 'foot',
}
})
});
```
So much shame, small problem raised to a big problem.
Thank you for your observation :)

**Comment by karussell** [comment]
No Problem. Probably we need to pass the "Origin:*" header even for other paths (and not found), to avoid the confusing error message. I also always test with curl if something like this happens to investigate headers etc.
