### ISSUE TITLE
add  group of waypoints with a variable

### ISSUE THREAD

**Issue by CodeBeeNiagara** [perliedman/leaflet-routing-machine#137]
Sorry if this is a silly question... I am trying to add waypoints from a variable to a  map. The resulting variable split_route1 is formatted correctly and when I hard-code the waypoints from the console log results, the waypoints render fine. When I try to use the var splitroute1 I get an error: TypeError: t is null (leaflet.js (line 6, col 17396))

    function splitroute(route1){

     split_route1 = '';

     for (x = 0; x < route1.length  ; x++) { 

            split_route1 +='L.latLng(' +      route1[x].ordered_locs.displayLatLng.lat + ',' + route1[x].ordered_locs.displayLatLng.lng + '),'
    }
    console.log(split_route1)
    L.Routing.control({
       waypoints:   [  

          split_route1

    ],
    routeWhileDragging: true
    }).addTo(map2);

     }

**Comment by perliedman** [comment]
Yeah, you can't just write JavaScript into a string like that and expect it to execute. You can do it with the `eval` function, but it's generally not recommended.

Put the `LatLng`s into an array instead, something like:

```javascript
split_route1 = [];
for (var x = 0; x < route1.length; x++) {
    split_route1.push(L.latLng(route1[x].ordered_locs.displayLatLng.lat, route1[x].ordered_locs.displayLatLng.lng));
}
```

Hope this helps!
