### ISSUE TITLE
Leaflet 1.0 compatibility

### ISSUE THREAD

**Issue by moimael** [perliedman/leaflet-routing-machine#138]
Hi,

Have you already tried the leaflet 1.0 beta with leaflet-routing-machine to see if it works ?

If not it would be great to have some compatibility !

Thanks

**Comment by perliedman** [comment]
Yes, see https://github.com/perliedman/leaflet-routing-machine/issues/33#issuecomment-69637739

It's been a while since I tried it, though, so it might be a good time to make sure it still works.

**Comment by perliedman** [comment]
The `leaflet-master` branch is now up to date with the `master` branch, and works with Leaflet 1.0.0-beta-1.
