### ISSUE TITLE
Load the OSRM response manually in the control

### ISSUE THREAD

**Issue by fhosen** [perliedman/leaflet-routing-machine#141]
Hi there!

I wanted to know if there is a way to load in the route control, the information provided by the OSRM service. The reason I want to do this is beacause my app is a carpool and I centralize the geo position of the people in the backend, and I want to send to the client the information returned by OSRM backend (the client is using leaflet-routing-machine). The information I am talking about is the response of the viaroute service.

Thanks!

**Comment by perliedman** [comment]
You can use the control's `setAlternatives` method to directly inject route alternatives. Note however, that the input needs to be an array of [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute)s, not the response directly from OSRM (although they are quite similar).

You can look at how `L.Routing.OSRM` performs the conversion from OSRM response to `IRoute`, if you want: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.OSRM.js#L75
