### ISSUE TITLE
Change the line color

### ISSUE THREAD

**Issue by andrewcarlos** [perliedman/leaflet-routing-machine#142]
Hi. I want to change the color of the route line to green, instead of red, I've looked the Issue #63 and followed your instructions, but I couldn't make it work, and the page you've passed, with the example code, is no longer available, can you help me with this?
Here is my code:
```
var pontos = [];
pontos.push(L.latLng(-18.963658, -49.469389));
pontos.push(L.latLng(-18.974041, -49.463091));
				
var rota = L.Routing.control({
	waypoints: pontos,
	lineOptions: L.Routing.Line({
		styles:[{color: 'black', opacity: 0.15, weight: 9}, {color: 'white', opacity: 0.8, weight: 6}, {color: 'green', opacity: 1, weight: 2}]
		}),
		draggableWaypoints: false,
		show: false
	});
	rota.addTo(map);
```

**Comment by HugoHeneault** [comment]
Hello @andrewcarlos. I'm stuck with the same issue. How did you fixed that? Thanks!

**Comment by HugoHeneault** [comment]
For future people looking for a fast solution, based on @DiegoJohan link in #63 : 

```js
L.Routing.control({
   waypoints: waypoints,
   lineOptions: {
      styles: [{color: 'white', opacity: 1, weight: 5}]
   }
}).addTo(this.map)
```

**Comment by omprabhakaran** [comment]
hello,

how to add multiple points with multiple colors..
