### ISSUE TITLE
IE: map still panning when adding via point

### ISSUE THREAD

**Issue by tyrasd** [perliedman/leaflet-routing-machine#144]
I'm using the latest *leaflet-master* https://github.com/perliedman/leaflet-routing-machine/issues/138#issuecomment-127045060 and see a glitch in Internet Explorer (all versions up to 11): After adding a via-point, the map doesn't stop panning under the mouse cursor, when one actually wants to move the via-marker around. It looks like as if this [`this._map.dragging.disable();`](https://github.com/perliedman/leaflet-routing-machine/commit/07ec6f19f3c65d7d8b2f589bd7f5e590debc2bc1#diff-51c89222756a9e84c6058f5ff5740560R382) doesn't kick in properly in IE.

**Comment by tyrasd** [comment]
seems to be an (already fixed) upstream issue: https://github.com/Leaflet/Leaflet/issues/3666

**Comment by perliedman** [comment]
Sorry for not getting back to you on this, but :+1: that it's already fixed! :)
