### ISSUE TITLE
Use without attaching to a map 

### ISSUE THREAD

**Issue by matbeard** [perliedman/leaflet-routing-machine#145]
Is it possible to use the routing machine without attaching it to a map?

I really just need to get a route summary from A to B (optionally via C), where A, B and C need to be geocoded. I don't need to display the route, just get the total travel time and distance.

I know it's possible to use the Geocoder without a map, but not sure about the routing machine.

Thanks

**Comment by perliedman** [comment]
Yes, you can use the class `L.Routing.OSRM` (or equivalent for the other router backends) directly. It has a `route` method that you need to pass the geocoded waypoints to, and a callback for handling the result; the result will include travel time and distance.

See ['IRouter`](http://www.liedman.net/leaflet-routing-machine/api/#irouter) and [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) API docs.

**Comment by matbeard** [comment]
Thanks, but can you tell me what's wrong with this:

    var waypoints = [
                L.latLng(54.57896, -1.1546),
                L.latLng(53, -1)
            ];
        var router = L.Routing.osrm();
        router.route(waypoints, function(results){
            console.log(results);
        });

As I get an error in leaflet-routing-machine.js saying 'Uncaught TypeError: Cannot read property 'lat' of undefined'

Thanks very much

**Comment by perliedman** [comment]
Yes, the `route` method expects `L.Routing.Waypoint`s as arguments, not `L.LatLng`s.
