### ISSUE TITLE
Route and distance calculation issues.

### ISSUE THREAD

**Issue by SamSalman** [perliedman/leaflet-routing-machine#151]
Hello again,

There seems to be some issues in drawing of routes. Attached are the screen shots of the routes:
![image3](https://cloud.githubusercontent.com/assets/3371099/9565203/f8e0c462-4ec9-11e5-9210-ba42c7d116b9.png)
![image1](https://cloud.githubusercontent.com/assets/3371099/9565205/f8e34f02-4ec9-11e5-962c-1e7fd1c95e0a.png)
![image2](https://cloud.githubusercontent.com/assets/3371099/9565204/f8e1c2e0-4ec9-11e5-9ca0-eb7f5fe04e8e.png)

If you note in one of the screen shot there are multiple lines drawn between two points. Besides in other two screenshots, routes took a wrong path and/or moved around a roundabout although there is no coordinates point there.

Distance is also calculated pretty much extra as compare to original distance due to drawing of extra routes.

Thank you in advance

**Comment by TheMarex** [comment]
Looks like the marker are placed on the road with the wrong direction. Can you provide an example link to http://map.project-osrm.org ? This does not look like a LRM bug.

**Comment by SamSalman** [comment]
Thanks for the replay.

Following are the links which generates attached routes on the map.

http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=61.1129262,25.9291408&loc=61.1127482,25.9263943&loc=61.0888998,25.8956675&loc=60.963643,25.7066063

http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=60.963643,25.7066063&loc=60.9369417,25.6452787&loc=60.9024502,25.6070535&loc=60.7998808,25.4970348&loc=60.7647237,25.4658422

http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=60.7647237,25.4658422&loc=60.7269937,25.4425682&loc=60.6954983,25.3996458&loc=60.6678622,25.3422447&loc=60.636532,25.2964108


I am not sure if its due to wrong direction, need to check that tomorrow.

**Comment by perliedman** [comment]
I agree with @TheMarex, it's most likely that the waypoints are positioned so that you have to turn around, which means going off the motorway and on it again, in the other direction, in this case.

Anyway - this is most definitely not a LRM bug: the plugin just shows the route calculated by OSRM (although I don't think it's an OSRM bug either).

**Comment by SamSalman** [comment]
@TheMarex and @perliedman : so finally today I got access to the server and found out that there was silly mistake made by my colleague in querying the position information. Specifically speaking, he was querying position records with:  `order by timestamp desc`.  So I just replace it with `order by timestamp asc` and then everything is ok.
