### ISSUE TITLE
Save route to variable for future use

### ISSUE THREAD

**Issue by 9SL9** [perliedman/leaflet-routing-machine#154]
I'd like to save the current route displayed on the map to a variable for future use to avoid have to go back out to the internet each time. Is this possible? Can you provide some example code?

Thanks

**Comment by perliedman** [comment]
Using the [`routeselected`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary) event, you can catch the currently displayed route. The [route](http://www.liedman.net/leaflet-routing-machine/api/#iroute) object contains all the info you need, for example waypoints, the coordinates and the instructions.

At a later point, you can use the `setAlternatives` method on the control, and pass the previously saved route, to show it again.
