### ISSUE TITLE
Set units to miles using Valhalla

### ISSUE THREAD

**Issue by matbeard** [perliedman/leaflet-routing-machine#155]
I can't find a way to set the units to miles when using Valhalla.

I've tried using: 
`formatter: new L.Routing.Valhalla.Formatter({units:'imperial', unitNames: 'mi'})`
as suggested [here](https://github.com/valhalla/lrm-valhalla/issues/27), but I can't get it to work.

Any suggestions? Thanks

**Comment by perliedman** [comment]
Hm, don't know but that line looks a bit weird, I don't think you should override `unitNames` like that. This should be enough, unless you want to change the unit abbreviations:

```
formatter: new L.Routing.Valhalla.Formatter({units:'imperial'})
```

**Comment by hanbyul-here** [comment]
Hi @matbeard , my suggestion was indeed wrong, I am truly sorry about this !!! If it still doesn't work without unitNames parameter, let us know ( on lrm-valhalla repo) please!

**Comment by perliedman** [comment]
Thanks for chiming in, @hanbyul-here!

Closing this for now. let me know if there are any further issues!
