### ISSUE TITLE
Zoom to waypoint

### ISSUE THREAD

**Issue by planemad** [perliedman/leaflet-routing-machine#156]
This is a handy feature currently available on the old [osrm-frontend](http://map.project-osrm.org) to quickly fine tune waypoint locations. 
![untitled](https://cloud.githubusercontent.com/assets/126868/9754918/172cf4a8-56eb-11e5-8410-d6e1f7aabdff.gif)

LRM lacks a method to do this currently.

**Comment by perliedman** [comment]
While not entirely obvious, you can override how the geocoder elements are created, and add new buttons etc.

I should probably write a tutorial on how to do this, but in the meantime, this might serve as an example: https://github.com/perliedman/cykelbanor/blob/gh-pages/src/routing-control.js#L25

This uses the default geocoder, but adds button for setting the location from the user's current location (geolocation). This should be similar to what you want to do: add a button, and do something with the waypoint data when it's clicked.

Does this seem like a way forward for you, @planemad ?

**Comment by perliedman** [comment]
Closing this since there's no new input.
