### ISSUE TITLE
Calculate the route in the browser with JavaScript

### ISSUE THREAD

**Issue by christophercliff** [perliedman/leaflet-routing-machine#159]
Are there any directions APIs that run entirely in the browser. If not, is there any work being done in this area?

Not necessarily an issue with this plugin, feel free to close. Hoping someone can advise.

**Comment by perliedman** [comment]
This does not sound likely, except for very small areas (limited number of roads and start and stopping points). OSRM, which is written in highly optimized C++, takes minutes to prepare even quite small areas, and consumes _very_ large amounts of memory doing so.

It does not sound likely you can download that amount of data to the client, or that the client will have the computing power necessary.

For smaller problems, you might want to look into Dijkstra's algorithm, or maybe A* path finding.

**Comment by christophercliff** [comment]
In case anybody's interested, I did a Djikstra routing implementation in Leaflet. You can view it at https://christophercliff.com/dijkstra/.

**Comment by perliedman** [comment]
@christophercliff awesome! Looks really cool.

Had forgotten about this question, but I did this related project a couple of months ago: https://github.com/perliedman/geojson-path-finder
