### ISSUE TITLE
Routing Does Not Work In IONIC Framework ( Solution)

### ISSUE THREAD

**Issue by garfiaslopez** [perliedman/leaflet-routing-machine#160]
Hi! 
Running in ionic framework Routing does not work on device, i fixed this error modifying just a line, in case you want to add this to the code:

in line: 1851 of leaflet-routing-machine.js 

		options: {
			serviceUrl: 'http://router.project-osrm.org/viaroute',
			timeout: 30 * 1000
		},

this way, the device can read the URL and draw the route, works in web too..

Thanks for this amazing plugin!, :D 
Have a good day...

**Comment by moimael** [comment]
Indeed this is a problem. I also hit this. Firefox OS throw someillegal value error, when inspected in dev tools, the url it tries to contact is ```//router.project-osrm.org/viaroute```

**Comment by perliedman** [comment]
Hi, just specify the `serverUrl` to use whatever protocol you need!

Having said that, I'm considering switching this to always using `https`, since this seems to be a quite common issue. Always using `http` would prevent the plugin from being used on secure pages.

**Comment by moimael** [comment]
By the way there seems to be an issue with OSRM router and https :

https://github.com/Project-OSRM/osrm-frontend-v2/issues/147

**Comment by perliedman** [comment]
Closing this, as it's a matter of setting up `serviceUrl` and/or OSRM fixing their certificate.
