### ISSUE TITLE
Add WP or Changing Route

### ISSUE THREAD

**Issue by Faraz95** [perliedman/leaflet-routing-machine#161]
Hi there,
I've started creating an interactive map using leafletjs and your great plugin RoutingMachine, however I have some difficulties in finding/implementing this feature:
The user need to be able to Add waypoints when the route is clicked; BUT if the user drags and drops the route, instead of adding a new wp, only the route needs to be updated.
I've checked the plugin API options for L.Routing.plan, but didn't find this option available. Can you please guide me if this is something already implemented, or if it's not, how I can add it to my script? Thanks in advanced.

**Comment by perliedman** [comment]
I'm not sure I understand the interactions you want to make here.

When the route is clicked, you want to add a waypoint - isn't this already covered by the plugin? If I click the route [here](http://www.liedman.net/leaflet-routing-machine/), a via point is added where I click it

When the route is dragged, you don't want to add a waypoint, but update the route - what does that mean? The route will not update unless a waypoint is added, or existing waypoints are moved.

**Comment by Faraz95** [comment]
Hi Per,
Actually when the route is clicked, a waypoint is already adding (this feature is already implemented in your plugin); Now I need to have a function to change the default route by drag&drop the route, without adding a new WayPoint (and without increasing the Waypoint Index/length).

Let me clarify: Consider that we have a route from Point A to Point B. Currently when we drag and drop the route (to change the default route between A and B), the plugin adds a new waypoint (labels it as "B", and changes the existing waypoint label from "B" to "C" ---    "A" remains "A"). But what I need is that, when we drag&drop the route, no 3rd waypoint adds to the route. Any idea on how we can implement that?

**Comment by Faraz95** [comment]
Hi again,
I've played more with the plugin and what I've found out now is that I need a new (different) event to be triggered/fired when the route is drag/dropped.

**Comment by perliedman** [comment]
The `L.Routing.Line` class fires an event called `linetouched`, maybe you can hook onto it?

It's still not entirely clear to me what you want to achieve when the line is dragged/dropped, but using that event, you should be able to do whatever you need.

You can attach your own listeners to the line by using the `createLine` option to the control, which gives you full control over how the line is created.

**Comment by perliedman** [comment]
Closing this for now.
