### ISSUE TITLE
Switching to imperial units causes an error

### ISSUE THREAD

**Issue by NickBowmanFindly** [perliedman/leaflet-routing-machine#165]
There error + some stack:

````
Uncaught Error: No value provided for variable {value}
(anonymous function) @ leaflet.js?ver=4.1.8:7
o.Util.template @ leaflet.js?ver=4.1.8:7
d.Routing.Formatter.d.Class.extend.formatDistance @ leaflet.js?ver=4.1.8:20
d.Routing.Itinerary.d.Control.extend._createItineraryContainer @ leaflet.js?ver=4.1.8:20
d.Routing.Itinerary.d.Control.extend._createAlternative @ leaflet.js?ver=4.1.8:20
d.Routing.Itinerary.d.Control.extend.setAlternatives @ leaflet.js?ver=4.1.8:20
````

The code in question:

````javascript
var opts = {
    geocoder: L.Control.Geocoder.nominatim(),
    lineOptions: {addWaypoints: false},
    fitSelectedRoutes: true,
    formatter: new L.Routing.Formatter({units: 'imperial'})
};

router = L.Routing.control(opts).addTo(map);
````

The error happens after the geocoding is complete and before the route is displayed. Removing the formatter option makes the error go away.

I'm using Leaflet v0.7.5 and Leaflet Routing Machine v2.4.0. Any ideas?

**Comment by NickBowmanFindly** [comment]
Found the problem.

https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Formatter.js#L40

````javascript
value: (this._round(d) / 1000, sensitivity)
````
needs to be
````javascript
value: (this._round(d / 1000, sensitivity)
````

**Comment by perliedman** [comment]
Big thanks for the heads up and fix!

While fixing this, I also caught an error with how yards where calculated, that must have been in there since forever.

**Comment by NickBowmanFindly** [comment]
Oh I didn't even look at yards. What was the problem if you don't mind me asking?
