### ISSUE TITLE
Indoor navigation making use of leaflet-routing-machine

### ISSUE THREAD

**Issue by Byronic94** [perliedman/leaflet-routing-machine#168]
now I have a indoor leaflet map,and I want to achieve the feature of indoor navigation, how can I make use of leaflet-routing-machine to complete the task?

**Comment by perliedman** [comment]
You need to set up OSRM, or some other routing engine, with your indoor data. For this to work, you need a way to map "roads" through your indoor map.

I'm not aware of anyone else doing this with OSRM, but I guess it should be possible with some tweaks. You might want to check with the OSRM mailing list to get hints and contact with other people doing the same thing.

I don't think there's something in LRM that can be done to support this, so I'm closing this ticket for now.

**Comment by Byronic94** [comment]
Thanks for your help.
