### ISSUE TITLE
Showing the route using LRM while using OSRM trip service

### ISSUE THREAD

**Issue by vladim1** [perliedman/leaflet-routing-machine#169]
There is a new plugin (service) in OSRM called trip, that solves Traveling Salesman Problem. 
[Documentation](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#service-trip)
The example of the answer:
[Example response](http://router.project-osrm.org/trip?loc=52.51642978796417,13.441085815429688&loc=52.51601193890388,13.448638916015625)
The response is the same as for viaroute service except the fact, that this information is inside array.
How can I use leaflet-routing-machine to show the the route according to the information from the response to the given url?

**Comment by perliedman** [comment]
You should write a new class that implements the [`IRouter`](http://www.liedman.net/leaflet-routing-machine/api/#irouter) interface, that can handle the response from the TSP plugin.

The easiest is probably to extend the class `L.Routing.OSRM` and override the `serviceUrl` option, as well as the [`_routeDone`](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.OSRM.js#L75) method. The latter takes care of parsing the response before calling the route callback.

That's the quick outline, feel free to ask if you have further questions!

**Comment by vladim1** [comment]
I have tried, but I haven't succeeded. I am not reall strong in JS.
This is the part I have changed:
```js
L.Routing.OSRMTrip = L.Routing.OSRM.extend({
        options: {
            serviceUrl: '//router.project-osrm.org/trip',
            timeout: 30 * 1000,
            routingOptions: {}
        },

        _routeDone: function(responseFull, inputWaypoints, callback, context) {

            var responseArray = responseFull.trip;
            var response = responseArray[0];
            ...
          callback.call(context, null, alts);
        }
    });
```
The first question is: where should I store the result?
```js
    L.Routing.osrm = function(options) {
        return new L.Routing.OSRMTrip(options);
    };
   module.exports = L.Routing;
```
I am trying to store new class to L.Routing.OSRMTrip.js
I am getting the error
```
ReferenceError: require is not defined
 var L = require('leaflet'),
```

**Comment by perliedman** [comment]
Yes, you can't use `require` directly from a page. Code using CommonJS features need to be processed with Browserify or similar before being sent to the browser. I don't think you should need it though, if you just load LRM before your code; then you will have all the LRM classes attached to Leaflet's `L` object, under `L.Routing`, and there's no need to require stuff (though it might still be a good idea for future modularization of your code).

Other than that, as long as your `L.Routing.OSRMTrip` class fullfills the [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) interface, you should be all set!

**Comment by vladim1** [comment]
I would like to handle this by myself, but I don't have enough experience in JS to get in done. It would be great if you could leave it as enhancement and create a module for trip service when you have time.
Thanks.

**Comment by danera** [comment]
I've got a preliminary version of this working, will post it later today.

**Comment by perliedman** [comment]
@danera sounds great! Keep us updated.

@vladim1 I'm currently doing Leaflet Routing Machine in my pretty limited free time, so I can't commit to anything, especially when it's not something I use myself. Sorry.

**Comment by vladim1** [comment]
@perliedman 
I understand. And I still really appreciate for your help. This is a great extension.
And I hope @danera will help me to solve the issue with a PR or working snippet.

**Comment by danera** [comment]
This is my attempt, which I load after leaflet-routing-machine.js:
```
L.Routing.OSRMTrip = L.Routing.OSRM.extend({

    _routeDone: function(response, inputWaypoints, callback, context) {
        var coordinates,
            alts,
            actualWaypoints,
            i;

        if (response.trips)
            response = response.trips[0];

        context = context || callback;
        if (response.status !== 0) {
                callback.call(context, {
                        status: response.status,
                        message: response.status_message
                });
                return;
        }
        
        coordinates = this._decodePolyline(response.route_geometry);
        actualWaypoints = this._toWaypoints(inputWaypoints, response.via_points, response.permutation);
        alts = [{
                name: this._createName(response.route_name),
                coordinates: coordinates,
                instructions: response.route_instructions ? this._convertInstructions(response.route_instructions) : [],
                summary: response.route_summary ? this._convertSummary(response.route_summary) : [],
                inputWaypoints: inputWaypoints,
                waypoints: actualWaypoints,
                waypointIndices: this._clampIndices(response.via_indices, coordinates)
        }];
        callback.call(context, null, alts);
    }, 

    _toWaypoints: function(inputWaypoints, vias, permutation) {
        var wps = [],
            i, j;
        for (i = 0; i < permutation.length; i++) {
            for (j = 0; j < inputWaypoints.length; j++) {
                if (permutation[i] == j) {
                    wps.push(L.Routing.waypoint(L.latLng(vias[i]),
                                            inputWaypoints[j].name,
                                            inputWaypoints[j].options));
                }
            }
        }

        return wps;
    },

    buildRouteUrl: function(waypoints, options) {
        var locs = [],
            wp,
            computeInstructions,
            locationKey,
            hint;

        for (var i = 0; i < waypoints.length; i++) {
                wp = waypoints[i];
                locationKey = this._locationKey(wp.latLng);
                locs.push('loc=' + locationKey);

                hint = this._hints.locations[locationKey];
                if (hint) {
                        locs.push('hint=' + hint);
                }

                if (wp.options && wp.options.allowUTurn) {
                        locs.push('u=true');
                }
        }

        computeInstructions = !(options && options.geometryOnly);

        return this.options.serviceUrl + '?' +
                'instructions=' + computeInstructions.toString() + '&' +
                (options.z ? 'z=' + options.z + '&' : '') +
                locs.join('&') +
                (this._hints.checksum !== undefined ? '&checksum=' + this._hints.checksum : '') +
                (options.fileformat ? '&output=' + options.fileformat : '') +
                (options.allowUTurns ? '&uturns=' + options.allowUTurns : '');
    },
});

L.Routing.osrmTrip = function(options) {
    return new L.Routing.OSRMTrip(options);
};
```
Can then be used as follows:
```
var lrm = L.Routing.control({
    router: L.Routing.osrmTrip({
        serviceUrl: 'http://my-server.org/trip',
    })
});
```
The main outstanding issue is the via/waypoints are returned in a different order to how they are submitted, which I fix up locally using response.permutation, but can't see a way of updating the plan and thus the markers when this happens - if you have the waypointMode set to snap, you'll see how they are out of order.

**Comment by perliedman** [comment]
@danera great work, and thanks for sharing it!

To fix the waypoint ordering, you could do something like this:

* Add a listener for `routesfound` on the control
* In the listener, disable the control's `autoRoute` option, to make sure it doesn't make a new routing calculation when the plan changes
* Update the plan's waypoints from the received route, using the plan's `setWaypoints` method
* Enable the `autoRoute` option again (if it was enabled to start with!)

**Comment by vladim1** [comment]
@danera Perfect work, thanks for sharing!!!
I have tested it and it works amazing on my example. Although it works great, if you're going to enhance it, please share!

@perliedman Is it possible to include this class as a module to LRM? I think this is great extension to LRM possibilities.

PS: When there are a lot of markers on the map, it can be confusing to track the route and find start and end points. So I would like to change the markers. Make start point red, end point blue and attach numbers(by order) to the markers (or by changing the icon) and assign popups. Can anybody give me a hint where I can do it?

**Comment by perliedman** [comment]
@vladim1 see the `createMarker` option for [`L.Routing.Plan`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan).

An example of it is the map on LRM's homepage: http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan - the code in question is here: https://github.com/perliedman/leaflet-routing-machine/blob/gh-pages/index.js

**Comment by danera** [comment]
@perliedman that seems to work, though the connect lines are still sometimes going to the wrong markers:
```
lrm.on('routesfound', function(result) {
    var plan = lrm.getPlan();
    var wps = result.routes[0].waypoints;
    lrm.options.autoRoute = false;
    plan.setWaypoints(wps);
    lrm.options.autoRoute = true;
}

@vladim1 I'm not using instructions, so haven't looked at these, but am trying to get a gpx out, which seems to be broken in the trip router, so also have the following in above listener:
```
    var router = L.Routing.osrm({ serviceUrl: 'http://my-server.org/viaroute' });
    var vias = wps.slice();
    vias.push(wps[0]);
    var url = router.buildRouteUrl(vias, L.extend({}, lrm.getRouter().options.routingOptions, {fileformat: 'gpx'}));
    console.log(url);
```

**Comment by perliedman** [comment]
@danera hm yes... I think you could try calling `lrm._updateLines()` after setting the waypoints, since they will be out of sync otherwise.

**Comment by martinlierschof** [comment]
@perliedman : is this going to find into lrm at any time? because with the api changes the code wont work anyway. It would be very useful, iam trying to do it if i can manage

**Comment by perliedman** [comment]
@martinlierschof I'd be happy to accept a pull request for this as long as it's unobtrusive and generally solid quality.

Except for maintenance, I'm not actively working on LRM at the moment, but sponsored development is also an option if you don't feel like implementing this yourself. Contact me privately if this is something you want to discuss.

**Comment by lisboeta** [comment]
Any news about this?
I tried the implement this service on OSRM Trip on leaflet, implementation is unsuccessful.

**Comment by perliedman** [comment]
@lisboeta to my knowledge, the situation is still pretty much like I wrote in https://github.com/perliedman/leaflet-routing-machine/issues/169#issuecomment-246258332; fixing this is probably not a huge undertaking, and I would be willing to take it on myself, but _not in my free time_.

I would also still be more than happy to accept a pull request for this, as long as it's solid code. I'll try to be of assistance if this is something you want to pursue.

**Comment by vsrdharca** [comment]
@perliedman Hello - Its been a while and I just came upon this thread.  Just checking to see if LRM L.Routing.osrmv1(<OSRMOptions> options?) supports the OSRM trip service for TSP support?  Much thanks for taking the time to update.

**Comment by perliedman** [comment]
@vsrdharca sorry, no news in this thread. There's currently no built-in support for trips in LRM, so the situation is still pretty much as described in https://github.com/perliedman/leaflet-routing-machine/issues/169#issuecomment-246258332.

**Comment by vsrdharca** [comment]
@perliedman - thank you for your message.  just a quick question.  I am trying to experiment with what danera implemented.  A novice question - why isn't he adding the new extended lrm control to the leaflet map? Is that what lrm.on does? Thanks for the entertaining the question.

**Comment by perliedman** [comment]
@vsrdharca 

1. The code is a control in itself, just the router implementation (the class used to communicate with the OSRM service), you need to provide an instance of this class to the `router` option when creating the control
2. The Mapbox API is backed by OSRM, but use slightly different names and URLs, so you need to base the work on the `L.Routing.Mapbox` class to make it work with their API (note that you have to modify the code above to make it extend the `Mapbox` class instead of `OSRM`)
3. Have not checked, see their API docs: https://www.mapbox.com/api-documentation/#directions

**Comment by vsrdharca** [comment]
Thank you for the message.  In #2, I instantiated the L.Routing.Mapbox
class and get a Bad Request error.  Wondering if the MapBox API url
embedded in the base class has changed?

On Oct 3, 2017 4:39 AM, "Per Liedman" <notifications@github.com> wrote:

@vsrdharca <https://github.com/vsrdharca>

   1. The code is a control in itself, just the router implementation (the
   class used to communicate with the OSRM service), you need to provide an
   instance of this class to the router option when creating the control
   2. The Mapbox API is backed by OSRM, but use slightly different names
   and URLs, so you need to base the work on the L.Routing.Mapbox class to
   make it work with their API (note that you have to modify the code above to
   make it extend the Mapbox class instead of OSRM)
   3. Have not checked, see their API docs: https://www.mapbox.com/api-
   documentation/#directions

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/perliedman/leaflet-routing-machine/issues/169#issuecomment-333816342>,
or mute the thread

**Comment by vsrdharca** [comment]
@perliedman - Thank you for the message.  In #2, I instantiated the L.Routing.Mapbox
class and get a Bad Request error.  Wondering if the MapBox API url
embedded in the base class has changed?

**Comment by curtisy1** [comment]
Reading this thread, I feel like this should be a plugin instead of being included in lrm itself. I'll go ahead and close this for the time being
