### ISSUE TITLE
Save route information 

### ISSUE THREAD

**Issue by cristodcgomez** [perliedman/leaflet-routing-machine#17]
Hi, I'm trying to save the data in a database of the routes that i create.

I'm using at the moment getPlan() to pick all the data of the route, but i have some doubts.
- How can I load this data again in te constructor? I know that I ca store the waypoints and later use it in the initialize, but i don't know if this will give me the same route  all the time
- There is one way to store in de database the planning in JSON and later load this JSON in the constructor?

Maybe there should be a google group forum where to ask this kind of questions, instead using this place.

Thank you in advance! :)

**Comment by tvjmohan** [comment]
Hi eigan,

I would like to know have you solved this . because I too have same requirement. I want to store route related line and points , even after years I need to draw same route as wat it is giving now ... For that I need to store the line related data.

**Comment by perliedman** [comment]
@tvjmohan it's pretty straight forward to store a route as GeoJSON, and you can store that in a database, file or whatever. Displaying GeoJSON on a map later is also very easy.

There's no builtin function for turning a route into GeoJSON in LRM, but I've written several versions of it before.

You can for example use this code, which hasn't been included in the stable version of LRM: https://github.com/perliedman/leaflet-routing-machine/blob/344ff09c8bb94d4e42fa583286d95396d8227c65/src/L.Routing.js

**Comment by tvjmohan** [comment]
Hi,    I have seen the code.    I just want to know how can i get it into javascript variable.  i am not sure which method to cal and what code i have to write (or use from )  in my program.  Please help me.

**Comment by perliedman** [comment]
Depends a bit on your environment, but you could probably get it to work by copying the two functions in that file into your code.

**Comment by tvjmohan** [comment]
Hmmm.   I am using Windows... And simple HTML CSS JavaScript project.

I will try it ...  If I get it OK else ... I  need ur help.

Thank you ..

**Comment by gfoxx29** [comment]
Hi ,
I have a problem. I want to get _route.coordinates_ and _time_ associate to a trip ( time, latLng.lng, latLng.lat ). Actually I just have only coordinates and summary.totalTime informations. Need your help, please.

**Comment by perliedman** [comment]
@gfoxx29 it's not clear to me what you're asking. You say you need the coordinates and time, but also that you "only" have the coordinates and the time.

You can always look at how the itinerary is built (`L.Routing.Itinerary`) for details.

**Comment by gfoxx29** [comment]
Ok, sorry. Actually I  know how to get routes.coordinates. But I want someting like 

time     coordinates
1.37     47.99903 , 3.1699 
1.50      47.99599, 3.17415

time = the time to get location

**Comment by perliedman** [comment]
@gfoxx29 ok, alright! Look at the `instructions` property of the route, it is an array of instructions where each instruction contains time as well as distance for that step. See [docs for `IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) for more details on what info is in there.

**Comment by adustdu2015** [comment]
hi,man ! My project now is about an indoor map route. I have to make a custom route by myself from one room to another room ,but I don't know how to begin making it .please give me some advice.thanks!

**Comment by Narimene29** [comment]
Bonsoir tout le monde, j'ai besoin de votre aide s'il vous plait,
J'aimerais savoir si vous avez résolu ce problème. car moi aussi ça fait presque un mois que je bloque sur ça, je veux stocker la ligne et les points liés à un itinéraire (que j'arrive à tracer) dans une base de données que j'ai déjà crée, Merci.
