### ISSUE TITLE
Make Waypoint not draggable

### ISSUE THREAD

**Issue by joa77** [perliedman/leaflet-routing-machine#172]
I need to lock specific waypoints to a location on the map, but others still need to be draggable

**Comment by perliedman** [comment]
You can do this by providing your own `createMarker` method as an option.

Look at the default implementation of `createMarker`: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Plan.js#L25

Set the `draggable` option in that method according to your needs.
