### ISSUE TITLE
v3.0.0-beta Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by harry-wood** [perliedman/leaflet-routing-machine#174]
Following the basic install instructions but getting the latest 'leaflet-routing-machine-3.0.0-beta.1.zip' download. It fails with the following error reported by chrome:
`Uncaught TypeError: Cannot read property 'extend' of undefined` at `leaflet-routing-machine.js:2161`

(That's just including the file per the instructions, without even trying to do anything)

Working OK when I download 'leaflet-routing-machine-2.5.0.zip' instead

**Comment by perliedman** [comment]
Hm, I can't reproduce this.

Are you sure you've included `leaflet.js` (or `leaflet-src.js`) _before_ you included `leaflet-routing-machine.js`?

**Comment by harry-wood** [comment]
Yep. Leaflet from the CDN as in the examples on the site:

```

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Leaflet Routing Machine Example</title>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <link rel="stylesheet" href="leaflet-routing-machine.css" />
    <style>
        .map {
            position: absolute;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
    <div id="map" class="map"></div>
    <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
    <script src="leaflet-routing-machine.js"></script>
</body>
</html>
```

**Comment by perliedman** [comment]
Yeah, ok. The 3.0.0-beta is _only_ to be used with Leaflet-1.0.0-beta. It will not work with 0.7.3.

You should use Leaflet Routing Machine 2.5.0!

**Comment by harry-wood** [comment]
I know. I figured that out. So this is a documentation issue.

I guess it'll resolve itself when you take v3.0.0 out of beta and update the examples to reference Leaflet-1.0.0
