### ISSUE TITLE
Itinerary positioning

### ISSUE THREAD

**Issue by web2style** [perliedman/leaflet-routing-machine#175]
By default itinerary's position is absolute so if map container height is small, itinerary is not visible - it doesn't affect container height. Any ideas on how to change this behavior to make itinerary stretch container if its height is too small? Any way to move it outside of `.leaflet-control-container` up in the DOM tree?

**Comment by perliedman** [comment]
@web2style hope you found a suitable solution.

I don't think you can force the container to resize based on the size of the itinerary, at least I've never tries that. You might want to use some JavaScript to accomplish that (and don't forget to call `invalidateSize` on your map when it resizes).

At some point I'd like to make it possible/easier to put the itinerary in another DOM element, making it independent of the map `div`, but it's not something I'm working on actively.

**Comment by web2style** [comment]
I've figured out I need to rewrite itinerary from scratch. I asked a question about it in #177.
