### ISSUE TITLE
Remove an itinerary

### ISSUE THREAD

**Issue by marcoamadori** [perliedman/leaflet-routing-machine#176]
Hello, I'm using LRM and it's great!
I have a problem, I'm not able to remove an itinerary when I create a new one.
Every time a create an itinerary from A to B it is added to the map, so I have many itinerary on the same map.
How can I do?

**Comment by LusterKot** [comment]
Id did something like this:
initialize myRoute=null then  create a route and i use "myRoute" to refence the last one. next time if is not Null i just delete the last route this way:
if (myRoute!=null) {
                            myRoute.spliceWaypoints(0, 2);

                        }
//here you can create a new one and you will always have only 1

**Comment by perliedman** [comment]
You shouldn't add a new control to the map to create a new route. The code from @LusterKot is a good start, but you don't need to save the old route to clear it. You can always clear a route like this:

```js
var control = L.Routing.control(...);

...

// Now, clear the current route
control.setWaypoints([]);
```
