### ISSUE TITLE
Can't get my language working

### ISSUE THREAD

**Issue by LusterKot** [perliedman/leaflet-routing-machine#178]
Hi, sorry if I'am reposting but I've checked every issue about changing the language, and I'm feeling reallly dumb becasue I can't get it work to use the directions with my language

still getting english directions:

myRoute=L.Routing.control({
                              waypoints: [
                                  L.latLng(myCrd.latitude, myCrd.longitude),
                                  L.latLng(selectedLocation)
                              ],
                              routeWhileDragging: false,
                              createMarker: function() { return null; },
                              router: L.Routing.graphHopper(myToken),
                              language:"sp"
                          }).addTo(map);

**Comment by perliedman** [comment]
That is weird.

Check this example: http://jsfiddle.net/drrnwwa8/14/

If you ignore the missing styling, you can see that is indeed using spanish as language, with code which is very similar to yours.

**Comment by LusterKot** [comment]
Well that's really weird, In a sepparated way it does so, I'll check out my code. But anyways in any case this option should work. 
Thanks

**Comment by rossanag** [comment]
I have a similar problem, sometimes it works and sometimes it doesn't. I put the language option inside the L.Routing.Plan and it seemed to work for a while. After a few testing attemps the english version come again. I began to have this issue after the upgrade.
I have no clue what is happening.
Thanks
