### ISSUE TITLE
Is something broken?

### ISSUE THREAD

**Issue by Yannick86** [perliedman/leaflet-routing-machine#179]
For some reason I keep getting JS error "invalid character" for every sample on http://www.liedman.net/leaflet-routing-machine/#getting-started

I've come to check this because in my application I get the same error since today. My application is still in a test phase at the moment and I haven't touched it for 2 weeks ...

I've tried the samples on IE & Chrome on 2 different PC's .. same problem persists.

Anyone got a clue what is going on?

Kind regards,
Yannick

**Comment by Yannick86** [comment]
So the default backend is OSRM ... and OSRM seems to be down ... http://map.project-osrm.org/
Does this happen often? Which alternative is advised? 

Kind regards.

**Comment by Yannick86** [comment]
Now http://map.project-osrm.org/ seems to work again, but the samples ( + my own code ) still do not work.

**Comment by FacundoPomar** [comment]
Hi, we have the same problem since today. Do you found any solution to fix the problem ? Maybe some hack :D

**Comment by NestorJavierLopez** [comment]
I have this error today:

Uncaught SyntaxError: Unexpected token 
(anonymous function)	@	leaflet-routing-machine.js:1895
(anonymous function)	@	leaflet.js:6
loaded	@	leaflet-routing-machine.js:46

What happen?

**Comment by berendberendsen** [comment]
Same problem here

**Comment by jofremarianoh** [comment]
I have the same problem since saturday by the afternoon. Is there any solution?

**Comment by perliedman** [comment]
There seems to be some problem with OSRM's server at the moment. I'm getting HTTP 503 and missing `Access-Control-Allow-Origin` headers at the moment, which probably explains the problem you're seeing.

Ideally, at least the demos should handle this more gracefully, though.

I will investigate and get back to you.

**Comment by berendberendsen** [comment]
it looks like OSRM will fix it on their side: https://github.com/Project-OSRM/osrm-frontend-v2/issues/150

**Comment by perliedman** [comment]
Also reported here: https://github.com/Project-OSRM/osrm-backend/issues/1815

**Comment by danpat** [comment]
This should be fixed, a change to the way we were storing street names meant that NULL chars were leaking into the JSON, breaking things.  The fix is in `develop` and has been deployed.  Should be good now.

**Comment by perliedman** [comment]
@danpat thanks for notifying and thanks to the team for a quick fix!

**Comment by rossanag** [comment]
Suddenly I began to have this error (it was working fine until yesterday) :  No route is rendered, even it seems to find the nearest point. I didn't change anything in the code, so I am very clueless about it. I appreciate any workaround. Thanks!

*XMLHttpRequest cannot load http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=-34.9137178,-56.1606047&loc=-34.91815,-56.16685. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.
controlrouting.js:226 Object {status: -1, message: "HTTP request failed: [object XMLHttpRequestProgressEvent]"}*

    routeControl = L.Routing.control({
         
            plan: L.Routing.plan([], {                      
                geocoder: L.Control.Geocoder.nominatim({
                geocodingQueryParams: { countrycodes: 'uy'}                
              }),               
              reverseWaypoints: true,         
              language: 'sp'                                      
            }),
        lineOptions: {    
            styles: 
                [
                    {color: 'black', opacity: 0.15, weight: 9}, //sombra
                    {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                    {color: 'red', opacity: 1, weight: 4}] // Centro
       },           
       summaryTemplate:  '<h2>Trayectoria: {name}</h2><h3>Distancia: {distance}</h3>',           
       language: 'sp',
        routeWhileDragging: true,        
        waypointMode:  'snap'
    }).addTo(mapa);

**Comment by rossanag** [comment]
Well again facing the same problem. I am working with leaflet routing machine version 2.6.2.
I don't know if OSRM server is down again. The error I got is:

_XMLHttpRequest cannot load https://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=-34.9137181,-56.160451099999996&loc=-34.913736705537715,-56.1615514755249. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bicimap.uy' is therefore not allowed access.
controlrouting.js:1 Objectmessage: "HTTP request failed: [object XMLHttpRequestProgressEvent]"status: -1__proto__: Object_

This is the code, it finds the route between 2 points without displaying the control. 

```
function rutaAB(latA, latB)  // it doesn't use the control
{
    var waypoints = [];
    var coords = [];
    var waysp = [];
 
   waypoints.length = 0;

    if ((latA != null) && (latB != null))     
 
    {     
            
        var latlngA = L.Routing.waypoint(latA);
        var latlngB = L.Routing.waypoint(latB);
 
        waypoints.push(latlngA);   
        waypoints.push(latlngB);   
        
        var routes = null;
        
        routes = L.Routing.osrm({addWaypoints: false});
                
        routes.route(waypoints, function(err, routes) {
             if (line) {
                 mapa.removeLayer(line);
             }
             
             if (err) {
                 console.log(err);                 
             } 
             else {        

                 coords = routes[0].coordinates;
                 waysp = routes[0].waypoints;                 
                 line = L.Routing.line(routes[0],{styles:[{color: 'black', opacity: 0.15, weight: 7}, {color: 'white', opacity: 0.8, weight: 4}, {color: '#1652F4', opacity: 1, weight: 3}]}).addTo(mapa);
                                                           
                 var distanciaCerc = convertirKM(routes[0].summary.totalDistance);
                 popup = L.popup({offset: L.point(0, -30)})
                        .setLatLng(latB)
                        .setContent('<p>Distancia: <b>' + distanciaCerc + '</b></p>')                    
                        .openOn(mapa);
                                                                 
             }
       });

    } 
    else
    {
        alert("Se necesita el par Origen-Destino para calcular la ruta");   
        
    }   
     
}

**Comment by danpat** [comment]
@rosannag sometimes the OSRM demo server goes down, when this happens, you will see the error message you pasted.

Also, you are using an outdated version of LRM, the OSRM server API has changed and the `/viaroute` endpoint is deprecated.  New versions of LRM will hit the new API, you should upgrade.

**Comment by rossanag** [comment]
@danpat thank you for your response. I will update to a newer version and very likely I will use Mapzen instead of OSRM
