### ISSUE TITLE
Logging of caught underlying errors

### ISSUE THREAD

**Issue by jekuno** [perliedman/leaflet-routing-machine#181]
The problem: On my production system the routing control element didn't show any content in the UI. Also the log didn't show any errors.

Finally I found out that this was caused by an underlying leaflet error ("Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually." as described in https://github.com/Leaflet/Leaflet/issues/766).

This error got caught internally by https://github.com/perliedman/leaflet-routing-machine/blob/cbc4740113155da1a2d53d633e42936c4667d55e/dist/leaflet-routing-machine.js#L1978 and was returned with a `routingerror` event.

It would be good if such errors would be logged to the console (`console.error(errorMessage);`) . Otherwise you have no chance of discovering these errors without registering for the `routingerror` event.

**Comment by perliedman** [comment]
Thanks for the suggestion! I've added the option `defaultErrorHandler`, which, if defined, will add console logging. The default is to do `console.error` like you suggest.

**Comment by jekuno** [comment]
Very nice. Thanks!
