### ISSUE TITLE
An easy way to add query parameter to routing API request

### ISSUE THREAD

**Issue by web2style** [perliedman/leaflet-routing-machine#182]
Is there an easy way to add `&compression=false` query parameter to API request without creating a custom plugin?

**Comment by perliedman** [comment]
Are you using OSRM (the default) for routing?

The rest of the plugin will not work if compression is disabled, since it assumes the geometry is compressed, so disabling it will not work at the moment.

**Comment by web2style** [comment]
Thank you for the quick reply. I'm using geofabrik routing service. They use OSRM but with old precision of 5 not to break compatibility for existing customers. I have to change precision to 5 here: https://github.com/perliedman/leaflet-routing-machine/blob/cbc4740113155da1a2d53d633e42936c4667d55e/src/L.Routing.OSRM.js#L145

Will you accept a PR if I add it as an option?

**Comment by perliedman** [comment]
Ok! Didn't know there were OSRM instances with other precision.

A PR with a new option, defaulting to the current precision, sounds great!

**Comment by web2style** [comment]
@perliedman So, will you accept #183? The plugin doesn't work for me without this option, so it would be great to have it here.
