### ISSUE TITLE
Example maps don't work

### ISSUE THREAD

**Issue by web2style** [perliedman/leaflet-routing-machine#184]
They return "Routing error. The route could not be calculated. Found route between points". What does it mean?

**Comment by perliedman** [comment]
Yes, noticed this as well.

Apparently OSRM decided to switch status codes: https://github.com/Project-OSRM/osrm-backend/commit/78ac3cffde39d5b3003c5efadd033f744fc5c512

Before, status `0` meant "OK", now `200` means ok. Unfortunately, this breaks Leaflet Routing Machine.

I will try to provide a fix shortly.

**Comment by perliedman** [comment]
I've released version 2.6.1 that contains a fix for this.

**Comment by jekuno** [comment]
Thanks for this. Your fix works. However I do not see a new version 2.6.1?!

**Comment by perliedman** [comment]
@jekuno yes, sorry about that, I was a bit quick.

I've published a release now!

**Comment by jekuno** [comment]
:+1:
