### ISSUE TITLE
addWaypoints

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#186]
Hi, when I set this propery to false I can't use the control because the two imput got disabled.
What I want to achive is not to allow to add more a new waypoint than the origin and the destiny.
Thanks!

**Comment by perliedman** [comment]
Yes, this is how it's currently implemented, although I agree it's a bit unintuitive. `addWaypoints` works more like "editable waypoints" in practice.

You can create a workaround by submitting your own `createGeocoder` option; look at how it's currently implemented: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.GeocoderElement.js#L22

**Comment by rossanag** [comment]
Thanks! I will extend the class to do it.
Best!
