### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by yantakus** [perliedman/leaflet-routing-machine#189]
For example, there's nothing about precision option of the `formatDistance` method, although it exists. I accidentally found it while looking through the source code and was very surprised, because I had searched for it in the docs before (and hadn't find one).

**Comment by perliedman** [comment]
PRs for stuff like this (and most other things) are welcome!

**Comment by web2style** [comment]
I didn't find the docs' source files in the repo. How can I create a PR for docs?

**Comment by perliedman** [comment]
Alright! The docs are, like in many Github projects, in the [gh-pages branch](https://github.com/perliedman/leaflet-routing-machine/tree/gh-pages), which are then automatically served as the project's website.

**Comment by curtisy1** [comment]
This should hopefully be fixed in the [new docs](https://www.liedman.net/leaflet-routing-machine/docs/) for v4 (not yet released). If not, please feel free to get back to me, so I can re-open it
