### ISSUE TITLE
L.Routing.Plan needs to extend L.Layer rather than L.Class

### ISSUE THREAD

**Issue by AlanBell** [perliedman/leaflet-routing-machine#191]
line 2244
        L.Routing.Plan = L.Layer.extend({
rather than
        L.Routing.Plan = L.Class.extend({

this lets it work with the next version of Leaflet, 1.0 right now it doesn't work with the beta because of this.

**Comment by perliedman** [comment]
See the [develop branch](https://github.com/perliedman/leaflet-routing-machine/tree/develop), which contains this fix, among other things.

You can also use the 3.0.0-beta.1 version which works with the Leaflet's 1.0.0 beta versions.
