### ISSUE TITLE
HTTP request failed: [object XMLHttpRequestProgressEvent]

### ISSUE THREAD

**Issue by BrandoIsNotASword** [perliedman/leaflet-routing-machine#193]
I think that the library has stopped doing the request correctly. Or maybe OSRM has changed something.  While I was working I realize an error on the console when I tried to create a route.

XMLHttpRequest cannot load http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=21.132310280223912,-86.84739254415035&loc=21.133591212401726,-86.84357307851315. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 503.

Also, if you check the main page the error also appears there!

**Comment by rossanag** [comment]
Yesterday I reported the same issue in the close thread: https://github.com/perliedman/leaflet-routing-machine/issues/179. Hope they fix this soon. I wish I could help.

**Comment by DiegoJohan** [comment]
I have the same problem, when i draw route it works fine some times and some times not work, i hope it fix this soon too, otherwise i will must search other plugin.

**Comment by cliffchew84** [comment]
Hi, the same thing is happening to my test page, although it was working when I first wrote it a couple of days ago.

**Comment by perliedman** [comment]
There seems to be some issue with the OSRM demo server which prevents Leaflet Routing Machine from working. Will investigate, but I doubt there's anything that can be done on the plugin side.

The missing `Access-Control-Allow-Origin` header means the plugin can't load any data from OSRM's server, because of browser JavaScript security rules; OSRM's server must include this header.

**Comment by perliedman** [comment]
Looking at the actual response from OSRM's server, it says:

`503 Service Unavailable: Back-end server is at capacity`

Not much the plugin can do about this!

**Comment by perliedman** [comment]
For reference, this issue on osrm-backend is the problem: https://github.com/Project-OSRM/osrm-backend/issues/1873
