### ISSUE TITLE
Get the Distance between the StartPoint and the first reached point

### ISSUE THREAD

**Issue by adam21** [perliedman/leaflet-routing-machine#196]
Hello everybody,

I have created a Routing.control with 4 waypoints (StartPoint, B, C, EndPoint) 
Is there a clean method to get time and distance from : 

1- StartPoint to B 
2 - B to C
3- C to EndPoint 

Thank you

**Comment by perliedman** [comment]
That requires some work, there's nothing in the API to calculate this.

You can iterate over the route's `instructions` and find `WaypointReached` instructions. Summing earlier instructions time and distance will give you the information you need.
