### ISSUE TITLE
NO EXAMPLE IS WORKING 

### ISSUE THREAD

**Issue by tvjmohan** [perliedman/leaflet-routing-machine#199]
I am working on leaflet maps.  So far i have done all markings and animations. But i am not able to implement the routing machine on my web page. 

i can see there are no copy of download examples also not working.  i can see blank page. 

is this my side or server side.

If you see on main page. http://www.liedman.net/leaflet-routing-machine/

routing is working fine. But why it is not working from examples.

**Comment by perliedman** [comment]
A quite common problem is that you just open the example as a file in the browser. With this technique, using a `file://` URL, it will not work.

You need to serve the file from a web server. If you just need it for debugging, there's for example the NPM package `http-server` which is handy to use from the command line, no configuration at all needed.

**Comment by tvjmohan** [comment]
Happy day,

Thank you for replying.

You mean we have to copy the example into web server and open the page.   ?

Similarly if we are building our own example with leaflet and leaflet
routing machine is and CSS files., we have to test it through the server
only not as a normal   file://  . ?

Let me try.

**Comment by perliedman** [comment]
Yes, exactly.

However, copying things to a web server, which might be another machine, can be tedious. So I recommend looking into running a local web server like [http-server](https://github.com/indexzero/http-server) or [SimpleHTTPServer](http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python).

**Comment by perliedman** [comment]
I've release 2.6.2 which now by default uses HTTPS, which probably solves your problem even without a local HTTP server.

**Comment by tvjmohan** [comment]
Thank you so much.   And sorry for delay in replying back.   Our
application is working fine after placing it in server.

You can close this ticket.
