### ISSUE TITLE
Is it possible to render Routing Machine in Meteor ?

### ISSUE THREAD

**Issue by braamin** [perliedman/leaflet-routing-machine#200]
Hello,

I've add the package for routing machine in my meteor project but I've got some issues to render it.

Indeed, in local I use "L.Routing.control" and then I've a layer with the routing but on meteor it's seems to not calculate or show it : 
<img width="1438" alt="capture d ecran 2016-01-26 a 11 10 09" src="https://cloud.githubusercontent.com/assets/16196776/12577851/6879687e-c41d-11e5-96cb-fadb8d35ca7e.png">

Do you know where is the problem ? Do I have to call routing differently ?

Thank you for answers

**Comment by perliedman** [comment]
Him
unfortunately, I do not have any experience with Meteor. However, from the looks of your screenshot, it looks like the control has been initialized, but the route hasn't been found.

Do you see any error messages in your JavaScript console? Any HTTP requests that indicate an error?

**Comment by braamin** [comment]
Hi, thank you for answer.
That's the problem ! There is no error according to Chrome's inspector and then it seems to work correctly (marker can be dragged everywhere). However as you said the route hasn't been found.

Is there any trick to access to the serviceURL from a server like in meteor ?

**Comment by perliedman** [comment]
Not exactly sure what you mean by "access to the serviceURL", but the option's value is accessible as `control.getRouter().options.serviceUrl`, if that's what you mean.

I think I need to see some code (ideally in jsfiddle or similar) to debug this.

**Comment by rossanag** [comment]
I don't know if it's the case since I can't see your code, but I had similar problems once.  I solved them adding a position atribute to an "extension" of the css file. Maybe changing a z-index could do the trick as well.

**Comment by braamin** [comment]
In saying "access to the serviceURL" I'm asking "Is there any way to check if we have a calculated route after the OSRM's call ?". 

Perliedman what is supposed to be returned by your function ? I don't get how to use it in my javascript file. It's hard to make a jsfiddle with a meteor project 'cause you have to run it in localhost.. do you want me to share you my private github project then you could run it ?

To sum, there is a different syntax to call function and I think here is the problem. I've added the package (https://github.com/ianng/leaflet-routing-machine/) to close the gap but I suppose that there's a problem when I search route in a normal way from meteor. I'm looking for something like this.

It would be interesting to make these route from Meteor.js because nowadays it is an interesting dynamic website technology ! 

I like your work man, and I appreciate how you spend time to solve my problem ! Thank U !

**Comment by braamin** [comment]
Rossanag I wonder what you're talking about in saying "extension" ? Does it represent div where are displayed the directions instructions ? Or does it represent the layer where route is displayed ? 

Because I can't see both of them.. and I'm looking in the "elements inspector".

Do you have other precision for your procedure, which css file are you talking about ?

**Comment by perliedman** [comment]
@braamin There's nothing "returned" from the control, since the control is a UI component. It will calculate the route between waypoints, and let the user edit the waypoints.

If you need to inspect the routes calculated, you can listen for events that the control fires when a route is found, etc.

You should probably look at some of the examples on http://www.liedman.net/leaflet-routing-machine/ to get familiar with how the control works, before integrating with meteor.

I'm closing this, since there's no apparent issue with LRM, but rather a problem integrating it into your project. Feel free to add more info, and I'll consider reopening if this is really a problem in LRM.

**Comment by braamin** [comment]
I agree with you, there is no problem with LRM since I opened this issue.
However I didn't know where ask questions and find answers so I try to contact you. 
Before, I've done the tutorials. 
I'll add solution to my topic if I find one.

Thank you for multiple advice.

Martin BRICARD

**Comment by rossanag** [comment]
Since it has many sense what @perliedman said to you, I will add this comment for claryfing my previous one. By "extension" I meant to make another css file to overwrite/add some control's CSS properties.  When something wasn't displayed in my case, there was a lack of the position property.
