### ISSUE TITLE
HTTP request failed: [object XMLHttpRequestProgressEvent]

### ISSUE THREAD

**Issue by donny08** [perliedman/leaflet-routing-machine#201]
I'm building Phonegap app where i using leaflet-routing-machine plugin(i.e js file) for  drawing route between two points 
This is code:

 var router = L.Routing.osrm(),
        waypoints = [],
        line;
    waypoints.push({
        latLng: L.latLng(37.422005, -122.084095)
    });
    waypoints.push({
        latLng: L.latLng(37.4267, -122.081)
    });

    router.route(waypoints, function(err, routes) {
        if (line) {
            map.removeLayer(line);
        }

        if (err) {
            console.log("error==" + JSON.stringify(err));
        } else {
            routesLayer.clearLayers();
            line = L.Routing.line(routes[0]).addTo(map);
            routesLayer.addLayer(line);
            routesLayer.addTo(map);

        }
    });

This works fine while testing on browser but fails in android phone producing error as HTTP request failed: [object XMLHttpRequestProgressEvent].

**Comment by perliedman** [comment]
Most likely the default `serviceUrl` to contact OSRM fails from PhoneGap. The default is a so called protocol relative URL, which only works if the app is loaded from `http` or `https`.

My advice is to set the `serviceUrl` option explicitly when creating the control, so that it uses `http`.

**Comment by perliedman** [comment]
You can also update to version 2.6.2, which I released just now. It will most likely resolve the issue.

**Comment by donny08** [comment]
Thanks Per Liedman

**Comment by Umar24** [comment]
@donny08  Will you please provide me the demo code of leaflet routing machine(PhoneGap / Ionic App) code. I am stuck, i need help.
