### ISSUE TITLE
step by step route showing frame/div problem

### ISSUE THREAD

**Issue by tvjmohan** [perliedman/leaflet-routing-machine#202]
i have made map with few buttons like  setzoom , showroute,clearroute, reloadmap.

i have a very small issue with step by step route box. when i click on show route i have coded it like 
control = L.Routing.control({
		waypoints: m,
			geocoder: L.Con..................
.......................................
	}).addTo(map1);

	L.Routing.errorControl(control).addTo(map1);  

where m is array of way points.

my issue is when i click first time show route step by step box is coming fine.
if i click cleraroute   (coded as remove control so its going off from map).
when i click show route this time  step by step box is coming slightly down (where its came slightly up first time)   i mean postion is changing.....
![1](https://cloud.githubusercontent.com/assets/414051/12697402/0713ecc4-c7a8-11e5-8ed6-b28c76815883.png)
![2](https://cloud.githubusercontent.com/assets/414051/12697403/0e052318-c7a8-11e5-8a05-a5a9020b6f36.png)
![3](https://cloud.githubusercontent.com/assets/414051/12697404/1174f97e-c7a8-11e5-8b55-9866ca430275.png)

please see the png files ....

**Comment by perliedman** [comment]
Hm, it looks like some element isn't properly removed. Could you check in the DOM inspector what it looks like? I guess some invisible element is left in there, and still takes up space in the layout.

**Comment by tvjmohan** [comment]
Hi,    I have solved the issue,  Thank you.   

i have added new line like **L.Routing.errorControl(control).addTo(map1);**   and above to this i have added   **control = L.Routing.control({ __________________).addTo(map1);**

now i have commented errorControl    line of code.   its working FINE   

but still i want to use that in case of error ? so how to code it.

**Comment by perliedman** [comment]
You need to remove the error control from the map as well. It's a separate control!

**Comment by tvjmohan** [comment]
ok.  Thank you so much .

Regards
Mohan.Thonangi
