### ISSUE TITLE
http status code check wrong in leaflet-master

### ISSUE THREAD

**Issue by chesty** [perliedman/leaflet-routing-machine#203]
https://github.com/perliedman/leaflet-routing-machine/blob/leaflet-master/src/L.Routing.OSRM.js#L82

if (response.status !== 0) {

should be

if (response.status !== 0 && response.status !== 200) {

as it is in master, 200 as in the http status code 200

**Comment by perliedman** [comment]
Yes, the situation is a bit messy. I do new dev that tracks Leaflet's master on the branch [`develop`](https://github.com/perliedman/leaflet-routing-machine/tree/develop) - it's a significant refactor of the current code, but it contains this fix as well.

I should probably just remove the `leaflet-master` branch to avoid confusion.

**Comment by chesty** [comment]
ok cool, I'll switch branches.
it was good experience tracking down the bug anyway.

on a different topic, if you wanted to support osrm /trip api, it returns the same data as /viaroute but some data is under a trips array rather than in the root.

**Comment by perliedman** [comment]
Supporting the trip API sounds like something that could be interesting. Opened #213 for this new feature, thanks!.
