### ISSUE TITLE
Is it possible to hide markers

### ISSUE THREAD

**Issue by zinotinder** [perliedman/leaflet-routing-machine#204]
When route is rendered I don't want to show markers (default blue marker icons) I want to draw only route line. How this can be done? Thanks

**Comment by perliedman** [comment]
See the [`createMarker`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan) option. If you return null, no makers will be added.

```javascript
L.Routing.control({
    [...]
    createMarker: function() { return null; }
}.addTo(map);
```
