### ISSUE TITLE
Install Server

### ISSUE THREAD

**Issue by bado57** [perliedman/leaflet-routing-machine#205]
Hi dear. I search all of leaflet examples. I want to this sample install in my server and I want to use that like restfull api. So I want to take request and get response. How can I do that . Can you help me about this situation. Have nice night.

**Comment by perliedman** [comment]
For the server side, you should look into installing [OSRM](http://project-osrm.org/), the software that Leaflet Routing Machine uses. It comes with an HTTP server and a [server API](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api).

If you need more flexibility, you can build your own REST API with [node-osrm](https://github.com/Project-OSRM/node-osrm/).

Hope this helps!

**Comment by bado57** [comment]
Thank you @perliedman. So, I installing OSRM my own server. And then ıt comes an HTTP server an a server API with Osrm. To make REST API, Im using node-osrm. Node osrm which, 
between my query with server?

**Comment by perliedman** [comment]
You can probably use OSRM directly, without node-osrm. OSRM's API isn't REST strictly speaking, but it's an HTTP API that is not very hard to work with.

If you don't like OSRM's builtin API, you can build your own API with node-osrm, which lets you integrate with OSRM from Node.js.

**Comment by bado57** [comment]
I understand @perliedman . So  Most companies(GrapHooper, Skobbler, Mapbox,Nutiteq) build them and then they also do sales.

**Comment by perliedman** [comment]
Yeah, I'm not familiar with Skobbler or Nutiteq, but Mapbox is the main company behind OSRM these days, and Graphhopper develops Graphhopper, which is a competitor to OSRM.

Leaflet Routing Machine is a user interface that can work with either one of them, and a few more, but uses OSRM as default, since its demo server is really good and can be used with few restrictions to get you started. Graphhopper, which is also very, very nice and high quality software, requires you to sign up for a license key to use it, which means a bit more friction just to get started.

**Comment by bado57** [comment]
Very good explanation @perliedman . I want to find the shortest distance between two points. 
There are locations in the database. So I do not want to view map, Location to get.I did a lot of research for this case.These firms are very expensive APİ. That's why I'm trying to solve this case myself.Set up my own server and than I just threw query with mobile device. Yes Graphhopper very beatifull but very expensive for a license key to use it.  
I do not know if Leaflet Routing Machine solves my business.
Thanks @perliedman everything. 
Best regards

**Comment by perliedman** [comment]
Yes. OSRM is not that complicated to setup, there are pretty good installation instructions.

Be aware though that OSRM uses OpenStreetMap's data, so the results will be as good as their data is. Also, if you need to cover a large geographic area, you need some pretty expensive hardware, or it will be very slow.

Having said that, I'm using OSRM with road data for Sweden without trouble on one of [DigitalOcean](https://www.digitalocean.com/)'s smallest servers, that costs me $5 per month.

**Comment by bado57** [comment]
Its a good idea. I tried to install linux server But I never could. Can you help in setting up the DigitalOcean server.If you want, I can give the charge but This is very important for me.I hope you can understand me.It always puts the resources on installation errors.I tried to install all of the resources on the Internet.
