### ISSUE TITLE
red line between 2 waypoint is not displayed

### ISSUE THREAD

**Issue by samtien** [perliedman/leaflet-routing-machine#206]
I want to show the route between 2 waypoint on the map. but the red line between 2 waypoint is not displayed.
Do you know where is the problem? 

the map is in element DIV (accordion), that show/hide on demand

following is my code:

var map2 = null;
var waypts = [];

// waypts ware initialised on load

function showRouteMap(){
	 if(map2 == null){
		 map2 = L.map("f1");
	 }
	 else   return;
   	
	L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
	}).addTo(map2);
	
	var lPlan = new L.Routing.Plan(waypts, {
		draggableWaypoints: false,
		addWaypoints:  false,
		createMarker: function(i, wp) {
			return L.marker(wp.latLng, {
				icon: new L.Icon({ iconUrl: "./img/redMarker"+i+".png" , iconSize: [20, 34]})
			});
		}
	});
	
	var routeControl = L.Routing.control({
		show: false,
		plan: lPlan 
	}).addTo(map2);
}

**Comment by perliedman** [comment]
That's unfortunately hard to tell.

I would suggest checking your JavaScript console for any error messages, and also check the network traffic to see if any request is actually done to OSRM.

**Comment by samtien** [comment]
Thanks for your reply, perliedman.
There are no error messages in firebug console and I can see the response of OSRM.

**Comment by perliedman** [comment]
Do you see the rest of the map? You mention that you use an accordion, which would likely resize the map. After resizing a Leaflet map, you usually have to call `map.invalidateSize()` to make sure Leaflet is aware of the map containers dimensions.

**Comment by perliedman** [comment]
Closing since there's no more info to debug from.
