### ISSUE TITLE
waypoint latLng is not attached into routeObj._routes[0].coordinate after routesfound event fired

### ISSUE THREAD

**Issue by mitulchauhan1** [perliedman/leaflet-routing-machine#207]
Hello Sir,
In my script i have override a routesfound event,
renderer1[iter].on('routesfound',function(e){

)};
and it fired when i drag a route. i can see a waypoint latLng in e.waypoints array and after when i alert
with renderer1[iter]._routes[0].coordinate. it will not give a latlng of waypoint inside that array.
i need a whole path latLng including a waypoints. how can i achieve this ?
Thank you.

**Comment by perliedman** [comment]
Hi,

variables and methods that begin with `_` are to be considered "private" - you shouldn't rely on them, and it's also why they are not documented in the API. So `_routes` is a private variable that you shouldn't use.

The `routesfound` event includes the routes that are found, so you should use that instead:

```
renderer1[iter].on('routesfound',function(e){
    var firstRoute = e.routes[0];
    console.log(JSON.stringify(firstRoute.coordinates));
)};
```

Hope this helps!

**Comment by mitulchauhan1** [comment]
Thank You sir
