### ISSUE TITLE
About waypoints (problem) and personalisation

### ISSUE THREAD

**Issue by russellhoff** [perliedman/leaflet-routing-machine#209]
I've started using your tool, and it's great!

However, I've several doubts and a problem... 

First off, it would be great that the box of the right could be hidden (through API or by the user). Additionally, I don't know whether the markers added by the plugin can be deleted (or hidden); i.e. that can be manipulated.

Unfortunately, I've found what I consider a bug. I've got an array of L.LatLng, which I want them to add as waypoints. If I add the whole array that way

`waypoints: [
	latlngs
],`

the polyline is not shown. If I add them that way

`waypoints: [
	latlngs[0],
	latlngs[1],
	latlngs[2],
	...
],`

it really works. Is that any bug or am I doing something wrong?

It would be great that the resulting polyline could be obtained and, thus, be manipulated a bit.

Thanks for reading me.

**Comment by russellhoff** [comment]
My error.... In order to add a whole latlng array, i was creating an array of another array. Doing this way solved my error:

`waypoints: latlngs,`

**Comment by russellhoff** [comment]
I've realised that the box can be modified, making markers and polylines not draggable. Now, I'm figuring out how to hide markers...

**Comment by perliedman** [comment]
You should use the `createMarker` option. If you set it to a function that returns `null` or `undefined`, it will not add any markers.

**Comment by russellhoff** [comment]
Could you tell me, please, what am I doing wrong? Markers are still shown:

`
	var plan = L.Routing.plan({
		addWaypoints: false,
		draggableWaypoints: false,
		routeWhileDragging: false,
		createMarker: function(i, wp, er) {
			return null;
		}
	});
	plan.setWaypoints(posiciones);
	
	var controlRouting = L.Routing.control({
		router: null,
		plan: plan,
		routeWhileDragging: false,
		lineOptions: {
			addWaypoints: false
		},
		geocoder: L.Control.Geocoder.nominatim()
	}).addTo(map);
	L.Routing.errorControl(controlRouting).addTo(map);
	`

**Comment by perliedman** [comment]
Hm, that code looks correct. Could you set up a JSFiddle or similar that illustrates the problem?

To get hold of the line, you can use the `routeLine` option for the control. Like `createMarker`, it's a factory function that is called when a line should be created. You can of course store the line or do whatever you need with it in that function.

**Comment by russellhoff** [comment]
I can't 100%... I'm using some data from closed web services, but I can provide the location of my code: https://apache.ingartek.com/wwwzendesk-red-mapapuntos/

**Comment by perliedman** [comment]
I'm pretty sure it's some minor detail, but I'm sorry, I don't have the time to walk through other peoples code.

If you think this is a bug, provide a small. runnable example that illustrates the problem, and I'd be happy to reopen this issue.

**Comment by russellhoff** [comment]
Thanks for your help. I've been able to "manage" and self construct the polyline that way:

`var controlRouting = L.Routing.control({
		//waypoints: posiciones,
		router: null,
		plan: plan,
		routeWhileDragging: false,
		lineOptions: {
			addWaypoints: false
		},
		**routeLine:  function(route, options){
			console.log("routeLine: " + JSON.stringify(route));
			polilineaPuntos = L.polyline(route.coordinates, options);
			return polilineaPuntos;
		},**
		geocoder: L.Control.Geocoder.nominatim()
		
	}).addTo(map);`

I'll keep looking why I can't provide null markers. As a "workaround", I've done the following (adding markers, colleting them and removing from the map):

`var marcadores = controlRouting._plan._markers, unMarker;
	for(var i = 0; i < marcadores.length; i++){
		unMarker = marcadores[i];
		map.removeLayer(unMarker);
	}`
