### ISSUE TITLE
Export to GPX

### ISSUE THREAD

**Issue by glandais** [perliedman/leaflet-routing-machine#210]
May be would be there a better way than this...
Using [togpx](https://github.com/tyrasd/togpx) and [easybutton](https://github.com/CliffCloud/Leaflet.EasyButton)

-> https://github.com/glandais/velorouter/blob/master/js/router.save.js

**Comment by perliedman** [comment]
Currently, no.

I think GPX is a bit specialized for having support being built into LRM. Having said that, I plan to use GeoJSON format for routes in [version 3.0](https://github.com/perliedman/leaflet-routing-machine/issues/187), which would remove some of the work in your example.

**Comment by glandais** [comment]
No prob, just for reference for anyone interested in.
Usage of togpx() will be easier with #187
