### ISSUE TITLE
Docs incorrect

### ISSUE THREAD

**Issue by billystalnaker** [perliedman/leaflet-routing-machine#212]
On your documentation page here :http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary the option name for the Itinerary Builder object is itineraryFormatter, when actual in the code it is itineraryBuilder. At least with the version I have 2.6.2 it is that.

**Comment by curtisy1** [comment]
This will be fixed in the upcoming v4. For a small preview, you can have a look [here](https://www.liedman.net/leaflet-routing-machine/docs/)
