### ISSUE TITLE
Osrm frontend and LRM give different results

### ISSUE THREAD

**Issue by emmexx** [perliedman/leaflet-routing-machine#214]
I'm experiencing an odd behaviour trying to set up a map that uses lrm.

I use a custom osrm server that uses non osm data (italian national cycleways network). Many of the ways are not connected.

I had used in the past the old osrm frontend based on the same routing server.
I try to calculate the path in the 2 systems using (approximately) the same starting and ending points.
osrm frontend shows the correct route, LRM finds a route elsewhere, far away from the correct route.
I checked the call to the server and it is almost identical. I don't understand what's happening.

This is the osrm frontend test: [](http://www.bicitalia.org/routing/) (ways are only along the red lines).
And this is the lrm test page: [](http://www.bicitalia.org/cms/it/?option=com_chronoforms&chronoform=mappaRouting)
The problem is that if I move that markers away from that way I can't position them there and get the right route. Why is that?

 Thank you
  maxx

**Comment by perliedman** [comment]
Hm, looks like your post is missing some screenshots?

I guess the answer lies in the difference between the URLs when calling OSRM - can you provide some examples? Is it just the coordinates that differ, or are other parameters different as well?

**Comment by emmexx** [comment]
Sorry, I entered the links to my test sites but probably used the link tag the wrong way.
http://www.bicitalia.org/yourls/a 
is the map that uses osrm-frontend old version. Use the layerswitcher to view the ways.
http://www.bicitalia.org/cms/it/?option=com_chronoforms&chronoform=mappaRouting is the test page with lrm.
If I move the markers to another way I can't move them on the 1st one again.

When I created the osrm-frontend I was suggested to use always the maximum zoom value. So I did the same for the lrm page.

The only difference in the call is jsonp in osrm-frontend.

**Comment by perliedman** [comment]
The coordinates differ quite significantly in your examples.

If you enter the same coordinates, you get the same result. Try this an compare to your second URL: http://www.bicitalia.org/routing/?hl=it&loc=45.26135,10.12651&loc=45.2266,10.2496&z=7&center=45.471688,9.129639&alt=0&df=0&re=0&ly=588398340

**Comment by emmexx** [comment]
Sorry but the problem is not the coordinates but the fact that I can't find a route on that same way when I define start and ending points by clicking on the map http://www.bicitalia.org/cms/it/?option=com_chronoforms&chronoform=mappaRouting
I modified the position of my waypoints on my test map. Please try to move the markers on the previous position and get a route?

**Comment by perliedman** [comment]
Hm, I fail to understand the problem. In the last link you posted, it appears the start and end is pretty far from the routable network: you can see the grey lines that extend at the start and end from red line; the grey lines are parts of the route not covered by OSRM's network.

By moving around the markers a bit, it seems your OSRM instance only has the large, red roads in its network, which means it will try to "snap" the start and end to the closest known road, which in your case is often quite far. This causes some pretty unintuitive results, where moving the marker just a couple of meters causes the routing to snap to another road kilometers away.

Hope this helps, but this is not an issue with LRM, but rather with your road network combined with how OSRM works.

**Comment by emmexx** [comment]
As I wrote in my OP I'm not using OSM data but the network of italian national cycleways, that is a very small subset of the osm ways. My osrm server knows only about those cycleways (the red lines in the overlay layer.)
My question was: why do I get different results if a set (by clicking on the map) the same starting and ending points in osrm-frontend and in lrm? The call to the routing server should be approximately the same for both of them. So I wonder if something is happening under the hood in osrm-frontend or in lrm.

**Comment by perliedman** [comment]
But as I mentioned in https://github.com/perliedman/leaflet-routing-machine/issues/214#issuecomment-196780680, if I actually _do_ set the coordinates to the same, they both produce the same results.

I can't reproduce this now, since the LRM solution doesn't give me any routes at the moment, but please check again, actually making sure the coords match up to the last digit - even small differences can cause different results, especially when there are so few roads in your network.

**Comment by emmexx** [comment]
I don't know, there's something that is not working right here, not sure what.
First of all, there's no difference between osrm- frontend and lrm. I was comparing 2 different ways of getting a route.
If I start with a blank map, no marker on it, I get a route. But if I start from an existing route I can't get both osrm-frontend and lrm to get a new route on a different way (probably only on disconnected ways). 
The only difference between a blank map and an existing route is that the 2nd sends to osrm server  the **hint** parameter. Probably it is an osrm-backend problem.
Thank you for narrowing this down.

**Comment by emmexx** [comment]
FYI
I commented out 
`locs.push('hint=' + hint);`
in function buildRouteUrl() and now routing works as I expected.
