### ISSUE TITLE
Graphhopper alternative routes

### ISSUE THREAD

**Issue by curiousc0w** [perliedman/leaflet-routing-machine#216]
Hi,

I was wondering why alternative routes for Graphhopper when set to true aren't displayed. This seems to work with OSRM.

```js
var routingEngine = L.Routing.control({
		waypoints: [  ],
		routeWhileDragging: true,
		showAlternatives: true,
		geocoder: L.Control.Geocoder.nominatim(), // Only use nominatim for routing for now
		router: L.Routing.graphHopper('', /*'9fb6dd59-4e36-4dbe-a0cb-71d58a048bd1' (empty string for local GraphHopper),*/ {
			serviceUrl: 'http://172.16.10.38:8989/route'
		})
	});

	routingEngine.addTo(map);

**Comment by perliedman** [comment]
It depends on what the server responds. If it does not return alternatives, no alternatives are shown (of course).

It's been a while since I tested GraphHopper, so things might have changed, but last time I checked, it did not return alternatives, although the API is built to support it.

**Comment by curiousc0w** [comment]
Hmm. Alternative routing seems to be fairly new to Graphhopper.

https://github.com/graphhopper/graphhopper/pull/640

I made a slight addition to ```lrm-graphhopper.js``` to show one alternative route in my Leaflet page.

``` js
return baseUrl + L.Util.getParamString(L.extend({
                                       	instructions: computeInstructions,
                                        type: 'json',
                                        algorithm: 'alternativeroute', // talks to the latest GH api to generate 1 alt. route
                                       	//alternative_route.max_paths: '4',
                                        key: this._apiKey,
                                }, this.options.urlParameters), baseUrl);
```

It doesn't totally fix this but it's a workaround temporary to display an alternate route in a Leaflet page for Graphhopper.

``` js
// Setup routing engine
        var routingEngine = L.Routing.control({
                waypoints: [  ],
                //routeWhileDragging: true,
                //showAlternatives: true,
                draggableWaypoints: true,
                //addWaypoints: false,
                routeWhileDragging: true,
                reverseWaypoints: true,
                useZoomParameter: false,
                showAlternatives: true,
                altLineOptions: {
                                styles: [
                                    {color: 'black', opacity: 0.15, weight: 9},
                                    {color: 'white', opacity: 0.8, weight: 6},
                                    {color: 'blue', opacity: 0.5, weight: 2}
                                ]
                            },
                geocoder: L.Control.Geocoder.nominatim(), // Only use nominatim for routing for now
                router: L.Routing.graphHopper('', /*'api_key' (empty string for local GraphHopper),*/ {
                        serviceUrl: 'http://172.16.10.38:8989/route'
                }),
        });

	routingEngine.addTo(map);
```

**Comment by perliedman** [comment]
Ok!

If it requires new URL parameters in the request to GraphHopper, some addition to [lrm-graphhopper](https://github.com/perliedman/lrm-graphhopper) would be nice. A pull request to fix this would be very appreciated!

**Comment by perliedman** [comment]
On a second look, this should already be easily doable with lrm-graphhopper, with something like this:

```javascript
router: L.Routing.graphHopper('api_key', {
                        serviceUrl: 'http://172.16.10.38:8989/route',
                        urlParameters: { algorithm: 'alternativeroute' }
                })
```

So it's more a documentation issue than a code change.

**Comment by curiousc0w** [comment]
@perliedman 

That works as well. Thank you!

**Comment by curiousc0w** [comment]
@perliedman 

Just wondering, have you explored the use of Leaflet.Elevation with Graphhopper/Leaflet Routing Machine?

https://github.com/MrMufflon/Leaflet.Elevation

**Comment by perliedman** [comment]
@curiousc0w I did look into it at some point, but think I encountered some difficulty integrating with LRM.

I went down a simpler route and hacked up an elevation graph using d3: http://cykelbanor.se/#bl=Karta&wps=57.7307%2C11.9195%3B57.7503%2C12.0248

It doesn't have all the functionality of Leaflet.Elevation, but it works for my use case.

**Comment by BastiR9** [comment]
> 
> 
> On a second look, this should already be easily doable with lrm-graphhopper, with something like this:
> 
> ```js
> router: L.Routing.graphHopper('api_key', {
>                         serviceUrl: 'http://172.16.10.38:8989/route',
>                         urlParameters: { algorithm: 'alternativeroute' }
>                 })
> ```
> 
> So it's more a documentation issue than a code change.

Algorithm parameter 'alternativeroute' is now changed to 'alternative_route'

source: https://docs.graphhopper.com/#tag/Routing-API
