### ISSUE TITLE
Multiple routes on map

### ISSUE THREAD

**Issue by SalimBensiali** [perliedman/leaflet-routing-machine#219]
Hi,

I am trying to render multiple routes on the same map. Is this currently supported?

I had assumed that calling `L.Routing.control` a second time with a different set of waypoints would do the trick, but it seems that the second call does not have any effect.

Regards,
Salim

**Comment by perliedman** [comment]
Adding multiple controls should work, although it probably will not look and work like you want.

If you want to show multiple routes (and not let the user edit/change them), you're probably better off using `L.Routing.OSRM` and `L.Routing.Line` directly instead.

Could you post an example on jsfiddle or similar illustrating the problem you're having?

**Comment by SalimBensiali** [comment]
Thanks @perliedman. In getting a jsfiddle to demonstrate the problem I realized I was having this issue https://github.com/Leaflet/Leaflet/issues/1657 on my local example which prevented the directions panel and the second route from displaying. I can confirm that more than one route can be displayed with this fiddle http://jsfiddle.net/5qvc7hqj/4/. Although as you said, I would be better off `L.Routing.OSRM` and `L.Routing.Line` directly as I don't want the directions panel.

Thanks for your help.

Cheers,
Salim

**Comment by perliedman** [comment]
Great to hear!

**Comment by MartinLauritsen** [comment]
Hi can anyone help me pls.. I have problem with multiple routes using XML data.  This is my code problem is it takes all positions in one stroke, insteda og making two.
 $(document).ready(function () {
            $.ajax({
                type: "GET",
                url: "DrivingPoints.xml",
                dataType: "xml",
                success: parseXml
            });
      
        });
        var message = [];
        function parseXml(xml) {

            var map = L.map('map');

            L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            var waypoints = [];

            $(xml).find("point").each(function () {

               var lat = $(this).find("lat").text();
               var lng = $(this).find("long").text();

                waypoints.push(L.latLng(lat, lng));

              
            });                   
            L.Routing.control({
                plan: L.Routing.plan(waypoints, {
                    geocoder: L.Control.Geocoder.nominatim(),
                    draggableWaypoints: false
                }),
                addWaypoints: false,
                useZoomParameter: false,
                lineOptions: {
                    styles: [{ color: "lightgreen", opacity: 1, weight: 5 }]
                }
            }).addTo(map)
          
           
        }

        L.Routing.errorControl(control).addTo(map);

XML 
<?xml version="1.0" encoding="utf-8" ?>

<destinations>
  <Trip>
    <LineColor>blue</LineColor>
   <point DriverNumber="11" name="Trip 1 start">    
      <lat>56.260919</lat>
      <long>10.057587</long>
      <type>Start</type>   
  </point>    
  <point DriverNumber="11" name="Trip 1 Destination">
    <lat>56.269234</lat>
    <long>10.00925</long>
    <type>Destination</type>
  </point>
</Trip>

  <Trip>
    <LineColor>blue</LineColor>
    <point DriverNumber="22" name="Trip 2 Sabro">
      <lat>56.211349</lat>
      <long>10.022631</long>
      <type>Start</type>
    </point>
    <point DriverNumber="22" name="Trip 2 Lyngballevej">
      <lat>56.222799</lat>
      <long>9.957336</long>
      <type>Start</type>
    </point>
    <point DriverNumber="22" name="Trip 2 Anbæk">
      <lat>56.234538</lat>
      <long>9.859930</long>
      <type>Destination</type>
    </point>
  </Trip>



</destinations>

**Comment by MartinLauritsen** [comment]
<?xml version="1.0" encoding="utf-8" ?>

<destinations>
  <Trip>
    <LineColor>blue</LineColor>
   <point DriverNumber="11" name="Trip 1 start">    
      <lat>56.260919</lat>
      <long>10.057587</long>
      <type>Start</type>   
  </point>    
  <point DriverNumber="11" name="Trip 1 Destination">
    <lat>56.269234</lat>
    <long>10.00925</long>
    <type>Destination</type>
  </point>
</Trip>

  <Trip>
    <LineColor>blue</LineColor>
    <point DriverNumber="22" name="Trip 2 Sabro">
      <lat>56.211349</lat>
      <long>10.022631</long>
      <type>Start</type>
    </point>
    <point DriverNumber="22" name="Trip 2 Lyngballevej">
      <lat>56.222799</lat>
      <long>9.957336</long>
      <type>Start</type>
    </point>
    <point DriverNumber="22" name="Trip 2 Anbæk">
      <lat>56.234538</lat>
      <long>9.859930</long>
      <type>Destination</type>
    </point>
  </Trip>



</destinations>

> 

>

**Comment by qvs5010** [comment]
Hi 

I'm trying to do the same, to add multiple routes on the map, do you have an example of how to use L.Routing.OSRM and L.Routing.Line, I tried but keep failing.

Thanks Q

**Comment by perliedman** [comment]
@qvs5010 here's an example that adds multiple routes to the map: http://playground-leaflet.rhcloud.com/pije/edit?html,output

Every time you click the map, a waypoint is added. When there are two waypoints, a route is created between the last two waypoints.

**Comment by layunne** [comment]
Hi, 
is there any API to identify intersection between routes?

**Comment by perliedman** [comment]
@layunne hm, that doesn't sound like something that should be discussed in this (closed) issue.

**Comment by edwardffs** [comment]
@perliedman First of all, thanks for this work, it's proving really useful! 
Any chance that example with multiple routes could be uploaded again? It's a dead link now  :-/

**Comment by healyp** [comment]
I'd second @edwardffs request for a working example of multiple routes.  Thanks.
