### ISSUE TITLE
UPDATING MARKERS WITH OUT PAGE REFRESHMENT.

### ISSUE THREAD

**Issue by tvjmohan** [perliedman/leaflet-routing-machine#220]
Hi , hope you are doing good.

i am with another problem. please help in fixing this.
I AM NOT ABLE TO CLEAR OR REMOVE THE MARKER LAYER FROM MAP. 
I AM WRITING CODE FOR - ON SELECT BOX GET NEW MARKERS AND ADD TO MAP.

I AM CREATING FEW ARRAYS TO STORE ALL THE CIRCLEMARKERS.
LIKE THIS   (EXAMPLE I AM PASTING ONLY 1 ARRAY)

**rArr[s] = L.circleMarker(obj, { color: c,  radius: 5 ,weight: 11,opacity: 10 } ).bindLabel(te, {direction: 'right' ,noHide: true}).addTo(map);**

AND THEN....

** red = L.layerGroup(rArr);**

SO I WANTED TO CLEAR THE MARKERS OR REMOVE THE MARKERS ON MAP. 
(MARKERS ARE PLACED ON MAP BASED ON SELECT BOX VALUE, FOR THAT I HAVE TO CLEAR THE MARKER AND ADD NEW MARKERS TO MAP)

UNFORTUNATELY I AM NOT ABLE TO FIND A SOLUTION . I HAVE TRIED FEW FUNCTIONS BUT I AM NOT ABLE TO MAKE IT FIX.    CAN U PLEASE SUGGEST OR SEND ME SAMPLE CODE IT WORKS LIKE ABOVE.  

PLEASE HELP ME ...

**Comment by perliedman** [comment]
Are you sure this has something to do with Leaflet Routing Machine? From your description, it sounds more like a problem with using Leaflet and LayerGroups?

You can remove layer groups (or any layer) with the [`removeLayer`](http://leafletjs.com/reference.html#map-removelayer) method on your map object.

Also, this is not the place to ask questions (especially not on Leaflet). You're better of asking on Stackoverflow or gis.stackexchange.com.
