### ISSUE TITLE
Problem when Control layer added to map

### ISSUE THREAD

**Issue by umacys** [perliedman/leaflet-routing-machine#222]
Hi, 

I create a LayerGroup (of Leaflet) consisting of Control object, and keep a reference to it so that i can be able to add/remove control layer, which i create to represent a route instance. I can sucessfully add this layer to map, and both line and waypoints are displayed properly. I can also successfully remove the layer. But, when add layer second time, waypoints do display but the line is not displayed. Either i do sth wrong, or there would be a bug at creating the layergroup object.

Any help would be appreciated.
Thanks

**Comment by perliedman** [comment]
Hi, sounds pretty weird that this works at all!

Controls can't be added to `LayerGroup` - controls are not layers, and need to be handled separately with `addControl` and `removeControl`.
