### ISSUE TITLE
automatically route

### ISSUE THREAD

**Issue by hack45** [perliedman/leaflet-routing-machine#223]
Hi!!!
As I can do automatically route the dots in the map with routing machine?

Thanks.

**Comment by hack45** [comment]
For example , when adding a track to the map has a coordinate default

![map](https://cloud.githubusercontent.com/assets/18289609/14296741/23918e8e-fb41-11e5-8dbe-b83d841b288f.PNG)

Thanks

**Comment by perliedman** [comment]
Hi,
if I understand your question correctly, you should be able to use the control's `setWaypoints` method, please check the API docs here: http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control

You can also use `spliceWaypoints` if you just want to modify, not change all waypoints.
