### ISSUE TITLE
IE 11 Geocoder Problem

### ISSUE THREAD

**Issue by webmap2015** [perliedman/leaflet-routing-machine#224]
Hi,

In Google Chrome, After I write city or etc. and enter, there is a geocoder pop-up, but IE 11 isn't.

Thanks.

**Comment by perliedman** [comment]
Hi and thanks for reporting!

Apparently IE11 does not have `window.scrollX` and `window.scrollY`, causing the results to get an invalid position, these are the offending lines: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Autocomplete.js#L44-45

**Comment by perliedman** [comment]
Checking the _Notes_ header on https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX, it appears to be the usual sad state of affairs with IE. We should use their workaround.

**Comment by webmap2015** [comment]
But, there is no error on below link with IE 11. Autocomplete is working.

"http://www.liedman.net/leaflet-control-geocoder/"

Thanks.

**Comment by perliedman** [comment]
That's weird, I tried exactly that link earlier today in IE11, and it didn't work.

Are you sure you're running IE11? Which version, OS?

**Comment by webmap2015** [comment]
IE8 in Windows 7

![ie8](https://cloud.githubusercontent.com/assets/10267317/14581327/a351024e-03f2-11e6-985d-da6e42c0b6f4.png)

IE9 in Windows 7

![ie9](https://cloud.githubusercontent.com/assets/10267317/14581328/a3706b02-03f2-11e6-8200-de116acf6a68.png)

IE11 in Windows 7

![ie11](https://cloud.githubusercontent.com/assets/10267317/14581329/a3834ccc-03f2-11e6-87eb-dd685294e26c.png)

Thanks.

**Comment by perliedman** [comment]
Ah, you're talking about Leaflet Control Geocoder, it actually uses a totally different code base. It's Leaflet Routing Machine that uses `scrollX` and `scrollY`.

**Comment by webmap2015** [comment]
Ok, thanks.

**Comment by webmap2015** [comment]
IE11 in Windows 7

"http://cykelbanor.se/#bl=Karta"

There is a pop-up, but top-left position.

![untitled](https://cloud.githubusercontent.com/assets/10267317/14688266/76e3510c-074a-11e6-9b4e-0a76134b592b.png)

**Comment by webmap2015** [comment]
Autocomplete is working with IE11, but on bottomleft of page.

"http://www.liedman.net/leaflet-routing-machine/tutorials/interaction/"

Thanks.

**Comment by perliedman** [comment]
Just pushed a fix for this, you can either build latest master, or wait until the next release, which shouldn't be too far off.
