### ISSUE TITLE
I can't see the control's close button 

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#227]
Hi, I can't see the X to close the control, so the button to hide-show the control appears.
Oddly I can see it on the mobile version, but not on desktop or laptops.

Any idea? Thanks a lot.

**Comment by perliedman** [comment]
By default it's hidden on larger screens, but becomes visible on smaller, like mobile.

If you always want it visible, use the option `collapsible: true`.

**Comment by rossanag** [comment]
Thanks for your response!. I will try it tomorrow morning, in this part of the globe it's time to go to sleep.
ASAP I have a result or trouble I will come back here. 
Best!

**Comment by rossanag** [comment]
Worked perfectly, thanks
