### ISSUE TITLE
Is there a way to avoid some path/street?

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#228]
Hi, I want to know if I can set the coordinates or name of the steet to avoid in the routing. Let's say I want to avoid some street on rush hour, so I can "filter" the input of the control.
Thanks

Ro

**Comment by perliedman** [comment]
Hi, this is entirely up to the rouing backend that LRM uses, there's no way for LRM to influence how the actual route optimization works.

I think both OSRM and GraphHopper are working on ways to do what you want, to alter route calculations depending on traffic situation and so on. You should bring this up on their mailing lists or discussion forums.

**Comment by rossanag** [comment]
Thanks so much for your quick response as always, I will bring this issue to them, then
Best!
