### ISSUE TITLE
Gateway Error

### ISSUE THREAD

**Issue by booper** [perliedman/leaflet-routing-machine#230]
Got this error:
![osrm](https://cloud.githubusercontent.com/assets/583898/14888484/404e9d30-0d63-11e6-9e94-ca4ae98361b9.png)

5 mins ago everything worked gread

**Comment by perliedman** [comment]
This looks like a problem with OSRM's demo server, and unfortunately not something LRM can do anything about.

If you need reliable uptime, you should look into hosting your own OSRM server, the demo server will always be a bit unreliable.
