### ISSUE TITLE
adding waypoint by dragging the route line not working

### ISSUE THREAD

**Issue by emmexx** [perliedman/leaflet-routing-machine#232]
I found this question asked many times and the answer is always "It is active by default".
Unfortunately on my website it doesn't work.
When the mouse is over the route line the mouse icon changes but if I click and drag the map moves instead (panning).
When I do the same on lrm site I get the expected result.

I'm using a very simple code to remove any other possible source of error.
The following is my code:

```
jQuery(document).ready(function()
{
  mymap = L.map('mapid').setView([45.26135, 10.12651], 10);

  L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 
  {
	 attribution: 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a>',
	 maxZoom: 18
  }).addTo(mymap);

  var mycontrol = L.Routing.control({
	 waypoints: [
		L.latLng(45.16135, 10.12651),
		L.latLng(45.1666, 10.2496)
	 ],
	 router: L.Routing.osrm({
		serviceUrl: 'http://myosrmserver',
		routingOptions:
		{
		  z: 18
		}
	 })
  }).addTo(mymap);

 }); //ready
```

Firebug reports no error.
What should I check for problems or errors?

Thank you
  maxx

**Comment by perliedman** [comment]
If it works in the example, but not in your page, it sounds like it must be something you add on that prevents it from working.

Unfortunately it's extremely hard for me to tell what the problem might be. I would suggest building from the example page and add on your own stuff and see when it stops working.

To be able to investigare, I would at least need to know what other stuff you're running on your page. A running example on for example [Leaflet playground](http://playground-leaflet.rhcloud.com/) would be even more helpful.

**Comment by emmexx** [comment]
I'm using LRM in Joomla, using Chronoforms to load leaflet, lrm and all necessary files.
On the same site I use leaflet without any problem.
Even LRM mostly works as expected. I can move around the start and end markers, I followed all the tutorials and they work, except for dragging new waypoints.

I'd be happy to build a running example but it is too difficult, there are at least 10 js files from various libraries (jquery, bootstrap, uikit and other template files).

You can check a (non) working example here: [http://www.bicitalia.org/cms/it/?option=com_chronoforms&chronoform=mappaRouting-Copy](http://www.bicitalia.org/cms/it/?option=com_chronoforms&chronoform=mappaRouting-Copy)
In firebug the relevant code is under Script -> ?option=com_chronoforms&chronoform=mappaRouting-Copy starting from line 200

**Comment by perliedman** [comment]
It looks like you're using canvas for vector rendering. Try and see if it works with SVG (Leaflet's default). It should theoretically work with canvas, but I have never tried it.

**Comment by emmexx** [comment]
Without canvas leaflet doesn't work with that setup.
I had to use it for all my leaflet maps in that site.
I tried not loading leaflet_canvas.js but now I see only the 2 markers, no route line.

**Comment by emmexx** [comment]
I tried:
- leaflet 0.7.7 with LRM 2 -> same problem
- leaflet 1.0.0.rc1 with LRM 3.0.1 
Only the route line is displayed, no markers, no route description box.
But there's a leaflet error.
Then I disabled bootstrap3 (in the joomla template settings) and now it works (leaflet 0.7.7 and LRM 2, no canvas).

**Comment by perliedman** [comment]
It sounds very strange that your site would not work unless you use canvas. Also, I don't know what `leaflet_canvas.js` is.

I guess that Bootstrap 3 has some styling that interacts in a bad way with Leaflet and/or LRM in this case.

I'm closing this for now, since this does not appear to be a LRM problem, but rather bad interaction with some other library. Having said that, if there's something that can be done in LRM to avoid this, I would happily include such a change.

**Comment by emmexx** [comment]
FYI
I don't know what to say, I had a lot of trouble making leaflet work with that joomla template. The only way to see markers and lines on the map was to enable canvas.
leaflet_canvas.js is just a way to set L_PREFER_CANVAS=true before leaflet.js is loaded.
[http://leafletjs.com/reference.html#path-canvas](http://leafletjs.com/reference.html#path-canvas)

Interaction with bootstrap is not rare. But since I'm the only one that reported this problem...

Thanks for your tips that helped me solve the problem.
