### ISSUE TITLE
How to set (interactively...) start / end points of the route using LRM GraphHopper or LRM MapBox

### ISSUE THREAD

**Issue by cesaregerbino** [perliedman/leaflet-routing-machine#233]
I've started to use LRM using OSRM and all works fine. 

Now I need to calculate my routes also for pedestrian or bike and so I've tried to use LRM GraphHopper or LRM MapBox.

I've tried to use the samples and both work fine BUT ..... I can't set my start and end point interactively in the same manner I use to set them when I use OSRM routing control.

Any suggestions / sample for it?

 Thank you very much in advance!!!

**Comment by perliedman** [comment]
Hm, you should be able to use `setWaypoints` and/or `spliceWaypoints` just the same no matter what router (OSRM/GraphHopper/Mapbox) you're using.

Could you provide an example on [Leaflet Playground](playground-leaflet.rhcloud.com) or JSFiddle that illustrates the problem you're seeing?

**Comment by cesaregerbino** [comment]
Thank you for the reply!!!

This is my code ....

        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8" />
            <title>LRM Example</title>
            <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
            <link rel="stylesheet" href="https://rawgit.com/perliedman/leaflet-routing-machine/master/dist/leaflet-routing-machine.css" />
            <link rel="stylesheet" href="index.css" />
        </head>
        <body>
            <div id="map" class="map"></div>
            <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
            <script src="https://rawgit.com/perliedman/leaflet-routing-machine/master/dist/leaflet-routing-machine.js"></script>
            <script src="dist/lrm-graphhopper.js"></script>
            <script src="Control.Geocoder.js"></script>
            <script src="index.js"></script>
        </body>
        </html>

and this is index.js

        var map = L.map('map');

        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        L.Routing.control({

        	waypoints: [
        		L.latLng(57.74, 11.94),
        		L.latLng(57.6792, 11.949)
        	],
        	geocoder: L.Control.Geocoder.nominatim(),
        	router: L.Routing.graphHopper('a585904f-5193-4605-bc3c-870c4f472177'),
        	autoRoute: true,
        	routeWhileDragging: true
        }).addTo(map);

Thank you for the suggestions in advance!

Cesare

**Comment by perliedman** [comment]
Ok, and what problem do you encounter with this code? I don't think I follow what you mean when you say that setting the waypoints interactively doesn't work.

Have you checked your browser's JavaScript console for errors?

**Comment by cesaregerbino** [comment]
The code works fine but if I try, for example to chance start and end
points deleting the current ones and trying to set them interactively with
a click on the map nothing happens. When I use LRM with OSRM I'm able to
this that  ....
Il 05/Mag/2016 21:45, "Per Liedman" <notifications@github.com> ha scritto:

**Comment by perliedman** [comment]
Ok. Does this work as expected for you: http://www.liedman.net/lrm-mapbox/ ?

It uses Mapbox Directions, and should work the same as your code.

**Comment by cesaregerbino** [comment]
Unfortunately no, it doesn't work. When I try to remove start and end points and try to add new ones interactively on the map nothing happens ... I've truid to capture a session to explain more ... here you are the link at the video https://youtu.be/APKf7pg1qtk

Thanks for the help!

**Comment by perliedman** [comment]
Alright.

The functionality you're looking for is explicitly _not_ built into LRM.

Check this tutorial for how to do this: http://www.liedman.net/leaflet-routing-machine/tutorials/interaction/
