### ISSUE TITLE
addWaypoints not working within L.Routing.Plan options

### ISSUE THREAD

**Issue by dominikveils** [perliedman/leaflet-routing-machine#234]
Hello,

My last issue was solved https://github.com/perliedman/leaflet-routing-machine/issues/57
But now I'm facing the new issue:
When creating route with:
```javascript
L.Routing.control({
 //...
 plan: L.Routing.plan(plan, {
    //...
    addWaypoints: false
 })
 //...
})
```
The actual `addWaypoints` is not working. I'm still can add new waypoints by clicking the line.

But when I'm passing `addWaypoints` to `L.Routing.control` (instead of `L.Routing.plan`) its working!
```javascript
L.Routing.control({
 //...
 addWaypoints: false
 plan: L.Routing.plan(plan, {
    //...
 })
 //...
})
```
The problem that `L.Routing.plan` does not pick the options...

PS
Using `"leaflet-routing-machine": "^2.6.2"` from NPM

**Comment by perliedman** [comment]
Yes, this is a bit confusing, but the logic is this: if you don't provide your own `plan`, `router`, etc. when you create the control, they will be created for you, and the options you pass to the control will also be passed to them.

If you on the other hand pass your own `plan`, it will get exactly the options you passed it when you created it, it will not inherit the control's options automatically.

This means that you will explicitly have to pass `addWaypoints: false` to the plan you create.
