### ISSUE TITLE
Multiple Routes on a map!

### ISSUE THREAD

**Issue by CusProjects** [perliedman/leaflet-routing-machine#244]

**Comment by perliedman** [comment]
Please elaborate more on what the problem is if you want a sensible answer.

**Comment by umacys** [comment]
In two ways you can do this. Create a control object for each route, or create single control object and add routingLine and markers layer for for each route. Personally, i would go with the second option.

**Comment by edwardffs** [comment]
Any chance I could see an example of this "add multiple routingLine" method? I'm having a hard time understanding the IRoute interface...
