### ISSUE TITLE
How to capture the click event in a Waypoint?

### ISSUE THREAD

**Issue by CusProjects** [perliedman/leaflet-routing-machine#245]

**Comment by perliedman** [comment]
Use the `createMarker` option for [`L.Routing.Plan`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan) to override how the markers are created. You can add your own click handler there.

Like this:

```
var control = L.Routing.control({
    createMarker: function(i, wp) {
        return L.marker(wp.latLng).on('click', function(e) { ... });
    }
});

**Comment by CusProjects** [comment]
Tanks its useful 👍

**Comment by arminus** [comment]
Adding createMarker as shown above prevents the marker from being draggable in my case

I see that L.Routing.Plan has a draggableWaypoints options, but adding this to the initialization of the L.Routing.control doesn't seem to have an effect either?

**Comment by perliedman** [comment]
@arminus you can check the default implementation here: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Plan.js#L25-32

To make the marker draggable, you need to set the `draggable` option to true.

**Comment by arminus** [comment]
Thx!

**Comment by irobust** [comment]
thanks!
