### ISSUE TITLE
How to get automaticaly start point of route from geojson request 

### ISSUE THREAD

**Issue by marie15** [perliedman/leaflet-routing-machine#247]
Hi everybody, I'm trying to get routee between two locations, therfore I used Leaflet routing machine. In my case, I want that user can enter start and end points, therfore I used Leaflet Control geocoder. To be more clear, I already made a search box that allow user searching anyplace in map. So my issue is that I want to get route between this location and another destination. To accomplish that, I want that the start point input will contain automaticaly the location searched by user and for sure he can enter any destination he want. I hope that I was clear.

Any help is appreciated. Thankx for advance :)

**Comment by perliedman** [comment]
Use the control's `setWaypoints` (see [the LRM API](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control)) method directly when you have the coordinates from the geocoder and your destination coordinate.

**Comment by marie15** [comment]
Oki thankx, I will try that

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-15 7:30 GMT+01:00 Per Liedman <notifications@github.com>:

**Comment by marie15** [comment]
Oki thankx. I will try that

**Comment by marie15** [comment]
The setWaypoints not working with me :(, it's not answer my issue

**Comment by perliedman** [comment]
I think you will have to elaborate more on what the problem is if you want anyone to be able to help you.

If I understand you correctly, you want to let the user choose the starting point for a route, using Leaflet Control Geocoder. You then want to route them to a fixed destination point, right?

What you need to do, is wait for the user to select a geocoded location, check the [example on customizing mark geocode](https://github.com/perliedman/leaflet-control-geocoder#customizing) on how to do this. When a location is selected, you have the start and destination coordinates. Pass these to `setWaypoints`.

If this is still a problem, please provide running code with clear indication of what's isn't working.

**Comment by marie15** [comment]
Hi, first thank you for according attention to my request. But I think I
wasn't clear, sorry for that. So to remove ambiguity, I will explain in
detail the situation. I made a search box to search for any location and so
locate this place in map. Now I want to add itinerary option to this
functionnality. So when user enter a location in search box and after that
click on itinerary option, the start point it will be by default contain
the location that he already search for it and after that he will only
enter a destination. It's like google maps.

I hope that I was clear. Thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-16 7:26 GMT+01:00 Per Liedman <notifications@github.com>:

**Comment by perliedman** [comment]
Ok, instantiate the control with a single waypoint. If you set it up like in [the LRM example](https://github.com/perliedman/leaflet-routing-machine/tree/master/examples), but only feed it one waypoint (the one your user selects), you should be fine.

If you want the selected coordinate to be the destination, not the start, feed it two waypoints, but set the first to `null`:

```javascript
waypoints: [null, destination]
```

**Comment by marie15** [comment]
Oki I understood you, but I want to pass the name in search box to the start point, so I don't want to use latLng,I want to pass this name in control.gocoder. I can put this name in a variable but I don't know how to use it. I hope that you understand me

**Comment by marie15** [comment]
I tried to use waypoint's name property, but it's not working

**Comment by perliedman** [comment]
Sorry, you'll have to provide some code illustrating the issue, I can't guess what the problem is.

**Comment by marie15** [comment]
Oki you are right. here is the snippet code:

$scope.$on("myEvent1", function (event, args) {

      var StartPoint= args.value;

      leafletData.getMap().then(function(map) {
        
               L.Routing.control({
                    waypoints: [
                        
                        String(StartPoint)
                        /*L.LatLngBounds(data["features"][0]["geometry"]["coordinates"]),
                        L.latLng(33.578440, -7.621731)*/
                    ],
                    routeWhileDragging: true,    
                    geocoder: L.Control.Geocoder.nominatim(),
                    autocomplete:true
                }).addTo(map);

The variable Startpoint contain the name in search box choose by user. So I want to put this name in stratpoint input.

**Comment by perliedman** [comment]
Try

```
                waypoints: [
                    new L.Routing.Waypoint(startCoord, startName),
                    L.latLng(33.578440, -7.621731)*/
                ]
```

where `startCoord` is the `L.LatLng` you want to start from, and `startName` is the name of the location, as a string.

**Comment by marie15** [comment]
But I don't have latitude and longitude of startpoint because I retreie search results from a geoson file which has this structure: 
    "type": "FeatureCollection",
    "features": 
    [
        {
            "type": "Feature",
            "id": "sto",
            "properties": {
                "name": "Stoke"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                   -6.8325500,
                   34.0132500
                ]
            }
        }]

},
So how can I retreive exactly lat and long of this location. I can't use only the name of location?

Sorry for all this question

**Comment by marie15** [comment]
and about destination I want user to enter the destination, So it's empty by default. SO I don't have to write destination in waypoint.

**Comment by perliedman** [comment]
Sorry, this is beyond the support I can give you. The API is there, but you have to piece together the information you need and pass it to it. LRM needs coordinates to be able to route, it's up to you to find them and feed them to it.

Alternatively, use the geocoders with LRM's builtin functionality. Maybe you can look at the [interaction tutorial](http://www.liedman.net/leaflet-routing-machine/tutorials/interaction/) to get some ideas, if you haven't already.

**Comment by marie15** [comment]
Oki thank you so much for your time. I will try to fix that. If you don't mind, I have a question, it seems simple but I can"t figure out the problem. when I add control.geocoder to be able to enter start and destination point, when I click "inspect" on this element nothing appears, so I can't change its css or nothing. Do you know what is the problem?

And thank you

**Comment by perliedman** [comment]
That sounds strange. There's nothing special about those elements, as far as I can tell. Check if you get the same results in the Leaflet geocoder demos.

**Comment by marie15** [comment]
the routing functionnality is working but when I tried to inspect the element it doesn't

**Comment by marie15** [comment]
Thank you for the snippet code, I'm trying to use it, it's working, just it still a problem with coordinates of location, as I said I don't have latitude and longitude separated but the geometry. So I'm trying to fix this problem, if you have any idea, I will be grateful :)

**Comment by marie15** [comment]
I solved the problem Thank you so much

**Comment by helios020156** [comment]
How can i set the current position ( var latitude = position.coords.latitude;
      var longitude = position.coords.longitude) as a waypoint
