### ISSUE TITLE
route() function callback called 2 times in IE

### ISSUE THREAD

**Issue by emmexx** [perliedman/leaflet-routing-machine#248]
I'm calling the IRouter.route() function inside the click event of a button to download the gpx of the route.

I call the function like this:
```javascript
    mycontrol.getRouter().route(mycontrol.getWaypoints(),
		function(e, res) {
   other code...
```
In Firefox and Chrome the callback is called one time. In IE (11) it is called 2 times, the 1st one `e` and `res` have the correct values, the 2nd time `res` is null and `e.status=3`. 

Update: the code I used is this: #210 
The problem is problably in the click() method inside the callback.
I modified the code to use jQuery.click() instead of element.click() and the same behaviour appears in FF and Chrome.

**Comment by perliedman** [comment]
If I understand you're description correctly, the problem lies with external code calling `element.click`, and not something within LRM itself, correct?

I'm closing for now, but please provide more info if this is actually a problem with LRM.
