### ISSUE TITLE
How to add Leaflet routing conatiner to html page using AngularJS

### ISSUE THREAD

**Issue by marie15** [perliedman/leaflet-routing-machine#249]
Hi everybody,I'm using leaflet routing machine, I want to add its container in a div in my html page to be able to customise it and also to controle it using Angularjs. Do you have any idea how to do that?

Thank you for advance

**Comment by perliedman** [comment]
Sorry, this is outside the scope of Leaflet Routing Machine. I would assume you could set up a Angular directive to do this, but it's much more about Angular than it is about LRM.

**Comment by marie15** [comment]
Oki thankx I will fix that
