### ISSUE TITLE
Integrating leaflet-routing-machine with angular-leaflet-directive

### ISSUE THREAD

**Issue by cosmicanant** [perliedman/leaflet-routing-machine#250]
I am using below code to add a custom control to angular-leaflet-directive: 
```
window.L.Routing.Control({
    waypoints: [{"lat":lat1,"lng": lng1},{"lat":lat2,"lng":lng2}],
    routeWhileDragging: true,
    reverseWaypoints: true, 
    showAlternatives: true  
}
```
But It always returns an undefined value. Although window.L.Routing.Control exists as a function.

**Comment by perliedman** [comment]
You want either `new window.L.Routing.Control(...)` or `window.L.Routing.control(...)` (notice lower case `c` in `control` - the first is an object constructor and must be used with `new`, the other is a factory method, and will return the new instance.

**Comment by cosmicanant** [comment]
Thanks a ton for you quick response. It worked pretty well.

**Comment by jospin2017** [comment]
bns y'a t'il une directive leaflet-routing-machine svp?
