### ISSUE TITLE
How to initialize geocoder object Leaflet routing machine

### ISSUE THREAD

**Issue by marie15** [perliedman/leaflet-routing-machine#251]
Hi everybody, I'm using Leaflet routing machine plugin and control geocoder to calculate route between two locations. I've successed to do that, but when I want for a second time to enter two locations, a new geocoder object were created, so in my application I got two object. What I want is when I close the route interface, the itinerary will be removed from map, and when I reopen it I want to have a geocoder object with empty input. I hope that I was clear.

Thanks for advance :)

**Comment by perliedman** [comment]
What exactly do you mean when you say "close the route interface"? Do you use the `hide` method, or do you remove the control entirely?

**Comment by marie15** [comment]
when I click a button I want to hide the interface of route and remove the route from map. For now, I can hide the interface but I can't remove the path from map, it's like google maps

**Comment by perliedman** [comment]
Remove then control with `map.removeControl(routeControl)`. Then just add a new one just like you already do.

**Comment by marie15** [comment]
I tried this snippet code but I got this error : Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by perliedman** [comment]
Again, it's impossible for me to comment on generic errors without seeing code.

Also, please understand that this is an issue tracker, not a discussion or support forum. The idea is to report actual errors _in Leaflet Routing Machine_, to keep track of them and hopefully get them fixed.

I want to help if possible, but I really don't have the time or energy to debug or guess the problems of other peoples code in my free time. If you really need help, I suggest hiring someone to do it.

**Comment by marie15** [comment]
Oki understood. I will fix that by myself. Thank you
