### ISSUE TITLE
Time and Distance between each waypoint along a route

### ISSUE THREAD

**Issue by willowvil** [perliedman/leaflet-routing-machine#253]
Hello,

How could I get the time and distance between for example 4 waypoints along a route?

Thank you in advance.

**Comment by perliedman** [comment]
There's currently no really easy way to do this.

Your best option is to loop over the route's `instructions` and sum up the `distance`s and `time`s. At the same time, check for the instructions with type `WaypointReached`, and you will be able to calculate the distances and times between waypoints.

See [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) and [`IInstruction`](http://www.liedman.net/leaflet-routing-machine/api/#iinstruction) for details on the members of those interfaces.

Hopes this makes sense to you!

**Comment by willowvil** [comment]
Thank you very much. Let me try it and keep you informed.
