### ISSUE TITLE
Leaflet has a display problem in Google Chrome

### ISSUE THREAD

**Issue by CusProjects** [perliedman/leaflet-routing-machine#254]
![screen shot 2016-05-19 at 10 06 48 am](https://cloud.githubusercontent.com/assets/14632593/15400678/957eec00-1da9-11e6-88ca-2d0ac1c49f1c.png)

**Comment by perliedman** [comment]
Sorry, this is not a bug report I can work with.

I suggest you read this excellent guide on reporting bugs: http://polite.technology/reportabug.html
