### ISSUE TITLE
No route displayed when use more than three waypoints

### ISSUE THREAD

**Issue by Pulstarter** [perliedman/leaflet-routing-machine#256]
Hi!

I am developing an app based on Ionic, and I need to add a route map on it. I was be able to show the route on a map, but for no reason I get the error: **Uncaught TypeError: Cannot read property 'lat' of undefined** since a couple weeks if I try to draw a route with more than two waypoints.

The control is:

     function getRoute() {
        var r = L.Routing.control({

          waypoints: waypoints,
          router: new L.Routing.Mapbox(Config.mapBoxApiKey,
            {
              serviceUrl: 'https://api.tiles.mapbox.com/v4/directions/',
              timeout: 30 * 1000,
              profile: 'mapbox.driving'
            }
          ),
          lineOptions: {
            styles: styles
          },
          fitSelectedRoutes: false,
          routeWhileDragging: false,
          createMarker: function () {
            return null;
          }

        });

        return r;
      }

      var control = getRoute();

      var routeLayer = L.layerGroup([control]);
      self.map.addLayer(routeLayer);

With this array works fine:

    var waypoints = [
           new L.LatLng(42.847159, -2.672249),
           new L.LatLng(42.848602, -2.672818)
         ]

But with this not work:

    var test = [
           new L.LatLng(42.847159, -2.672249),
           new L.LatLng(42.848602, -2.672818),
           new L.LatLng(42.849470, -2.673123)
         ] 

I have updated to last version of leaflet-routing-machine with no luck.

Leaftleft version: 0.7.7
leaflet-routing-machine version: 3.0.1

Any idea to resolve this?

Best regards

**Comment by perliedman** [comment]
Hi!

This looks like the same issue as https://github.com/perliedman/lrm-mapbox/issues/4

Which version of lrm-mapbox are you running? A workaround is included in 1.0.4, but I suspect the real issue is with Mapbox's API, and I have an ongoing discussion with their support regarding this issue.

**Comment by Pulstarter** [comment]
Thanks for the quick response!

I am using 1.0.3, so I will update to 1.0.4 and will tell.

Best regards

**Comment by Pulstarter** [comment]
Hi!

Works perfect with lrm-mapbox 1.0.4

Thank you very much again and best regards
