### ISSUE TITLE
Can't init the plugin

### ISSUE THREAD

**Issue by 440459012** [perliedman/leaflet-routing-machine#257]
I get this error when try to init plugin in Leaflet 1.0.0-rc.1 dev:
`leaflet-src.js Uncaught TypeError: Cannot read property 'call' of undefined
o.Map.o.Evented.extend.whenReady @ leaflet-src.js?v=be81f83…:6o.Map.include.addLayer @ leaflet-src.js?v=be81f83…:6L.Routing.Control.L.Routing.Itinerary.extend.onAdd @ leaflet-routing-machine.js:443o.Control.o.Class.extend.addTo @ leaflet-src.js?v=be81f83…:8Map.initMap @ map.coffee:120(anonymous function) @ map.coffee:1Map @ map.coffee:58Main @ main.coffee:13(anonymous function) @ main.coffee:31(anonymous function) @ main.coffee:3`

**Comment by Chaoste** [comment]
Had the same problem but using Leaflet 0.7.7 fixed it.

**Comment by perliedman** [comment]
Yes, you need to use the `develop` branch if you're using Leaflet master or the 1.0.0-series.
