### ISSUE TITLE
country information within the route in ResultSet

### ISSUE THREAD

**Issue by simplogithub** [perliedman/leaflet-routing-machine#258]
Hi , 
in the route ResultSet there is no information about the current country the route goes through.
there is way to get this information by adding an additional parameters ? 
 it will be nice to know when the route is entering in a new country. 
in case this plugin does'nt support this , there is a way to get this information ?
Tanks

**Comment by perliedman** [comment]
Unfortunately, this is not part of what OSRM returns. You can check the data format here: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#properties-2
