### ISSUE TITLE
How to fire events?

### ISSUE THREAD

**Issue by eroshenko** [perliedman/leaflet-routing-machine#259]
Hi, @perliedman!
First, thanks for your awesome Routing Machine. Great job!
Second, can you help me, please?

**1. How correct can i fire "events"?**

I do:

```javascript
L.Routing.control({
    waypoints: waypoints,
    routeWhileDragging: true,
    geocoder: L.Control.Geocoder.google()
})
.addTo(map)
.on('waypointschanged', function (e) {
    console.log('waypoint changed');
});
```

Or have something better?

And one more question: 

**2. How can i change type of the route (ex. driving, cycling, walking)?**

Thanks.

**Comment by perliedman** [comment]
Hi there,
great to hear that you're finding the plugin useful!

Regarding your first question, I'm not sure I fully understand. The code you posted looks correct, and should receive an event every time a waypoint changes. But you ask about firing events - normally, you never need to fire events, but the plugin itself fires events that you receive.

The type of route is controlled by the backend routing software - by default, OSRM's demo server is used, and it only supports car.

If you're interested in other modes of transportation, you have the option of setting up your own OSRM server, or you can use another backend that supports other modes. Both GraphHopper and Mapbox offer such services, and can be integrated with Leaflet Routing Machine with the projects lrm-graphhopper and lrm-mapbox.

**Comment by eroshenko** [comment]
Hi and thanks for answer.

1. I saw your comment https://github.com/perliedman/leaflet-routing-machine/issues/18#issuecomment-43174207 and confused what correct (in your comment or my example).

2. Yes, i'm using MapBox. I will try. Thanks

**Comment by eroshenko** [comment]
@perliedman "But you ask about firing events - normally, you never need to fire events, but the plugin itself fires events that you receive."
I need write to DB new coords if the waypoint is changed, then i fired "waypointschanged". Right?

**Comment by perliedman** [comment]
I think you got the terminology wrong. To "fire" an event means sending it. Typically, the plugin sends, _fires_, events, and the code using the plugin _listens_ for those events.

The `on` method adds a listener, that will be called when the plugin fires the `waypointschanged` event.

So, you've added a listener in the code above, and you should be able to save the waypoints in your DB in that listener.

**Comment by eroshenko** [comment]
Yes you are right)) I mixed up the listener and "fire".
