### ISSUE TITLE
Canceling a routing during click or drag event

### ISSUE THREAD

**Issue by arminus** [perliedman/leaflet-routing-machine#263]
Is there a way to cancel a routing change during a click or routingstart event? So far, I do this in the routingstart event handler

    g_router.setWaypoints(null);
    g_router.removeFrom(map);

but this throws a couple of exceptions...

I use GH as backend and need to do some pre-checking before calling GH (line of sight distance < a certain amount to avoid overloading GH and the Server with routing requests from New York to Buenos Aires) (ideally this should be handeled in GH, but apparently it isn't, at least not yet)

I suppose I could patch this into lrm-graphhopper's route function and handle the "out-of-bounds" like a GH timeout, but I was wondering wether there might be a better way to do this.

**Comment by perliedman** [comment]
For things like these, I usually subclass `L.Routing.Control` and override its `route` method.

If you check the current implementation, it already does some checking before actually making the routing request.

Another option is to set `autoRoute` to `false`, and call the `route` method exactly when you need to - then you can have your checks in the event handler for `waypointschanged`, for example.

**Comment by arminus** [comment]
Ok, overriding the route method works. Follow up question, though: How do I properly cancel a drag event?

Suppose the "out-of-bounds pre-routing check" I've now added to my route method fires a routingerror. In case a new marker was created, I just delete it from the waypoints and everything is ok. In case of a drag, I want to cancel the drag, though and that doesn't quite work yet.

My current approach is to remember the drag start position in a waypointdrag event handler and use that to update the position of the marker in the waypoints list in case of an out-of-bounds drag. Basically seems to work, but something's not quite right since I don't know how to fully cancel the drag, right now I have a revertRouteMarker like this

    MyRouterControl = L.Routing.Control.extend({
        revertRouteMarker: function(dragEndPos, dragStartPos) {
            // builds the new newWps list by replacing the drag end position with the start position
            this.getPlan().fire('waypointdragend');
            this.setWaypoints(newWps);
        }
    };
        
But this still leaves the mouse cursor in drag mode and "often" results in a endless loop for the revert function.

So what is the right way to cancel a marker drag?

**Comment by arminus** [comment]
Well, turns out I shouldn't use .fire('waypointdragend') (after lots of trial&error) and the endless loops where actually caused by an issue on my side.

Last small problem (I hope): 

Canceling a drag on a WP which was inserted during a linetouch: I managed to delete the newly inserted WP but the only way I found to "get out of drag" mode in that case is to call map.fire("mouseup") (which seems to work)
