### ISSUE TITLE
Add vehicle and weighting params to lrm-graphhopper

### ISSUE THREAD

**Issue by arminus** [perliedman/leaflet-routing-machine#264]
Basically with this

	L.Routing.GraphHopper = L.Class.extend({
		options: {
			serviceUrl: 'https://graphhopper.com/api/1/route',
            vehicle: 'car',
            weighting: 'shortest',
			timeout: 30 * 1000,
			urlParameters: {}
		},

          ...

			baseUrl = this.options.serviceUrl + '?' +
                'vehicle=' + this.options.vehicle + '&' +
                'weighting=' + this.options.weighting + '&' +
				locs.join('&');

**Comment by perliedman** [comment]
There's already the `urlParameters` option, that is intended for exactly this!

No biggie, but for the future, please open issues like these on [lrm-graphhopper](https://github.com/perliedman/lrm-graphhopper), where they belong!

**Comment by arminus** [comment]
thx, sorry
