### ISSUE TITLE
map.getSize is not a function

### ISSUE THREAD

**Issue by bonlemuel** [perliedman/leaflet-routing-machine#270]
Upon loading the map. I got this:
Error: map.getSize is not a function. (In 'map.getSize()', 'map.getSize' is undefined)

I'm trying to load the routing machine onto my mobile app project that is created via Ionic Framework. Anyone tried using this on Ionic Framework? Please help. Thanks!

**Comment by perliedman** [comment]
Can you show some code you're using?

It sounds weird, almost like you've added the control to something that is not a map instance. [`getSize`](http://leafletjs.com/reference.html#map-getsize) is definitely a method on Leaflet's map object.

**Comment by perliedman** [comment]
Closing since no more info has been provided.

**Comment by yporret** [comment]
i think he tried to do something like that
 

```
var lLayerRed = new L.LayerGroup();
		mymap.addLayer(lLayerRed);
		var lLayerPurp = new L.FeatureGroup();
		mymap.addLayer(lLayerPurp);
		
		var overlays = {
		  "red": lLayerRed,
		  "purp": lLayerPurp
		};
		L.control.layers(null, overlays).addTo(mymap);
		
		
		L.Routing.control({
		  waypoints: [
			L.latLng(57.74, 11.94),
			L.latLng(57.6792, 11.949)
		  ],
		  routeWhileDragging: true
		}).addTo(lLayerRed);
```

by the way, is that even possible to do it? (adding the routing to something else than the map? )

It would help me a lot...

**Comment by perliedman** [comment]
No, Leaflet controls can only be added to maps, not to layers.

If you just want to add the route _line_ to a separate layer, you can use the class `L.Routing.Line` directly, it works fine to attach it to a layergroup or whatever you need to do.

**Comment by yporret** [comment]
ok thanks for the information.

**Comment by barrypearseburke** [comment]
Just to add to this although it is closed i had the same error message, however my problem was that i defined map in one function and had my routing in another. Simple fix is define map as global. When making the map, do not refined map(ie , leave out the var) and in the routing function just say map.

**Comment by ebisLab** [comment]
> Just to add to this although it is closed i had the same error message, however my problem was that i defined map in one function and had my routing in another. Simple fix is define map as global. When making the map, do not refined map(ie , leave out the var) and in the routing function just say map.

do you have an example?

**Comment by barrypearseburke** [comment]
> 
> 
> > Just to add to this although it is closed i had the same error message, however my problem was that i defined map in one function and had my routing in another. Simple fix is define map as global. When making the map, do not refined map(ie , leave out the var) and in the routing function just say map.
> 
> do you have an example?

So i wrote this doggy code when i was in college a few years ago and probably haven't wrote any js since
so, take this with a grain of salt. Ive just extracted this from a private repo. Dont know how well it works if at all.

https://pastebin.com/LHBituZF
