### ISSUE TITLE
Adding popup content to routing machine

### ISSUE THREAD

**Issue by canute2008** [perliedman/leaflet-routing-machine#271]
Hi,
I managed to configure Routing Machine. I would like to add a popup content so for example start and finish can be displayed when the two pop buttons are clicked. 
Thanks for your advice
Here is a working [example](http://locate.paris/routing/route_foot/interface/foot.html?flat=6.9270786&flng=79.86124300000006&tlat=6.9194507&tlng=79.8500303)

**Comment by perliedman** [comment]
Not entirely sure what type of popup you want, but check out the interactivity tutorial, which adds popups to interact with the routing control: http://www.liedman.net/leaflet-routing-machine/tutorials/interaction/

**Comment by canute2008** [comment]
![popup](https://cloud.githubusercontent.com/assets/1959184/16085043/11adf182-331b-11e6-959f-d99a65de0251.png)

Hi, Thanks for your reply.  I went through the tutorial, its complete...and very nicely done. 
I just want to display a popup text as in the image here with. 
Thanks in advance for any help

**Comment by perliedman** [comment]
You mean a popup on one of the waypoint markers?

You can achieve this with the `createMarker` option, which takes a function that you can use to create markers any way you like:

```javascript
L.Routing.control({
    createMarker: function(i, wp, nWps) {
        return L.marker(wp.latLng)
            .bindPopup('I\'m waypoint ' + i);
    },
    ...
}
```

**Comment by canute2008** [comment]
Hi, Thanks a lot, I managed add add content in marker with createMarker.

**Comment by rafaneri** [comment]
Hi @perliedman,

Did createMarker removed from the L.Routing.control() arguments options?

**Comment by sankethj** [comment]
> Hi @perliedman,
> 
> Did createMarker removed from the L.Routing.control() arguments options?

No...
