### ISSUE TITLE
How to change the route automatically by changing the mode of travel?

### ISSUE THREAD

**Issue by dmitrykhramov** [perliedman/leaflet-routing-machine#273]
Hi! I'm working with improved version of LRM where multy travel methods are supported. The problem is when I put the waypoints with the mode "walk" for example and the route is built, I want that if you click to another mode "Car" the route would be automatically changed. Now I have to drag a marker or fill in waypoints again to make route changed. Do you have any ideas how it could be done?

**Comment by perliedman** [comment]
It depends a lot on how you implemented this, but as long as you use the same router instance (the control's `options.router`), you should be fine with just calling the control's `route()` method when you change the mode of travel.

**Comment by dmitrykhramov** [comment]
Oh yeah, thanks, because of the lack of knoweledhe I tried to call this method in a wrong way, now it's working, thanks for help.
