### ISSUE TITLE
Install and Usage on Rails

### ISSUE THREAD

**Issue by kirantpatil** [perliedman/leaflet-routing-machine#277]
Hi,

Please provide me the steps to install leaflet-routing-machine on rails.

Thanks.

**Comment by perliedman** [comment]
Sorry, LRM has nothing to do with Rails. I'm not sure in what way you want to integrate with Rails; LRM needs a routing backend (it will use OSRM's demo server by default, but you probably want to switch to something else for production use).

I have no Rails experience myself, so I can't guide you, but there's nothing special with LRM that should  differ from other JavaScript libraries.

**Comment by kirantpatil** [comment]
Thanks for your feedback. Yes I will build OSRM server for our need. Do you suggest anything else for production use ?
