### ISSUE TITLE
Maximum number of waypoints?

### ISSUE THREAD

**Issue by Dr-Mx** [perliedman/leaflet-routing-machine#278]
Hi Mr L,

Is there an option to set the maximum number of waypoints?  It would be useful as the free GraphHopper API only allows 5.

Cheers.

**Comment by perliedman** [comment]
Sorry, no way to do this currently, but it seems like a sensible addition. My main concern would be how to best inform the user that the maximum number of waypoints has been reached.

A pull request to address this would be very welcome!

**Comment by Johnstands** [comment]
Mapbox Manimum limit is 25.
`{"message":"Too many coordinates; maximum number of coordinates is 25.","code":"InvalidInput"}`
