### ISSUE TITLE
the server responded with a status of 504 (GATEWAY_TIMEOUT)

### ISSUE THREAD

**Issue by dhrubo001** [perliedman/leaflet-routing-machine#279]
Hello guys,

It was all ok till yesterday, but today morning when trying to fetch the direction using this packages it gives

the server responded with a status of 504 (GATEWAY_TIMEOUT)

Why this is happening????
Any ideas??

The full error:-

Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT)
home-search:1 XMLHttpRequest cannot load http://router.project-osrm.org/route/v1/driving/12.568337100000008,55.6760968;12.5603228,55.6742804?alternatives=true&steps=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fiksable.com' is therefore not allowed access. The response had HTTP status code 504.

**Comment by Robertmw** [comment]
Had the same problem, and I saw a lot of people here having the same problem. I tried Mapbox and it works fine. (https://github.com/perliedman/lrm-mapbox)

As @perliedman  said

> By default, LRM uses OSRM's demo server. The demo server comes without guarantees, and also with the usage policy linked to above. Sometimes it works, sometimes it doesn't

**Comment by carlosduall** [comment]
Hi i have the same problem and the lrm-mapbox dont work, some workaround, thanks for your help

**Comment by Zacaria** [comment]
The [Mapzen](https://github.com/mapzen/lrm-mapzen) router worked for me

**Comment by perliedman** [comment]
Yeah, like @Robertmw already said. The demo server comes without SLA, but on the other hand you're not paying anyone.

If you need guarantees, set up your own OSRM server (not terribly hard) and maintain it, or pay a provider like Mapbox, GraphHopper or Mapzen, which can be used through the plugins.
