### ISSUE TITLE
Routing error - HTTP request failed: [object ProgressEvent]

### ISSUE THREAD

**Issue by LailaMai** [perliedman/leaflet-routing-machine#280]
Hello guys,
Since two days ago , the map doesn't show correctly and there is an error shown in  console : Routing error: Object { status=-1,  message="HTTP request failed: [object ProgressEvent]"} , when I check the website http://www.liedman.net/leaflet-routing-machine , I saw the same thing, so it's certainly from the API server , is there any solution for that ?

**Comment by LailaMai** [comment]
After some research I found that the problem is not from LRM but from the OSRM's demo server that comes without guarantees , and not advised for production use ... Apparently it's not the first time that happens , I spent a lot of time setting the leaflet routing map in the project and I can't deliver a work to my client that can be broken at any time , unfortunately I have to simply switch to Google map API .

**Comment by LailaMai** [comment]
#194

**Comment by LailaMai** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/1873#issuecomment-234326497

**Comment by perliedman** [comment]
@LailaMai There are cheap alternatives for using OSRM or other backends compatible with LRM, but not entirely free. On the other hand, Google Maps isn't free if your solution uses a login or is a paid service, and depending on how you see it not really free otherwise either - your users are paying by delivering data to Google.

Bottom line: if you want something to work, it will have to be paid, one way or another.

**Comment by LailaMai** [comment]
@perliedman Actually I made my solution with GoogleMap Api and yeah it's not free , especially that Google has restriction on 10 waypoints per route , if you want more you have to pay for premium account .
I finally made a work around that seems to work fine with the "free" account and displayed more than 10 waypoints and multiple routes also.

**Comment by ciaran036** [comment]
Hi @Zacaria , how did you know it was a CORS issue? I'm currently experiencing this with an ASP.NET Web API app and I have been unable to figure out why I'm getting the issue.
