### ISSUE TITLE
Modifier on type=depart/arrive does not indicate a turn but relative positions

### ISSUE THREAD

**Issue by daniel-j-h** [perliedman/leaflet-routing-machine#283]
Please see discussion over at: https://github.com/Project-OSRM/osrm-backend/issues/2725#issuecomment-236646518.

Per the [v5 API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md):
> depart/arrive     modifier indicates the position of departure point and arrival point in relation to the current direction of travel

This needs to be special-cased otherwise the instructions are confusion to the user.

**Comment by perliedman** [comment]
Thanks for the heads up! Hadn't noticed this.
