### ISSUE TITLE
URL string malformed

### ISSUE THREAD

**Issue by codepro1** [perliedman/leaflet-routing-machine#284]
I am using OSRM 5.3.0, Leaflet 1.0.0-rc2 and Leaflet routing machine v3.03.  I am receiving the following error:
{"message":"URL string malformed close to position 9: \"ng\/-83\"","code":"InvalidUrl"}

Request:
`
http://streetmap.test.com:5000/driving/-83.211343,42.266365;-83.68214,42.242492?
overview=false&alternatives=true&steps=true&hints=;
`

Source code:
````
<!DOCTYPE html>
<html>
<head>
    <title>Leaflet Quick Start Guide Example</title>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="leaflet.css" />
    <link rel="stylesheet" href="leaflet-routing-machine.css" />
</head>
<body>
    <div id="mapid" style="width: 600px; height: 400px"></div>
    <script src="leaflet.js"></script>
    <script src="Control.Geocoder.js"></script>
    <script src="leaflet-routing-machine.js"></script>
    <script>
		var mymap = L.map('mapid').setView([42.266365, -83.211343], 15);

		L.tileLayer('http://streetmap.test.com/{id}/{z}/{x}/{y}.png', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
				'<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ',
			id: 'osm_tiles'
		}).addTo(mymap);

		var control = L.Routing.control({
			waypoints: [
				L.latLng(42.266365, -83.211343),
				L.latLng(42.242492, -83.682140)
			],
			lineOptions: {
				styles: [ {color: 'white',opacity: 0.8, weight: 12},
				{color: '#2676C6', opacity: 1, weight: 6}]},
			serviceUrl: 'http://streetmap.test.com:5000'
		}).addTo(mymap);
    </script>
</body>
</html>
````

**Comment by jtackk** [comment]
I'm having the same basic problem. Get back a malformed url:
http://192.168.240.78:5000/viaroute/driving/-83.5956,42.873;-83.763,43.0974?overview=false&alternatives=true&steps=true&hints=;

I've tried it this way:
    var closureRoute = L.Routing.control({
        waypoints: routePoints,
        lineOptions: { styles: [{ color: 'red', opacity: 1, weight: 5 }] },
        serviceUrl: 'http://192.168.240.78:5000'
     }).addTo(myMap);

and also with "viaroute" in the serviceurl
    var closureRoute = L.Routing.control({
        waypoints: routePoints,
        lineOptions: { styles: [{ color: 'red', opacity: 1, weight: 5 }] },
        serviceUrl: 'http://192.168.240.78:5000/viaroute'
     }).addTo(myMap);

**Comment by jtackk** [comment]
I got mine fixed by adding the profile option to the call.

var closureRoute = L.Routing.control({
waypoints: routePoints,
lineOptions: { styles: [{ color: 'red', opacity: 1, weight: 5 }] },
profile: 'route/v1/driving',
serviceUrl: 'http://192.168.240.78:5000'
}).addTo(myMap);

**Comment by codepro1** [comment]
Using profile has resolve the issue.  Thanks!

**Comment by perliedman** [comment]
When using a custom `serviceUrl`, the path `route/v1` should be included. For example, the default value for `serviceUrl` is `https://router.project-osrm.org/route/v1`, and your overridden value should look the same way.

**Comment by jtackk** [comment]
After reading your reply, consider this a "duh" moment for me. And thanks for the reply.
