### ISSUE TITLE
New Api of route.project-OSRM 

### ISSUE THREAD

**Issue by booper** [perliedman/leaflet-routing-machine#287]
Hey,
Using your plugin got an error from server:
![2016-08-25_1933](https://cloud.githubusercontent.com/assets/583898/17979269/645e11a4-6b02-11e6-8736-f6f13fe433db.png)

When i post issue on OSRM project git, i got reply:

> @booper you're hitting the V4 api (/viaroute) which we will be deprecating soon. We're not monitoring it for uptime at all any more. Please take this opportunity to move to the new API.

Will you update this amazing plugin with new API ?

**Comment by danpat** [comment]
@booper See https://github.com/perliedman/leaflet-routing-machine/pull/226

Support for v5 is available via the L.Routing.OSRMv1 object.

**Comment by perliedman** [comment]
Yes, as @danpat says, you should use `L.Routing.OSRMv1`. However, that should be the default if you use Leaflet Routing Machine 3.0.0 or later.

I realized the API docs is somehow missing the docs for the `OSRMv1` class, I'll have to check why that change hasn't be pushed, but unfortunately it might be on a computer that I don't have access to.
