### ISSUE TITLE
OSRM problem frequently

### ISSUE THREAD

**Issue by mepadron** [perliedman/leaflet-routing-machine#291]
Good afternoon to let me know that this error is due:

GET https://router.project-osrm.org/route/v1/driving/-67.34821389999999,9.92991…0003,9.891369599999999?overview=false&alternatives=true&steps=true&hints=; **503 (Service Unavailable: Back-end server is at capacity**)d @ leaflet-routing-machine.min.js:3d.Routing.OSRMv1.d.Class.extend.route @ leaflet-routing-machine.min.js:4d.Routing.Control.d.Routing.Itinerary.extend.route @ leaflet-routing-machine.min.js:3d.Routing.Control.d.Routing.Itinerary.extend.initialize @ leaflet-routing-machine.min.js:3NewClass @ leaflet-src.js:229d.Routing.control @ leaflet-routing-machine.min.js:3(anonymous function) @ app.js:274
leaflet-routing-machine.min.js:3 XHR finished loading: GET "https://router.project-osrm.org/route/v1/driving/-67.34821389999999,9.92991…00003,9.891369599999999?overview=false&alternatives=true&steps=true&hints=;".d @ leaflet-routing-machine.min.js:3d.Routing.OSRMv1.d.Class.extend.route @ leaflet-routing-machine.min.js:4d.Routing.Control.d.Routing.Itinerary.extend.route @ leaflet-routing-machine.min.js:3d.Routing.Control.d.Routing.Itinerary.extend.initialize @ leaflet-routing-machine.min.js:3NewClass @ leaflet-src.js:229d.Routing.control @ leaflet-routing-machine.min.js:3(anonymous function) @ app.js:274
**leaflet-routing-machine.min.js:3 Routing error: Object {status: -1, message: "HTTP request failed: [object XMLHttpRequest]"}**

**Comment by perliedman** [comment]
This is because OSRM's demo server is down.

The demo server is free, but comes without SLA or warranties. It often works, but sometimes it doesn't.

If you need better uptime, I suggest paying for a service provider (Mapbox's directions API is built on OSRM and works with LRM out of the box), or setting up your own server, which isn't that hard or expensive if you don't need global coverage.

**Comment by catbadger** [comment]
The demo server is teh suck. You can't use it in production. Also this is a duplicate issue.
