### ISSUE TITLE
Unable to load routes from https://router.project-osrm.org

### ISSUE THREAD

**Issue by madebymats** [perliedman/leaflet-routing-machine#294]
`XMLHttpRequest cannot load https://router.project-osrm.org/route/v1/driving/2.3469,48.8588;4.9039,52.3546?overview=false&alternatives=true&steps=true&hints=;. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.liedman.net' is therefore not allowed access. The response had HTTP status code 504.`

**Comment by andrx** [comment]
I also have something similar:

`XMLHttpRequest cannot load https://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=38.462661,-77.622253&loc=38.257685,-77.496633. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localversion' is therefore not allowed access.`

When I go to this link manually [https://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=38.462661,-77.622253&loc=38.257685,-77.496633](https://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=38.462661,-77.622253&loc=38.257685,-77.496633) I see the following error message:

	The OSRM Demo server has moved to API Version 5. Documentation for the new version can be found at https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

**Comment by catbadger** [comment]
This is a duplicate. Please search before posting issues.

**Comment by madebymats** [comment]
Sorry about that.

**Comment by perliedman** [comment]
@andrx you're using the old OSRM 4 demo server, that has been shut down. You need to either upgrade your Leaflet Routing Machine to 3.0.0 or later (that has OSRM 5 support by default), or host your own OSRM 4 server.

**Comment by andrx** [comment]
@perliedman thank you! don't know why but my bower.json was set to 2.6.2 version
So, it started to work but some custom functionality doesn't. I don't see where exactly the problem starts, but [here](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.OSRMv1.js#L134) something strange happens. it reverses _lat_ and _lng_ property values. I can't check now, but possibly OSRM4 was serving location as `[lat, lng]` and OSRM5 as `[lng, lat]`.

Anyway, [this seems](https://github.com/andrx/leaflet-routing-machine/commit/5f7eb35fe507f06430ed2065994890fcb720aa8d) to fix custom functionality built on top of Leaflet Routing Machine on my end. Not sure if it brakes anything else but so far, so good. I can create pull request if you think it's ok.

**Comment by perliedman** [comment]
@andrx ok, hard to tell without seeing running code, but OSRM v5 uses lng/lat order as compared to v4, that used lat/lng.

**Comment by andrx** [comment]
@perliedman I set up a quick and dirty [jsfiddle sample](http://jsfiddle.net/pu39s9wn/8/) to illustrate it.

**Comment by perliedman** [comment]
@andrx unfortunately, it doesn't load for me.

Have you tried the tutorials/examples in LRM? They're pretty basic and use the new OSRM 5 API, and have no trouble with swapped lat/lng.

**Comment by andrx** [comment]
sorry, @perliedman looks like it works with Chrome and not with other browsers. I moved it [here](http://s.codepen.io/andrx/debug/QKyyWR), and [the code](http://codepen.io/andrx/pen/QKyyWR). It should load now. Example shows how to get waypoints when the route has been selected. Waypoints contain correct `L.LatLng` objects. However, after `routeselected` event fired, waypoints contain `L.LatLng` objects with swapped lat/lng which is obviously a problem. 

Yes, I tried the examples. We've used LRM for year and a half already.

**Comment by perliedman** [comment]
@andrx sorry about that, I misunderstood the problem, but I totally get the problem once I saw your PR.

Great to hear that there are long time LRM users out there! Thanks for reporting problems, and even better with fixes for my mistakes!

**Comment by andrx** [comment]
@perliedman thank you for this great project!
