### ISSUE TITLE
Tutorials do not work

### ISSUE THREAD

**Issue by artemkarpovich** [perliedman/leaflet-routing-machine#295]
falls routing error. Calculating the route caused an error. No cors. status -1

**Comment by perliedman** [comment]
Checked all tutorials, and they work from here as far as I can see.

Just guessing, but OSRM's demo server (that the demos and tutorials use) might have been down when you tested. Does it work for you now, and could you otherwise post a link to the tutorial that doesn't work?

**Comment by artemkarpovich** [comment]
All tutorials work now, thanks.

**Comment by artemkarpovich** [comment]
the second day of the same error. down server.
![image](https://cloud.githubusercontent.com/assets/14793310/18464119/a1fdf328-7997-11e6-9c0b-9ea17baafd9c.png)

**Comment by perliedman** [comment]
@artemkarpovich sorry, but I have no control over OSRM's demo server, and it's not a part of Leaflet Routing Machine.

Note that the demo server is free to use for anyone, but that also means it comes without any guarantees. I'm hoping on better stability than the current situation, but the only long term solution if you really need stability is to pay for the service (like Mapbox), or set up your own server (easy as long as you only need to cover a limited geographic area).

**Comment by artemkarpovich** [comment]
@perliedman , thanks for answer. I will take note of your advice.

**Comment by catbadger** [comment]
@perliedman The OSRM project is aware of this and afaik there are no plans to fix the demo server.

@artemkarpovich - You should likely set up your own gis server with osrm and tile maps.
