### ISSUE TITLE
spliceLatLngs is not a function (LRM 3.0.0-beta.1)

### ISSUE THREAD

**Issue by qvsmith** [perliedman/leaflet-routing-machine#298]
On line 304 in L.Routing.Plan:
`lines[i].spliceLatLngs(1, 1, e.latlng);`
Throws error mentioned in title.

That line can be replaced with:
`lines[i].setLatLngs(lines[i].getLatLngs().splice(1, 1, e.latlng));`

Would have created a PR but, still a bit new to GitHub and not sure which branch to contribute to :)

**Comment by catbadger** [comment]
Thanks.

**Comment by qvsmith** [comment]
My apologies.

I realised that splice doesn't return original array so my suggestion above is invalid.
To be functionally equivalent to previous line of code, it has to be split out and will have to look someting like:

`var latLngs = lines[i].getLatLngs();`
`latLngs.splice(1, 1, e.latlng);`
`lines[i].setLatLngs(latLngs);`

**Comment by perliedman** [comment]
This was fixed in c3dd45c2814f77a33b69f1518864488ff8fae89d.
