### ISSUE TITLE
Cannot read property 'call' of undefined on addTo(map)

### ISSUE THREAD

**Issue by Qcharton** [perliedman/leaflet-routing-machine#299]
Hi,

i'm trying to use leaflet-routing-machine to display a simple itinerary on my map.

The fact is, when i set my route with : 

```
L.Routing.control({
  waypoints: [
    L.latLng(57.74, 11.94),
    L.latLng(57.6792, 11.949)
  ]
}).addTo(map);
```

with custom latlng points, i get the error displayed on the title. 
The itinerary is display on the map but i even got this error and i can't do anything after the code above.

For information i use : 

Leaflet : https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js

l-r-m : V 3.1.1

I can't use an other leaflet version because i already use too many plugins and i don't want to readjust everything.

here is the detail of the error from my console : 

> leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined
> whenReady @ leaflet.js:6
> addLayer @ leaflet.js:6
> onAdd @ leaflet-routing-machine.js:455
> addTo @ leaflet.js:8
>(anonymous function) @ script.js?:231
> (anonymous function) @ control.geocoder.js:376
> (anonymous function) @ q=aze&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0:1
> 

do anyone have already encountered the same problem ?

Thanks for your help !

**Comment by perliedman** [comment]
The master version of LRM is unfortunately not compatible with Leaflet 1.0.0, which is the reason you're seeing this error.

There's a `develop` branch you can use: it is compatible with Leaflet 1.0.0, but also contains a lot of experimental features.

I'll try to fix 1.0.0 support in the master branch soon!

**Comment by Qcharton** [comment]
oh ok ! Well, I'll waiting for an update that will make LRM be compatible with leaflet 1.0.0.
For now, i'll try to deal with version 0.7.

Thanks a lot for the fast reply !

**Comment by perliedman** [comment]
From now on, `master` branch is compatible with Leaflet 1.0.0. Can't believe it took me this long to make this really trivial fix. Thanks for the nudge, @Qcharton!

**Comment by Lawrence23** [comment]
I am still getting this error. And I can't find your latest code in the dist folder

**Comment by perliedman** [comment]
@Lawrence23 haven't made a release of this change. Either build from master, or wait for a new release.

**Comment by cordovapolymer** [comment]
still getting this error on lrm 3.2.5 and leaflet 1.0.3

**Comment by perliedman** [comment]
@cordovapolymer please provide an example illustrating the problem you're seeing. The demo site (http://www.liedman.net/leaflet-routing-machine/) uses Leaflet 1.0.1, so LRM definitely works with Leaflet 1.0.
