### ISSUE TITLE
Marker not getting plotted

### ISSUE THREAD

**Issue by priya12891** [perliedman/leaflet-routing-machine#301]
Hii 
I am using LRM 3.1.1 - L.Routing.OSRMv1 route gets draw but marker not creating
is there any plroblem with new api
Or i want to add any extra permission

is it necessary to add **geocoder**

**JQuery for adding marker is ::**

```
{
L.Routing.control({
        plan: L.Routing.plan(data5, {
            createMarker: function(i, wp) {         
                return L.marker(wp.latLng, {
                    draggable: false,
                    icon: new L.NumberedDivIcon({number: (i)})
                }).bindPopup("Time:"+tConvert(data6[i]));

            },
            routeWhileDragging: false
        }),
        lineOptions : {
            addWaypoints: false,
            styles:[{color: 'black', opacity: 0.15, weight: 9}, {color: 'white', opacity: 0.8, weight: 6}, {color: '#43ABDB', opacity: 1, weight: 6}]
        },
        waypointMode:'snap'
    }).addTo(map);
}
```

**Comment by perliedman** [comment]
Hard to tell without seeing a running example. From a quick look the codes looks ok.

Check your console for any error messages. For example, how is `L.NumberedDivIcon` defined?

**Comment by perliedman** [comment]
Closing for now, feel free to add more information if you feel this is still an issue.
