### ISSUE TITLE
RouteSelectedEvent have all waypoints with lattitude and longtitude reversed

### ISSUE THREAD

**Issue by candidtim** [perliedman/leaflet-routing-machine#303]
It seems that in the `RouteSelectedEvent` (in response to `routeselected`), waypoints array in the `IRoute` included have all waypoints with lattitude and longtitude misplaced with each other (lat instead of lng, and vice versa). 

Following example shows the issue. For example, use same code as in [basic tutorial](http://www.liedman.net/leaflet-routing-machine/tutorials/basic-usage/) and only change the JS to the following:

```
        var map = L.map('map');

        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap contributors'
        }).addTo(map);

        // added `routing` var
        var routing = L.Routing.control({
            waypoints: [
                L.latLng(57.74, 11.94),
                L.latLng(57.6792, 11.949)
            ],
            routeWhileDragging: true
        }).addTo(map);
    
        // added event handler
        L.DomEvent.on(routing, 'routeselected', function(event) {
            console.log(JSON.stringify(event.route.waypoints));
            console.log(JSON.stringify(routing.getWaypoints()));
        });
```

And it is seen that waypoints in the routing event are:

```
[{"options":{"allowUTurn":false},"latLng":{"lat":11.940062,"lng":57.739978},"_initHooksCalled":true},{"options":{"allowUTurn":false},"latLng":{"lat":11.948969,"lng":57.679211},"_initHooksCalled":true}]
```

Interesting that waypoints in the routing control itself are correct (although not as precise, because start-end are not replaced on routing events):

```
[{"options":{"allowUTurn":false},"latLng":{"lat":57.74,"lng":11.94},"_initHooksCalled":true},{"options":{"allowUTurn":false},"latLng":{"lat":57.6792,"lng":11.949},"_initHooksCalled":true}]
```

I'm using Leaflet 0.7.3 and Leaflet Routing Machine 3.1.1

**Comment by perliedman** [comment]
Hi,

what version of LRM are you running? This should have been fixed by 8dc69a67fa1192914eb2f584322af5664984aff8, so if you run latest the coordinates should be correct.

**Comment by candidtim** [comment]
Aha, that's it then. I'm using 3.1.1, I didn't realize there is 3.1.2 already. I will upgrade, thank you.

**Comment by perliedman** [comment]
@candidtim there's always a new version in JavaScript/npm land! :wink:
