### ISSUE TITLE
Order of waypoints when adding a new WP on an existing route (A->B->C turns into A->C->B)

### ISSUE THREAD

**Issue by arminus** [perliedman/leaflet-routing-machine#305]
Taking the demo route on http://www.liedman.net/leaflet-routing-machine/ as an example:

A = Paris, B = Amsterdam, now create WP C by clicking **onto** the route, say somewhere in Belgium.

I would have expected that I now get a route which goes from A->B->C and which is thus significantly longer than the original 500km, but I don't, because apparently the order of the waypoints is changed to A->C->B.

Why is that and how could it be avoided (i.e. I really want to keep the order of the waypoints in which they were created by the user)?

**Comment by perliedman** [comment]
Clicking on the route is a means to add via points. You click and drag the line to insert the via point where you like. It's a feature, and works like Google Maps last time I checked.

If you want to prevent this behavior, you can disable it by using the option `addWaypoints: false` when creating the routing line; when creating the control, this should work:

```
L.Routing.control({
  ....
  lineOptions: { addWaypoints: false }
}
```

**Comment by arminus** [comment]
Confirmed that this works - but then this also prevents me from inserting a via point by a "click-drag" on the route (which one could argue is a different intent, i.e. click-drag means change the existing route, while single click is insert a new and additional waypoint).

I'm just in the process of trying if I can override routeLine to see if I can influence the point order there...

**Comment by perliedman** [comment]
Yes, that is of course a good option as well. I think you're looking for this line: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Line.js#L117
