### ISSUE TITLE
L.Routing.OSRM  is not a function (LRM 3.1.2)

### ISSUE THREAD

**Issue by Alexus230** [perliedman/leaflet-routing-machine#306]
I am trying to use LRM with OSRM v4, which uses the old API. When my script calls the function `L.Routing.OSRM`  console says:

```
L.Routing.OSRM  is not a function
```

I realized that pre-builded JS in "dist" catalogue doesn't include this function. But I see L.Routing.OSRM.js in "src". So I add this file in L.Routing.Control.js

``` js
...
L.extend(L.Routing, require('./L.Routing.OSRM'));
...
```

and build distrib. Error with function has disappeared, but I've found that leaflet is broken and routes are not displayed.

**Comment by catbadger** [comment]
Hi @Alexus230. That's probably not how to do that.
Have you included jQuery, leaflet.js and leaflet-routing-machine.min.js?

**Comment by perliedman** [comment]
@Alexus230 yeah, sorry about that, OSRM v4 support is broken like you say, the class isn't included. Having said that, I would have expected your fix to work - it should be enough to include the class like you did.

Do you have an error message, what does your code for creating the control look like?

@catbadger neither LRM or Leaflet depends on jQuery, so no need to load it.

**Comment by Alexus230** [comment]
Hello @perliedman. 

I use the code provided below:
```js
        L.Routing.control({
                router: L.Routing.OSRM({
                serviceUrl: 'http://map.server.lan/viaroute'
                }),
          waypoints: [
                L.latLng(55.797514, 37.932964),
                L.latLng(55.4223, 37.891433)
          ]
        }).addTo(map);
```

Error in console:
```
leaflet.js:5 Uncaught TypeError: this.callInitHooks is not a function

e	@	leaflet.js:5
(anonymous function)	@	(index):77

```

By the way, I use Leaflet 1.0.0-rc3

**Comment by perliedman** [comment]
@Alexus230 ok, will have to check that out, sounds weird.

**Comment by martinnaughton** [comment]
I am also getting the same issue. Here is the complete code that I am using 

The error i am getting 
`TypeError: this.callInitHooks is not a function
L.Class.extend/NewClass()
leaflet.js:314
<anonymous>
route.html:13
[Learn More]`

`  <html>
<head>
<link rel="stylesheet" href="leaflet.css" />
<script src="leaflet.js"></script>
<script type="text/javascript" src="leaflet.ajax.js"></script>
<link rel="stylesheet" href="leaflet-routing-machine.css" />
<script src="leaflet-routing-machine.js"></script>
</head>

 <body>
<script>
        var waypoints = [ L.Routing.Waypoint(L.latLng(54.6958153, -5.94996)), L.Routing.Waypoint(L.latLng(54.639743, -5.710526)) ];
        var router = L.Routing.osrmv1();
        router.route(waypoints, function(results){
                        console.log("There is a way");
                        console.log(results);
                    });

</script>
</body>
</html>  `

I tracked it down to this callInitHooks line.
`L.Class.extend = function (props) {

	// @function extend(props: Object): Function
	// [Extends the current class](#class-inheritance) given the properties to be included.
	// Returns a Javascript function that is a class constructor (to be called with `new`).
	var NewClass = function () {

		// call the constructor
		if (this.initialize) {
			this.initialize.apply(this, arguments);
		}

		// call all constructor hooks
		this.callInitHooks();
	};`

**Comment by curtisy1** [comment]
Closing as v4 support should be enabled by using [lrm-osrm4](https://github.com/perliedman/lrm-osrm4)
