### ISSUE TITLE
The OSRM Demo server has moved to API Version 5

### ISSUE THREAD

**Issue by bardu** [perliedman/leaflet-routing-machine#310]
I have installed leaflet and leaflet-routing-machine via npm.

leaflet version is: 0.7.7
leaflet-routing-machine version is: 3.1.2

my implementation looks like this:
```
class MapWithRouting extends Map {
    componentDidMount() {
        super.componentDidMount();
        const { business, userCoords } = this.props;
        const that = this;
        const routingControl = L.Routing.control(
                                    {
                                        plan: L.Routing.plan([
                                            L.latLng([business.location.coordinates[1], business.location.coordinates[0]]),
                                            L.latLng(userCoords)
                                        ],{
                                            createMarker: function() {return false}
                                        }),
                                        autoRoute: true,
                                        show: false,
                                        fitSelectedRoutes: true,
                                        serviceUrl: 'https://router.project-osrm.org/viaroute'
                                    }
                                );
        routingControl.on('routesfound', function(e) {
            // add routing to map
            that.leafletElement.add(this);
        });
        routingControl.on('routingerror', function(e) {
            console.log('routing error = ', e.message);
        });             
    }
}
```
which generates the following request:

https://router.project-osrm.org/viaroute/driving/-135.052892,60.7196;-135.1435311,60.7765783?overview=false&alternatives=true&steps=true

which response to:

> The OSRM Demo server has moved to API Version 5. Documentation for the new version can be found at https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md

Any idea what's going on or what I missed?

**Comment by catbadger** [comment]
You're using the wrong server for the version of OSRM you're using. Don't use the demo server.

**Comment by bardu** [comment]
Thanks. Do you know the right sercvieUrl?

**Comment by catbadger** [comment]
We set up our own OSRM server on our dedicated mapping server, so nope I can't help you there, but the guys in the osrm room on irc should have an answer.

**Comment by bardu** [comment]
OK, looks like this is the right one:
http://router.project-osrm.org/route/v1

**Comment by perliedman** [comment]
@bardu note that you don't have to set that `serviceUrl` explicitly, it's the default!

**Comment by bardu** [comment]
@perliedman  OK, thanks.
