### ISSUE TITLE
Tracing road, get loop

### ISSUE THREAD

**Issue by emulienfou** [perliedman/leaflet-routing-machine#311]
Hi, since I update the library from **2.6.0** to **3.1.1**, my road is not a single `one-way` road but a loop road.

And **IF** I click on this road going back from by destination to my starting point, this road disappear!

This is an sample of my code:

```
var secondaryRoute = {
0: {lat: 45.778577982045285, lng: -74.00321352114872},
1: {lat: 45.7384398, lng: -74.13826619999998}
![screenshot](https://cloud.githubusercontent.com/assets/84061/18936287/18827050-85b4-11e6-94e4-9905ec40fb23.png)

};
L.Routing.control({
                 waypoints: secondaryRoute,
                 lineOptions: {
                     styles: [
                         { color: '#000', opacity: 1, weight: 2 }
                     ]
                 }
}).addTo(map);
```

![screenshot](https://cloud.githubusercontent.com/assets/84061/18936298/3309dce2-85b4-11e6-866f-65f7baefa2a9.png)

Thanks for your help!

**Comment by perliedman** [comment]
I think there must be something more to the code than what you posted above.

Here's a short example using more or less the code you posted above: http://playground-leaflet.rhcloud.com/here/edit?html,output

(I did however change the `secondaryRoute` variable to be a normal array.)

**Comment by perliedman** [comment]
Closing this for now, feel free to add more information if you feel this is an issue with Leaflet Routing Machine!
