### ISSUE TITLE
How to show icon if collapsible undefined

### ISSUE THREAD

**Issue by holimatic** [perliedman/leaflet-routing-machine#317]
I want to show the nice icon also if collapsible not defined in option list. How can I do that?

        var routingControl = L.Routing.control({
          waypoints: [null],
          routeWhileDragging: false,
          //showAlternatives: false,
          show: false,
          //collapsible: true,
          language: getcc,
          geocoder: L.Control.Geocoder.nominatim(),
          autoRoute: true,
        });//.addTo(map);
        map.addControl(routingControl);

**Comment by holimatic** [comment]
This is solved. One can add background-image in css file.
 `.leaflet-control-container .leaflet-routing-container-hide {
    width: 36px;
    height: 36px;
    background-image: url('routing-icon.png');
}
`

**Comment by perliedman** [comment]
👍
