### ISSUE TITLE
Incorrect object scale

### ISSUE THREAD

**Issue by hclubmk** [perliedman/leaflet-routing-machine#321]
After adding the object like a polyline and remove **L.Routing.control**, the added object is scaled incorrectly:
```
...
L.polyline([L.latLng(57.74, 11.94),L.latLng(57.6792, 11.949)], {color: "black",weight: 3,opacity: 1,smoothFactor: 1}).addTo(map);
...
map.removeControl (control);
```
After the object is scaled incorrectly on zoon-in and zoom-out.

**Comment by perliedman** [comment]
Could you provide a running example? Any errors in the console?

This sounds like a possible duplicate of #304.

**Comment by hclubmk** [comment]
Fix #304 applied.

**index.js** from your exaple:
```
var map = L.map('map');

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var control = L.Routing.control(L.extend(window.lrmConfig, {
	waypoints: [
		L.latLng(57.74, 11.94),
		L.latLng(57.6792, 11.949)
	],
	geocoder: L.Control.Geocoder.nominatim(),
	routeWhileDragging: true,
	reverseWaypoints: true,
	showAlternatives: true,
	altLineOptions: {
		styles: [
			{color: 'black', opacity: 0.15, weight: 9},
			{color: 'white', opacity: 0.8, weight: 6},
			{color: 'blue', opacity: 0.5, weight: 2}
		]
	}
})).addTo(map);

L.Routing.errorControl(control).addTo(map);

// add polyline
L.polyline([L.latLng(57.74, 11.94),L.latLng(57.6792, 11.949)], {color: "black",weight: 3,opacity: 1,smoothFactor: 1}).addTo(map);

// wait some time and remove control
setTimeout('map.removeControl(control);',5000);
// here is problem begin. Until control not removed - no probem detected
```

**Comment by perliedman** [comment]
Again, please tell if the console shows any errors.

Please realize I don't actively work with this project, so my time to put into debugging other users issues is _very limited_.

**Comment by hclubmk** [comment]
Console:

> Uncaught TypeError: Cannot read property 'getZoom' of null
> (anonymous function)	@	leaflet-routing-machine.js:465
> fire					@	leaflet.js:5
> _moveEnd			@	leaflet.js:5
> (anonymous function)	@	leaflet.js:9

**Comment by perliedman** [comment]
Sounds like a listener is still registered after the control is removed, which causes it to throw and then botches up Leaflet's internals.

I would check which handler it's in on line 465. We should make sure that listener is removed when the control is removed.

**Comment by hclubmk** [comment]
It was my folt, your fix absolutly solves the problem. Excuse for troubling.
