### ISSUE TITLE
Change route color

### ISSUE THREAD

**Issue by mathisloge** [perliedman/leaflet-routing-machine#322]
Hello, 
how to change the style of a route, if the route is already present? 
And how to change the color of the line between two segments? 

Like this: https://drive.google.com/file/d/0B-a8saE9ykmfVUFvcW03SEQ3VWs/view?usp=sharing

**Comment by perliedman** [comment]
You can override how the line is created using the `routeLine` option (see [docs for `L.Rounting.Control`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control)). For example, you could use something like [MultiOptionsPolyline](http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/).

Having said that, it might be a bit tricky to get exactly the same functionality as the default line class `L.Routing.Line` has, so depending on your use case, this might be complicated.
