### ISSUE TITLE
Uncaught TypeError: Cannot read property 'control' of undefined

### ISSUE THREAD

**Issue by oliverwilson118** [perliedman/leaflet-routing-machine#326]
I get an error message in the console 'Uncaught TypeError: Cannot read property 'control' of undefined' where am I going wrong? Has anyone else experienced this issue?

**Comment by catbadger** [comment]
Can you share some code please?

**Comment by oliverwilson118** [comment]
Yeah thanks here you go: 


<!DOCTYPE html>
<html>
<head>
	<title>Cornwallis UKC</title>
	
	<link rel="stylesheet" type="text/css" href="css/keylayout.css" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css"/>
	<link rel="stylesheet" href="css/searchbar.css"> 
	<link rel="stylesheet" href="theme/jquery-ui.css">
	<link rel="stylesheet" href="routing/dist/leaflet-routing-machine.css" />
	
	

	<script src="jQuery/jquery.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="javascript/main.js"></script>
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
    <script src="javascript/markers/Leaflet.MakiMarkers.js"></script>
    <script src="routing/dist/leaflet-routing-machine.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <div id="leftcolumn">
            <div id="map"></div>
			<script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
			<script type="text/javascript">
				var imageBounds = L.latLngBounds([[51.29930, 1.06877], [51.29997, 1.07155]]); //SW and NE coordinates
				var imageUrl = 'cornwallis_first_border.png';

				var map = L.map('map', {zoomControl:false}).setView([51.29915, 1.07020], 19);
				var overlay = L.imageOverlay(imageUrl, imageBounds).addTo(map);
				var osm = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';

				L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var here_icon = L.icon({
				    iconUrl: 'red_icon.png',
				    iconRetinaUrl: 'red_icon.png',
				    //first number is left and right, second is up and down:
				    iconSize: [38, 40],
				    iconAnchor: [18, 40],
				    tooltipAnchor: [10, 0]
				});


				var marker_mainEntrance = L.marker([51.29842, 1.07009], {icon: here_icon}).addTo(map); marker_mainEntrance.bindTooltip("<b>Main Entrance!</b><br>School of Computing.",  {permanent: true, direction: 'right'});
				map.dragging.disable(); map.scrollWheelZoom.disable(); map.doubleClickZoom.disable(); map.touchZoom.disable();
				 marker_mainEntrance.setOpacity(1);

				var marker_SW101 = L.marker([51.29851, 1.06987]).addTo(map); marker_SW101.bindPopup("<b>SW101!</b><br>Homework Club.");
				 marker_SW101.setOpacity(0);

				var marker_SW101b = L.marker([51.29961, 1.06993]).addTo(map); marker_SW101b.setOpacity(0);

				var marker_deliveries = L.marker([51.29859, 1.07044]).addTo(map); marker_deliveries.bindPopup("<b>Delivery Office!</b><br>All Deliveries Must Be Delivered Here.");
				 marker_deliveries.setOpacity(0);

				//L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.ey//J1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var routesw101 = L.Routing.Control({
						  waypoints: [
						    L.latLng(51.29842, 1.07009),
						    L.latLng(51.29851, 1.06987)
						  ]
						}).addTo(map);




				var lastSearchedRoom = "";
				function mapfunc(){
					if (document.getElementById("searchbox").value == "Main Entrance"){
						clearLastSearched();
						marker_mainEntrance.setOpacity(1);
						marker_mainEntrance.togglePopup();
						lastSearchedRoom = "Main Entrance";
						document.getElementById('directionLbl').innerHTML = ""
						document.getElementById('directionsLbl').innerHTML = "Welcome to the School of Computing";
					}
					else if (document.getElementById("searchbox").value == "SW101"){
						clearLastSearched();
						marker_SW101.setOpacity(1);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(1);
						lastSearchedRoom = "SW101";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Go up the stairs and through the doors in front of you.<br>\ 2. Turn left, then right then left.<br>\ 3. Continue forward through two sets of doors.<br>\ 4. SW101 is the third door on your left.";

					}
					else if (document.getElementById("searchbox").value == "Delivery Office"){
						clearLastSearched();
						marker_deliveries.setOpacity(1);
						marker_deliveries.togglePopup();
						lastSearchedRoom = "Delivery Office";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Turn right through the double doors on the ground floor.<br>\ 2. Walk to the end of the hallway.<br>\ 3. The Delivery Office is the last door on your right.";
					}
				}

				function clearLastSearched(){
					if(lastSearchedRoom == "Main Entrance"){
						marker_mainEntrance.setOpacity(0);
						marker_mainEntrance.togglePopup();
					}
					else if(lastSearchedRoom == "SW101"){
						marker_SW101.setOpacity(0);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(0);
						marker_SW101b.togglePopup();
					} 
					else if(lastSearchedRoom == "Delivery Office"){
						marker_deliveries.setOpacity(0);
						marker_deliveries.togglePopup();
					} 
					else if(lastSearchedRoom == "") return;
				}
			</script>
        </div>

        <div id="rightcolumn">
           <h1> Cornwallis Room Finder </h1>
			<form id="searchform">
                                <input id="searchbox" type="text" placeholder="Search Room/Staff" required>
                                <input id="searchbtn" type="button" value="Search" onclick="mapfunc()">
                                <label id="directionLbl"><br></label>
                                <label id="directionsLbl">Welcome to the School of Computing</label>
			</form>
       </div>
    </div>
</body>
</html>

**Comment by oliverwilson118** [comment]
`<!DOCTYPE html>
<html>
<head>
	<title>Cornwallis UKC</title>
	
	<link rel="stylesheet" type="text/css" href="css/keylayout.css" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css"/>
	<link rel="stylesheet" href="css/searchbar.css"> 
	<link rel="stylesheet" href="theme/jquery-ui.css">
	<link rel="stylesheet" href="routing/dist/leaflet-routing-machine.css" />
	
	

	<script src="jQuery/jquery.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="javascript/main.js"></script>
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
    <script src="javascript/markers/Leaflet.MakiMarkers.js"></script>
    <script src="routing/dist/leaflet-routing-machine.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <div id="leftcolumn">
            <div id="map"></div>
			<script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
			<script type="text/javascript">
				var imageBounds = L.latLngBounds([[51.29930, 1.06877], [51.29997, 1.07155]]); //SW and NE coordinates
				var imageUrl = 'cornwallis_first_border.png';

				var map = L.map('map', {zoomControl:false}).setView([51.29915, 1.07020], 19);
				var overlay = L.imageOverlay(imageUrl, imageBounds).addTo(map);
				var osm = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';

				L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var here_icon = L.icon({
				    iconUrl: 'red_icon.png',
				    iconRetinaUrl: 'red_icon.png',
				    //first number is left and right, second is up and down:
				    iconSize: [38, 40],
				    iconAnchor: [18, 40],
				    tooltipAnchor: [10, 0]
				});


				var marker_mainEntrance = L.marker([51.29842, 1.07009], {icon: here_icon}).addTo(map); marker_mainEntrance.bindTooltip("<b>Main Entrance!</b><br>School of Computing.",  {permanent: true, direction: 'right'});
				map.dragging.disable(); map.scrollWheelZoom.disable(); map.doubleClickZoom.disable(); map.touchZoom.disable();
				 marker_mainEntrance.setOpacity(1);

				var marker_SW101 = L.marker([51.29851, 1.06987]).addTo(map); marker_SW101.bindPopup("<b>SW101!</b><br>Homework Club.");
				 marker_SW101.setOpacity(0);

				var marker_SW101b = L.marker([51.29961, 1.06993]).addTo(map); marker_SW101b.setOpacity(0);

				var marker_deliveries = L.marker([51.29859, 1.07044]).addTo(map); marker_deliveries.bindPopup("<b>Delivery Office!</b><br>All Deliveries Must Be Delivered Here.");
				 marker_deliveries.setOpacity(0);

				//L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.ey//J1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var routesw101 = L.Routing.Control({
						  waypoints: [
						    L.latLng(51.29842, 1.07009),
						    L.latLng(51.29851, 1.06987)
						  ]
						}).addTo(map);




				var lastSearchedRoom = "";
				function mapfunc(){
					if (document.getElementById("searchbox").value == "Main Entrance"){
						clearLastSearched();
						marker_mainEntrance.setOpacity(1);
						marker_mainEntrance.togglePopup();
						lastSearchedRoom = "Main Entrance";
						document.getElementById('directionLbl').innerHTML = ""
						document.getElementById('directionsLbl').innerHTML = "Welcome to the School of Computing";
					}
					else if (document.getElementById("searchbox").value == "SW101"){
						clearLastSearched();
						marker_SW101.setOpacity(1);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(1);
						lastSearchedRoom = "SW101";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Go up the stairs and through the doors in front of you.<br>\ 2. Turn left, then right then left.<br>\ 3. Continue forward through two sets of doors.<br>\ 4. SW101 is the third door on your left.";

					}
					else if (document.getElementById("searchbox").value == "Delivery Office"){
						clearLastSearched();
						marker_deliveries.setOpacity(1);
						marker_deliveries.togglePopup();
						lastSearchedRoom = "Delivery Office";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Turn right through the double doors on the ground floor.<br>\ 2. Walk to the end of the hallway.<br>\ 3. The Delivery Office is the last door on your right.";
					}
				}

				function clearLastSearched(){
					if(lastSearchedRoom == "Main Entrance"){
						marker_mainEntrance.setOpacity(0);
						marker_mainEntrance.togglePopup();
					}
					else if(lastSearchedRoom == "SW101"){
						marker_SW101.setOpacity(0);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(0);
						marker_SW101b.togglePopup();
					} 
					else if(lastSearchedRoom == "Delivery Office"){
						marker_deliveries.setOpacity(0);
						marker_deliveries.togglePopup();
					} 
					else if(lastSearchedRoom == "") return;
				}
			</script>
        </div>

        <div id="rightcolumn">
           <h1> Cornwallis Room Finder </h1>
			<form id="searchform">
                                <input id="searchbox" type="text" placeholder="Search Room/Staff" required>
                                <input id="searchbtn" type="button" value="Search" onclick="mapfunc()">
                                <label id="directionLbl"><br></label>
                                <label id="directionsLbl">Welcome to the School of Computing</label>
			</form>
       </div>
    </div>
</body>
</html>`

**Comment by catbadger** [comment]
That's it? If that's all your code, I can tell you that your problem is in MakiMakers.

**Comment by oliverwilson118** [comment]
it is not letting me paste all my code for some reason... sorry! 

oh really? what is wrong with MakiMakers?

**Comment by perliedman** [comment]
@oliverwilson118 the error message is telling you that the term `control` is not defined, presumably in the context that you're trying to create an `L.Routing.control`, but `L.Routing` isn't defined. This error typically happens because the Leaflet Routing Machine code hasn't been loaded for one reason or another.

It's hard to tell without seeing more of your code and structure, but you should check that `leaflet-routing-machine.min.js` actually loads, and that the code where you're accessing it is _after_ you loaded the script.

I doubt that the problem is with MakiMarkers, but it's of course hard to tell.

**Comment by catbadger** [comment]
Sorry I was being glib in my first post. We need more of your code. maybe google how to paste code into github?

**Comment by oliverwilson118** [comment]
`<!DOCTYPE html>
<html>
<head>
	<title>Cornwallis UKC</title>
	
	<link rel="stylesheet" type="text/css" href="css/keylayout.css" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css"/>
	<link rel="stylesheet" href="css/searchbar.css"> 
	<link rel="stylesheet" href="theme/jquery-ui.css">
	<link rel="stylesheet" href="routing/dist/leaflet-routing-machine.css" />
	
	

	<script src="jQuery/jquery.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="javascript/main.js"></script>
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
    
    <script src="routing/dist/leaflet-routing-machine.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <div id="leftcolumn">
            <div id="map"></div>
			<script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
			<script type="text/javascript">
				var imageBounds = L.latLngBounds([[51.29930, 1.06877], [51.29997, 1.07155]]); //SW and NE coordinates
				var imageUrl = 'cornwallis_first_border.png';

				var map = L.map('map', {zoomControl:false}).setView([51.29915, 1.07020], 19);
				var overlay = L.imageOverlay(imageUrl, imageBounds).addTo(map);
				var osm = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';

				L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var here_icon = L.icon({
				    iconUrl: 'red_icon.png',
				    iconRetinaUrl: 'red_icon.png',
				    //first number is left and right, second is up and down:
				    iconSize: [38, 40],
				    iconAnchor: [18, 40],
				    tooltipAnchor: [10, 0]
				});


				var marker_mainEntrance = L.marker([51.29842, 1.07009], {icon: here_icon}).addTo(map); marker_mainEntrance.bindTooltip("<b>Main Entrance!</b><br>School of Computing.",  {permanent: true, direction: 'right'});
				map.dragging.disable(); map.scrollWheelZoom.disable(); map.doubleClickZoom.disable(); map.touchZoom.disable();
				 marker_mainEntrance.setOpacity(1);

				var marker_SW101 = L.marker([51.29851, 1.06987]).addTo(map); marker_SW101.bindPopup("<b>SW101!</b><br>Homework Club.");
				 marker_SW101.setOpacity(0);

				var marker_SW101b = L.marker([51.29963, 1.06982]).addTo(map); marker_SW101b.setOpacity(0);

				var marker_deliveries = L.marker([51.29859, 1.07044]).addTo(map); marker_deliveries.bindPopup("<b>Delivery Office!</b><br>All Deliveries Must Be Delivered Here.");
				 marker_deliveries.setOpacity(0);

				//L.tileLayer('https://api.mapbox.com/styles/v1/oliverwilson118/citv7be83003k2iqisq5c611p/tiles/256/{z}/{x}/{y}?access_token=pk.ey//J1Ijoib2xpdmVyd2lsc29uMTE4IiwiYSI6ImNpdHU4cXVxdTAwMTcyc29hemVpeWVvOXcifQ.jADpCIu12TqqyNoKkv-IGA', { maxZoom: 19, minZoom:7 }).addTo(map);

				var routez = L.Routing.control({waypoints: [L.latLng(51.29842, 1.07009), L.latLng(51.29851, 1.06987)]}).addTo(map);

			




				var lastSearchedRoom = "";
				function mapfunc(){
					if (document.getElementById("searchbox").value == "Main Entrance"){
						clearLastSearched();
						marker_mainEntrance.setOpacity(1);
						marker_mainEntrance.togglePopup();
						lastSearchedRoom = "Main Entrance";
						document.getElementById('directionLbl').innerHTML = ""
						document.getElementById('directionsLbl').innerHTML = "Welcome to the School of Computing";
					}
					else if (document.getElementById("searchbox").value == "SW101"){
						clearLastSearched();
						marker_SW101.setOpacity(1);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(1);
						lastSearchedRoom = "SW101";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Go up the stairs and through the doors in front of you.<br>\ 2. Turn left, then right then left.<br>\ 3. Continue forward through two sets of doors.<br>\ 4. SW101 is the third door on your left.";

					}
					else if (document.getElementById("searchbox").value == "Delivery Office"){
						clearLastSearched();
						marker_deliveries.setOpacity(1);
						marker_deliveries.togglePopup();
						lastSearchedRoom = "Delivery Office";
						document.getElementById('directionLbl').innerHTML = "Directions:"
						document.getElementById('directionsLbl').innerHTML = "1. Turn right through the double doors on the ground floor.<br>\ 2. Walk to the end of the hallway.<br>\ 3. The Delivery Office is the last door on your right.";
					}
				}

				function clearLastSearched(){
					if(lastSearchedRoom == "Main Entrance"){
						marker_mainEntrance.setOpacity(0);
						marker_mainEntrance.togglePopup();
					}
					else if(lastSearchedRoom == "SW101"){
						marker_SW101.setOpacity(0);
						marker_SW101.togglePopup();
						marker_SW101b.setOpacity(0);
						marker_SW101b.togglePopup();
					} 
					else if(lastSearchedRoom == "Delivery Office"){
						marker_deliveries.setOpacity(0);
						marker_deliveries.togglePopup();
					} 
					else if(lastSearchedRoom == "") return;
				}
			</script>
        </div>

        <div id="rightcolumn">
           <h1> Cornwallis Room Finder </h1>
			<form id="searchform">
                                <input id="searchbox" type="text" placeholder="Search Room/Staff" required>
                                <input id="searchbtn" type="button" value="Search" onclick="mapfunc()">
                                <label id="directionLbl"><br></label>
                                <label id="directionsLbl">Welcome to the School of Computing</label>
			</form>
       </div>
    </div>
</body>
</html>`

**Comment by oliverwilson118** [comment]
I am having issues with pasting the code. Could I email you instead?

Thanks for your help!

**Comment by perliedman** [comment]
@oliverwilson118 sorry if this sounds a bit harsh, but please don't. I'm happy to help, but please realize that I'm not paid to provide help on Leaflet Routing Machine - I'm more or less doing this in my free time or on breaks at work. Development is sometimes sponsored by my customers and sometimes directly by my employer, but support questions are not.

I'm very happy to answer quick questions and actual issues with LRM, but it simply is not possible for me to dig into other people's code outside work.

**Comment by Lweaver5051** [comment]
Hello everyone, 
I have made a post but not getting any responses. Im new to leaflet and dont know whats going on or why. I believe I added everything the documents say to add but I'm still getting the error. 

 _<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"></script>_

import L from 'leaflet';

### ERROR TypeError: Cannot read property 'control' of undefined
 My Code where -->  **var polylineRouteB = L.Routing.control**({**

**Comment by wadclapp** [comment]
Was getting this error originally too, when trying to add to my Leaflet project.

Now, after trying some different recent versions of LRM, I'm getting a slightly different error each time, along the lines of
```
Routing error: {status: -3, message: ...

leaflet-routing-machine.js?5bfd:11785 Routing error: {status: -3, message: "TypeError: Cannot read property 'x' of undefined"}

Routing error: {message: "HTTP request failed: undefined", url: "https://router.project-osrm.org/route/v1/driving/1…erview=false&alternatives=true&steps=true&hints=;", status: -1, target: XMLHttpRequest}
```
```javascript
import L from 'leaflet/dist/leaflet'
import 'leaflet-routing-machine'
```
...
```javascript
L.Routing.control({
  waypoints: [
    L.latLng(57.74, 11.94),
    L.latLng(57.6792, 11.949),
  ],
  routeWhileDragging: true,
}).addTo(this.map);
```

Any idea what's going wrong? Possibly something to do with Webpack? (I got it working outside my project env)

**Comment by wadclapp** [comment]
Ok, problem appears related to how I'm importing. Works fine using cdn links. What's the proper way to import?

**Comment by Zhikun-zack** [comment]
> I get an error message in the console 'Uncaught TypeError: Cannot read property 'control' of undefined' where am I going wrong? Has anyone else experienced this issue?

You should change the order of the leaflet.js and leaflet-routing-machine.min.js when you invoking them. Order Matter!!!

**Comment by rafaelSomerBarbosa** [comment]
> Ok, problem appears related to how I'm importing. Works fine using cdn links. What's the proper way to import?

import * as L from 'leaflet/dist/leaflet'
import 'leaflet-routing-machine'

**Comment by aldrichclementd** [comment]
Hi the error comes from the fact that you load your js before that of the leaflet-routing-machine. To correct this you must do this:

My personal js is: <script src="/js/jsfile.js"></script>

<img width="666" alt="Capture d’écran 2024-06-12 à 13 29 47" src="https://github.com/perliedman/leaflet-routing-machine/assets/68656322/ca342dc9-4ed7-4a20-a6b7-741f0950fad9">
