### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by dmalisani** [perliedman/leaflet-routing-machine#327]
In the home page, the sample shows an error ("routing error")
http://www.liedman.net/leaflet-routing-machine/

**Comment by perliedman** [comment]
Sorry, this is a problem with OSRM's demo server, not with Leaflet Routing Machine. The error message could be better, though.

The OSRM demo server will likely be up again in a while, try again then. Otherwise, use your own OSRM server, and LRM will work like a charm.
