### ISSUE TITLE
Improve error messages when OSRM server is down

### ISSUE THREAD

**Issue by priya12891** [perliedman/leaflet-routing-machine#329]
Hello,
When osrm demo server starts working fine And anather suggestion is Create a better error message on the site when the OSRM demo server is down.

**Comment by perliedman** [comment]
It's at least in part prevented by the fact that errors from OSRM's demo server does not include the `Access-Control-Allow-Origins` header. See https://github.com/Project-OSRM/osrm-backend/issues/3051

I'll try to improve the messages at least a bit, though.

**Comment by priya12891** [comment]
Hello sir ,

**Comment by priya12891** [comment]
Hello Sir,
But When osrm demo server starts working fine

**Comment by perliedman** [comment]
I've added an error message to the site that includes some info about the status of the OSRM demo server.
