### ISSUE TITLE
LRM and leaflet 0.8 dev

### ISSUE THREAD

**Issue by zheffie** [perliedman/leaflet-routing-machine#33]
Does LRM wordt with leaflet 0.8?

i'm getting browser erros like "Uncaught TypeError: Cannot read property 'call' of undefined"

**Comment by perliedman** [comment]
I've started a new branch, [`leaflet-master`](https://github.com/perliedman/leaflet-routing-machine/tree/leaflet-master), that should work with Leaflet's master branch. Some minor changes.
