### ISSUE TITLE
Disable zoom event after removing the control

### ISSUE THREAD

**Issue by Mg-Yaya** [perliedman/leaflet-routing-machine#330]
After removing the routing control from the map : 
`map.removeControl(control);`

I get this error when changing zoom : 
`Uncaught TypeError: Cannot read property 'getZoom' of null`

So I fixed in 2 steps : 

1. Put the function of zoomend event of "**onAdd**" function in a new named function  : 
     `this._map.on('zoomend', zoomendFunction, this);`

2. Disable the event of zoomend in "**onRemove**" function : 
      `map.off('zoomend', zoomendFunction, this);`

**Comment by perliedman** [comment]
Hi there! This was fixed in 06d0264ddf20222256096ce3117b6d6145fd193d. If you update to the latest version of Leaflet Routing Machine (3.2.4 at the moment), you should not see this error!
