### ISSUE TITLE
If 'routeWhileDragging: false' drags map

### ISSUE THREAD

**Issue by Dr-Mx** [perliedman/leaflet-routing-machine#332]
When setting `routeWhileDragging: false` and creating a new point by dragging a route line, the map drags and the console says:

TypeError: i[b].spliceLatLngs is not a function

Tested on IE11 and FF49.

**Comment by perliedman** [comment]
Hi and thanks for reporting! Will look into it sooner or later, but it's probably an easy fix, so help to get it done sooner is of course very appreciated.

**Comment by oliverheilig** [comment]
@perliedman spliceLatLngs has been removed in Leaflet 1.0. One fix is to reimplement it in routing-machine, see https://github.com/Leaflet/Leaflet.draw/commit/a9e409d07e1cca803de8e2e53e5b8438c7de438f
