### ISSUE TITLE
 leaflet-routing-machine and  Leaflet.Locate

### ISSUE THREAD

**Issue by vlad-shtark** [perliedman/leaflet-routing-machine#334]
Hello!

how to determine the location (my position)?

If I use leaflet-routing-machine and  Leaflet.Locate then appears the error "L.control.locate is not a function"

By the way there is no file on github leaflet-routing-mahine.js 

That may suggest that it was possible to use leaflet-routing-machine and some lefleat location service  at the same time?

Thank you very much!

**Comment by perliedman** [comment]
There shouldn't be any problem using LRM and Leaflet.Locate together, to my knowledge. I use geolocation and LRM in several projects. Hard to tell without seeing you running code, but it sounds like you might not be loading the js file correctly.

The build `dist/leaflet-routing-machine.js` is only included in tagged versions, so either [download a built release](https://github.com/perliedman/leaflet-routing-machine/releases), or check out a [tag](https://github.com/perliedman/leaflet-routing-machine/tree/v3.2.4).

**Comment by vlad-shtark** [comment]
ok! Thanks you!
