### ISSUE TITLE
German localization: missing some translations

### ISSUE THREAD

**Issue by slowlyCoder** [perliedman/leaflet-routing-machine#338]
In the german localization missing some translations. I think the missing translations are: 
- Fork
- Merge
- OnRamp
- OffRamp
- EndOfRoad
- Onto

**Comment by perliedman** [comment]
Very likely, since these were added recently by OSRM.

I'm not a native german speaker (and hardly a german speaker at all), so feel free to submit a pull request to address this!

**Comment by perliedman** [comment]
Closed by #342.
