### ISSUE TITLE
itinerary problem since today

### ISSUE THREAD

**Issue by Qcharton** [perliedman/leaflet-routing-machine#339]
Hi,
I just noticed that there is a problem when i create a route using your plugin. No matter what i use for origin and destination coordinate, i'll always have the same result that is : 

AZ 95
0.0 m, 0 s
Head north	0 m
Destination reached	0 m

Then, i said to my self ' let's check on http://www.liedman.net/leaflet-routing-machine/ for an issue !', but, i realize that there is the same problem on your demo.

So, i put on stand by my solution until you deal with this problem on your side ! :)

if you could answer me when you find the problem, i'll be glad.

Pending, good luck !

**Comment by perliedman** [comment]
See https://github.com/Project-OSRM/osrm-backend/issues/3185 and https://github.com/Project-OSRM/osrm-backend/issues/3186

This is not an issue with LRM, but with OSRM's demo server. You shouldn't run against the demo server except for demo purposes, it breaks every now and then so you can't rely on it. Set up your own server, or use a service provider maintains the server for you.
