### ISSUE TITLE
Defining Waypoints

### ISSUE THREAD

**Issue by ljkbrost** [perliedman/leaflet-routing-machine#34]
I have seen in the documentation that IWaypoint is defined as having a lngLat and name variables.  How do I define the array of IWaypoints to pass to L.Routing.Control so that the 'name' variable is passed to waypointIcon function.

**Comment by perliedman** [comment]
This has actually been fixed quite a while ago. `waypointIcon` has been replaced by the more flexible [`createMarker` option](http://www.liedman.net/leaflet-routing-machine/api/#planoptions), which does indeed take the waypoint as argument, such that the name of the waypoint can be used.
