### ISSUE TITLE
Control.Geocoder.js Nominatim serviceUrl

### ISSUE THREAD

**Issue by jaska120** [perliedman/leaflet-routing-machine#345]
In example folder Control.Geocoder.js contains serviceUrl at line 312 as `serviceUrl: '//nominatim.openstreetmap.org/'`. As for me it is returning to console ERR_FILE_NOT_FOUND or something similiar and the geocoder won't work.

Shouldn't this be updated to: `serviceUrl: '//nominatim.openstreetmap.org/'` ?

**Comment by perliedman** [comment]
Yes, the examples must be run from a web server, since the geocoders use a protocol relative URL. The geocoders is an external lib (leaflet-control-geocoder), so any changes should be made there.
