### ISSUE TITLE
Route list

### ISSUE THREAD

**Issue by Rusland3000** [perliedman/leaflet-routing-machine#349]
If browser window is small then is not able to see whole route list (impossible to scroll to the list end). http://i.piccy.info/i9/f22cf0b020b28c967e397f058547810b/1480421023/348042/1094617/CantSeeWholeRoute.png

Some questions:
1.) Is it possible deprecate new points on route line clicking? Any option for this? http://i.piccy.info/i9/3e8def632fcaf245a56460014bbb8d17/1480421505/245187/1094617/NewPoint.png
2.) How to make Routes panel Close button always visible? (not only browser window width small)  http://i.piccy.info/i9/8684a7396cf19f61fda3e94552a6677d/1480421364/21979/1094617/CloseButton.png

**Comment by Rusland3000** [comment]
I found answer to the 1 question:
`lineOptions: { addWaypoints: false },`

**Comment by perliedman** [comment]
1. You can probably set a smaller [`max-height` for the CSS class `leaflet-routing-alt`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L178)

2. Use the option `collapsible: true` (see [`Itinerary` options](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary))
