### ISSUE TITLE
Double request from A to B search

### ISSUE THREAD

**Issue by tauthomas01** [perliedman/leaflet-routing-machine#355]
Hi,

I'm using Leaflet Routing Machine with OSRM server in our website and there's an issue I found : 

**How to reproduce**
- Go to this url : http://www.yellowpages.ca/merchant/directions/100958466
- Type starting point (e.g. nord)
- Click on button "Get directions"
- Type another starting point (e.g. nordelec)
- Click on button "Get directions"

**Current**
- Left hand sidebar directions waypoint doesn't refresh
- Map refreshes

**Expected**
- Left hand sidebar directions waypoint should refresh

This is what I notice :

The first time I press "Get Directions", the plugin returns the good waypoint URL (with "nord" in the from field):
http://www.yellowpages.ca/route/v1/car/-79.42238,43.74721;-73.5672113,45.4871085?overview=false&alternatives=true&steps=true&hints=;

Second time I press "Get Directions" with "nordelec" in the from field, there are 2 requests for some reason : 
http://www.yellowpages.ca/route/v1/car/-73.5621,45.484;-73.5672113,45.4871085?overview=false&alternatives=true&steps=true&hints=;tC9ggmu9S4MncBcARgAAAAYAAAAAAAAAEQAAABK2SgITtkoCJS0AABV0nfsEFLYCFXSd-wQUtgIAAAEBlNLEzw==

http://www.yellowpages.ca/route/v1/car/-73.5621,45.484;-73.5672113,45.4871085?overview=full&alternatives=true&steps=false&hints=;tC9ggmu9S4MncBcARgAAAAYAAAAAAAAAEQAAABK2SgITtkoCJS0AABV0nfsEFLYCFXSd-wQUtgIAAAEBlNLEzw==

On the 2 links above, as you can notice, there are params **overview=false** and **steps=true** whereas the second request has different one: **overview=full** and **steps=false**

What is the reason behind it?
Thank you

**Comment by perliedman** [comment]
Hi there,

the double requests are normal - OSRM serves the route coordinates simplified depending on zoom, and when zooming closer, it is sometimes necessary to get more detailed route coordinates, which is the cause of the second request.

It's kind of hard to debug a complex and minified site, so it would be great if you could provide a simpler example of the problem, or explain how your code differs from the examples provided with LRM. For example, I notice that you seem to use custom geocoder inputs - my guess is that the problem somehow comes from how those interact with LRM.

**Comment by tauthomas01** [comment]
Hi @perliedman,

Thank you for your reply. There are a few differences between the default behavior of LRM and our implementation.

1. We use our own Geocoding system (the service returns Lat + Long from an address string)
2. We use a custom submit button which triggers setWaypoints() + fitBounds()

**Comment by perliedman** [comment]
In that case, it's pretty certain the second request is caused by the call to `fitBounds`, since LRM will listen to `zoomend` and figure out it needs to fetch a more detailed route geometry when the route is zoomed under some conditions.

That doesn't explain why the directions don't update, however. To dig into that, I would look what happens when the router calls [`setAlternatives`](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/control.js#L324) after routes are found.

**Comment by tauthomas01** [comment]
Thank you for the hints. Here's what I notice : 

`this._pendingRequest` is called but when it does the 2nd OSRM call, it stopped at `return options.callback.call(this, err, routes);` so it would not trigger `this.setAlternatives(routes)`. It's keeping the old directions so I assume that extra request has a callback.

**Comment by perliedman** [comment]
Yes, that is expected. The second call comes from the control's zoom handler, which provides its own callback, and should not call setAlternatives.

Could you look into what happens after you call setWaypoints the second time? For this case, setAlternatives should be called.

**Comment by tauthomas01** [comment]
I'm not sure if I understand your question correctly, but on the 2nd time, setAlternatives is not called.

After more troubleshooting, the problem is indeed the `fitBounds()`. Basically, when you're on a zoomed-out view (e.g. the whole Canada map) and you set a destination from point A to point B in a city like Toronto (Ontario), everything works fine without the extra `fitBounds()` call that I added in my code.

However, now that I see my directions point A & B in Toronto, if I want to set another destination from point A to point B further (e.g. Vancouver point A to another Vancouver point B destination), it would not recenter the map since fitBounds() is not added, but the waypoint directions are updated on the left hand side. My question is if you have another function that could recenter the map without `fitBounds()`? I would like the same default behavior but also consider zooming out automatically.

When you're on you do from a "zoomed" out level and you set a waypoint from point A to point B, everything works well and it automatically center + zoom in. Is there a similar behavior when you set a waypoint but zoom out?

**Comment by perliedman** [comment]
I think you want to look at the `fitRoute` option. It defaults to "smart", but setting it to `true` will make the plugin always fitting the route after a new route is received.

**Comment by tauthomas01** [comment]
Sorry for the late reply. It seems to work, amazing! Thank you very much for your help & support.
