### ISSUE TITLE
Wish: Route altitude profile

### ISSUE THREAD

**Issue by Benvorth** [perliedman/leaflet-routing-machine#360]
Your routing-machine is an ultra-awesome extension, thank you for bringing it into being!

Having an altitude profile for each route at hand would be great. Something like mentioned [here](https://www.mapbox.com/blog/third-party-data-in-osrm/)...

**Comment by perliedman** [comment]
Hi,
elevation is indeed interesting for some scenarios, but I don't think it should go into LRM itself.

I've worked with elevation data in LRM for some apps, you can see an example of how it can be done here: https://github.com/perliedman/cykelbanor/blob/gh-pages/src/routing-control.js (search for "elevation" in the code, and check related files, especially https://github.com/perliedman/cykelbanor/blob/gh-pages/src/elevation.js). See it in action here: https://cykelbanor.se/#bl=Karta&wps=57.7318%2C11.9413%3B57.7389%2C11.9219

Hope this helps!

**Comment by Benvorth** [comment]
Great, thank you for the hints!
