### ISSUE TITLE
Use autocomplete placefinding only

### ISSUE THREAD

**Issue by Benvorth** [perliedman/leaflet-routing-machine#361]
I like to use the autocomplete input-element for locations as a DOM elements separated from the actual map. What would be the best path to extract it as a separate component? Can I just use 

    L.Routing.geocoderElement

for it?

**Comment by perliedman** [comment]
Yes, you should be able to use `L.Routing.geocoderElement` - use its `getContainer` method to get the DOM element and insert it where you need.

Note: I have not tried this, so there's probably a few gotchas when using it as a standalone component.
