### ISSUE TITLE
Get time and distance when waypoints are changed

### ISSUE THREAD

**Issue by Armays** [perliedman/leaflet-routing-machine#366]
Hello again :) Thanks for your answrers, it really helped, but I have an issue whan I try to get the total distance and the total time when the waypoints are changed, could you please help me ? I get  "Uncaught RangeError: Maximum call stack size exceeded". Thanks !

```
import L from 'leaflet';

class CarteController {
  /* @ngInject */
  constructor($http) {
    this.name = 'carte';
    this.$http = $http;

    this.map = L.map('map');

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}{r}.png', {
      attribution: '© OpenStreetMap contributors'
    }).addTo(this.map);

    const control = L.Routing.control({
      waypoints: [
        L.latLng(45.750000, 4.850000),
        L.latLng(45.188529, 5.724523999999974),
        L.latLng(45.00, 5.74)
      ],
      routeWhileDragging: true,
      geocoder: L.Control.Geocoder.photon(),
      lineOptions: {
        styles: [{color: 'blue', opacity: 1, weight: 5}]
      }
      fitSelectedRoutes: true
    });
    control.addTo(this.map);
    control.on('waypointschanged', function (e) {
        for(let i = 0; i < e.waypoints.length; i++) {
          const newLatLngA = new L.LatLng(e.waypoints[i].latLng.lat, e.waypoints[i].latLng.lng, null);
          console.log(newLatLngA);
          control.spliceWaypoints(i, 1, newLatLngA);
        }
        console.log('test');
      this.distance = `${Math.round(control._routes[0].summary.totalDistance / 1000)} km`;
      this.temps = this.secondsToHm(control._routes[0].summary.totalTime);
      console.log(this);
    }.bind(this));

    new L.Routing.Plan({
      geocoderPlaceholder: (i, numberWaypoints) => {
        return i === 0 ?
          'Départ' :
          (i < numberWaypoints - 1 ?
            `Via ${i}` :
            'Arrivée');
      }
    }).addTo(this.map);
  }

  secondsToHm(d) {
    d = Number(d);
    const h = Math.floor(d / 3600);
    const m = Math.floor(d % 3600 / 60);
    return ((h > 0 ? h + " h " + (m < 10 ? "0" : "") : "") + m + " min"); // eslint-disable-line
  }
}

export default CarteController;

```

**Comment by Armays** [comment]
I resolved my problem :+1: 
import L from 'leaflet';

class CarteController {
  /* @ngInject */
  constructor($http) {
    this.name = 'carte';
    this.$http = $http;

    this.map = L.map('map');

    const waypoints = [
  		L.latLng(45.750000, 4.850000),
  		L.latLng(45.188529, 5.724523999999974)
  	];

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}{r}.png', {
      attribution: '© OpenStreetMap contributors'
    }).addTo(this.map);

    const control = L.Routing.control({
      plan: L.Routing.plan(waypoints, {
        geocoderPlaceholder: (i, numberWaypoints) => {
          return i === 0 ?
            'Départ' :
            (i < numberWaypoints - 1 ?
              `Via ${i}` :
              'Arrivée');
        },
  			geocoder: L.Control.Geocoder.nominatim(),
  			routeWhileDragging: true
		  }),
      routeWhileDragging: true,
      lineOptions: {
        styles: [{color: 'blue', opacity: 1, weight: 5}]
      },
      fitSelectedRoutes: true
    });
    control.addTo(this.map);
    control.on('routeselected', function (e) {
      this.distance = `${Math.round(control._routes[0].summary.totalDistance / 1000)} km`;
      this.temps = control._routes[0].summary.totalTime;
    }.bind(this));
  }

  secondsToHm(d) {
    d = Number(d);
    const h = Math.floor(d / 3600);
    const m = Math.floor(d % 3600 / 60);
    return ((h > 0 ? h + " h " + (m < 10 ? "0" : "") : "") + m + " min"); // eslint-disable-line
  }
}

export default CarteController;

**Comment by perliedman** [comment]
You probably don't want to use `control._routes`, variables prefixed with underscore are "private", undocumented and can change in coming versions.

I'd suggest using the `routeselected` event instead, where the event object contains the selected route, so you can examine it.
