### ISSUE TITLE
How to pass json as parameter in Routing.Control?

### ISSUE THREAD

**Issue by pedrosalpr** [perliedman/leaflet-routing-machine#368]
Hi! Is there a way to pass the coordinates and json already in the Routing.Control, not to make the request in the OSRM api? And your API already calculate the route automatically via json.

Because I already have the coordinate json returned from the OSRM api. And I did not want him to make the requisition.

**Comment by perliedman** [comment]
Hi @pedrosalpr,
yes, if you already have the route, you can pass it to the control's `setAlternatives` method - it takes an array of [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) objects (but it's of course fine to pass an array with only one element).

Note that this has to be routes in Leaflet Routing Machine's own format, _not_ the OSRM response, although they are similar. You can look at [OSRMv1](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/osrm-v1.js) for how the transformation can be done.

**Comment by pedrosalpr** [comment]
I saw in source code in OSRMv1, which has the _routeDone method and you call this method in the corslite function:

this._routeDone (data, wps, options, callback, context);

Where the OSRM json data is passed, and then it is this transformation that must be done.

So instead of writing the OSRM json data, I write the json data already in the LRM format in the database.
