### ISSUE TITLE
Portuguese-Brasil Traduction

### ISSUE THREAD

**Issue by sachadee** [perliedman/leaflet-routing-machine#370]
Hi,

First of all thanks for your great job !

Here are the traduction for 'pt_br' (brasil portugueses) I don't know where i can publish them.

```
'pt_br': {
    directions: {
        N: 'norte',
        NE: 'nordeste',
        E: 'este',
        SE: 'sudeste',
        S: 'sul',
        SW: 'sudoeste',
        W: 'oeste',
        NW: 'nordoeste'
    },
    instructions: {
        // instruction, postfix if the road is named
        'Head':
            ['Pra frente no {dir}', ' na {road}'],
        'Continue':
            ['Continuar no {dir}', ' na {road}'],
        'SlightRight':
            ['Levemente na direita', ' na {road}'],
        'Right':
            ['A direita', ' na {road}'],
        'SharpRight':
            ['Completamente a direita', ' na {road}'],
        'TurnAround':
            ['Dar meia volta'],
        'SharpLeft':
            ['Completamente a esquerda', ' na {road}'],
        'Left':
            ['A esquerda', ' na {road}'],
        'SlightLeft':
            ['Levemente a esquerda', ' na {road}'],
        'WaypointReached':
            ['Ponto de etapa alcançado'],
        'Roundabout':
            ['No giratorio, pegue a  {exitStr} saida'],
        'DestinationReached':
            ['Chegou na destinação'],
    },
    formatOrder: function(n) {
        return n + 'º';
    }
}
```

Please can you make a small example how I can implemante this Traduction in a small snippet like this

```
 marker.on('click', function(e) {
                L.Routing.control({
                waypoints: [
                MyLoc,
                e.latlng
               ]
               }).addTo(map);
```
Thanks.

**Comment by rsofista** [comment]
See the file: src/localization.js
There's already a 'pt' key, see if you need to merge.

P.S: The correct word is 'translation' when referring to text.

**Comment by perliedman** [comment]
Yes, check if the current portugese localization is correct - if there is need for a specific Brazilian version, please submit a pull request to add this.

**Comment by rsofista** [comment]
@perliedman in the version 3.2.5 i noticed that the object used for localizing has changed.
And forgive my javascript ignorance with that: _dereq_('./instructions/en.json');
The file does not exist and is referenced on line 276 and 301

https://github.com/perliedman/leaflet-routing-machine/blob/v3.2.5/dist/leaflet-routing-machine.js#L276
https://github.com/perliedman/leaflet-routing-machine/blob/v3.2.5/dist/leaflet-routing-machine.js#L301

Shouldn't that localization.js file be in the new format?

**Comment by perliedman** [comment]
@rsofista you're looking at the built `dist` files. `dereq` is something added while building.

Look at https://github.com/perliedman/leaflet-routing-machine/blob/master/src/localization.js instead for the actual source, where changes should be made.

**Comment by rsofista** [comment]
Don't take me wrong when i say the translation process is far too long and complicated and I'm not gonna do it.
But I needed in production so I simply replaced the 'en' on the leaflet-routing-machine.js.

If a kind soul could add the file and make the necessary modifications, here it is:


{
    "meta": {
        "capitalizeFirstLetter": true
    },
    "v5": {
        "constants": {
            "ordinalize": {
                "1": "1º",
                "2": "2º",
                "3": "3º",
                "4": "4º",
                "5": "5º",
                "6": "6º",
                "7": "7º",
                "8": "8º",
                "9": "9º",
                "10": "10º"
            },
            "direction": {
                "north": "norte",
                "northeast": "nordeste",
                "east": "leste",
                "southeast": "sudeste",
                "south": "sul",
                "southwest": "sudoeste",
                "west": "oeste",
                "northwest": "noroeste"
            },
            "modifier": {
                "left": "à esquerda",
                "right": "à direita",
                "sharp left": "curva fechada à esquerda",
                "sharp right": "curva fechada à direita",
                "slight left": "curva ligeira à esquerda",
                "slight right": "curva ligeira à direita",
                "straight": "em frente",
                "uturn": "Meia volta"
            },
            "lanes": {
                "xo": "Mantenha-se a direita",
                "ox": "Mantenha-se a esquerda",
                "xox": "Mantenha-se no meio",
                "oxo": "Mantenha-se à direita ou esquerda"
            }
        },
        "modes": {
            "ferry": {
                "default": "Pegue a balsa",
                "name": "Pegue a balsa {way_name}",
                "destination": "Pegue a balsa para {destination}"
            }
        },
        "arrive": {
            "default": {
                "default": "Você chegou ao {nth} destino"
            },
            "left": {
                "default": "Você chegou ao {nth} destino, à esquerda"
            },
            "right": {
                "default": "Você chegou ao {nth} destino, à direita"
            },
            "sharp left": {
                "default": "Você chegou ao {nth} destino, à esquerda"
            },
            "sharp right": {
                "default": "Você chegou ao {nth} destino, à direita"
            },
            "slight right": {
                "default": "Você chegou ao {nth} destino, à direita"
            },
            "slight left": {
                "default": "Você chegou ao {nth} destino, à esquerda"
            },
            "straight": {
                "default": "Você chegou ao {nth} destino, em frente"
            }
        },
        "continue": {
            "default": {
                "default": "Continue {modifier}",
                "name": "Continue {modifier} na {way_name}",
                "destination": "Continue {modifier} em direção à {destination}"
            },
            "straight": {
                "default": "Continue reto",
                "name": "Continue na {way_name}",
                "destination": "Continue em direção à {destination}"
            },
            "slight left": {
                "default": "Continue ligeiramente à esquerda",
                "name": "Continue ligeiramente à esquerda na {way_name}",
                "destination": "Continue ligeiramente à esquerda em direção à {destination}"
            },
            "slight right": {
                "default": "Continue ligeiramente à direita",
                "name": "Continue ligeiramente à direita na {way_name}",
                "destination": "Continue ligeiramente à direita em direção à {destination}"
            },
            "uturn": {
                "default": "Faça meia volta",
                "name": "Faça meia volta na {way_name}",
                "destination": "Faça meia volta em direção à {destination}"
            }
        },
        "depart": {
            "default": {
                "default": "Siga {direction}",
                "name": "Siga {direction} na {way_name}"
            }
        },
        "end of road": {
            "default": {
                "default": "Vire {modifier}",
                "name": "Vire {modifier} na {way_name}",
                "destination": "Vira {modifier} em direção à {destination}"
            },
            "straight": {
                "default": "Continue reto",
                "name": "Continue reto na {way_name}",
                "destination": "Continue reto em direção à {destination}"
            },
            "uturn": {
                "default": "Faça meia volta no fim da rua",
                "name": "Faça meia volta na {way_name} no fim da rua",
                "destination": "Faça meia volta em direção à {destination} no fim da rua"
            }
        },
        "fork": {
            "default": {
                "default": "Mantenha-se {modifier} na bifurcação",
                "name": "Mantenha-se {modifier} na bifurcação para {way_name}",
                "destination": "Mantenha-se {modifier} na encruzilhada em direção à {destination}"
            },
            "slight left": {
                "default": "Mantenha-se à esquerda na bifurcação",
                "name": "Mantenha-se à esquerda na bifurcação na {way_name}",
                "destination": "Mantenha-se à esquerda na bifurcação em direção à {destination}"
            },
            "slight right": {
                "default": "Mantenha-se à direita na bifurcação",
                "name": "Mantenha-se à direita na bifurcação na {way_name}",
                "destination": "Mantenha-se à direita na bifurcação em direção à {destination}"
            },
            "sharp left": {
                "default": "Faça curva acentuada à esquerda na bifurcação",
                "name": "faça curva acentuada à esquerda na bifurcação na {way_name}",
                "destination": "faça curva acentuada à esquerda na bifurcação em direção à {destination}"
            },
            "sharp right": {
                "default": "Faça curva acentuada à direita na bifurcação",
                "name": "faça curva acentuada à direita na bifurcação na {way_name}",
                "destination": "faça curva acentuada à direita na bifurcação em direção à {destination}"
            },
            "uturn": {
                "default": "Dê meia volta",
                "name": "Dê meia volta na {way_name}",
                "destination": "Dê meia volta em direção à {destination}"
            }
        },
        "merge": {
            "default": {
                "default": "Entre {modifier}",
                "name": "Entre {modifier} na {way_name}",
                "destination": "Entre {modifier} em direção à {destination}"
            },
            "slight left": {
                "default": "Entre à esquerda",
                "name": "Entre à esquerda na {way_name}",
                "destination": "Entre à esquerda em direção à {destination}"
            },
            "slight right": {
                "default": "Entre à direita",
                "name": "Entre à direita na {way_name}",
                "destination": "Entre à direita em direção à {destination}"
            },
            "sharp left": {
                "default": "Entre à esquerda",
                "name": "Entre à esquerda na {way_name}",
                "destination": "Entre à esquerda em direção à {destination}"
            },
            "sharp right": {
                "default": "Entre à direita",
                "name": "Entre à direita na {way_name}",
                "destination": "Entre `Pa direita em direção à {destination}"
            },
            "uturn": {
                "default": "Faça meia volta",
                "name": "Faça meia volta na {way_name}",
                "destination": "Faça meia volta em direção à {destination}"
            }
        },
        "new name": {
            "default": {
                "default": "Continue {modifier}",
                "name": "Continue {modifier} na {way_name}",
                "destination": "Continue {modifier} em direção à {destination}"
            },
            "sharp left": {
                "default": "Faça uma curva acentuada à esquerda",
                "name": "Faça uma curva acentuada à esquerda na {way_name}",
                "destination": "Faça uma curva acentuada à esquerda em direção à {destination}"
            },
            "sharp right": {
                "default": "Faça uma curva acentuada à direita",
                "name": "Faça uma curva acentuada à direita na {way_name}",
                "destination": "Faça uma curva acentuada à direita em direção à {destination}"
            },
            "slight left": {
                "default": "Continue ligeiramente à esquerda",
                "name": "Continue ligeiramente à esquerda na {way_name}",
                "destination": "Continue ligeiramente à esquerda em direção à {destination}"
            },
            "slight right": {
                "default": "Continue ligeiramente à direita",
                "name": "Continue ligeiramente à direita na {way_name}",
                "destination": "Continue ligeiramente à direita em direção à {destination}"
            },
            "uturn": {
                "default": "Faça meia volta",
                "name": "Faça meia volta na {way_name}",
                "destination": "Faça meia volta em direção à {destination}"
            }
        },
        "notification": {
            "default": {
                "default": "Continue {modifier}",
                "name": "Continue {modifier} na {way_name}",
                "destination" : "Continue {modifier} em direção à {destination}"
            },
            "uturn": {
                "default": "Faça meia volta",
                "name": "Faça meia volta na {way_name}",
                "destination": "Faça meia volta em direção à {destination}"
            }
        },
        "off ramp": {
            "default": {
                "default": "Pegue a rampa",
                "name": "Pegue a rampa na {way_name}",
                "destination": "Pegue a rampa em direção à {destination}"
            },
            "left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            },
            "sharp left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "sharp right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            },
            "slight left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "slight right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            }
        },
        "on ramp": {
            "default": {
                "default": "Pegue a rampa",
                "name": "Pegue a rampa na {way_name}",
                "destination": "Pegue a rampa em direção à {destination}"
            },
            "left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            },
            "sharp left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "sharp right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            },
            "slight left": {
                "default": "Pegue a rampa à esquerda",
                "name": "Pegue a rampa à esquerda na {way_name}",
                "destination": "Pegue a rampa à esquerda em direção à {destination}"
            },
            "slight right": {
                "default": "Pegue a rampa à direita",
                "name": "Pegue a rampa à direita na {way_name}",
                "destination": "Pegue a rampa à direita em direção à {destination}"
            }
        },
        "rotary": {
            "default": {
                "default": {
                    "default": "Entre na rotatória",
                    "name": "Entre na rotatória e saia na {way_name}",
                    "destination": "Entre na rotatória e saia em direção à {destination}"
                },
                "name": {
                    "default": "Entre na {rotary_name}",
                    "name": "Entre na {rotary_name} e saia na {way_name}",
                    "destination": "Entre na {rotary_name} e saia em direção à {destination}"
                },
                "exit": {
                    "default": "Entre na rotatória e pegue a {exit_number} saída",
                    "name": "Entre na rotatória e pegue a {exit_number} saída na {way_name}",
                    "destination": "Entre na rotatória e pegue a {exit_number} saída em direção à {destination}"
                },
                "name_exit": {
                    "default": "Entre na {rotary_name} e pegue a {exit_number} saída",
                    "name": "Entre na {rotary_name} e pegue a {exit_number} saída na {way_name}",
                    "destination": "Entre na {rotary_name} e pegue a {exit_number} saída em direção à {destination}"
                }
            }
        },
        "roundabout": {
            "default": {
                "exit": {
                    "default": "Entre na rótula e pegue a {exit_number} saída",
                    "name": "Entre na rótula e pegue a {exit_number} saída na {way_name}",
                    "destination": "Entre na rótula e pegue a {exit_number} saída em direção à {destination}"
                },
                "default": {
                    "default": "Entre na rótula",
                    "name": "Entre na rótula e saia na {way_name}",
                    "destination": "Entre na rótula e saia em direção à {destination}"
                }
            }
        },
        "roundabout turn": {
            "default": {
                "default": "Na rótula vire {modifier}",
                "name": "Na rótula vire {modifier} na {way_name}",
                "destination": "Na rótula vire {modifier} em direção à {destination}"
            },
            "left": {
                "default": "Na rótula vire à esquerda",
                "name": "Na rótula vire à esquerda na {way_name}",
                "destination": "Na rótula vire à esquerda em direção à {destination}"
            },
            "right": {
                "default": "Na rótula vire à direita",
                "name": "Na rótula vire à direita na {way_name}",
                "destination": "Na rótula vire à direita em direção à {destination}"
            },
            "straight": {
                "default": "Na rótula continue reto",
                "name": "Na rótula continue reto na {way_name}",
                "destination": "Na rótula continue reto em direção à {destination}"
            }
        },
        "turn": {
            "default": {
                "default": "Vire {modifier}",
                "name": "Vire {modifier} na {way_name}",
                "destination": "Vire {modifier} em direção à {destination}"
            },
            "left": {
                "default": "Vire à esquerda",
                "name": "Vire à esquerda na {way_name}",
                "destination": "Vire à esquerda em direção à {destination}"
            },
            "right": {
                "default": "Vire à direita",
                "name": "Vire à direita na {way_name}",
                "destination": "Vire à direita em direção à {destination}"
            },
            "straight": {
                "default": "Vá reto",
                "name": "Vá reto na {way_name}",
                "destination": "Vá reto em direção à {destination}"
            }
        },
        "use lane": {
            "no_lanes": {
                "default": "Continue reto"
            },
            "default": {
                "default": "{lane_instruction}"
            }
        }
    }
}

**Comment by perliedman** [comment]
@rsofista well, please consider the amount of time I and the OSRM team puts into making and maintaining this software before you say "too long and complicated" :)

For us, this is the most efficient method we've come up with, that is both maintainable for us and makes sure as many users as possible can use the internationalization support.

I'm sorry you feel it's complex, and I'm open to suggestions for improving the situation, but also realize that this isn't necessarily trivial.

**Comment by FernandoSFerreira** [comment]
> Don't take me wrong when i say the translation process is far too long and complicated and I'm not gonna do it. But I needed in production so I simply replaced the 'en' on the leaflet-routing-machine.js.
> 
> If a kind soul could add the file and make the necessary modifications, here it is:
> 
> { "meta": { "capitalizeFirstLetter": true }, "v5": { "constants": { "ordinalize": { "1": "1º", "2": "2º", "3": "3º", "4": "4º", "5": "5º", "6": "6º", "7": "7º", "8": "8º", "9": "9º", "10": "10º" }, "direction": { "north": "norte", "northeast": "nordeste", "east": "leste", "southeast": "sudeste", "south": "sul", "southwest": "sudoeste", "west": "oeste", "northwest": "noroeste" }, "modifier": { "left": "à esquerda", "right": "à direita", "sharp left": "curva fechada à esquerda", "sharp right": "curva fechada à direita", "slight left": "curva ligeira à esquerda", "slight right": "curva ligeira à direita", "straight": "em frente", "uturn": "Meia volta" }, "lanes": { "xo": "Mantenha-se a direita", "ox": "Mantenha-se a esquerda", "xox": "Mantenha-se no meio", "oxo": "Mantenha-se à direita ou esquerda" } }, "modes": { "ferry": { "default": "Pegue a balsa", "name": "Pegue a balsa {way_name}", "destination": "Pegue a balsa para {destination}" } }, "arrive": { "default": { "default": "Você chegou ao {nth} destino" }, "left": { "default": "Você chegou ao {nth} destino, à esquerda" }, "right": { "default": "Você chegou ao {nth} destino, à direita" }, "sharp left": { "default": "Você chegou ao {nth} destino, à esquerda" }, "sharp right": { "default": "Você chegou ao {nth} destino, à direita" }, "slight right": { "default": "Você chegou ao {nth} destino, à direita" }, "slight left": { "default": "Você chegou ao {nth} destino, à esquerda" }, "straight": { "default": "Você chegou ao {nth} destino, em frente" } }, "continue": { "default": { "default": "Continue {modifier}", "name": "Continue {modifier} na {way_name}", "destination": "Continue {modifier} em direção à {destination}" }, "straight": { "default": "Continue reto", "name": "Continue na {way_name}", "destination": "Continue em direção à {destination}" }, "slight left": { "default": "Continue ligeiramente à esquerda", "name": "Continue ligeiramente à esquerda na {way_name}", "destination": "Continue ligeiramente à esquerda em direção à {destination}" }, "slight right": { "default": "Continue ligeiramente à direita", "name": "Continue ligeiramente à direita na {way_name}", "destination": "Continue ligeiramente à direita em direção à {destination}" }, "uturn": { "default": "Faça meia volta", "name": "Faça meia volta na {way_name}", "destination": "Faça meia volta em direção à {destination}" } }, "depart": { "default": { "default": "Siga {direction}", "name": "Siga {direction} na {way_name}" } }, "end of road": { "default": { "default": "Vire {modifier}", "name": "Vire {modifier} na {way_name}", "destination": "Vira {modifier} em direção à {destination}" }, "straight": { "default": "Continue reto", "name": "Continue reto na {way_name}", "destination": "Continue reto em direção à {destination}" }, "uturn": { "default": "Faça meia volta no fim da rua", "name": "Faça meia volta na {way_name} no fim da rua", "destination": "Faça meia volta em direção à {destination} no fim da rua" } }, "fork": { "default": { "default": "Mantenha-se {modifier} na bifurcação", "name": "Mantenha-se {modifier} na bifurcação para {way_name}", "destination": "Mantenha-se {modifier} na encruzilhada em direção à {destination}" }, "slight left": { "default": "Mantenha-se à esquerda na bifurcação", "name": "Mantenha-se à esquerda na bifurcação na {way_name}", "destination": "Mantenha-se à esquerda na bifurcação em direção à {destination}" }, "slight right": { "default": "Mantenha-se à direita na bifurcação", "name": "Mantenha-se à direita na bifurcação na {way_name}", "destination": "Mantenha-se à direita na bifurcação em direção à {destination}" }, "sharp left": { "default": "Faça curva acentuada à esquerda na bifurcação", "name": "faça curva acentuada à esquerda na bifurcação na {way_name}", "destination": "faça curva acentuada à esquerda na bifurcação em direção à {destination}" }, "sharp right": { "default": "Faça curva acentuada à direita na bifurcação", "name": "faça curva acentuada à direita na bifurcação na {way_name}", "destination": "faça curva acentuada à direita na bifurcação em direção à {destination}" }, "uturn": { "default": "Dê meia volta", "name": "Dê meia volta na {way_name}", "destination": "Dê meia volta em direção à {destination}" } }, "merge": { "default": { "default": "Entre {modifier}", "name": "Entre {modifier} na {way_name}", "destination": "Entre {modifier} em direção à {destination}" }, "slight left": { "default": "Entre à esquerda", "name": "Entre à esquerda na {way_name}", "destination": "Entre à esquerda em direção à {destination}" }, "slight right": { "default": "Entre à direita", "name": "Entre à direita na {way_name}", "destination": "Entre à direita em direção à {destination}" }, "sharp left": { "default": "Entre à esquerda", "name": "Entre à esquerda na {way_name}", "destination": "Entre à esquerda em direção à {destination}" }, "sharp right": { "default": "Entre à direita", "name": "Entre à direita na {way_name}", "destination": "Entre `Pa direita em direção à {destination}" }, "uturn": { "default": "Faça meia volta", "name": "Faça meia volta na {way_name}", "destination": "Faça meia volta em direção à {destination}" } }, "new name": { "default": { "default": "Continue {modifier}", "name": "Continue {modifier} na {way_name}", "destination": "Continue {modifier} em direção à {destination}" }, "sharp left": { "default": "Faça uma curva acentuada à esquerda", "name": "Faça uma curva acentuada à esquerda na {way_name}", "destination": "Faça uma curva acentuada à esquerda em direção à {destination}" }, "sharp right": { "default": "Faça uma curva acentuada à direita", "name": "Faça uma curva acentuada à direita na {way_name}", "destination": "Faça uma curva acentuada à direita em direção à {destination}" }, "slight left": { "default": "Continue ligeiramente à esquerda", "name": "Continue ligeiramente à esquerda na {way_name}", "destination": "Continue ligeiramente à esquerda em direção à {destination}" }, "slight right": { "default": "Continue ligeiramente à direita", "name": "Continue ligeiramente à direita na {way_name}", "destination": "Continue ligeiramente à direita em direção à {destination}" }, "uturn": { "default": "Faça meia volta", "name": "Faça meia volta na {way_name}", "destination": "Faça meia volta em direção à {destination}" } }, "notification": { "default": { "default": "Continue {modifier}", "name": "Continue {modifier} na {way_name}", "destination" : "Continue {modifier} em direção à {destination}" }, "uturn": { "default": "Faça meia volta", "name": "Faça meia volta na {way_name}", "destination": "Faça meia volta em direção à {destination}" } }, "off ramp": { "default": { "default": "Pegue a rampa", "name": "Pegue a rampa na {way_name}", "destination": "Pegue a rampa em direção à {destination}" }, "left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" }, "sharp left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "sharp right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" }, "slight left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "slight right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" } }, "on ramp": { "default": { "default": "Pegue a rampa", "name": "Pegue a rampa na {way_name}", "destination": "Pegue a rampa em direção à {destination}" }, "left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" }, "sharp left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "sharp right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" }, "slight left": { "default": "Pegue a rampa à esquerda", "name": "Pegue a rampa à esquerda na {way_name}", "destination": "Pegue a rampa à esquerda em direção à {destination}" }, "slight right": { "default": "Pegue a rampa à direita", "name": "Pegue a rampa à direita na {way_name}", "destination": "Pegue a rampa à direita em direção à {destination}" } }, "rotary": { "default": { "default": { "default": "Entre na rotatória", "name": "Entre na rotatória e saia na {way_name}", "destination": "Entre na rotatória e saia em direção à {destination}" }, "name": { "default": "Entre na {rotary_name}", "name": "Entre na {rotary_name} e saia na {way_name}", "destination": "Entre na {rotary_name} e saia em direção à {destination}" }, "exit": { "default": "Entre na rotatória e pegue a {exit_number} saída", "name": "Entre na rotatória e pegue a {exit_number} saída na {way_name}", "destination": "Entre na rotatória e pegue a {exit_number} saída em direção à {destination}" }, "name_exit": { "default": "Entre na {rotary_name} e pegue a {exit_number} saída", "name": "Entre na {rotary_name} e pegue a {exit_number} saída na {way_name}", "destination": "Entre na {rotary_name} e pegue a {exit_number} saída em direção à {destination}" } } }, "roundabout": { "default": { "exit": { "default": "Entre na rótula e pegue a {exit_number} saída", "name": "Entre na rótula e pegue a {exit_number} saída na {way_name}", "destination": "Entre na rótula e pegue a {exit_number} saída em direção à {destination}" }, "default": { "default": "Entre na rótula", "name": "Entre na rótula e saia na {way_name}", "destination": "Entre na rótula e saia em direção à {destination}" } } }, "roundabout turn": { "default": { "default": "Na rótula vire {modifier}", "name": "Na rótula vire {modifier} na {way_name}", "destination": "Na rótula vire {modifier} em direção à {destination}" }, "left": { "default": "Na rótula vire à esquerda", "name": "Na rótula vire à esquerda na {way_name}", "destination": "Na rótula vire à esquerda em direção à {destination}" }, "right": { "default": "Na rótula vire à direita", "name": "Na rótula vire à direita na {way_name}", "destination": "Na rótula vire à direita em direção à {destination}" }, "straight": { "default": "Na rótula continue reto", "name": "Na rótula continue reto na {way_name}", "destination": "Na rótula continue reto em direção à {destination}" } }, "turn": { "default": { "default": "Vire {modifier}", "name": "Vire {modifier} na {way_name}", "destination": "Vire {modifier} em direção à {destination}" }, "left": { "default": "Vire à esquerda", "name": "Vire à esquerda na {way_name}", "destination": "Vire à esquerda em direção à {destination}" }, "right": { "default": "Vire à direita", "name": "Vire à direita na {way_name}", "destination": "Vire à direita em direção à {destination}" }, "straight": { "default": "Vá reto", "name": "Vá reto na {way_name}", "destination": "Vá reto em direção à {destination}" } }, "use lane": { "no_lanes": { "default": "Continue reto" }, "default": { "default": "{lane_instruction}" } } } }

On version leaflet-routing-machine-3.2.12 you can just set language to pt-BR.
![image](https://user-images.githubusercontent.com/23156804/195827585-a8f2e9fc-0c24-4f23-950f-42668171a255.png)
