### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by josek5494** [perliedman/leaflet-routing-machine#372]
I already have the translated code. If you could include it in the js file we will appreciate it! Thank you!

[http://www.filedropper.com/spanishtranslation](url)

**Comment by josek5494** [comment]
I found another issue, the navigation panel when the instructions are shown doesnt scroll in Android and iOS :(

**Comment by perliedman** [comment]
Hi, translation (or rather, internationalization/i18n) is done by the [osrm-text-instruction](https://github.com/Project-OSRM/osrm-text-instructions/) module, so any changes need to be made there!

Please open a new issue, preferably with a bit more detail, about the scroll.
