### ISSUE TITLE
Get Nearest Marker

### ISSUE THREAD

**Issue by frolody** [perliedman/leaflet-routing-machine#376]
I have 4 marker.
3 green marker is my destination and 1 red marker is my position.
how to get nearest marker from my position and add route to map?

I use graphopper for route service

![untitled](https://cloud.githubusercontent.com/assets/11209411/22206347/7318413e-e1ad-11e6-8e4b-6de4eb703aca.png)

**Comment by perliedman** [comment]
Hi there, this is a bit outside the scope of LRM, so I think you're better off asking these types of questions someplace else. gis.stackexchange.com or stackoverflow are usually good.

For looking up closest points, have a look at turf.js, which among many functions has something called `nearest`.
