### ISSUE TITLE
Route planning mode

### ISSUE THREAD

**Issue by Duckord** [perliedman/leaflet-routing-machine#379]
I'm not able to change the profile when initializing a route. I'd like to change driving mode to walking mode. 
Isn't it possible ?

**Comment by perliedman** [comment]
The actual route calculation is done by the backend, which also contains the profile.

By default, OSRM's demo server is used, and it only supports driving. If you set up your own server with multiple profiles, or use a paid service like Mapbox, you can switch profile by altering the `profile` option of the router:

```
control.getRouter().options.profile = 'walking';
```
