### ISSUE TITLE
Changing route title

### ISSUE THREAD

**Issue by Duckord** [perliedman/leaflet-routing-machine#380]
When creating a route, the title displayed above instructions is a combination of all the streets (?) where the route goes. Is there a way to change the title ? Because when the route is composed of more than 10 places, the title becomes too long.

**Comment by perliedman** [comment]
The title is currently a concatenation of all leg summaries in OSRM's response, so if you have a lot of legs, it might be excessively long.

Unfortunately, there's currently no quick/easy way to override this behaviour, you could inherit from `L.Routing.OSRMv1` and implement your own logic.

**Comment by perliedman** [comment]
Closing this, I have summarized suggested changes in #386.
