### ISSUE TITLE
Show and hide controls or routes

### ISSUE THREAD

**Issue by gustavozafra** [perliedman/leaflet-routing-machine#381]
Hello, is there any way to show and hide controls and routes added on a map? If possible I could give me an example by clicking the button of an external button, because in my case I add several controls being one for each day of the week.

**Comment by perliedman** [comment]
Hi, the easiest way is to use Leaflet's built in functions for adding/removing a control from the map:

```
map.removeControl(control);
//...
control.addTo(map);
```

**Comment by gustavozafra** [comment]
Hi @perliedman Thank you very much, but I'm still having the following problem. I have two external controls, one of show and hide a route, and the other to show the itinerary of that route (the streets that it must pass, etc ...) because I am hiding the itinerary that it creates automatically. I found this example http://jsfiddle.net/kuzvac/kjwrutj2/ where I can see how to get the object and add it to an external div, however by applying this example I can not do the show and hide controls, it returns me the error:

> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by perliedman** [comment]
Well, that code you linked to rearranges the DOM behind LRM's back, so LRM crashes when it tries to clean up after itself. I have no quick way to solve that - that jsfiddle is definitely not a supported way of doing things.

**Comment by FernandoFranco** [comment]
This error occurred from by container is not a child of the parent.
You can add container in the correct parent to remove, or ignore if not expected parent in container

`<script type="text/javascript" src="./leaflet.js"></script>
<script type="text/javascript">
    L.Control = L.Control.extend({
        removeFrom: function(t) {
            var e = this.getPosition(),
            i = t._controlCorners[e];
						
            i.appendChild(this._container);
            return i.removeChild(this._container), this._map = null, this.onRemove && this.onRemove(t), this
        }
    });
</script>
<script type="text/javascript" src="./leaflet-routing-machine.js"></script> `
