### ISSUE TITLE
Dragging from the middle creates waypoint at the beginning

### ISSUE THREAD

**Issue by rsofista** [perliedman/leaflet-routing-machine#383]
Using http://map.project-osrm.org/ I added 3 waypoints to my route

Brasília, Região Integrada de Desenvolvimento do Distrito Federal e Entorno, Distrito Federal, Região Centro-Oeste, Brasil

São Paulo, Região Sudeste, Brasil

Brasília, Região Integrada de Desenvolvimento do Distrito Federal e Entorno, Distrito Federal, Região Centro-Oeste, Brasil

![osrm_1](https://cloud.githubusercontent.com/assets/11434148/22476385/533776d8-e7c9-11e6-9e42-860d78bfe324.jpg)

When I drag from the city of "Luziânia" i expect to create a new waypoint between the 1º and 2º point, or between the 2º and 3º, but the map makes the new waypoint as the first.

![osrm_2](https://cloud.githubusercontent.com/assets/11434148/22476528/e608cd5e-e7c9-11e6-93d7-1d18ee344bb2.jpg)

![osrm_3](https://cloud.githubusercontent.com/assets/11434148/22476547/f479e990-e7c9-11e6-8734-a69db860fa7e.jpg)

**Comment by perliedman** [comment]
Not sure which version of LRM the OSRM demo page is using, and what other differences there might be in their implementation, but I can't reproduce this problem with a standalone LRM implementation:

http://playground-leaflet.rhcloud.com/cuze/1/edit?html,output

Dragging the route works as expected for me, and inserts a waypoint between second and third waypoint.

**Comment by rsofista** [comment]
I worked 😄 

But now if you add (language: 'pt',) to your snippet it will not work.

I throws the exception "Invalid language pt", at line 297, so I presume the way you choose the language changed since there is now only 6 options and and 'pt' key still exists at line 4233.
