### ISSUE TITLE
Exporting the route

### ISSUE THREAD

**Issue by BasmaNabil** [perliedman/leaflet-routing-machine#387]
Hello,

I want to export the route so that it is easy given to the driver to follow it,can this be done?

Thanks in advance.

**Comment by perliedman** [comment]
Hi there,
sorry about a late reply.

If you listen to the `routeselected` event, you will get the currently selected route instance, and you can export it any way you like: it contains the waypoints, coordinates and instructions for the route. See the documentation for [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) for more details.

**Comment by BasmaNabil** [comment]
Hello,

Thanks for your reply,is there anyway to export the map with the route on it to scale?

Thanks

**Comment by perliedman** [comment]
Sorry, nothing like that built into Leaflet Routing Machine; making print maps or similar is outside the scope of this plugin, but check the [Print/Export](http://leafletjs.com/plugins.html#printexport) plugins for that type of thing.
