### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by cordovapolymer** [perliedman/leaflet-routing-machine#397]
I'm getting this error on lrm 3.2.5 and leaflet 1.0.3
```
Routing error: Object {status: -3, message: "TypeError: Cannot read property 'call' of undefined"}
defaultErrorHandler @ leaflet-routing-machine.js:2605
fire @ leaflet.js:5
(anonymous) @ leaflet-routing-machine.js:2900
(anonymous) @ leaflet-routing-machine.js:4662
loaded @ leaflet-routing-machine.js:46
XMLHttpRequest.send (async)
corslite @ leaflet-routing-machine.js:88
route @ leaflet-routing-machine.js:4635
route @ leaflet-routing-machine.js:2885
_onWaypointsChanged @ leaflet-routing-machine.js:2821
fire @ leaflet.js:5
_fireChanged @ leaflet-routing-machine.js:5147
spliceWaypoints @ leaflet-routing-machine.js:5007
setWaypoints @ leaflet-routing-machine.js:4987
setWaypoints @ leaflet-routing-machine.js:2692
(anonymous) @ my-map.html:733
fire @ leaflet.js:5
_fireDOMEvent @ leaflet.js:6
_handleDOMEvent @ leaflet.js:6
h @ leaflet.js:6

```
I've seen it was corrected in https://github.com/perliedman/leaflet-routing-machine/issues/299 , but it doesn't work in my case, my code works in 0.7x but not in 1.x leaflet.

**Comment by perliedman** [comment]
Sorry, I can't really do anything with this error report. The demo site works with Leaflet 1.0, so there must be something related to your use. Can you provide a running example of the issue you're seeing=

**Comment by cordovapolymer** [comment]
@perliedman this code works in 0.7x and doesn't in 1.0.x, do you have a clue what's the reason?

```
createRoutes: function(item, waypoints) {
  this.line = L.Routing.control({
    plan: L.Routing.plan(waypoints, {
      createMarker: function(i, wp, n) {
        return;
      }.bind(this),
    }),
    serviceUrl: 'https://routerurl/route/v1',
    addWaypoints: true,
    draggableWaypoints: false,
    routeWhileDragging: false,
    fitSelectedRoutes: false,
    lineOptions: {
      styles: [
        {color: 'red', opacity: 0.15, weight: 9},
        {color: 'green', opacity: 0.8, weight: 6},
        {color: 'black', opacity: 1, weight: 2}
      ]
    },
  });
  this.line.on("routesfound", function(e) {
    this.groups.addLayer(this.line[item._id]);
  }.bind(this));
},
```

**Comment by perliedman** [comment]
I noticed that you never add to control to the map anywhere in the code above.

I created a slightly modified version of the code above, and it works with 1.0.3: http://playground-leaflet.rhcloud.com/vuxa/edit?html,output

**Comment by cordovapolymer** [comment]
Thanks for your answer, of course I add it to the map just as you did in the example, just posted the most important part. 
After checking out your example I've found where the incompatibility with 0.7x is.

I've been adding route as a layer to the map, but this doesn't work anymore in 1.x
```
  this.line.on("routesfound", function(e) {
    groups.addLayer(line[item._id]);
  }.bind(this));
```
as you have suggested, the addTo based code works.
```
  this.line.on("routesfound", function(e) {
    this.line.addTo(this.myMap);
  }.bind(this));
```

I would still like to add route to a dedicated layer, could you advise how to archive this?

**Comment by perliedman** [comment]
Ok, but it looks like those two examples do different things? Whats `line[item._id]`? In the second example, you add `this.line` instead (using `this`, so different scope).

If `line`, in the first example, is an array of controls, then `addLayer` will not work, since a control is not a layer, you have to use `addControl` instead, or `addTo`, which implicitly uses `addControl`.

Does this mean this issue is resolved?

**Comment by cordovapolymer** [comment]
@perliedman , I've corrected my example, I made a mistake during simplifying code for you from my actual version, where there are many lines each with it's id.

In the above example this.line is L.Routing.control, and this.groups['line'] is L.layerGroup()

So calling `this.groups['line'].addTo(this.line[item._id]);` gives
`Object {status: -3, message: "TypeError: t.addLayer is not a function"}`
and calling `this.groups['line'].addControl(this.line[item._id]);` gives 
`Object {status: -3, message: "TypeError: this.groups.line.addControl is not a function"}`

**Comment by perliedman** [comment]
I'm surprised if you could add a control to a layer group in 0.7, since it has no semantic meaning and layer groups have no logic for controls. Even if it didn't throw error, I'm fairly certain it wouldn't work as expected.

Regarding hiding and showing the control, there's a whole bunch of issues already regarding this. Short summary: add a CSS rule or remove the control from the map if you really want to hide it. Contributions to improve the current situation is of course always welcome as well.
