### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by fsiarazvan** [perliedman/leaflet-routing-machine#399]
How can i install the script without running it to a server...i whant to install directly to a webserver (php)

**Comment by perliedman** [comment]
Hi there,
I'm not entirely sure what you're asking here:

* If you  just want to use the plugin, just download the script to your server, as stated in the [getting started instructions](http://www.liedman.net/leaflet-routing-machine/#getting-started)
* If you mean you want to run routing without a backend server, that is generally not possible: routing is a very complex and resource intensive computation, and except for limited areas, you need a server for this; if you really have a very small routing network, you can perhaps use something like [geojson-path-finder](https://github.com/perliedman/geojson-path-finder) instead, which doesn't require an OSRM server
