### ISSUE TITLE
L.Routing.Plan fire event

### ISSUE THREAD

**Issue by s0fthunter** [perliedman/leaflet-routing-machine#401]
How to fire event 'waypointgeocoded' event? I tried everything,but nothing works. Please help. Thank you!

**Comment by perliedman** [comment]
@s0fthunter hm, what are you trying to accomplish? You shouldn't have to fire `waypointgeocoded`... or if you do, it most likely will not do what you want; that event is fired internally after a waypoint's coordinate has been geocoded.

**Comment by s0fthunter** [comment]
@perliedman ,ok ,I got it. I found what I was looking for. Thank you

**Comment by perliedman** [comment]
Alright, great :+1:
