### ISSUE TITLE
refresh map for new route

### ISSUE THREAD

**Issue by charlessabenin** [perliedman/leaflet-routing-machine#404]
Hi, am new with routing machine and i have it working but when i run it for a second time it keeps the first line and draw a second.

I want the map clear befor it draw the second route. 
can you help me throw ??

**Comment by perliedman** [comment]
Hi there,

it sounds like you're adding a second control to the map for the new route.

You have two options:

* Don't add a new control, just use `setWaypoints` on the control you have, and it will update to the new route
* Remove the first control using `map.removeControl` before adding a new control

Good luck!

**Comment by charlessabenin** [comment]
solved with map.removeControl
thanks
