### ISSUE TITLE
Highlight waypoints in route description

### ISSUE THREAD

**Issue by mdomnita** [perliedman/leaflet-routing-machine#405]
When I create a route with multiple waypoints I have no way of knowing which waypoint is which. 
I could think of two solutions for this:
A click on the waypoint highlights the corresponding field in the routing description 
or
the markers are marked and labeled with numbers both on the map and in the description. 
Any of these functionalities would be nice to have.

**Comment by sanastasiou** [comment]
I have exactly the same issue. The create marker callback is not called for the waypoints used in the route..

**Comment by perliedman** [comment]
Hi and sorry for a late reply to this.

You can use the `createMarker` option to override how markers are created, and for example use the nice [Leaflet.Icon.Glyph](https://github.com/Leaflet/Leaflet.Icon.Glyph) plugin to create numbered markers. I have done so many times myself. The only reason it's not built into Leaflet Routing Machine is that I don't want to rely on other plugins, but it is straight forward to implement if you're used to working with markers and icons.

@sanastasiou not sure what you mean when you say "The create marker callback is not called for the waypoints used in the route." but it sounds like either a problem in your code or something you should open a separate issue for.
