### ISSUE TITLE
Issue with routing icons not displaying correctly!

### ISSUE THREAD

**Issue by soynotoi** [perliedman/leaflet-routing-machine#406]
Hey, I'm having a weird issue where the routing icons do not display correctly. Here are some screenshots that show what I'm talking about:
![icons](https://cloud.githubusercontent.com/assets/25410744/25828623/33184632-341f-11e7-9150-d7f3b42775c4.PNG)
![icons2](https://cloud.githubusercontent.com/assets/25410744/25828624/331c0a56-341f-11e7-80ca-6a4a486cb5c3.png)

I've done exactly as specified and included all the relevant files, but I must be doing something wrong. Any ideas that could help me get on the right path would be greatly appreciated. Also, I apologize if this is an easily-fixable problem, but I found nothing related during my searches on the issue. Thank you!!!!

**Comment by perliedman** [comment]
Hi there,
hard to tell exactly what went wrong here, but if you look at the class names, they are not correct. In the screenshot you provided, you have for example `leaflet-routing-icon-kRight`, which isn't one of the defined icon classes: https://github.com/perliedman/leaflet-routing-machine/blob/master/dist/leaflet-routing-machine.css#L89

I guess you must have made some modifications to end up with this?

**Comment by soynotoi** [comment]
I did notice that, but I have no inclination as to what modifications I could have made that would result in this. I haven't altered the LRM css and js or the icons png either. I've gone over my code more than a few times but I haven't noticed anything that would do this. I've included that too for reference. Also thanks for the quick reply!

```
var map = L.map('map').setView([42.3601, -71.0589], 13);
  
    var url = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=XXX';
  
    var attr = 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,'
        + '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>,'
        + 'Imagery © <a href="http://mapbox.com">Mapbox</a>';
  
    L.tileLayer(url, {id:'mapbox.outdoors', attribution: attr, maxZoom: 18
    }).addTo(map);

    var control = L.Routing.control({
        waypoints: [null],
            // L.latLng(57.74, 11.94),
            // L.latLng(57.6792, 11.949)
        routeWhileDragging: true,
        show: true,
        fitSelectedRoutes: false,
        autoRoute: true,
        reverseWaypoints: true,
        showAlternatives: true,
        geocoder: L.Control.Geocoder.mapzen('XXX'),
        router: road,
        formatter: new L.Routing.mapzenFormatter()
    }).addTo(map);
    
    L.Routing.errorControl(control).addTo(map);
```

```
var road = L.Routing.mapzen('XXX', {

    costing: 'bicycle'
    costing_options: {
        bicycle : {
            bicycle_type: 'road',
            use_roads: '1',
            use_hills: '0.5',
            use_ferry: '0.1'
        },
    },
});
road.options.profile = 'mapbox.cycling';
```

**Comment by perliedman** [comment]
It looks like you're using Mapzen's LRM plugin, I think they include their own CSS/routing icons, so you should follow their instructions closely instead of the generic instructions; my guess is that the CSS classes you're seeing above is generated by Mapzen's plugin, but you're still using LRM's CSS, which doesn't have these classes.

**Comment by soynotoi** [comment]
Yup, you were right! After a lot of tinkering, I still couldn't figure out why it was doing that. My efforts to fix it ended up breaking the map, so I decided to drop lrm-mapzen entirely. Thank you though!
