### ISSUE TITLE
Show alternative route more than one (Graphopper)

### ISSUE THREAD

**Issue by frolody** [perliedman/leaflet-routing-machine#409]
How to show Show alternative route more than one ?
this my code :

```js
rute = L.Routing.control({
                waypoints: [marker_awal.getLatLng(), markerCabang[index].getLatLng()],
                draggableWaypoints: false,
                routeWhileDragging: false,
                reverseWaypoints: false,
                useZoomParameter: false,
                showAlternatives: true, 
                fitSelectedRoutes : false,
                createMarker: function(i, wp, er) {
                        return null;
                },
                lineOptions: {
                    styles: [{color: 'black', opacity: 0.15, weight: 9},
                                    {color: 'white', opacity: 0.8, weight: 6},
                                    {color: 'blue', opacity: 1, weight: 2}]
                },
                altLineOptions: {
                    styles: [
                        {color: 'red', opacity: 0.15, weight: 9},
                        {color: 'white', opacity: 0.8, weight: 6},
                        {color: 'blue', opacity: 0.5, weight: 2}
                    ]
                },
                router: L.Routing.graphHopper('', {
                    serviceUrl: 'http://localhost:8989/route',
                    urlParameters: {
                        vehicle: 'car',
                        algorithm: 'alternative_route',
                        max_paths: 3,
                        weighting: 'shortest'
                    }
                })
            });
```

**Comment by perliedman** [comment]
Hi there,

are you sure GraphHopper actually returns more than one result to you?

I'm not actively using GraphHopper myself, so I can't verify, but it looks like the code should support multiple alternatives if they are provided by the server.

**Comment by frolody** [comment]
graphopper returns 3 route points  json format (2 primary route, and 1 alt route), but LRM just show 2 route (1 primary route, and 1 alt route). what i'm missing?

**Comment by perliedman** [comment]
To get further, I think you either need to supply an example we can debug, or try to debug at your end.

If you look at this line of code: https://github.com/perliedman/lrm-graphhopper/blob/master/src/L.Routing.GraphHopper.js#L99 - you can see that we loop over the `paths` array to build the alternatives, so we need to figure out why that isn't working, or what happens to the other alternatives after that loop.

**Comment by curtisy1** [comment]
Since there is no repro and it seems to be graphhopper specific, I'll go ahead and close this for the time being
