### ISSUE TITLE
Incorrect routing line waypoints outside landmass

### ISSUE THREAD

**Issue by oxidase** [perliedman/leaflet-routing-machine#417]
Hi there,

there is a minor issue with waypoints for http://map.project-osrm.org/?z=5&center=75.442029%2C37.485352&loc=77.201150%2C28.553070&loc=79.201526%2C30.553529&hl=en&alt=0 at  [`_findClosestRoutePoint(wps[i].latLng)`](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/line.js#L49) returns two 0 values so `indices = [0, 0]`

* [ ] This is actually an issue with Leaflet Routing Machine, not a question
* [ ] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [ ] You have looked through existing issues

Also, are you making a feature request, or are you in need of more advanced support?
Please consider **sponsoring development**, or paying for support. Not only will this most likely solve your issue quickly,
it's also an awesome way to keep open source projects alive and maintained, as well as giving something back for the
open source you're using. Contact me at per@liedman.net for more information.

**Comment by perliedman** [comment]
Hi,
I'm pretty certain this is more or less the same issue as #356, which is fixed and part of version 3.2.5, but from the looks of it the OSRM frontend uses an older version. Could you try upgrading and see if that fixes the problem?

**Comment by oxidase** [comment]
@perliedman thanks! The issue is fixed in 3.2.5
