### ISSUE TITLE
Question - how to fire linetouched event

### ISSUE THREAD

**Issue by PriyeshT** [perliedman/leaflet-routing-machine#419]
Hello,

How do I fire the linetouched event?

I need to disable to default functionality wherein a waypoint is added when a point is clicked on the map? 

The API docs mention about L.Routing.line's linetouched event. But I am unable to understand how I can fire this event.

Thanks,
Priyesh T.

**Comment by perliedman** [comment]
You should be able to disable adding new waypoints when the line is touched by setting the option `addWaypoints: false`.

Unless you're re-implementing the `RouteLine` class, you shouldn't need to fire the `linetouched` event yourself, it's done by the `RouteLine` object.

**Comment by PriyeshT** [comment]
If I set addWaypoints: false, I am unable to edit the waypoints which are set using the geocoder. I need a way to restrict the user to add the waypoints only when they click on the route line.

The users should still be able to enter the required Start and End destination values.

**Comment by perliedman** [comment]
Ok. Use the `lineOptions` option, to set `addWaypoints: false` only for lines.

```js
var control = L.routing.control({
    lineOptions: { addWaypoints: false }
    ...
});

**Comment by PriyeshT** [comment]
Using lineOptions to set addWaypoints: false, also doesn't work.  I am still able to click on the line and add waypoints.

**Comment by PriyeshT** [comment]
OK. This resolved the issue. Thanks for the help :)
