### ISSUE TITLE
remove routing

### ISSUE THREAD

**Issue by sag3ll0** [perliedman/leaflet-routing-machine#423]
Hi, i try hide routing instrument and call
```
this.routeC.hide(); 
```
where 
```
this.routeC = L.Routing.control({...});
```
but its only minimize route panel and route its still placed on map
then i try 
```
this.routeC._plan._removeMarkers();
this.routeC._clearLines();
```
and its ckear all on map, but if i change zoom the route its still drawing
![image](https://user-images.githubusercontent.com/18505406/28691086-4a65d248-7324-11e7-9617-045f23138d11.png)
what comman i should use for disable routing?

**Comment by perliedman** [comment]
Hi,
you're probably best off using `map.removeControl` if you really want to remove the routing control.
