### ISSUE TITLE
Vertical Offset

### ISSUE THREAD

**Issue by oxk4r01** [perliedman/leaflet-routing-machine#424]
Hi. I'm using a function similar to this one for verticall offseting map points when clicked in Leaflet, and it works, but when I try to make the same with the route coordinates doesn't works at all. I'm getting the coordinate by clicking the corresponding routing machine pane, and the p_LatLng_arr is the array with the latitude and longitude of the coordinate choosed. I think it could be a problem with the LRM itself, cause I think it performs a centering of the coordinate to the middle of the map before the function does, but I'm not sure. Can you help me, please? Thanks in advance.

function f_OffsetNode( p_LatLng_arr ) {
    L.Map.prototype.f_PanToOffset = function ( latlng, offset, options ) {
        var x = this.latLngToContainerPoint( latlng )
            .x - offset[ 0 ];
        var y = this.latLngToContainerPoint( latlng )
            .y - offset[ 1 ];
        var point = this.containerPointToLatLng( [ x, y ] )
        console.log( point );
        return this.setView( point, this._zoom, {
            pan: options
        } )
    }
    var ViewPortOffset = ViewPortHeigth / 3;
    MyMap.f_PanToOffset( p_LatLng_arr, [ 0, ViewPortOffset ], {
        "animate": true
    } );
}the

**Comment by perliedman** [comment]
Hi!

I'm not sure I understand what it is you're trying to achieve, but if you mean the LRM moves the map center, this is true by default. However, you can disable LRM from moving the map's center/zoom by setting the option `fitSelectedRoutes: false`.

Hope this helps!

**Comment by oxk4r01** [comment]
This way?
var myRoute = L
    .Routing
    .control( {
        waypoints: [],
        fitSelectedRoutes: false
    } );

I tried with no results...

**Comment by oxk4r01** [comment]
![lrm_captura](https://user-images.githubusercontent.com/1032224/29073675-c81f122c-7c4c-11e7-9666-fc4963d2490b.png)
Moreover, I would like to assing dinamically an id to the current blue circle, when I click it in the pane with the instructions for change it's style. Could you help me with that too, please?

**Comment by perliedman** [comment]
@oxk4r01 you'd probably have to override some code in `Itinerary`, I don't remember the specifics.

As you can see in the issue template, I do offer support for LRM on a consulting basis, but my time to work for free is too limited to help out with these type of issues. Sorry.

**Comment by oxk4r01** [comment]
Ok, I understand. But what about the fitSelectedRoutes: false? Where should I place it? As I point in the prior post, couldn't find the way to make it work...

**Comment by perliedman** [comment]
Not sure what's wrong in your example, here's a working example:http://playground-leaflet.rhcloud.com/lava/edit?html,output
