### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by alterx** [perliedman/leaflet-routing-machine#425]
* [x] This is actually an issue with Leaflet Routing Machine, not a question
* [x] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [x] You have looked through existing issues
-------
I'm currently working on a small react project and getting warnings about: 
`Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead.` from leaflet. It looks like this plugin is using something that's deprecated or in the process of being so.

The package versions I'm using are:
"leaflet": "1.2.0"
"leaflet-routing-machine": "3.2.5"

Thanks in advance :)

**Comment by perliedman** [comment]
Indeed. I even added that message to Leaflet myself: https://github.com/Leaflet/Leaflet/pull/5365 :smiley: 

I haven't had much time to work on Leaflet Routing Machine lately, but this is definitely something I should look at. I would guess it's a little bit involved, though, since I expect this to break compatibility with Leaflet 0.7, so it would probably have to be a Leaflet Routing Machine version 4.0.

**Comment by Wh1teFr0st** [comment]
I have this also and some more plugins threw this warning. In my case it is for example the Leaflet.draw 0.4.9 and the Control.Geocoder 1.5.4.

**Comment by muenchhagen** [comment]
Would love to see a version 4.0. 
My solution so far is to turn off the warnings. But my heart breaks doing so.

**Comment by jamesjefferies** [comment]
My PR - #445 means this issue can be closed - @perliedman is it worth doing a release do you think? 3.2.8? (and thanks for accepting the PR in the end!)

**Comment by perliedman** [comment]
Yes, closing this.

I should do a 3.2.8 release, but it might take a while to find the time to do it.

**Comment by alterx** [comment]
Hey @perliedman, maybe re open this one until the 3.2.8 release is out?

**Comment by Berkmann18** [comment]
Any idea when this v3.2.8 will be released?

**Comment by perliedman** [comment]
FYI, I released 3.2.8 just now.
