### ISSUE TITLE
Get widget instructions coordinates

### ISSUE THREAD

**Issue by oxk4r01** [perliedman/leaflet-routing-machine#426]
The route.coordinates array shows me a number of keys with coordinates that it's not the same length than the route.instructions one. I would like to get an array with coords just only for the instructions shown in the widget. is this possible? Thanks.

**Comment by perliedman** [comment]
@oxk4r01 each instruction has an `index` property, that is the index into the route's `coordinates` array for the instruction's related coordinate.
