### ISSUE TITLE
Property Routing does not exist on type L

### ISSUE THREAD

**Issue by MaryCooperGD** [perliedman/leaflet-routing-machine#430]
Hi, I have installed the plugin using npm and imported Routing this way:

`import { Routing} from "leaflet-routing-machine"`

However, when I write `L.Routing` it tells me that Routing does not exist for L. Did I miss something? Do I have to import other modules?

**Comment by perliedman** [comment]
`L` is Leaflet's namespace, so you need to make sure your app and Leaflet Routing Machine uses the same `L` instance. Depending on how you bundle your code, there might actually be more than one Leaflet instance around, and therefor you might be referencing a different `L`.

**Comment by MaryCooperGD** [comment]
How can I check that? I have just one .js file in which I use L.
Before trying `L.Routing` I just do:

    this.map = L.map('map', {
      center: this.center,
      zoom: 13
    });
    L.marker(this.center).addTo(this.map)
    .bindPopup('Popup')
    .openPopup();
    this.map.panTo(this.center)
    
    //Add OSM Layer
    L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?access_token={accessToken}",{
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
      accessToken:'*token*'
    })
      .addTo(this.map);

**Comment by perliedman** [comment]
I would usually check in DevTools: in the bundled file, find where Leaflet Routing Machine attaches to the `L` object - it's essentially this code: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/index.js#L16 - check which `L` that uses, and if it's a different one than you use later in the code. Hopefully you can trace where it comes from, and why the two are not the same, but that depends a lot on your bundling process.

**Comment by wangzi6578** [comment]
hello,
i have set up osrm demo server. and i already have the respond json from match service,so,how could i use the lrm draw this ponits in demo web,

**Comment by sikucing** [comment]
i use this plugin with ionic 3 and face the same problem with you a while ago...
i found this solution on stackoverflow that work for me, hope it will also solve your problem

```
declare var L:any;
import 'leaflet';
import 'leaflet-routing-machine';
```

source https://stackoverflow.com/questions/42380525/how-to-import-leaflet-routing-machine-into-an-ionic2-project

**Comment by perliedman** [comment]
Not sure we have any indication this is actually a problem with LRM, closing for now but feel free to add more info if you think this is an issue with Leaflet Routing Machine.

**Comment by fracergu** [comment]
Probably a bit late, but I'm writing this in case someone ends here looking for help.

The solution of @nurizzahudin works but in my case I lost Intellisense. I found two more ways to fix this on Angular and hopefully any framework that works with typescript.

First solution is to import `leaflet-routing-machine` after the leaflet namespace, i.e:

```ts
import * as L from 'leaflet'
import 'leaflet-routing-machine'
```

This seems to override the namespace and fixes the error at runtime.

The other solution, a bit more elegant imho 🧐 is to add both types on `tsconfig`:

```ts
{
  ...
  "compilerOptions": {
    ...
    "types": ["leaflet", "leaflet-routing-machine"]
  },
}
```

Hope this helps!
