### ISSUE TITLE
Extra comma on Mapbox API call

### ISSUE THREAD

**Issue by luigi0229** [perliedman/leaflet-routing-machine#432]
Hello,
For some strange reason (after the same code working for weeks) something changed on the API call to the Mapbox Router, where it adds an extra comma after the lat,lng, generating an invalid input error message. The API call looks like the one below:

https://api.tiles.mapbox.com/v4/directions/mapbox.walking/-73.995066,40.745176,;-74.0038951579,40.7508878031.json?instructions=true&alternatives=true&geometry=polyline&access_token='API_KEY'

Not sure what changed. Removing the comma before the semicolon after first coordinate generates the correct route. The function calling the API looks like this:

```
    L.Routing.control({
  waypoints : waypoints2,
  show: false,
  router: new L.Routing.Mapbox('API_KEY'),
  lineOptions: {
   styles: [{color: 'purple', opacity: .5, weight: 3},{color: 'white', opacity: .5, weight: 3}]
    },
  createMarker: function() { return null; }
  }).addTo(map);
```

Again, this worked for a while, and without making any changes, the route no longer gets generated. if anyone can help i would really appreciate it.

**Comment by perliedman** [comment]
What does your `waypoint2` array look like when this happens?

Unfortunately it's very hard to say anything about this without code that reproduces the issue.

**Comment by luigi0229** [comment]
I just replaced that with the waypoint array from the LRM example, same behavior. Now my code looks like this:

```
    L.Routing.control({
      waypoints: [
          L.latLng(57.74, 11.94),
          L.latLng(57.6792, 11.949)
      ],
  show: false,
  router: new L.Routing.Mapbox('pk.eyJ1IjoibHVpZ2kwMjI5IiwiYSI6ImNqNnhseGNsczFyb2Eyd3Bkbmp4cW5jbzAifQ.auFCa3NZcIgFS20o8QreNw'),
  }).addTo(map);
```
The same issue with the extra comma on the API call to Mapbox:

https://api.tiles.mapbox.com/v4/directions/mapbox.walking/11.94,57.74,;11.949,57.6792.json?instructions=true&alternatives=true&geometry=polyline&access_token=pk.eyJ1IjoibHVpZ2kwMjI5IiwiYSI6ImNqNnhseGNsczFyb2Eyd3Bkbmp4cW5jbzAifQ.auFCa3NZcIgFS20o8QreNw

If I remove that extra comma on the URL (right after 57.74), then it works:

https://api.tiles.mapbox.com/v4/directions/mapbox.walking/11.94,57.74;11.949,57.6792.json?instructions=true&alternatives=true&geometry=polyline&access_token=pk.eyJ1IjoibHVpZ2kwMjI5IiwiYSI6ImNqNnhseGNsczFyb2Eyd3Bkbmp4cW5jbzAifQ.auFCa3NZcIgFS20o8QreNw

Thanks again!

**Comment by perliedman** [comment]
Hm, strange. It seems something weird must be going on in your code.

Check this example that uses the code you pasted above: http://playground-leaflet.rhcloud.com/heso/edit?html,output

**Comment by luigi0229** [comment]
Very interesting. So i was using the lrm-mapbox-1.0.4.js and calling Mapbox using `new L.Routing.Mapbox(...)`. I did this because i needed walking directions, and had to edit the source code and hard code "walking" on the profile. I switched it to look like your example `router:  L.Routing.mapbox(...)` (with a lower case M) and now it seems to be working. I have to figure out how to get around the driving profile though. But thank you so much!
You're Awesome!

**Comment by sharkinsspatial** [comment]
@luigi0229 I was experiencing the same issue using an older version of leaflet-routing-machine with [lrm-mapbox](https://github.com/perliedman/lrm-mapbox) which is now deprecated.  I believe lrm-mapbox was always inserting the extra comma and Mapbox has recently changed the coordinate validation in their Directions API which caused the breaking change (not confirmed).
  
If you upgrade to the latest version of leaflet-routing-machine and use the new router constructor `L.Routing.mapbox(...)` you can pass the Mapbox Directions API walking profile in via the options parameter
```javascript
let options = { profile: 'mapbox/walking' }
L.Routing.control({
  [...],
  router: L.Routing.mapbox(MapBoxToken, options),
});
```
Also note the change in the Mapbox profile naming convention from 'mapbox.walking' to 'mapbox/walking'.

@perliedman I will try to submit a pull request with documentation updates for this if that is ok with you.

**Comment by perliedman** [comment]
@sharkinsspatial oh, nice catch, didn't think about the old lrm-mapbox plugin. A PR would be welcome!

@luigi0229 are you using the old plugin? In that case, switch to the builtin Mapbox router instead!

**Comment by sharkinsspatial** [comment]
@perliedman Is the repository for the [documentation page](http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/) available for contributions or would you just prefer adding more to the examples section of leaflet-routing-machine?

**Comment by perliedman** [comment]
@sharkinsspatial the docs page is in the `gh-pages` branch on github!

**Comment by wangzi6578** [comment]
hello,
i have set up osrm demo server. and i already have the respond json from match service,so,how could i use the lrm draw this ponits in demo web,
