### ISSUE TITLE
L.Routing.control

### ISSUE THREAD

**Issue by hellracer** [perliedman/leaflet-routing-machine#434]
Hi There,

I try to load an array of waypoints to waypoints option On L.Routing.control, doing so manually it's working as expected but getting the data via ajax, though I can concur the data is there the marker and the polyline is not shown on the map. Please see chrome developer screen shot as evidence the data was there.

![untitled](https://user-images.githubusercontent.com/3840828/30257408-8688b4f0-96e4-11e7-8ae2-45b480890af9.png)

**Comment by hellracer** [comment]
Thanks for someone who can shed some light on this thanks!

**Comment by hellracer** [comment]
` var points = [];
        $.get( "../api/loadmarker/862462030603939", function( data ) {
        for(var i in data.waypoints) { points.push(L.Routing.waypoint(L.latLng(data.waypoints[i].latitude,data.waypoints[i].longitude),data.waypoints[i].status));}
        });

var rc = L.Routing.control({
        createMarker: function(i, wp, nWps) {

        var icon = L.icon.glyph({
                                    prefix: '',
                                    glyph: String.fromCharCode(65 + i)
                                });

        return L.marker(wp.latLng,{draggable: false,icon: icon})
            .bindPopup(wp.name);
        },

        routeWhileDragging: false,
        lineOptions: {
        styles:
            [
                {color: 'black', opacity: 0.15, weight: 9}, //sombra
                {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                {color: 'green', opacity: 1, weight: 2}] // Centro
   },
          show: true,
          waypointMode : "snap",
          draggableWaypoints : false,
          waypoints: points
...
`
Relevant section of the code

**Comment by perliedman** [comment]
Hi,
ideally, if you could provide a running example, that helps a lot in identifying the problem.

Otherwise, please report any errors you see in the console. Also check the request to OSRM and see what what the response looks like. My guess is that your waypoints array is somehow not correctly formed.

**Comment by hellracer** [comment]
Basically If i manually pass this array it's working fine. but passing my "points" array of object variable it doesn't work at all, basically if you check the screenshot I can successfully pass the variable it just that it doesn't work


waypoints:  [
            L.latLng(14.36133, 121.02755),
            L.latLng(14.36135, 121.02766),
            L.latLng(14.36136, 121.02808),
            L.latLng(14.36126, 121.0279),
            L.latLng(14.3585, 121.02672),
            L.latLng(14.35841, 121.02669),
            L.latLng(14.35838, 121.02618)]

This is working fine,

**Comment by hellracer** [comment]
![untitled](https://user-images.githubusercontent.com/3840828/30264398-1408a242-970b-11e7-9cae-d2567907f402.png)

**Comment by hellracer** [comment]
This is really a red herring to me, trivial think to do but I couldn't really figure this out why, :), thanks for looking into this

**Comment by hellracer** [comment]
Additional Information, 

If I manually passed the array, I can see there's a request to OSRM server otherwise no request has been sent to the server.

**Comment by perliedman** [comment]
As I said before, almost impossible to debug without a running example illustrating the problem.

Given what I've seen so far, I'd check that all waypoints really have valid `LatLng`s - the router will check that before making a request to OSRM.

Your `for var i in data.waypoints` looks suspicious, depending exactly on what keys are in the `data.waypoints` object. I'd prefer a normal `for (var i = 0; i < data.waypoints.length; i++)` or possibly `data.waypoints.map` in this case.

**Comment by hellracer** [comment]
Hi perliedman,

Please close this, it's not bug but a textbook JS issue, it's about variable scoping I refactored the code and now it's working properly, thanks for taking time on this
