### ISSUE TITLE
Changing color of leaflet-routing-machine dynamically?

### ISSUE THREAD

**Issue by coviedo** [perliedman/leaflet-routing-machine#435]
I'm trying to change properties the leaflet-routing-machine like they are width, color, opacity through a user tool once it was created.
```
var route = L.Routing.control({
   waypoints: [
        L.latLng(57.74, 11.94),
        L.latLng(57.6792, 11.949)
    ],
    routeWhileDragging: true,

       lineOptions: {
      styles: [{color: 'blue', opacity: 1, weight: 10}]
   }
}).addTo(map);

$(".pick-color").colorselector({
callback: function (value, color, title) {
    L.Routing.line(route, {styles:[{color: color}]})
}
```
![changecolor](https://user-images.githubusercontent.com/2223503/30515549-0474f39e-9af8-11e7-9623-961d196bfea6.png)

**Comment by perliedman** [comment]
You can control the styling of the route line from the [`lineOptions`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control).[`style`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-line), but that can only be done in advance, not after the route is actually added to the map.
