### ISSUE TITLE
Profiles OSRM Routing

### ISSUE THREAD

**Issue by astridx** [perliedman/leaflet-routing-machine#436]
I have got a very basic skript for integrating a routing control into a leaflet map.

```
<!DOCTYPE HTML>
<html>
<head>
<title>Eine OSM Karte mit Leaflet</title>
<link rel="stylesheet" href="../leaflet/leaflet.css" />
<script src="../leaflet/leaflet.js"></script>
<script src="leaflet-routing-machine.js"></script>
<script src="Control.Geocoder.js"></script>
<link rel="stylesheet" href="Control.Geocoder.css" />
<link rel="stylesheet" href="leaflet-routing-machine.css" />
</head>
<body>
<div style="height: 400px;" id="mapid"></div>
<script>
var mymap = L.map('mapid').setView([50.27264, 7.26469], 13);
console.log(mymap);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(mymap);
var control = L.Routing.control({
waypoints: [
L.latLng(50.273543, 7.262993),
L.latLng(50.281168, 7.276211)
],
router: new L.Routing.osrmv1({
language: 'de',
profil: 'car'
}),
geocoder: L.Control.Geocoder.nominatim({})
}).addTo(mymap);
</script>
</body>
</html>
```

Everything works fine. I only have problems with the profile. It is equal what I put into this option (car, foot, biycle), there is no different routing.

I found in the documentation of the leaflet routing machine (http://www.liedman.net/leaflet-routing-machine/api/#l-routing-osrmv1) a link to the documentation of the router: https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md How can I use the different profiles of the Project-OSRM? Can I only use this as a web service?

Crossposting: https://stackoverflow.com/questions/46298652/leaflet-routing-machine-and-osrm-routing

**Comment by perliedman** [comment]
From the code you posted you've typed `profil`, while it should be `profile` (note that final "e" in "profile"). Is that possibly the source of the problem?

**Comment by astridx** [comment]
Thank you for your very fast reply. But I made this typo only in the post. 
There is no difference if I  
`profil: 'car'`
or if I insert
`profil: 'foot'`

**Comment by perliedman** [comment]
Hm, thinking about it, it looks like you're using OSRM's demo server (the default for Leaflet Routing Machine). To my knowledge, the demo server only supports the car profile, so there will not be any difference by specifying another profile.

If you use another (usually paid) provider, or set up your own OSRM server, they can provide more profiles. For example, I know Mapbox has multiple profiles.

**Comment by astridx** [comment]
OK, thank you for your answer. That is it. I use the OSRM demo server in this example and I did not know, that this demo server is limited.
With Mapbox it works fine.

**Comment by HunzlaSheikh** [comment]
@astridx How you use Mapbox?

**Comment by astridx** [comment]
@HunzlaSheikh perliedman has explained it here: https://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/

**Comment by HunzlaSheikh** [comment]
Ok, thank you :)
