### ISSUE TITLE
route again when map zoom

### ISSUE THREAD

**Issue by muratonal** [perliedman/leaflet-routing-machine#439]
why this make reroute when I zoom in map?

**Comment by perliedman** [comment]
The initial route response from OSRM is a low resolution route (the route coordinates are simplified according after some heuristics). When zooming in, LRM will fetch a more detailed version of the route geometry if necessary.

**Comment by muratonal** [comment]
thanks for reply

**Comment by NValanos** [comment]
Is there any way to disable the recalculation of the route on zoom?
