### ISSUE TITLE
No line between two markers

### ISSUE THREAD

**Issue by ke90** [perliedman/leaflet-routing-machine#440]
Hey,

i have a problem with the line between two markers with Leaflet. The Map is displayed with the markers but without a line....

`    var mymap = L.map('mapid').setView([57.74, 11.94], 13);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'Here is my token ;)',
    style: 'mapbox://styles/mapbox/streets-v10'
}).addTo(mymap);

L.Routing.control({
    waypoints: [
        L.latLng(57.74, 11.94),
        L.latLng(57.6792, 11.949)
    ],
    routeWhileDragging: true
}).addTo(mymap);`

The two markers are displayed, but the line beetween them is missing.

At the page from Leaflet is this message:Leaflet

Is that the reason why it doesn't work? What can i do?

mfg

**Comment by perliedman** [comment]
Hi, it looks like you're using the default router, which is OSRM's demo server. This server has recently been shut down, as far as I know, so you can't use it for routing any more.

You either need to use a paid routing service, or set up your own OSRM server to make this work.
