### ISSUE TITLE
route planner re-order waypoints

### ISSUE THREAD

**Issue by jrischma** [perliedman/leaflet-routing-machine#441]
Hi, is it possible that the points are automatically sorted to get the best route possible?

thanks

**Comment by perliedman** [comment]
Hi, that's outside the scope of Leaflet Routing Machine, which is just a frontend to OSRM (or other routing backends).

It sounds like you should look at [OSRM's trip service](http://project-osrm.org/docs/v5.9.1/api/#trip-service); related to that: #169.
