### ISSUE TITLE
Routing Error: step is undefined

### ISSUE THREAD

**Issue by barlima** [perliedman/leaflet-routing-machine#442]
Hello,
I have just set up OSRM server locally and I am trying to draw a line between two points.
It worked on the demo server but when I moved it to the local OSRM I received an error:
```
Routing error: Object { status: -3, message: "TypeError: step is undefined" }
```

What I have done. I have cloned OSRM repo, built it, downloaded Massachusetts, extracted it using car.lua profile (at the beginning) and then foot.lua profile, and then I have started the server. I have modified src.js, so now it looks like that:
```
module.exports = L.Class.extend({
		options: {
			//serviceUrl: 'https://router.project-osrm.org/route/v1',
			serviceUrl: 'http://127.0.0.1:5000/route/v1',
			profile: 'driving',
			timeout: 30 * 1000,
			routingOptions: {
				alternatives: true,
				steps: true
			},
			polylinePrecision: 5,
			useHints: true,
			suppressDemoServerWarning: false,
			language: 'en'
		},
```
Then I used ```npm install``` to apply the changes.

When I try to connect two points on the map, the error appears. When I run the same request with curl I receive the data from OSRM. Request looks like this:
```http://127.0.0.1:5000/route/v1/driving/-71.06,42.36;-71.11,42.36?overview=false&alternatives=true&steps=false&hints=;```

Routing part of the code:
```// Draw selected paths
        L.Routing.control({
            waypoints: [
                    L.latLng(42.36, -71.06),
                    L.latLng(42.36, -71.11),
            ],
            routeWhileDragging: true,
            show: false
        }).addTo(map);
```
The rest of the code looks almost the same as in the Leaflet Routing Machine tutorial.
Please advise.

**Comment by perliedman** [comment]
Hi!

Can't say that this is an issue I've heard about before. Unfortunately, it's really hard to say anything about it without seeing a live example.

Note that in general you shouldn't modify the source - that just opens up for a lot of trouble. Instead, use the `serviceUrl` option to override the default. You should leave the plugin code untouched, and instantiate the control like this instead:

```js
        L.Routing.control({
            serviceUrl: 'http://127.0.0.1:5000/route/v1',
            waypoints: [
                    L.latLng(42.36, -71.06),
                    L.latLng(42.36, -71.11),
            ],
            routeWhileDragging: true,
            show: false
        }).addTo(map);
```

If you can't publish a running version that illustrates the problem, I receommend stepping through the code in Chrome devtools or similar to see what's going on. A stack trace and a copy OSRM's query response might also help.

**Comment by barlima** [comment]
Thanks you for the quick reply. 
I used the source code and I added the serviceUrl option. It works smoothly right now.
Thank you!
