### ISSUE TITLE
Geocoding Mapzen Search

### ISSUE THREAD

**Issue by webmap2015** [perliedman/leaflet-routing-machine#443]
Hi, leaflet routing machine's default geocoder is OSM/Nominatim.

Does it supports Mapzen Search?

**Comment by perliedman** [comment]
Hi, please check out the tutorial on geocoders: http://www.liedman.net/leaflet-routing-machine/tutorials/geocoders/

As mentioned in the tutorial, it's really compatible with any geocoder that is supported by Leaflet Control Geocoder - with the latest version of it, it also supports Mapzen.

You can also add your own geocoder as long as you follow the interface defined by Leaflet Control Geocoder.

**Comment by webmap2015** [comment]
Thank you for your quick answer. But, I have another question.

With two plugins 

"https://github.com/perliedman/leaflet-routing-machine
"https://github.com/mapzen/leaflet-geocoder"

And with below codes

L.Routing.control({
	waypoints: [
		L.latLng(57.74, 11.94),
		L.latLng(57.6792, 11.949)
	]
}).addTo(map);

my project are working good.

But, when I add "geocoder: L.Control.Geocoder.nominatim()," line

L.Routing.control({
	geocoder: L.Control.Geocoder.nominatim(),
	waypoints: [
		L.latLng(57.74, 11.94),
		L.latLng(57.6792, 11.949)
	]
}).addTo(map);

There is a error "Uncaught TypeError: L.Control.Geocoder.nominatim is not a function"

and "leaflet-routing-machine" is disappeared.

**Comment by webmap2015** [comment]
Thank you @perliedman

**Comment by webmap2015** [comment]
Hi @perliedman,

When I add "geocoder: L.Control.Geocoder.mapzen(apikey), "

there is a error:

"L.Control.Geocoder.mapzen is not a function"

Thanks.

**Comment by perliedman** [comment]
@webmap2015 sorry,very hard to tell why, no more than that the class in question hasn't been properly loade. Check that the script loaded properly without errors and that the name is correct.
