### ISSUE TITLE
Routing error with Leaflet v0.7.2

### ISSUE THREAD

**Issue by Mapjotr** [perliedman/leaflet-routing-machine#444]
Hi!
I'm working with Leaflet  v0.7.2. 
As all works fine with LRM v3.2.5, it gives me the following error when working with LRM v.3.2.7 after loading the page:

**leaflet-routing-machine.js?body=1:10477 
Routing error: {status: -3, message: "TypeError: Cannot read property 'maneuver' of undefined"}**

**My setup:** 
index.html:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Leaflet OSRM Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
    <link rel="stylesheet" href="../dist/leaflet-routing-machine.css" />
    <link rel="stylesheet" href="index.css" />
</head>
<body>
    <div id="map" class="map"></div>
    <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
    <script src="../dist/leaflet-routing-machine.js"></script>
    <script src="Control.Geocoder.js"></script>
    <script src="config.js"></script>
    <script src="index.js"></script>
</body>
</html>
```
index.js:
```javascript
var map = L.map('map');

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var control = L.Routing.control(L.extend(window.lrmConfig, {
	waypoints: [
		L.latLng(57.74, 11.94),
		L.latLng(57.6792, 11.949)
	],
	geocoder: L.Control.Geocoder.nominatim(),
	routeWhileDragging: true,
	reverseWaypoints: true,
	showAlternatives: true,
	altLineOptions: {
		styles: [
			{color: 'black', opacity: 0.15, weight: 9},
			{color: 'white', opacity: 0.8, weight: 6},
			{color: 'blue', opacity: 0.5, weight: 2}
		]
	}
})).addTo(map);

L.Routing.errorControl(control).addTo(map);
```

Is Leaflet  v.0.7.2 still supported?
Many thanks in advance for your help and best regards,
Peter

**Comment by perliedman** [comment]
Hi!

Without seeing a live example, or at least a stack trace and some local variables, it's more or less impossible for me to say anything about this. Please set up a JSFiddle or similar, if possible.

In theory, I guess we still support Leaflet 0.7.2, but I never try with such old versions these days, the time I have to spend on maintaining LRM is too limited to really try out anything other than Leaflet 1.0+ (and I think you should really consider upgrading to 1.0).

**Comment by andrewharvey** [comment]
I ran into this when following the example. Upgrading to a recent leaflet resolves the issue for me.

**Comment by perliedman** [comment]
:+1: Nice. If this is a real problem for someone, please provide an example of the issue you're running into.

Closing this for now, but will consider re-opening if I see a running example.

**Comment by dwiyatci** [comment]
Since upgrading to Leaflet 1.x is not an option for me at the moment, downgrading to LRM v3.2.5 works fine for me. 😁👍
