### ISSUE TITLE
Leaflet ignores Tracks when no other road is available

### ISSUE THREAD

**Issue by JAT86** [perliedman/leaflet-routing-machine#450]
In isolated villages with only track roads, Leaflet Routing Machine appears to ignore those roads and searches for the nearest non-track road, even though it is several miles away. It creates a straight line from the isolated villages to that distant road, ignoring the tracks route (I have recently updated the road type in OSM to minor):

https://www.openstreetmap.org/#map=15/17.7760/120.9408
![lroutingmachineignoringtracks](https://user-images.githubusercontent.com/30237173/33973094-01946b8c-e0bc-11e7-88c2-73a7424d42a7.png)

Zoomed out:
![lroutingmachineignoringtrackszoomedout](https://user-images.githubusercontent.com/30237173/33973518-45184598-e0be-11e7-9a3e-726f7b80d749.png)

**Comment by perliedman** [comment]
Hi, as you might know, Leaflet Routing Machine is just a web user interface to calculate routes. It uses a routing backend to actually calculate the route. As default, it uses OSRM's demo server, for example.

So, LRM can't do anything about the actual route calculation. Probably, you could alter OSRM's configuration to address your particular issue, if it ignores track roads. Check out the [OSRM backend] if you haven't already.
