### ISSUE TITLE
Using Leaflet Line to show routes

### ISSUE THREAD

**Issue by alu0100782974** [perliedman/leaflet-routing-machine#451]
Hi, I'm trying to show the route between two points without using the Routing control and I don't know how. I've read all the issues and I found one where you recommend using the Routing line but the resource you posted there is not available so i can't find a solution. 
I really appreciate if you can give me an example that solves this.
Sorry for the inconveniences and thank you in advance.

**Comment by Giserwu** [comment]
Hello there! I also happened to encounter a similar problem: I calculated the path result of GeoJSON format by other ways, and I want to realize the effect of the path interface of the icon in the similar case, as shown in the figure. Could you please give a detailed case? Thank you! !
![qq 20180103205500](https://user-images.githubusercontent.com/23161877/34521451-c7c0c8ac-f0c8-11e7-80bd-b8c5280ef43a.jpg)

**Comment by perliedman** [comment]
@alu0100782974 here's an example: https://plnkr.co/edit/jGJqsjB1TjapsTkM1jZt?p=preview

**Comment by perliedman** [comment]
@Giserwu sounds like a separate issue. Do you mean you have the route as GeoJSON, and would like to produce an itinerary from it?

**Comment by alu0100782974** [comment]
@perliedman thank you
