### ISSUE TITLE
Add own Landmark and Data for Routing

### ISSUE THREAD

**Issue by anilkumar93** [perliedman/leaflet-routing-machine#452]
Hi,
I am new to leaflet, and developing an application for routing but i have some issue.
1. I need alternative route for every route. Is it possible?
2. Can we add or use our own landmark while creating route. I mean route should be made showing my own landmark if present?
3. Can we use our own data for geocoding and also for creating route?

Thanks & Regards
Anil Kumar

**Comment by perliedman** [comment]
Hi,
Leaflet Routing Machine is a frontend used to edit waypoints and display routes - the actual routing calculations are done by a routing backend; by default, OSRM is used for calculating the routes, and the routing data is built from OpenStreetMap data.

If you set up your own OSRM server, you can configure it as you like, and the same goes for geocoding, you can replace the backend used to make it work with any data source.

I suggest you look at the [Alternative routers tutorial](http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/) and [Geocoders tutorial](http://www.liedman.net/leaflet-routing-machine/tutorials/geocoders/) (which has a section on implementing your own geocoder).

**Comment by anilkumar93** [comment]
Your map included landmark or not? if yes then i would like to bind them in route direction table

**Comment by perliedman** [comment]
The thing is that I (or rather Leaflet Routing Machine) does not have a map. It uses some backend to present routes. As mentioned above, the default is OSRM. OSRM does not contain landmarks or similar, it just calculates routes.

So no, you can't just add landmarks to the itinerary, it's not something built into Leaflet Routing Machine. You will have to implement that functionality yourself.
