### ISSUE TITLE
What usage limitations exist?

### ISSUE THREAD

**Issue by parky128** [perliedman/leaflet-routing-machine#454]
Hi,

With the out of the box API, are there are usage restrictions for:

-The number of waypoints that can be added
-The number of routing requests that can be made, e.g  over a 24hour period

I have seen such limits with the Google maps API and so wondered how this library compared.

Thanks

**Comment by perliedman** [comment]
Hi,
Leaflet Routing Machine is just a user interface, you need a routing backend to actually calculate the routes.

By default, Leaflet Routing Machine use OSRM's demo server. As the name says, that server is intended for _demo_ purposes, and comes without any warranties, and you do not want to use it for production use.

For production, you have several options: set up your own OSRM server (cheap and easy for a limited geographic area, quite complex for global coverage), or you can use a paid service like GraphHopper or Mapbox, which both provide excellent services that work well with Leaflet Routing Machine.
