### ISSUE TITLE
Disable user interaction with the route

### ISSUE THREAD

**Issue by esurnet** [perliedman/leaflet-routing-machine#455]
Hello. 
I set draggableWaypoints as well as addWaypoints to false, but i can still drag the first and last point. So is there a way to disable all interaction with the user.

**Comment by perliedman** [comment]
Can you show a code example when this is a problem? As far as I know, setting both `draggableWaypoints` and `addWaypoints` to `false` should disable all interactions.

**Comment by HunzlaSheikh** [comment]
L.Routing.control({
    waypoints: waypoint,
    router: L.Routing.mapbox('access-token'),
    lineOptions: {styles: [{color: '#242c81', weight: 2}]},
    fitSelectedRoutes: true,
    draggableWaypoints: false,
    routeWhileDragging: false,
    createMarker: function() { return null; } 
  }).addTo(this.map);
But i can still drag any route point and change route. How can i solve/disable it?

**Comment by nadhirxz** [comment]
> L.Routing.control({
> waypoints: waypoint,
> router: L.Routing.mapbox('access-token'),
> lineOptions: {styles: [{color: '#242c81', weight: 2}]},
> fitSelectedRoutes: true,
> draggableWaypoints: false,
> routeWhileDragging: false,
> createMarker: function() { return null; }
> }).addTo(this.map);
> But i can still drag any route point and change route. How can i solve/disable it?

when instantiating `L.Routing.Control` pass `lineOptions` property with `addWaypoints: false` inside and your code would look like this :
```
L.Routing.control({
    waypoints: waypoint,
    router: L.Routing.mapbox('access-token'),
    lineOptions: {styles: [{color: '#242c81', weight: 2}]},
    fitSelectedRoutes: true,
    draggableWaypoints: false,
    routeWhileDragging: false,
    createMarker: function() { return null; },
    lineOptions : {
        addWaypoints: false
    }
}).addTo(this.map);

```

**Comment by ruijramos** [comment]
Hello! :) 

Working with Angular version 15, I have this error:

- Object literal may only specify known properties, and 'draggableWaypoints' does not exist in type 'RoutingControlOptions'.

Has the parameter been de-implemented?
