### ISSUE TITLE
this._altContainer not initialized

### ISSUE THREAD

**Issue by solarsea** [perliedman/leaflet-routing-machine#462]
A rather basic setup, like

            this.egressRouteControl = L.Routing.control({
              waypoints: [
                this.office,
                L.latLng(this.user.latitude, this.user.longitude)
              ],
              serviceUrl: osrm // my own osrm instance
            });

crashes with:

Routing error: 
{status: -3, message: "TypeError: Cannot read property 'appendChild' of undefined"}
defaultErrorHandler	@	leaflet-routing-machine.js:10477
fire	@	leaflet-src.js:593
(anonymous)	@	leaflet-routing-machine.js:10772
(anonymous)	@	leaflet-routing-machine.js:12546
loaded	@	leaflet-routing-machine.js:46

Which seems to be caused by setAlternatives that unconditionally tries to add them this._altContainer.appendChild(altDiv); but this._altContainer is undefined at that point.

**Comment by perliedman** [comment]
Hi,
I'm a bit confused by this. From the looks of your code, this is more or less exactly the code from the example, which does work for this scenario, if I'm not mistaken.

Could there be anything else in your setup that causes this? It would also be a lot easier to debug if you could show a running example of the issue, preferably on JSFiddle or similar.

**Comment by solarsea** [comment]
Is there a unit test for the example ? I worked around it by settings the waypoints after the control was added to the map - the altContainer was then initialized and it worked fine

**Comment by perliedman** [comment]
Alright, I figure you're not adding the control to the but until some point after the routes have been calculated? That is, you're not immediately adding the control to the map after creating it.

That might be an untested use case, actually.

There are no unit tests in this project.

**Comment by solarsea** [comment]
Correct, I was waiting for the map to be initialized and ready as well before adding the control to it.
