### ISSUE TITLE
itineraryClassName is not used

### ISSUE THREAD

**Issue by Brandhor** [perliedman/leaflet-routing-machine#463]
itineraryClassName is passed as containerClassName argument in itinerary-builder but containerClassName is never actually used in createContainer https://github.com/perliedman/leaflet-routing-machine/blob/2877d2e092bda5b30ef82c6cad74b380e018c082/src/itinerary-builder.js#L16

**Comment by perliedman** [comment]
A very late thank you for the heads up! :+1:
