### ISSUE TITLE
Route with Ordered List of Waypoints

### ISSUE THREAD

**Issue by cexposit** [perliedman/leaflet-routing-machine#464]
Hi, I have noticed that given an array of waypoints the obtained route does not respect the order of waypoints provided in the array (in some cases). This means the i-th waypoint in the array is not always  immediately before (i+1)-th. 

In the following I include a snippet:

```
L.Routing.control({
        waypoints: myWaypoints,
        draggableWaypoints: false,
        routeWhileDragging: false,
        lineOptions: {
          addWaypoints: false
        }
}).addTo(map)
```

Is it possible to guarantee the order of the waypoints provided?

Thank you in advance :)

**Comment by perliedman** [comment]
Hi,
that sounds very odd. The order of the waypoints should never be altered by Leaflet Routing Machine or the routing backend. Can you provide an example of waypoints where this happens?
