### ISSUE TITLE
Adding a Point on the map as a waypoint?

### ISSUE THREAD

**Issue by habib-farhan** [perliedman/leaflet-routing-machine#467]
I have a bunch of poi's loaded on the map form external source and i am trying to add them as waypoint, so in the popup with each marker i bind a button to add that poi as a waypoint, but as soon as click on it, another marker is put on the map which is expected, but the problem is, the point that appears, is located 5-10 pixels away from the poi, even when they have the same co-ordinates. Why is that?
And how can i not put a new marker on the map rather just use the poi and route through it without having to have an additional marker on the map.
Looking for some help! 
![poi](https://user-images.githubusercontent.com/19238093/37149420-2ca583b6-22ce-11e8-84f7-31ddff764efa.png)
![poi2](https://user-images.githubusercontent.com/19238093/37149508-8c729798-22ce-11e8-8b1f-495c631a85f0.png)

**Comment by perliedman** [comment]
Hard to tell without seeing the actual implementation, but my guess is that your POI marker's icon doesn't have its anchor point set properly. This means the icon's tip will not point at the markers coordinate. From your screenshot, it does actually look like the anchor point is (0, 0), the icon image's top left corner.

So, set the icon's [`iconAnchor`](http://leafletjs.com/reference-1.3.0.html#icon-iconanchor) properly.

**Comment by habib-farhan** [comment]
Yep, that was exactly the problem. thanks a lot.
I had another problem which is, i dont want to put a new pin on the map when i say **add it as a waypoint**, but instead i just want to use the same poi as a waypoint and route through it.
Here is my code: 
`  success: function(data) {
        var markers = [];
        var poiData = jQuery.parseJSON(data);
        var customOptions = {
          'className': 'poiPopup'
        }
        var marker;
        $.each(poiData, function(i, item) {
          var customPopup = document.createElement('div');
          customPopup.innerHTML = '<div class="customDiv">' +
                                  '<h3><strong style="color: #900">' + item.Title + '</strong></h3>' +
                                  '<div class="row">'+
                                  '<div class="col-sm-6"><h4>Lat: ' + item.Lat + '</h4></div>' +
                                  '<div class="col-sm-6"><h4>Lon: ' + item.Lon + '</h4></div>' +
                                  '</div>' +
                                  '<h3><strong>Description:</strong></h3>' +
                                  '<p>' + item.Description + '</p>' +
                                  '</div>' ;
          var addPointBtn = document.createElement('button');
          addPointBtn.className = 'btn btn-primary';
          addPointBtn.innerHTML = '<span>Add as a waypoint</span>';
          addPointBtn.addEventListener('click', function(e){
          var waypoint = new  L.Routing.Waypoint();
              waypoint.latLng = {};
              waypoint.latLng.lat = item.Lat;
              waypoint.latLng.lng = item.Lon;
              Routing.spliceWaypoints(1,0, waypoint.latLng);
              map.closePopup();
          });
          customPopup.appendChild(addPointBtn);
          marker = new L.marker([item.Lat, item.Lon], {
            icon: poiIcon
          });
          marker.bindPopup(customPopup, customOptions).addTo(map);
          markers.push(marker);

        });
        markersObj[pid] = markers;
      }`
here is make a waypoint object while looping through my data and call Routing.spliceWaypoint(); , which adds a waypoint.
I want to add the point by keeping the same icon and not putting another one.
![poi3](https://user-images.githubusercontent.com/19238093/37154470-6e5cac00-22e0-11e8-88ad-5a7232204d0d.png)
![poi4](https://user-images.githubusercontent.com/19238093/37154475-7054952c-22e0-11e8-9ad8-b45c361a68bc.png)
![poi5](https://user-images.githubusercontent.com/19238093/37154480-71e902e2-22e0-11e8-86b1-2105319460ea.png)

**Comment by perliedman** [comment]
There's an option for the router called `createMarker`, which overrides how the waypoint markers are created - you pass it a function that takes the waypoint index and the waypoint itself as arguments. If you do not want a marker for the waypoint, simply return `null` from this function.

**Comment by habib-farhan** [comment]
I have a followup question to this issue.
The problem that i find create marker is that it overrides everything and every other marker that has been  created.
I have Defined my function like this.
`  createMarker: function(i, wp, nWps) {
                    if (i === 0  ) {
                      var myStartIcon = L.icon({
                        iconUrl: 'assets/img/2.png',
                        iconAnchor: [13,20]
                      });
                      return L.marker(wp.latLng, {icon: myStartIcon });
                    }
                   else if(i === nWps - 1){
                      var myEndIcon = L.icon({
                        iconUrl: 'assets/img/end_16.png'
                      });
                      return L.marker(wp.latLng, {icon: myEndIcon });
                    }
                    else if(poiFlag) {
                        var poiMarker = L.icon({
                          iconUrl: 'assets/img/2.png'
                        });
                          poiFlag = false;
                          return L.marker(wp.latLng, {icon: poiMarker});
                    }
                    else {                        
                        poiNumber++;
                        return L.marker(wp.latLng, {icon: new L.NumberedDivIcon({number: poiNumber})});
                    }
                  }, 
`
Now to check if a waypoint is added i have a set poiFlag, and for the via points i am adding numbers.
The problem is when i add a via point, the number on all existing markers increases by one, which mean it creates every marker every time or i am missing something?
![1](https://user-images.githubusercontent.com/19238093/37651882-e57f7742-2c39-11e8-8577-f96dcf81f85a.png)
![2](https://user-images.githubusercontent.com/19238093/37651885-e7e499cc-2c39-11e8-90ba-10689c5b1ea6.png)

**Comment by perliedman** [comment]
Yes, it will recreate markers on updates. I don't think you should worry about that, creating markers is cheap. Or is there anything in particular about this that causes trouble for you?

**Comment by Sofiane23i** [comment]
Hello,

i tried to follow these comments and use the createmaker function on a list of L.lanLang affected waypoints to show marker with popup. the marker are presented on the map but the popup option does not work.

<?php
      foreach ($conn->query($sqlArArrets) as $row) {
        $sqlAr222 = "SELECT longuitude, latitude FROM dictioAnnaba where WilayaFr = '".$row['Arret']."' ";
      	$rowsAr222 = $conn->query($sqlAr222);
          $rowAr222 = $rowsAr222->fetch();     
    ?>    
   
    split_route.push(L.latLng(<?php echo $rowAr222['longuitude']; ?>,<?php echo $rowAr222['latitude'];?>));          

      <?php
        }
        ?>
           
    var route = L.Routing.control({
      createMarker: function(i, wp, nWps) {
        return L.marker(wp.latLng).bindPopup('Hello' + i).openPopup();
    },

      router: L.Routing.mapbox('pk.eyJ1Ijoic2FmZXJkeiIsImEiOiJjazZxdWgwajMwMGptM2t1aXJvaDU2b2M4In0.N9nKLkCGg6CZjVJtoVvZYg'),
     waypoints: split_route,

    addWaypoints: false,
    draggableWaypoints : false,
    routeWhileDragging: false,
   show: false,
     }).addTo(mymap);

**Comment by Beto-kopong** [comment]
can i ask for your coding

**Comment by Sofiane23i** [comment]
yes, of course
