### ISSUE TITLE
Using LRM with Angular4/TS/Ionic throws error

### ISSUE THREAD

**Issue by tryadelion** [perliedman/leaflet-routing-machine#468]
Hi there,
before submitting a new issue, please consider the following:

* [X ] This is actually an issue with Leaflet Routing Machine, not a question
* [ X] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [X ] You have looked through existing issues

Good morning,

when importing this library as a standard JS lib into Angular 5 (Because TS/Angular don't support the L.* weird way leaflet plugins work):
`import * as Routing from 'leaflet-routing-machine';`

Routing.control.([array_of_waypoints])/Routing.Control.([array_of_waypoints])/new Routing().control.([array_of_waypoints])/new Routing.Control([array_of_waypoints])  all throw errors.
The first two say "Control/control is not a function". the 2nd two say "control/Control/Routing is not a Constructor".

There is some weird compatibility issue with typescript/Angular that shouldn't be there.
To provide a working example, leaflet-heatmap did a great job and is easily importable as stand-alone, works flawlessly by just npm-ing it and doing an:
`import * as heat from 'leaflet-heatmap';`

**Comment by perliedman** [comment]
Hi!

I understand the issue. Unfortunately, I don't use Angular/TS (and I'm guessing WebPack) myself, so I have little input on this issue, and unfortunately not enough time to dive into this myself.

We've had this issue reported before, which sounds similar to what you describe - at the bottom there's a comment with a possible workaround: https://github.com/perliedman/leaflet-routing-machine/issues/430

Any help to improve this is of course appreciated!

**Comment by tryadelion** [comment]
it sadly didn't work, there must've been a change in how angular5 / newest typescript behaves with this kind of "imports".
i'll try again with a small workaround i did once for another plugin, if not, would you have a spare moment to try it out on a blank Ionic project? it takes less than a minute to have a working Ionic browser preview (ionic serve) running, and i'tll include angular5 an the latest TS for you to see how it behaves.

https://ionicframework.com/

**Comment by tryadelion** [comment]
After clearing up node_modules  this solution worked.  thanks!
