### ISSUE TITLE
Openrouteservice

### ISSUE THREAD

**Issue by NiekRood** [perliedman/leaflet-routing-machine#469]
I was using your plugin for Mapbox and it was al very easy to set up. However, using Mapbox is getting too expensive so I was looking for an alternative. I came across https://openrouteservice.org/documentation/

But now I am struggling. Does your plugin support openrouteservice? I don't know how to set things up so that leaflet routing machine will use openrouteservice

**Comment by perliedman** [comment]
Hi, there's a plugin that I haven't either written or used myself, but please try it out: https://github.com/willmorejg/lrm-openrouteservice

**Comment by NiekRood** [comment]
Thanks a lot for the quick response! I will check it out
