### ISSUE TITLE
autocomplete without having to press Enter

### ISSUE THREAD

**Issue by alfraidi** [perliedman/leaflet-routing-machine#476]
Is there a way to get the drop-down menu for google autocomplete without having to press enter?  

geocoder: L.Control.Geocoder.google("KEY")

Thanks a lot in advance

**Comment by perliedman** [comment]
For geocoders that support the `suggest` method, you do not have to press the enter key, so it is a matter of choosing such a geocoder (or implementing one).

Be advised that using Google's geocoder is not allowed unless you show the results on a Google map (which you normally do not when using Leaflet).
