### ISSUE TITLE
How can I set the lang to 'pt-BR' using osrm-text-instructions?

### ISSUE THREAD

**Issue by fagworio** [perliedman/leaflet-routing-machine#479]
How can I set the lang to 'pt-BR' using osrm-text-instructions to leaflet-routing-machine?
Someone has a sample to share how to do this.

                waypoints: [
                    L.latLng(57.74, 11.94),
                    L.latLng(57.6792, 11.949)
                ],
                language: 'pt-BR',
            }).addTo(map);
Thanks.

**Comment by davicustodio** [comment]
see #474

**Comment by perliedman** [comment]
Sorry for not getting back to you on this before. I have attempted a fix for this in the newly released version 3.2.9.
