### ISSUE TITLE
Can't drag new waypoints after they are created

### ISSUE THREAD

**Issue by rsofista** [perliedman/leaflet-routing-machine#480]
If you go to the demo page http://www.liedman.net/leaflet-routing-machine/ click on the route, a new blue marker is created, and if you try to drag it, it drags the map instead, the second time you click on the new marker to drag it, you can drag it.
If you click on the route to create the new marker, then click anywhere else on the map, then you can drag the new marker.

It looks like it isn't binding the drag events upon instantiation.
Is there any workaround to bind the those events right after it is created?

**Comment by perliedman** [comment]
Hm, that's indeed very weird, and I haven't noticed it before.

Don't know what the problem is, so unfortunately no workaround at the moment. Will have to investigate further. Any help is of course welcome.

**Comment by rsofista** [comment]
Just updated my project to the latest version of Leaflet 1.3.1 and it the problem doesn't occur.

**Comment by perliedman** [comment]
Ah, nice find! Also, very nice that I don't have to do anything but upgrade the Leaflet version 😉 

I'll keep this issue open to remind me that I have to fix the demo web site!
