### ISSUE TITLE
Remove fitBounds after drawing route

### ISSUE THREAD

**Issue by AbdallahMezo** [perliedman/leaflet-routing-machine#481]
I am using this library to draw a real-time routing, It works perfectly for me and all cases for the job had been done but there's something I cant fix, when the route ends, its sets a new zoom to map (bounds) and I dont want that to be done, searched for an option to pass it to control and didnt find, how can I fix that?
 Thanks.

**Comment by perliedman** [comment]
Hi! Great to hear that you're finding the plugin useful.

I think you're looking for the `fitSelectedRoutes` option (see [docs](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control), which you can just set to `false` to avoid fitting the route.
