### ISSUE TITLE
Removing a L.Routing.line() added to map

### ISSUE THREAD

**Issue by JasonDalton** [perliedman/leaflet-routing-machine#49]
I've added a line to the map  using

`L.Routing.line(routes[0]).addTo(map);`

when a user drops a pin on the map.   When they drop a new pin, I'd like to remove the previous line, but don't see a method for removing it.

**Comment by oleoduc** [comment]
I am currently facing the same issue. I can't find any workaround for it. It seems that a line instanciated within the callback function of router.route can't escape this context :/

**Comment by perliedman** [comment]
@oleoduc set the waypoints to an empty array, or just remove the control altogether from the map, that will remove the line.

**Comment by jammastergirish** [comment]
> ```js
> var line = L.Routing.line(routes[0]).addTo(map);
> ```

Thanks. What if you generated your line with `L.Routing.control(...).addTo(map);`? The same format doesn't seem to work.

Thank you!

**Comment by perliedman** [comment]
@jammastergirish then `line` will be a Leaflet layer, you should remove it with `map.removeLayer(line)`.
