### ISSUE TITLE
Limited WayPoints (Mapbox api) 

### ISSUE THREAD

**Issue by Johnstands** [perliedman/leaflet-routing-machine#491]
I notice that there is a limit as to how many waypoints can be used.
`{"message":"Too many coordinates; maximum number of coordinates is 25.","code":"InvalidInput"}`

**Comment by perliedman** [comment]
Yes, that is a limitation in Mapbox's API, and nothing Leaflet Routing Machine can change.

Having said that, if you find yourself needing more than 25 waypoints, maybe you should consider using the [`match` service](https://www.mapbox.com/api-documentation/#map-matching) instead.
