### ISSUE TITLE
t is not defined

### ISSUE THREAD

**Issue by RohanAsmat** [perliedman/leaflet-routing-machine#493]
Hi,

I am getting the following error: t is undefined. 
any clues?

Best Regards,
Muhammad Rohan Ali Asmat

**Comment by perliedman** [comment]
Hi,
unfortunately impossible to say anything about this since I don't know what your code is doing. Please provide a code example if you think this is an issue in Leaflet Routing Machine.

**Comment by curtisy1** [comment]
Cannot really do anything here without a reproducible code example. Since it's been a few years, I'll close this for now
