### ISSUE TITLE
Dollar signs in routing directions?

### ISSUE THREAD

**Issue by hpntk** [perliedman/leaflet-routing-machine#495]
Hi there,
before submitting a new issue, please consider the following:

* [x] This is actually an issue with Leaflet Routing Machine, not a question
* [x] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [x] You have looked through existing issues

Is this on purpose? It looks a little strange. Have disabled any font styling in my own stylesheets to make sure it wasn't a font compatibility issue, but the issue remains.

<img width="303" alt="screen shot 2018-10-21 at 11 47 06 am" src="https://user-images.githubusercontent.com/27933405/47269077-25d5a780-d527-11e8-96f0-c81ee3bd15b5.png">

**Comment by perliedman** [comment]
Does indeed look weird, which backend are you running? Is this from OSRM's demo server or some other routing service?

If it's OSRM, could you share the waypoint coordinates?

I suspect this is actually what the server responds, and therefor outside Leaflet Routing Machine's control, but hard to tell definitely without seeing the context.
