### ISSUE TITLE
How to change the route line color in leaflet when it is already added to map

### ISSUE THREAD

**Issue by Ramyapriya24** [perliedman/leaflet-routing-machine#497]
_Originally posted by @Ramyapriya24 in https://github.com/perliedman/leaflet-routing-machine/issues/63#issuecomment-436980105_

**Comment by perliedman** [comment]
Hi,

to do this you need to keep track of the line layer instance that the control creates for routes. You can probably do this by using the `createLine` option, where you can specify your own callback function to create the lines. You can then update the layer when you need to.

**Comment by Ramyapriya24** [comment]
Hi,
Could please provide any example using createLine option. Actually I have maintain the track for lines but it not updated.
Thanks
