### ISSUE TITLE
support - How to remove router

### ISSUE THREAD

**Issue by jowan** [perliedman/leaflet-routing-machine#5]
Hi, can you please tell me how you would remove the router ?

**Comment by web2style** [comment]
Leaflet has `remove` method to destroy the map completely: http://leafletjs.com/reference.html#map-remove It would be great to have smth similar here to destroy itinerary and route completely with a single method.

**Comment by perliedman** [comment]
@web2style use Leaflet's [`removeControl`](http://leafletjs.com/reference.html#map-removecontrol) method for this!

**Comment by marie15** [comment]
Thank you so much, this line : routing.spliceWaypoints(0, 2); helps me to remove my route from map. thank you so much :)

**Comment by StevenBedoya** [comment]
This line save my life, thanks! routing.spliceWaypoints(0, 2); //

**Comment by messaooudi** [comment]
you can simply set the waypoints to an empty array (to be sure it will be empty ) 
`routing.setWaypoints([])`

**Comment by rsofista** [comment]
When I use removeControl it gives an error in the line 465 in the map.getZoom(), when I zoom the map.
spliceWaypoints(0, 2) solved my problem
using leaflet 1.0

**Comment by renandegrandi** [comment]
+1 for review, I have the same problem as was said @rsofista.

**Comment by perliedman** [comment]
@renandegrandi this issue should be fixed if you're running 3.2.1 or later.

**Comment by renandegrandi** [comment]
@perliedman How do I get this version 3.2.1 or higher, if it is not already released in the release version, is there a test version?

**Comment by perliedman** [comment]
@renandegrandi right, I had forgot to publish the latest four (!) releases on Github, since I don't use that interface myself... I heartily recommend using npm for version manangement - that's a place new versions are always published.

**Comment by renandegrandi** [comment]
@perliedman thanks, in 3.2.4 problem is solved.

**Comment by oxk4r01** [comment]
map.removeControl(route) worked for me too, but any of the other options...

**Comment by kasunsk** [comment]
routing.spliceWaypoints(0, 2); work for me

**Comment by tenznhok** [comment]
How do I keep the markers after remove router? I used map.removeControl(route) or routing.spliceWaypoints(0, 2); all markers and routers are removed but I just want to remove the router lines not the markers.

**Comment by Fab-V** [comment]
Hi,
I also tried to remove the route from my map by following your suggestions, but it seems not to work with me. I am a newcomer to leaflet/js, so I am not really sure where exactly in my script I should apply routing.spliceWaypoints(0, 2) or the map.removeControl(route). I placed both options in several lines in my script, but nothing works. But I also do not have only two setWaypoints in my map as the example of bruha shows. I added the routing service of openrouteservice. Can anyone tell me, where in my script I need to place the lines!?

Here is my script:

`onload = function () {
		

		// Defining variable for Tipp Marker
		var tipp_marker;

		// Adding and minimizing Routing control to the map; Using openrouteservice API
		var routing_control = L.Routing.control({
			router: new L.Routing.openrouteservice('my API'),	
			show: false
		}).addTo(map);

		// Starting process with double-click on map 
		map.on("dblclick", function (event) {
			if (tipp_marker) {
				routing_control.setWaypoints([
					tipp_marker.getLatLng(),
					event.latlng
				]);
				routing_control.show();
				map.removeLayer(tipp_marker);
				tipp_marker = null; 
			} 
		else {
				routing_control.hide()
				tipp_marker = L.marker(event.latlng).addTo(map);
			} 
					
		});
		};`

**Comment by Ingfaces** [comment]
> Puede eliminar la ruta con este
> 
> ```
> var routing = L.Routing.control({
>     waypoints: [
>         L.latLng(57.74, 11.94),
>         L.latLng(57.6792, 11.949)
>     ]
> }).addTo(map);
> //...
> routing.spliceWaypoints(0, 2); // <-- removes your route
> ```
> donde 2 es el número de puntos de ruta

Como hago para que solo aparezca la ruta y no las instrucciones??

**Comment by brianbentancourt** [comment]
> > Puede eliminar la ruta con este
> > ```
> > var routing = L.Routing.control({
> >     waypoints: [
> >         L.latLng(57.74, 11.94),
> >         L.latLng(57.6792, 11.949)
> >     ]
> > }).addTo(map);
> > //...
> > routing.spliceWaypoints(0, 2); // <-- removes your route
> > ```
> > 
> > 
> > donde 2 es el número de puntos de ruta
> 
> Como hago para que solo aparezca la ruta y no las instrucciones??

`
routing ._container.style.display = "none"
`

**Comment by ddthanhdat** [comment]
> you can simply set the waypoints to an empty array (to be sure it will be empty )
> `routing.setWaypoints([])`

nice answer
