### ISSUE TITLE
Get itinerary item coordinates

### ISSUE THREAD

**Issue by frufin** [perliedman/leaflet-routing-machine#500]
In case of alternative routes, i intend to display informations on top of diverging segments.
I tried working with routes coordinates arrays differences, but in case of large arrays this requires too much CPU usage.
It would be easier to manage itineraries differences as it requires much less data calculations.
But i will need to get each itinerary step coordinate in order to add markers or popups at the right place on top of the routes.
Those coordinates are stored somewhere as click event on each itineary TR element displays a marker on the route.
Any way to get those informations ?

**Comment by frufin** [comment]
I found it...
each route.itineraries item has an 'index' property pointing to the route.coordinates array

**Comment by perliedman** [comment]
:+1:
