### ISSUE TITLE
Personnaliser input départ

### ISSUE THREAD

**Issue by arverne63** [perliedman/leaflet-routing-machine#501]
Good evening,
 I want to use Leaflet-Routing-Machine with mapbox router, on a hiking site so that visitors to the site can access the starting parking of the hike. So that I wish that I would enter (Parking) leave the input departure empty (image-1.jpg) which would inform the visitor in the site of his place of departure. (image-2.jpg) Is it possible to customize the markers? Thank you for a possible solution.
 Jean Marc

![image-1](https://user-images.githubusercontent.com/6421496/49391284-86155700-f72b-11e8-8bd0-522d646b55a4.jpg)
![image-2](https://user-images.githubusercontent.com/6421496/49391307-8f9ebf00-f72b-11e8-992f-a04a21638d2b.jpg)

**Comment by perliedman** [comment]
Hi, you can use the [`createMarker`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-plan) option to override how the waypoint markers are created.
