### ISSUE TITLE
Error: vue2_leaflet__WEBPACK_IMPORTED_MODULE_0__.L.Routing.graphHopper is not a function

### ISSUE THREAD

**Issue by NowshinAlam** [perliedman/leaflet-routing-machine#509]
Hi there,
I am using Vuejs as framework
leaflet: "^1.0.0"
Vue2-leaflet :"^1.2.3"
Leafler-routing-machine:"^3.2.12"
lrm-graphHopper:"^1.3.0"

But I am getting this error:

Uncaught TypeError: vue2_leaflet__WEBPACK_IMPORTED_MODULE_0__.L.Routing.graphHopper is not a constructor

And for routing :

initializeRouting() {
        L.Routing.control({
               waypoints: [
                      L.latLng(48.7801165, 9.1731849),
                      L.latLng(48.7764501, 9.2500882)
],
                router: new L.Routing.graphHopper('api_key'),
                geocoder: L.Control.Geocoder.nominatim({}),
                routeWhileDragging: true,
                collapsible: false,
        }).addTo(this.$refs.map.mapObject);
},

Can anyone suggest me any solution please?

Thanks in advance

**Comment by perliedman** [comment]
This is most likely related to how you import LRM and lrm-graphhopper in your Vue/Webpack environment, and not specifically related to Leaflet, so I am going to close this.

Please add more information if you believe this to actually be a problem in Leaflet Routing Machine.
