### ISSUE TITLE
Doc: now OSRM supports routes for cars and bicycle

### ISSUE THREAD

**Issue by JulioJu** [perliedman/leaflet-routing-machine#516]
Hi,

At http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/ you say 

> However, there are cases where OSRM’s defaults doesn’t cut it: you want to do bike routing, while OSRM’s open servers only route for cars at the time of writing. 

Maybe you could delete this sentence as actually OSRM support several profiles, like bicycle or foot ! See https://github.com/Project-OSRM/osrm-backend/tree/master/profiles

Thanks for your project

<hr />

Hi there,
before submitting a new issue, please consider the following:

* [X] This is actually an issue with Leaflet Routing Machine, not a question
* [X] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [X] You have looked through existing issues

Also, are you making a feature request, or are you in need of more advanced support?
Please consider **sponsoring development**, or paying for support. Not only will this most likely solve your issue quickly,
it's also an awesome way to keep open source projects alive and maintained, as well as giving something back for the
open source you're using. Contact me at per@liedman.net for more information.

**Comment by perliedman** [comment]
Hi, thanks for the notification. I changed the first paragraph to better explain why and when you need an alternative router.
