### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by donvie** [perliedman/leaflet-routing-machine#517]
Hi there,
before submitting a new issue, please consider the following:

* [x] This is actually an issue with Leaflet Routing Machine, not a question
* [x] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [x] You have looked through existing issues

Also, are you making a feature request, or are you in need of more advanced support?
Please consider **sponsoring development**, or paying for support. Not only will this most likely solve your issue quickly,
it's also an awesome way to keep open source projects alive and maintained, as well as giving something back for the
open source you're using. Contact me at per@liedman.net for more information.

**Comment by donvie** [comment]
<template>
  <q-page>
    <l-map style="z-index: 0" ref="map" class="fullscreen">
      <l-tile-layer :url="url" :attribution="attribution"></l-tile-layer>
    </l-map>
  </q-page>
</template>

<script>
import L from 'leaflet'
import 'leaflet-routing-machine'
require('leaflet/dist/leaflet.css')
require('leaflet-routing-machine/dist/leaflet-routing-machine.css')
import { LMap, LTileLayer } from 'vue2-leaflet'

import wiRequesterUrl from 'src/assets/wiRequesterMarker.png'
import wiSkillerUrl from 'src/assets/wiSkillerMarker.png'

let wiRequesterMarker = L.icon({
  iconUrl: wiRequesterUrl,
  iconSize: [48, 48]
})

let wiSkillerMarker = L.icon({
  iconUrl: wiSkillerUrl,
  iconSize: [48, 48]
})

export default {
  name: 'index',
  components: {
    LMap,
    LTileLayer
  },
  props: ['wiRequester'],
  data () {
    return {
      wiRequesterMarker,
      wiSkillerMarker,
      center: L.latLng(14.5790947, 121.0541893),
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }
  },
  mounted () {
    let options = { profile: 'mapbox/driving-traffic' }
    let self = this
    L.Routing.control({
      show: false,
      draggableWaypoints: false,
      router: L.Routing.mapbox('pk.eyJ1IjoiZG9udmllIiwiYSI6ImNqaTFxaDgxMTBoOTkzcW9heHV1bm54ZmsifQ.pNfXE9J6HLLFjfdg72E_Cg', options),
      waypoints: [
        L.latLng(14.5790947, 121.0541893),
        L.latLng(14.5790947, 121.041893)
      ],
      lineOptions: {
        styles: [
          { color: 'white', opacity: 0.9, weight: 9 },
          { color: 'purple', opacity: 1, weight: 5 }
        ]
      },
      createMarker: function (i, wp, nWps) {
        if (i === 0) {
          return L.marker(wp.latLng, { icon: self.wiSkillerMarker, draggable: false, bounceOnAdd: false })
        } else if (i === nWps - 1) {
          return L.marker(wp.latLng, { icon: self.wiRequesterMarker, draggable: false, bounceOnAdd: false })
        }
      }
    }).addTo(this.$refs.map.mapObject)
  }
}
</script>
<style>
.leaflet-bottom.leaflet-right {
  display: none;
}
.leaflet-left .leaflet-control {
  margin-left: 10px;
  margin-top: 60px;
}
.leaflet-right {
  margin-right: 10px !important;
  margin-top: 60px;
}
</style>

**Comment by wadclapp** [comment]
I had this issue in the past, and just had it again after a large project refactor.

Also using Vue and Vue2Leaflet, updating to latest (v2.0.2 from v1.2.3) Vue2Leaflet solved it for me. Possibly related to v1.x coming with its own version of leaflet.

**Comment by curtisy1** [comment]
Since this is a vue specific problem, I'll close this
