### ISSUE TITLE
Slope of the terrain

### ISSUE THREAD

**Issue by pantro** [perliedman/leaflet-routing-machine#519]
Best regards,
I would like to know if the calculation of the route between two points takes into account the slope of the terrain?
PD: I'm working with mapbox.

**Comment by perliedman** [comment]
Hi, it entirely depends on the backend, and is not controlled by Leaflet Routing Machine.

In Mapbox's case, I am not sure, actually. I would guess that it is not used for car routing, but maybe for bike routing. But again, this is outside Leaflet Routing Machine's scope, and something you would need to check with Mapbox or whatever provider you choose to use.
