### ISSUE TITLE
Mapbox - access different vehicle types

### ISSUE THREAD

**Issue by TeamKinetic** [perliedman/leaflet-routing-machine#520]
Hi there,

Is there the option of defining the vehicle type when using Mapbox as the router..?

The API call doesn't use a parameter but a folder 

https://api.mapbox.com/directions/v5/mapbox/cycling/-84.518641,39.134270;-84.512023,39.102779?geometries=geojson

I can see examples of using graphopper using urlParameters but this doesnt seem to have any effect with MapBox.

Thanks, great library.

**Comment by kumbraGrr** [comment]
Hi TeamKinetic,

There should not be a problem to access different vehicle types. Just add a profile you want(eg. cycling) after your API key in options of your Routing control. Something like this:  

let options = { profile: 'mapbox/cycling' }
L.Routing.control({
  [...],
  router: L.Routing.mapbox(MapBoxToken, options),
}); 

Hope it helps :)

**Comment by TeamKinetic** [comment]
Perfect, thanks
