### ISSUE TITLE
ERROR in ./node_modules/leaflet-routing-machine

### ISSUE THREAD

**Issue by lasya07** [perliedman/leaflet-routing-machine#523]
Hey, I am new to react maps and my project involves routing . So I tried doing it by following your other articles . Any help is appreciated in solving this error.

Below is my File:

import { MapLayer } from 'react-leaflet';
import L from 'leaflet';
import { withLeaflet } from 'react-leaflet';
import 'leaflet-routing-machine';
import 'leaflet-routing-machine/dist/leaflet-routing-machine.css';

class RoutingMachine extends MapLayer {
  createLeafletElement() {
    const { color, map, road } = this.props;

    console.log("Route computation: ", road)

    let leafletElement = L.Routing.control({
      waypoints: road,
      //router: L.Routing.mapbox('TOKEN'),
      lineOptions: {
        styles: [{ 
          color, 
          opacity: .8,
          weight: 6 
        }]
      },
      addWaypoints: true,
      draggableWaypoints: true,
      routeWhileDragging: false,
      fitSelectedRoutes: true,
      showAlternatives: false,
      altLineOptions: { styles: [{opacity: 1}] },
      createMarker: () => { return null; }
    })
    .addTo(map.current.leafletElement);

    leafletElement.hide(); // hide road describtion
    console.log(leafletElement)
    return leafletElement.getPlan();
  }
}

export default withLeaflet(RoutingMachine);

ERROR in ./node_modules/leaflet-routing-machine/dist/leaflet-routing-machine.css (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--5-3!./node_modules/leaflet-routing-machine/dist/leaflet-routing-machine.css)
Module not found: Error: Can't resolve 'leaflet.routing.icons.png' in '/Users/Lasya/Documents/restaurantFinder/node_modules/leaflet-routing-machine/dist'
 @ ./node_modules/leaflet-routing-machine/dist/leaflet-routing-machine.css (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--5-3!./node_modules/leaflet-routing-machine/dist/leaflet-routing-machine.css) 7:1357-1393
 @ ./node_modules/leaflet-routing-machine/dist/leaflet-routing-machine.css
 @ ./src/components/App/maps/RoutingMachine.js
 @ ./src/components/App/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8086 (webpack)/hot/dev-server.js ./src/index.js

**Comment by perliedman** [comment]
Hi,

this is not a LRM issue but an issue with your project setup.

From the looks of it, webpack/postcss is looking for the images in the wrong directory, for some reason (see the message: `Module not found: Error: Can't resolve 'leaflet.routing.icons.png'`).

This is outside the scope of this project, so I am unfortunately not able to help you further.
