### ISSUE TITLE
Start Waypiont From Realtime GPS Coordinates

### ISSUE THREAD

**Issue by wolfbgn** [perliedman/leaflet-routing-machine#524]
Hi. First thanks for your work. I have been using  your Realtime for some time. I get data from MySQL and PHP to produce geojson file. Evry thing works fine. I track my phone in real time.
I have searched and read but I could not figure out how to feed those coordinates ( from my phone) in leaflet-routing-machine as starting waypoint. Could you point the right direction?

**Comment by perliedman** [comment]
Hi! Great to hear that you're finding the plugin useful!

For something simple, this should be fairly straight forward: Leaflet has built in support for geolocation (the map has a `locate` method) that will give you a `LatLng` for the user's current location. You can simply set this as the starting waypoint for your route. You can then recalculate the route when the location changes (but be advised that doing this frequently will cost a lot of bandwidth as well as resources for the routing backend).

Having said that, for a more navigator-like experience, you would have to do a lot more complicated things like snapping to roads, etc., but this is at least a start. Hope this helps!
