### ISSUE TITLE
setWaypoints doesn't fill with array 

### ISSUE THREAD

**Issue by bahrammzm** [perliedman/leaflet-routing-machine#527]
Hi, i try to fill setWaypoints with array but it returns null result 

```
var routing = L.Routing.control({});
function load_history(){
    latLongList = new Array();
    var historyUrl = 'history.php';

    $.ajax(historyUrl, {
        type: 'GET',
        dataType: 'json',
        success: function (data) {
            data.forEach(history => {
                var latlong = new L.latLng(history['Lat'], history['Long']);
                latLongList.push(latlong);
            })
        }
    })        
    routing.setWaypoints(latLongList);

}
    console.log(routing.getWaypoints());
```
![issue](https://user-images.githubusercontent.com/15061349/57189044-81dda780-6f1e-11e9-8fef-3854492167c8.PNG)

**Comment by uv337** [comment]
I don't well about  your question, sorry.
but  I can say that  consider  check below 3 step by step , and slowly.
1.  var historyUrl 
2. ﻿case about failed situation
3. latLongList
by using console.log()  or alert()
 
I hope this is helpful.
===============================================
var routing = L.Routing.control({}); function load_history(){ latLongList = new Array(); var historyUrl = 'history.php'; $.ajax(historyUrl, { type: 'GET', dataType: 'json', success: function (data) { data.forEach(history => { var latlong = new L.LatLng(history['Lat'], history['Long']); latLongList.push(latlong); }) }﻿case about failed situation}) routing.setWaypoints(latLongList); console.log(routing.getWaypoints()); }========================================================
 
 
 
 
 
-----Original Message-----

**Comment by bahrammzm** [comment]
> I don't well about your question, sorry. but I can say that consider check below 3 step by step , and slowly. 1. var historyUrl 2. ﻿case about failed situation 3. latLongList by using console.log() or alert() I hope this is helpful. =============================================== var routing = L.Routing.control({}); function load_history(){ latLongList = new Array(); var historyUrl = 'history.php'; $.ajax(historyUrl, { type: 'GET', dataType: 'json', success: function (data) { data.forEach(history => { var latlong = new L.LatLng(history['Lat'], history['Long']); latLongList.push(latlong); }) }﻿case about failed situation}) routing.setWaypoints(latLongList); console.log(routing.getWaypoints()); }========================================================
> […](#)
> -----Original Message----- From: "bahrammzm"<notifications@github.com> To: "perliedman/leaflet-routing-machine"<leaflet-routing-machine@noreply.github.com>; Cc: "Subscribed"<subscribed@noreply.github.com>; Sent: 2019-05-05 (일) 14:44:10 (GMT+09:00) Subject: [perliedman/leaflet-routing-machine] setWaypoints doesn't fill with array (#527) Hi, i try to fill setWaypoints with array but it returns null result var routing = L.Routing.control({}); function load_history(){ latLongList = new Array(); var historyUrl = 'history.php'; $.ajax(historyUrl, { type: 'GET', dataType: 'json', success: function (data) { data.forEach(history => { var latlong = new L.LatLng(history['Lat'], history['Long']); latLongList.push(latlong); }) } }) routing.setWaypoints(latLongList); console.log(routing.getWaypoints()); } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I've already checked your suggestion cases , 
`console.log(latLongList, routing.getWaypoints());`
![issue2](https://user-images.githubusercontent.com/15061349/57207364-68059880-6fe2-11e9-9772-549a3ac2af78.PNG)

Any suggestion?

**Comment by perliedman** [comment]
Hi,

the ajax call you make is asynchronous. The `success` callback will not run until after your results have loaded from the server, while your call to `setWaypoints` is executed immediately, before the callback has run.

You should put the call to `setWaypoints` (and the debug output with `console.log`) inside the `success` callback.
