### ISSUE TITLE
Multiple sources and destinations

### ISSUE THREAD

**Issue by ahmedmdl** [perliedman/leaflet-routing-machine#529]
Hi,
So i have to route a multitude of vehicles,
each has a start point, waypoints and an end point,
I can do this through js easily on google maps,
Is that possible here.
thx a lot

**Comment by perliedman** [comment]
Hi, I guess it's way too late to try to respond to this anyway, but I think you need to make it more clear what the question actually is.

From my guess of what you mean, the answer is probably somewhere between yes and no.
