### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by booleenter** [perliedman/leaflet-routing-machine#540]
Hi! Congratulations on the development of this wonderful plugin. How do I put the itinerary box below the Div map

**Comment by ElHassaniWalid** [comment]
Hi,
there's an eventListener  "**routesfound**", once the OSM Server return the itinerary, you can get the result and do what you want to do.

Exemple : 
L.Routing.control({
...
})
.on('routesfound', (e)=>{
   // e is the object return by the server
    console.log(e);
});

Hope that helps you :)
