### ISSUE TITLE
Hi there! your script is great! I was wondering how to add a button to have my own location

### ISSUE THREAD

**Issue by devcodep** [perliedman/leaflet-routing-machine#541]
Hi there! your script is great! I was wondering how to add a button to have my own location in the example tutorials / interaction / in the title "Adding waypoints by clicking the map". How can I add the locate button?

**Comment by perliedman** [comment]
Hi!

Sorry, this is a bit outside the scope of the plugin. There are plenty of examples of how to get your location (geolocation) in Leaflet, you should find them if you use Google. It should be straight forward to adapt to Leaflet Routing Machine given the tutorial you mentioned above.
