### ISSUE TITLE
How to connect an external router

### ISSUE THREAD

**Issue by cristianogle** [perliedman/leaflet-routing-machine#542]
Hi,

i'm trying to attach my own routing software (in this case a java servlet, located on localhost for the moment) to Leaflet Routing Machine.
According to [this](http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/#using-other-routers):

> The basic requirement is that the router class must implement the IRouter interface, so that Leaflet Routing Machine knows how to communicate with your router. The interface is pretty simple and contains a single method:
> `router.route(waypoints, callback, context, options)`
> waypoints is the array of waypoints the route should pass, and contains at least two elements when route is called; each element will have at least a latLng property, containing a L.LatLng that describes the waypoints location, optionally it will also have a name as string and options.
> ...
> By implementing these interfaces, you will get all the other functionality of Leaflet Routing Machine for free.

So i'd like to know more on this topic, since it is poor documented, and it would be perfect see an example of how this works. 

For the moment, i'm only able to use the OSRM's demo server:

```
var lrmControl = L.Routing.control({
    waypoints: [],
    routeWhileDragging: true,
    geocoder: L.Control.Geocoder.nominatim(),
    reverseWaypoints: true,
}).addTo(map);
```

One possible option could be:

`lrmControl.route = function(waypoints, callback, context, options) { ... }
`

But this not works.

Thank you.

**Comment by perliedman** [comment]
You need to implement a class that has the `route` method. Look at the `OSRMv1` class, or one of the many routing plugins for GraphHopper ect, for examples of what it can look like.

**Comment by Patabugen** [comment]
I'm also struggling with this, the included routers do a lot more than just return the route, and the documentation doesn't really describe how or what to return. For example in the OSRM file there's no reference to IRoute - which is what the API doc says needs to be returned.

I'm actually trying to make a router which simply draws a straight line between each waypoint - I managed to implement it about a year ago but am sturggling to do it again (my old code doesn't seem to be working, and the script isn't in a state where I can run it to check).

Any advice would be appreciated, I'd happily push a PR to the docs after figuring it out.

**Comment by perliedman** [comment]
`IRoute` is an interface, there is no real class. You have to return an object with the properties described by the interface. The docs for it are here: https://www.liedman.net/leaflet-routing-machine/api/#iroute

**Comment by cristianogle** [comment]
I''ve found a solution that consists in brutally forcing the call to my own
router, editing the parameter serviceUrl of lrm-graphhopper (
https://github.com/perliedman/lrm-graphhopper).
However, is was not easy to create my router, in particular in building the
response according to what GH expects to receive from router.

Il giorno ven 31 gen 2020 alle ore 14:13 Per Liedman <
notifications@github.com> ha scritto:
