### ISSUE TITLE
Documentation. IRoute descreption in Leaflet Routing Machine API 

### ISSUE THREAD

**Issue by EmelyanovKonstantin** [perliedman/leaflet-routing-machine#545]
In Leaflet Routing Machine documentation(http://www.liedman.net/leaflet-routing-machine/api/)<br>
IRoute have property waypoints whith type L.LatLng[] .  `IRoute.waypoints `return L.Routing.Waypoint[]

**Comment by curtisy1** [comment]
Closing this in favor of #601 
If you feel like it should be reopened, please get back to me
