### ISSUE TITLE
how i can set just lat.lng in watch

### ISSUE THREAD

**Issue by 95moja71** [perliedman/leaflet-routing-machine#548]
Hi there,
before submitting a new issue, please consider the following:

* [ ] This is actually an issue with Leaflet Routing Machine, not a question
* [x] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [x] You have looked through existing issues

  
```

    var latGoal = $('#lat').val();
    var lngGoal = $('#lng').val();

   var hh = map.locate({
        watch: true,
        setView: true,
        maxZoom: 16
    }).once('locationfound', (e) => {

       L.Routing.control({
           waypoints: [
               L.latLng(e.latitude,e.longitude),

               L.latLng(latGoal, lngGoal)
           ],
           routeWhileDragging: false,
       }).addTo(map)

    });
```

**Comment by perliedman** [comment]
Not sure what the question is. Also, it looks like it is not really an issue with Leaflet Routing Machine, but rather a question on how to use it or Leaflet. Although I certainly want to help out, please realize that my time for solving other peoples' programming problems is very close to zero.
