### ISSUE TITLE
Interactive example doesn't work

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#55]
Hi, I don't get it working neither Chrome nor Firefox. I copied the code and tryed it in my server and I haven't had luck either.

First question:
I want to use a line to get the route between two point without using the default L.Routing.Control, I want to create amuch more minimalistic display at this stage and I thought that it could be the way. Am I right?.
For sure I'l need the summarize data to get distance and time information.

Second: if I choose the L.Routing Control, I need to change the default language to mine. I guess with a forked version and by modifying the _getInstructionTemplate  function  could work.

I highly appreciate any hints, I am a totally beginner with mapping and javascript too.
Thanks :)

**Comment by DeepakkumarArumugam** [comment]
Hi @perliedman ,
I am trying to use your OSRM. It is awesome. Examples are working fine. however when I implement with backbone i am facing below issue,
leaflet-routing-machine.js:424 Routing error: Object {status: -3, message: "TypeError: Cannot read property 'Localization' of undefined"}
It would be great if you help me out.

**Comment by perliedman** [comment]
@DeepakkumarArumugam sorry, impossible to say without a more detailed example of the problem, preferably something I can run and test (JSFiddle or [Leaflet Playground](http://playground-leaflet.rhcloud.com) for example).

Also, please understand that the amount of time I can put into debugging other peoples code is very limited, so please make sure this is actually an issue with Leaflet Routing Machine and not your own code.
