### ISSUE TITLE
Combine manual routing

### ISSUE THREAD

**Issue by javierpose** [perliedman/leaflet-routing-machine#553]
Hi
leaflet-routing-machine creates automatic routes. Is it possible to create part of the route manually? For example, on paths that do not appear in openstreetmaps or part of a route that goes by sea

**Comment by perliedman** [comment]
Hi,
you can, but you have to write your own `IRouter` class that combines the automatic parts with the manual parts. There is nothing built in to LRM to do this today.

I suggest you look at the existing routers for examples how to write an `IRouter`; `L.Routing.OSRMv1` is part of core LRM, and there are quite a few plugins that build their own.
