### ISSUE TITLE
Mapbox walking profile

### ISSUE THREAD

**Issue by javierpose** [perliedman/leaflet-routing-machine#555]
Hi
I want to use walking profile with mapbox. Am I doing something wrong?

```
router: L.Routing.mapbox("MY_API_KEY", {
  urlParameters: {
    profile: "mapbox/walking",
    serviceUrl: "https://api.mapbox.com/directions/v5"

    //elevation: true
  }
}),
```

![Screenshot_1](https://user-images.githubusercontent.com/210588/66552474-b7c82d00-eb49-11e9-8348-12e6751c1804.png)

Thanks in advance

**Comment by perliedman** [comment]
Hi, `profile` is not a URL parameter, you should put at the top-level of the options, not in `urlParameters`.

**Comment by javierpose** [comment]
Ok, Thanks
