### ISSUE TITLE
Hide the map option for viewing navigation options

### ISSUE THREAD

**Issue by BrsJsk** [perliedman/leaflet-routing-machine#556]
Hello,

Is there a way to hide the map option for viewing navigating routes? For example, if we just want to show the routes on the map.

I'm thinking on this box. Any way to hide it through the config file ?
![question](https://user-images.githubusercontent.com/26108825/66639324-efe97180-ec16-11e9-8964-7a673068fbd7.png)

**Comment by BrsJsk** [comment]
Actually..it can be hidden by adding following code to config
`show: false`

**Comment by santhoshMahesh** [comment]
Hey, Can you please send me the piece of code to make it disappear.

**Comment by curtisy1** [comment]
Please don't comment on closed issues and open a new one instead if necessary.
To answer your question, the itinerary has an option called [show](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/itinerary.js#L26)
So basically, you pass it an option during initialization
```
L.Routing.Control({show: false});
```
and it should disappear automatically
