### ISSUE TITLE
Drawing routes

### ISSUE THREAD

**Issue by AlessandroMFerreira** [perliedman/leaflet-routing-machine#568]
Hi there,
before submitting a new issue, please consider the following:

* [ ] This is actually an issue with Leaflet Routing Machine, not a question
* [ ] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [ ] You have looked through existing issues

**Comment by AlessandroMFerreira** [comment]
Hello,

I started using the Leaflet routing machine with little time and I ran into the following problem:
You need to track a route on the map with latitude and longitude data captured in a database which in turn are recorded on a location device that is installed on some cars. My problem here is to use polylines from the brochure as lines that are drawn on the map that do not follow the highway traffic, and often when there are lines like finished lines exiting the highway.

![image](https://user-images.githubusercontent.com/29022905/73562760-919d0480-443a-11ea-9ea8-23843d556e60.png)

When using the Leaflet Routing machine most of the route is perfectly designed, however in some cases where there are curves or intersections in the route it seems to calculate the best route between the two closest points and ends up generating meaningless routes.

I just want to show on the map the route taken by the car and not calculate the best route. I don't know if it's my lack of experience or if I don't know what to look for to solve this problem but any help would be welcome.

The image below using the Leaflet routing machine. The red arrow should be the path that should be drawn on the map, but it makes this outline marked in black

![image](https://user-images.githubusercontent.com/29022905/73562838-ad080f80-443a-11ea-9d58-323ffc9835e3.png)

Note: I created my own OSRM server, the latitude and longitude points easily pass the 1700 points.

Here is the code I used

`function(){
        jsonRota = self.montaJsonRota();
        $.ajax({
            type: "POST",
            url: location.origin + '/sis/' + jsGet('sis') + "/framework/Localizacao.php",
            dataType: 'JSON',
            cache: false,
            data: {jsonRota: jsonRota, "sis": jsGet("sis")},
            success: function(response){
                var arrayLngLat  = [];

                for(var i = 0; i < response.rota.length -1; i++){
                    arrayLngLat.push(L.latLng(response.rota[i].lat.replace(",","."), response.rota[i].lng.replace(",",".")));
                }
                
                var route = new L.Routing.OSRMv1({
                    serviceUrl: 'http://localhost:5000/route/v1',
                    useHints: false,
                    timeout: 60000                
                });
                //var polyline = L.polyline(arrayLngLat).addTo(self.mapa);
                var control = L.Routing.control({
                    router: route,
                    lineOptions: {
                        styles: [{color: '#0066ff', opacity: 0.7, weight: 5}]
                    },
                    waypoints: arrayLngLat,
                    routeWhileDragging: false,
                    show: false,
                    waypointMode: 'snap',
                    autoRoute: true,
                    showAlternatives: false
                });
                control.addTo(self.mapa);
                control.hide();
            }
        });
    }`

**Comment by perliedman** [comment]
If you are trying to match up an existing GPS route against the road network, you are better off using OSRM's [match service](http://project-osrm.org/docs/v5.5.1/api/#match-service), which is specifically designed for with this use case in mind. I believe it is less likely to return routes like the one in your example.

Having said that, this is outside the scope of Leaflet Routing Machine, so closing.

**Comment by AlessandroMFerreira** [comment]
Ok,

Thankyou very much!!
