### ISSUE TITLE
Remove itinerary instructions on the second click

### ISSUE THREAD

**Issue by Mehditeranee** [perliedman/leaflet-routing-machine#572]
I'm currently trying to put a route map on my website. I want to display the road and itinerary instructions at the click of a button.

But when I click a second time on the button, itinerary instructions are displayed a second time as you can see below :

<img width="387" alt="Capture d’écran 2020-03-15 à 15 06 00" src="https://user-images.githubusercontent.com/38721898/76703012-85a99100-66ce-11ea-9ba6-94250cfdabf8.png">

How can I prevent this behavior?

**Comment by perliedman** [comment]
Most likely you are creating a second instance of the control an adding it to the map. Hard to tell without seeing an example, though.
