### ISSUE TITLE
Control outside map

### ISSUE THREAD

**Issue by asiermusa** [perliedman/leaflet-routing-machine#578]
Hi!

Is there any way to customize search inputs and put them outside map component, as a html wrapper?

Thanks

**Comment by perliedman** [comment]
Not built in and supported by the API, but I think someone told me they had some luck overriding `Itinerary`'s `onAdd` method to set the `_container` property to some element outside the map.

It's not something I have tried myself, but it looks like it could work!

**Comment by asiermusa** [comment]
Thanks!
