### ISSUE TITLE
calculating the route caused an error. technical description follows: http request failed: error

### ISSUE THREAD

**Issue by anirmukh** [perliedman/leaflet-routing-machine#579]
![Routing Error](https://user-images.githubusercontent.com/19611802/79915020-d639aa00-8443-11ea-9a16-0af8588215e1.png)

Hello,

I am trying to connect two points on the map using the routing control waypoints but it is not showing rather giving an error "Calculating the route caused an error. technical description follows: http request failed: error". Attached is the screen shot.

Is there any problem with the version which I am using.

Following is the source code.
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Leaflet Path</title>

    
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />

</head>
<body>
    <div id = "map" style = "width: 900px; height: 580px"></div>
	<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
	<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <div id="distancetravelled"></div>

    <script>		
		var mapOptions = {
			center: [22.510920, 88.382350],
			zoom: 14
		}
		 var map = new L.map('map', mapOptions);
		
        L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			attribution: '© OpenStreetMap contributors'
		}).addTo(map);

		try {
			var control = L.Routing.control({
				waypoints: [
					L.latLng(22.510920, 88.382350),
					L.latLng(22.4807, 88.3942)
				],    
				routeWhileDragging: true,
				show: true
			}).addTo(map);
		}
		catch(err) {
			alert(err);
		}
		L.Routing.errorControl(control).addTo(map);
        console.log(control);

    </script>
</body>
</html>

**Comment by perliedman** [comment]
Hi,
most likely because OSRM's demo server is no longer operational, or at least not with HTTPS (see #574). Check your devtools network tab to see the actual error with the request.
