### ISSUE TITLE
leaflet-routing-machine.js:88 Mixed Content: The page at '' was loaded over HTTPS

### ISSUE THREAD

**Issue by sunstarwar** [perliedman/leaflet-routing-machine#586]
Hi friends,

i am working in a leaflet routing map, when i was working in a local machine it doesn't say error but when i move the code to server throws an error like
"leaflet-routing-machine.js:88 Mixed Content: The page at 'https://moesctest.artha.com/Employee/Students_OnRoute_OSM.aspx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://router.project-osrm.org/route/v1/driving/-74.1170343,40.4456482;-74.1195227,40.4440501;-74.1189951,40.4431026;-74.1234684,40.4424305;-74.126634,40.4413222;-74.1290197,40.4491485;-74.1305336,40.4500597;-74.1352131,40.4517255;-74.1372316,40.4491365;-74.1374725,40.4490829;-74.129298,40.4371859?overview=false&alternatives=true&steps=true&hints=;;;;;;;;;;'. This request has been blocked; the content must be served over HTTPS."

I dont know much knowledge in leaflet routing machine, so i need help to make this work in server any help would be appreciated..

thanks in advance...

**Comment by ThomasG77** [comment]
As mentioned in the [README.md](https://github.com/perliedman/leaflet-routing-machine/blob/master/README.md) from this plugin project, the https certificate from the https://router.project-osrm.org URL expired.
You can't really avoid to use your own server for OSRM (see below screenshot from the mentioned `README.md`). Imagining your server could be hosted without a certificate, (so without https only http), you would be able to call OSRM demo url without http but you would be stuck by another problem: you absolutely need https for using geolocation e.g https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

![Sélection_193](https://user-images.githubusercontent.com/642120/81757180-47f29a00-94be-11ea-84c5-82c40383c196.png)

**Comment by rebos** [comment]
As of today, the [OSRM's demo server](https://router.project-osrm.org/) seems to be back again and is presenting a valid certificate for HTTPS verified by Let's Encrypt:

![grafik](https://user-images.githubusercontent.com/490798/114280754-0e624000-9a3b-11eb-95f1-97b3f1bcc20e.png)



[Probing the routing service via HTTP GET](https://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false) with an URL copied[ from the API documentation](http://project-osrm.org/docs/v5.23.0/api/#route-service) seems to produce a valid response.

But nevertheless currently the [demo page for leaflet-routing-machine](https://www.liedman.net/leaflet-routing-machine/) still shows an error message:

![grafik](https://user-images.githubusercontent.com/490798/114280796-55503580-9a3b-11eb-856a-f49753793969.png)

**Comment by mguignes** [comment]
Hello,
It is said that we should be using our own server.
But if we are not able to use a valid certificate, how should we proceed ???
Because using the demo server, we will always be limited to a certain number of requests per second...

**Comment by curtisy1** [comment]
> But if we are not able to use a valid certificate, how should we proceed ???

You have a few options.
1. If you want to self-host an OSM server, you can get a free certificate via Let's Encrypt
2. Use a different routing provider such as Mapbox or a different OSM router
3. Use Http instead of Https (although I would generally advise against this)

> Because using the demo server, we will always be limited to a certain number of requests per second...

The demo server is generally feasible if you want to prototype some application. It's not suitable for production use since it would probably drastically increase server load (and cost) for the OpenStreetMap folks and as such throttle all the other people wanting to use the demo server.

That being said, the demo server is working fine now as can be seen in the [docs](https://www.liedman.net/leaflet-routing-machine/). They use https://routing.openstreetmap.de/routed-car/route/v1 for routing now by default

**Comment by curtisy1** [comment]
Closing as this seems to be resolved. If the issue persists, feel free to open another one or ask me to reopen this one
