### ISSUE TITLE
Exclude paths in specified area.

### ISSUE THREAD

**Issue by AdamSawoscianik** [perliedman/leaflet-routing-machine#595]
Hello,

Im currently working on some project using your awesome library( Thanks btw :) ), and im wondering if is there a way to exclude paths beeing for example in geojson area and make it find some path around?

Thank you in advance for response.

**Comment by perliedman** [comment]
Hi,
the actual routing calculation is performed by the routing backend (which is OSRM by default), so you would need to have support for this on the backend. To my knowledge, OSRM does not support something like this, at least not dynamically, maybe other routers do (see tutorials on how to change routing backend).

So, in short the answer is currently no.
