### ISSUE TITLE
Autocomplete without Enter

### ISSUE THREAD

**Issue by PeterPan73** [perliedman/leaflet-routing-machine#597]
Hello,
I try to make search results appear automatically without having to press Enter.
For now its working when I press Enter, but will be great without press Enter.
I use custom made
`geocoder:` new L.Control.Geocoder.Nominatim({serviceUrl: `"ajax/getAddress.php"}),`

Can you give me an example(idea) of how I can do it after entering 2(or more) characters in the field then to make the request to display the addresses without press Enter?
Thanks.

**Comment by perliedman** [comment]
Hi, this is supported for geocoders that allow suggestions/autocomplete. Unfortunately, Nominatim is not such a geocoder: its usage policy explicitly says it's not allowed to use the service for suggestions (or at least it did last time I checked, which was a while ago, to be honest).

Supporting suggestions is just a matter of the geocoder having a `suggest`method.
