### ISSUE TITLE
Display realtime traffic congestion on generated route just like google maps.

### ISSUE THREAD

**Issue by imaginevinay** [perliedman/leaflet-routing-machine#599]
Hi there,

Leaflet routing machine is awesome but there is a use case wherein I  need to display congestion on the generated route (low/moderate/high) only  just like google maps.  

I am using mapbox router along with LRM. It would be very helpful if anyone can help me if out or if this is possible with LRM or any other library which can help me for this use case.

![image](https://user-images.githubusercontent.com/12834674/88806559-37ed7b00-d1ce-11ea-8f10-04947299043c.png)

What we want is to show colours on route depending on congestion (traffic) : 

![image](https://user-images.githubusercontent.com/12834674/88806611-463b9700-d1ce-11ea-86bc-e2d932bd1d2f.png)

Note : I do not want to use google maps api due to high cost so please suggest a way out for this[](url)

**Comment by perliedman** [comment]
Hi, sorry but this is outside the scope of LRM. You would need to find a data source for congestion data and a way to query that information for the LRM route, and finally customize the line to display on the map.
