### ISSUE TITLE
documentation on IRoute interface incorrect

### ISSUE THREAD

**Issue by noerw** [perliedman/leaflet-routing-machine#601]
[The docs say](https://www.liedman.net/leaflet-routing-machine/api/#iroute) that a custom route should have the field `waypoints`.
This is not correct, my router implementation only worked once i created routes with the following fields instead:
```
inputWaypoints,   // waypoints passed to route()
actualWaypoints,  // corresponding waypoints returned by the router
waypointIndices,  // indices of the waypoints in `coordinates[]`
```

**Comment by noerw** [comment]
related: #545

**Comment by curtisy1** [comment]
Nice catch! The properties were indeed undocumented before. I revamped the docs a bit for the upcoming v4 so this is now corrected.
One thing to look out for however: The actualWaypoints will only be called waypoints in the next version
