### ISSUE TITLE
show estimated time and length on routes

### ISSUE THREAD

**Issue by RZsam** [perliedman/leaflet-routing-machine#605]
hi there.
I've searched through docs and issues but did not find anything. can distance and time between two waypoints be shown on route like google maps?

![image](https://user-images.githubusercontent.com/26380519/92322254-6cfab200-f045-11ea-95ba-fbe62f4095bb.png)

**Comment by perliedman** [comment]
Nothing built in to do this, but you can do it by using for example the [`routeLine` option](https://www.liedman.net/leaflet-routing-machine/api/#l-routing-control).
