### ISSUE TITLE
Overlapped lines/Routes Leaflet

### ISSUE THREAD

**Issue by Sofiane23i** [perliedman/leaflet-routing-machine#614]
Hello, 

I'm working on map project where I hope to display all Lines for a particular City. Using the library of Leaflet with MapBox I suceeded to display them in different colors with corresponding annotation markers except that some lines of this city have some portion in commune where the last route will overlap the color of other lines.

Is there an option to display the overlapped portion as rainbow lines ?

Thanks

**Comment by perliedman** [comment]
Sorry, no. Layout of "rainbow lines" is highly complex and outside the scope of this plugin.
