### ISSUE TITLE
IIs there any way to get place name from OSRM? if yes kindly explain with code if possible

### ISSUE THREAD

**Issue by nvngkr** [perliedman/leaflet-routing-machine#615]
Hi there,
before submitting a new issue, please consider the following:

* [ ] This is actually an issue with Leaflet Routing Machine, not a question
* [ ] You have read [the Leaflet Routing Machine documentation](http://www.liedman.net/leaflet-routing-machine/api/) and [tutorials](http://www.liedman.net/leaflet-routing-machine/tutorials/)
* [ ] You have looked through existing issues

**Comment by perliedman** [comment]
Not to my knowledge. OSRM is a router, not a geocoder. Please check the [tutorial on addresses and geocoders](https://www.liedman.net/leaflet-routing-machine/tutorials/geocoders/) for more info.
