### ISSUE TITLE
Generate leaflet-routing-machine.js

### ISSUE THREAD

**Issue by bilbomaticaeugis** [perliedman/leaflet-routing-machine#616]
Hi there,

I modified the file src/OSRM-v1.js  and I want to regenerate the leaflet-routing-machine.js file. I tried npm and bower with no success. Could you please explain how to do this?

Thanks in advance.
Oskar.

**Comment by perliedman** [comment]
Hi!

Running `npm install` will build `leaflet-routing-machine.js` and other required files and put htem in the `dist` directory.
