### ISSUE TITLE
Walking directions

### ISSUE THREAD

**Issue by dpliscoff** [perliedman/leaflet-routing-machine#62]
Hello, I'm using the routing machine on a Drupal installation, and could not figure out how to specify to OSM the route as walk/foot instead of driving/car. Is that supported? If it is, how must be specified?

**Comment by Qberon** [comment]
Open Source Routing Machine is excellent service but 
http://wiki.openstreetmap.org/wiki/OpenRouteService#OpenRouteService_API
offer walking and biking routes which very important for us

Is it possible to change from one server to another? Even better switch betwen servers.

**Comment by perliedman** [comment]
@Qberon check out this tutortial: http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/

**Comment by kaio328** [comment]
Is there any public server for walk/foot instead of driving/car by now? Kinda afraid of setting up my own server...

**Comment by perliedman** [comment]
@kaio328 [Mapbox's Directions API](https://www.mapbox.com/api-documentation/#directions) has support for walking as well as some other profiles.

**Comment by kaio328** [comment]
Thanks for your reply! I already figured out that Valhalla also got a support for walking. 

Since im using leaflet with a custom made map im struggling with the OSM based routing. Is there a way to have influence on the OSM street data to improve accuracy on routing?

**Comment by perliedman** [comment]
@kaio328 OpenStreetMap is free for anyone to edit, improvements are of course very welcome. There are an enormous amount of material on the internet on how to contribute to OSM, so go ahead!

**Comment by kaio328** [comment]
Im looking forward to do! 

Before opening a new issue: is there a way do deactive turn-by-turn directions? Had a look at your documentation and didnt find what i was looking for. Removing `formatter: new L.Routing.mapzenFormatter(),` just turns the single direction to _undefined_!

**Comment by perliedman** [comment]
@kaio328 this is a very common issue: https://github.com/perliedman/leaflet-routing-machine/issues?utf8=%E2%9C%93&q=is%3Aissue%20hide

Short summary: use a CSS rule if you want to completely hide the itinerary.

**Comment by kaio328** [comment]
Awesome!

**Comment by burzum** [comment]
Any news on OSM or Open Topo map support for walking direction?

**Comment by billelkhanfri** [comment]
> Any news on OSM or Open Topo map support for walking direction?

hello, did you find a solution for walking path instead of car default route in leaflet?

**Comment by curtisy1** [comment]
@billelkhanfri Please don't comment on old, closed issues. Chances are high that no one will read them or they get lost in a search filter.

If this is still an issue for you, you can always open a new issue or ask on StackOverflow and people will be happy to help you out.

To answer your question, yes it's possible but as Per said in [his answer](https://github.com/perliedman/leaflet-routing-machine/issues/62#issuecomment-67067024), you will need to change the URL of your LRM instance to include the walking profile. The current API URL for OSRM's demo server is https://routing.openstreetmap.de/routed-foot/route/v1/driving/ if you want to use the walking/foot profile (simply change the serviceUrl option of your instance)

If you plan on using this in production, I still recommend using your own OSRM or Valhalla instance.
