### ISSUE TITLE
Change route line color

### ISSUE THREAD

**Issue by paulobraga** [perliedman/leaflet-routing-machine#63]
Hello,

I would like to change the route line color to blue, the default is red, how can I do?

my code looks like:

<pre lang="javascript"><code>
 var router = new L.Routing.OSRM({serviceUrl: 'http://localhost:5000/viaroute'});
            var waypoints = [];
           // I fill the waypoints array dinamically
            L.Routing.control({
                router: router,
                waypoints: waypoints,
                //geocoder: L.Control.Geocoder.nominatim(),
                routeWhileDragging: true
            }).addTo(map);
</code></pre>

**Comment by DiegoJohan** [comment]
Hi, the url http://www.liedman.net/leaflet-routing-machine/styling.html not work, but I found this page
http://trustdarkness.com/wordpress/leaflet-routing-machine-custom-icons-and-custom-lines/
It works.

bye

**Comment by HugoHeneault** [comment]
For future people looking for a fast solution, based on @DiegoJohan link: 

Find out the solution!

```js
L.Routing.control({
   waypoints: waypoints,
   lineOptions: {
      styles: [{color: 'white', opacity: 1, weight: 5}]
   }
}).addTo(this.map)
```

**Comment by MayurDynamo** [comment]
I am printing route on map but i need doted line so plz tell about doted style

**Comment by perliedman** [comment]
@MayurDynamo LRM uses Leaflet's standard options for styling lines. You likely want to use the [`dasharray`](http://leafletjs.com/reference-1.0.3.html#path-dasharray) option.

**Comment by MayurDynamo** [comment]
Than you a got this solution.
My problem is solved

**Comment by Ramyapriya24** [comment]
How to change the route line color in leaflet when it is already added to map

**Comment by anviloro** [comment]
you can try a dirty solution, by changing the style on the routesfound event,
on('routesfound', (e) => {
    if (e !== undefined && e.routes !== undefined && e.routes.length > 0){
      e.sourceTarget.options.lineOptions.styles[0].color = "blue";  
}
}

btw amazing control, thanks!

**Comment by BenLaKnet** [comment]
Hi,

I want to change route color when I click on Start or End marker, how is it possible ?
https://www.lamaraudiere.com/d4ua/cartographie.php

**Comment by hugohernani** [comment]
I saw you managed to change the route color, @BenLaKnet . Can you tell how you did that?

**Comment by BenLaKnet** [comment]
Hi,

I create a new issue:
https://github.com/perliedman/leaflet-routing-machine/issues/654

**Comment by ujangaripin24** [comment]
thx this help me!!!
