### ISSUE TITLE
Leaflet Routing Machine not workin

### ISSUE THREAD

**Issue by IgnacioMS22** [perliedman/leaflet-routing-machine#631]
I was using the leaflet routing machine API and now this message appears when I try to use their functions:

Access to XMLHttpRequest at 'https://router.project-osrm.org/route/v1/driving/-85.585825,10.259279;-83.033133,9.992395?overview=false&alternatives=true&steps=true&hints=;' from origin 'https://myApplication.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by perliedman** [comment]
This is the OSRM demo server responding with some error. Leaflet Routing Machine has no control over the demo server, and it's known to be a bit unstable, so nothing to do on our part.
