### ISSUE TITLE
Examples not working!

### ISSUE THREAD

**Issue by inforuta0** [perliedman/leaflet-routing-machine#65]
Hello, I've checked http://www.liedman.net/leaflet-routing-machine/styling.html several times during last week, and it worked ok. But today, none of the three examples is working... perhaps an issue with OSRM? Thank you!

**Comment by jomollin** [comment]
Hallo,
I checked OSRM. It's responding. Did they change the output format
Regards
Jo

**Comment by inforuta0** [comment]
Somebody knows if OSRM officially announced a change in its output format?

**Comment by perliedman** [comment]
Hi, thanks for reporting!

It appears the response from OSRM does no longer contain `hint_data`, causing an error in `_saveHintData`.

I'm currently travelling, so I have no time to check it out right now. Best is probably to add a check that `hint_data` actually exists before using it - it should be safe to just skip running the code in `_saveHintData` if there's no hints to process.

**Comment by jomollin** [comment]
Hi Per,
I commented out the code in _saveHintData without having success.

As an example I got these data back from OSRM:
{"route_name":["B 304","Münchener Straße"],"via_indices":[0,106],"found_alternative":false,"route_summary":{"end_point":"","start_point":"B 304","total_time":350,"total_distance":5712},"via_points":[[48.075119,11.886191],[48.075974,11.955014]],"route_instructions":[["10","B 304",3554,0,214,"3553m","E",109,1],["7","Münchener Straße",2112,62,138,"2112m","NE",23,1],["7","",22,101,3,"22m","N",356,1],["1","",24,103,1,"23m","N",356,1],["15","",0,105,0,"0m","N",0]],"route_geometry":"{uguzA}entUxJer@~AyKhA}HbIad@~EwXdBoJjA_IdIwi@lEaZrFq]rE_f@nFgr@xD}r@d@sR`CcdAbDuxAjAyY~@sNrAwNxC_U~CyTzHu`@|UgbApGkYtFm\\pDe]lDu_@rC}b@zCqp@tCaYvDse@nRcaAlJsg@nIwa@xIoc@fI_a@hFe[fHcd@pDoXtDg]tCa\\vBsYfCce@zCk~@d@a~@i@ykAQ{yAXym@dAok@rBum@zD_q@tHi_AjG{k@hJyr@vImg@vL}q@tMmq@n|@wyDbu@uaDd[auAhDiNt`@stB}KeGyIyHyGuMyEaP{D{XuTssCmJ}l@knAcjGuL}e@{Pqd@eYgj@aQgXkRgTag@ak@qUiWoEuFcFyGsVe^ejBepDiFgKsCoGuBeFwGwOqKsVeJ_WwJmYoD}IyLu`@qLah@aHi]gEaXmCkYoBcWs@iNMeC_AuYcAe[mCgz@gBa^cERsERqH\\kBO","status_message":"Found route between points","status":0}

Any suggestions?

regards

**Comment by jomollin** [comment]
ok,

i commented out this line //this._saveHintData(response, inputWaypoints);

now it woks again

**Comment by inforuta0** [comment]
Thanks jomollin, I've commented out the same line, and my application runs ok now.

**Comment by dominikveils** [comment]
Confirm bug.

Commenting this line:
//this._saveHintData(response, inputWaypoints);

solve the problem

**Comment by TheMarex** [comment]
Yes ```hint_data``` was removed. The demo server is running on the ```develop``` branch, which is the development branch, and as such the API might break at any time if we are testing stuff.
Will work on a fix ASAP.

**Comment by TheMarex** [comment]
See #66.

**Comment by perliedman** [comment]
Fixed by @TheMarex in bb6583642f2a37ce01370c1aedb24fc837ce37b2

**Comment by jomollin** [comment]
Hi all,

again not working anymore. What happened now??

**Comment by jomollin** [comment]
sorry was my mistake. Did a typing error
