### ISSUE TITLE
Changing route color when click on marker

### ISSUE THREAD

**Issue by BenLaKnet** [perliedman/leaflet-routing-machine#654]
Hi,

I want to change route color when I click on Start or End marker, how is it possible ?
https://www.lamaraudiere.com/d4ua/cartographie.php

**Comment by curtisy1** [comment]
You should be able to use the `routeLine` option on `L.Routing.Control` to customize the line appearance depending on which line is currently selected. Technically, clicking a marker should trigger a `route` event in your example since it displays the itinerary and would also redraw the routes

**Comment by BenLaKnet** [comment]
Hi @curtisy1 ,

I found this link https://stackoverflow.com/questions/53963285/routing-control-name-and-add-custom-markers and that helps me to change route line color.

Many thanks
