### ISSUE TITLE
How is it possible to calculate distance from a route ?

### ISSUE THREAD

**Issue by BenLaKnet** [perliedman/leaflet-routing-machine#660]
Hi,

I have to calculate distance from an address between route.

https://www.lamaraudiere.com/d4ua/cartographie.php

How is it possible ?

**Comment by curtisy1** [comment]
I'm not sure I understand the question. The route request already returns the total distance and distance between points as can be seen in [the example](https://www.liedman.net/leaflet-routing-machine/)

**Comment by BenLaKnet** [comment]
Hi @curtisy1 ,

I have to find distance from a point to route.

**Comment by curtisy1** [comment]
Okay, so looking at the source code from your website sample, you have a situation where you have a few waypoints and you do something with geolocation. I'm also seeing a `distanceFromAddress` function that seems to work just fine. If I run it in the console, my current position or the one I specified gets added to the route's waypoint and osrm returns the new route properly.

Or is the question unrelated to LRM and you just want the distance from point A to B in general? Then you can do 
```
L.latLng(routes[j].options.waypoints[0].lat, routes[j].options.waypoints[0].lng).distanceTo(L.latLng(document.getElementById("latitude").value, document.getElementById("longitude").value))
```

**Comment by BenLaKnet** [comment]
Hi @curtisy1 ,

Many thanks for "distanceTo", but I want to know the distance from a point to route, the minimal distance to route.

**Comment by BenLaKnet** [comment]
Hi @curtisy1 ,

I found, the points are in route.coordinates.

Many thanks for your helps.

**Comment by curtisy1** [comment]
Great to hear you solved it! I'll go ahead and close the issue. Feel free to reopen it if  you think the question is still not answered
