### ISSUE TITLE
How to select route?

### ISSUE THREAD

**Issue by 16bc** [perliedman/leaflet-routing-machine#673]
How to select route (to fire 'routeselected') by index?
this way partly working:
```
control._routeSelected({route: routes[idx]});
```
but hides altroutes on map.
```routes``` variable got by 'routesfound' event.
What is the right way?

**Comment by curtisy1** [comment]
You're on the right track!

`_routeSelected` accepts a second event argument called alternatives that updates the alternative routes.

```js
control._routeSelected({route: routes[idx], alternatives: routes.filter((r, i) => routes.indexOf(r) !== i)});
```

should work, hopefully

**Comment by 16bc** [comment]
> You're on the right track!

Thanks, i replace **i** to **idx**, and it works!
`control._routeSelected({route: routes[idx], alternatives: routes.filter((r, i) => routes.indexOf(r) !== idx)});`
