### ISSUE TITLE
set the End-Start input box text to my language

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#70]
Hi, I need to set the control in spanish, even it was translated, at the very begining appears "Start" and "End" which isn't consistent enough with the control language.
My workaround: I added 2 options to L.Routing.Plan, "source" and  "dest" which are set at the begining.
Then I modified the geocoderPlaceholder function by replacing 'Start 'with 'source' and so on.
For sure there could be a better solution, I appreciate so much any tip to improve it.
Thanks!

**Comment by TheMarex** [comment]
Oh yeah good, point. Didn't even notice they where not translated.
There is a option https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Plan.js#L34 that you could override in your case. To do this properly we would need to pass the selected language and include L.Routing.Localization.

**Comment by rossanag** [comment]
Yes, at the first option I overwrite the function. However I think a more customizable solution it would be better. Having said that, could you please explain your last sentence further?.
*"To do this properly we would need to pass the selected language and include L.Routing.Localization. "*

**Comment by TheMarex** [comment]
We pass the language as parameter to ```L.Routing.Control```, which creates a ```L.Routing.Plan``` instance, which then creates the input boxes. So, in order to localize the "Start" and "End" texts in ```L.Routing.Plan``` we need to pass the currently selected language to it as option. We could then add localizations for this strings to ```L.Routing.Localization``` and query it at the correct position in ```L.Routing.Plan```.
You can have a look at ```L.Routing.Control``` to see how the localization module is used.
It is a rather straight forward change. You should give it a try. :+1:

**Comment by rossanag** [comment]
Thanks for your detailed answer. Actualy I passed the language parameter set to the 'sp' value, however it doesn't change the control language (itinerary still in english).
    
    var controlR = L.Routing.control({
        waypoints: [
            L.latLng(-34.905753, -56.180346),
            L.latLng(-34.9098918 ,-56.1657234)
        ],    
        geocoder: L.Control.Geocoder.nominatim(),
        language: 'sp',
       routeWhileDragging: true
    }).addTo(map);
    
I'll give a try as you suggested, very likely I missed something.

**Comment by rossanag** [comment]
Sorry for this silly question, but I can't set the language option, any example?
Thanks!

**Comment by perliedman** [comment]
@rossanag: does your note in the last comment mean that this issue can be closed?

I'm closing for now, just tell me if there's still an issue.

**Comment by rossanag** [comment]
Yes, it can since I will digg into it later.

2015-01-14 17:19 GMT-02:00 Per Liedman <notifications@github.com>:

**Comment by tanviralambd** [comment]
I am trying to show route in Arabic, But it is not working. It is working fine with English. 
Here is my code, I just changed lat, long and Language from example provided by developer:
============================================================
var control = L.Routing.control(L.extend(window.lrmConfig, {
	waypoints: [
		L.latLng(24.750114, 46.686395),
		L.latLng(24.683354, 46.697532)
	],
    language: 'ar', /*  'en' 'ar' */
	geocoder: L.Control.Geocoder.nominatim(),
    routeWhileDragging: true,
    reverseWaypoints: true,
    showAlternatives: true,
    altLineOptions: {
        styles: [
            {color: 'black', opacity: 0.15, weight: 9},
            {color: 'white', opacity: 0.8, weight: 6},
            {color: 'blue', opacity: 0.5, weight: 2}
        ]
    }
})).addTo(map);
