### ISSUE TITLE
How to use with angular?

### ISSUE THREAD

**Issue by rozzwalla** [perliedman/leaflet-routing-machine#72]
Already has the library installed but whenever I call L.Routing I am getting an error that there is no such function. Do you have a simple example on how I can use this with Angular?

**Comment by perliedman** [comment]
There's nothing special about using Leaflet Routing Machine from Angular. You have to make the same calls.

There control's name is `L.Routing.Control`, not just `L.Routing` - the latter is just the plugin's namespace.

This example should is a good starting point, if you haven't already found it: http://www.liedman.net/leaflet-routing-machine/
