### ISSUE TITLE
Where's the place in the code to catch the control input text?

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#73]
Hi everyone! I meant the text of the input boxes in **L.Routing.Control**. I need to apply regular expressions to the values entered before doing the search that throws the suggested streets. I was tinkering into the code without luck yet.
Thanks a lot!

**Comment by rossanag** [comment]
PD: I found it. I check the text  it in the _complete method of the L.Routing.Autocomplete class.
If there's no any suggestions (always are welcome), the thread can be closed.

**Comment by perliedman** [comment]
I think the best way to do this is to implement your own `IGeocoder`, that wraps the implementation you're already using. This way, you can implement any regex or other stuff you might need, without having to change the LRM code (so that you don't have to maintain your own version).

**Comment by rossanag** [comment]
Thanks, I already did it so I keep safe the original plugin
