### ISSUE TITLE
show variable and show() method

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#74]
Hi, what's the purpose of the show variable? As far as I saw it isn't changed along the code. I thought it was changed within the show() and hide() methods.

Secondly, I had an issue with the following code:

     if (routeControl.show)
    {
        routeControl.hide();
        routeControl.show = false;
    }
    else
    {
       routControl.show();
       routeControl.show = true;
    }    
    
However it throws an error *Uncaught TypeError: boolean is not a function'*. I am a newbie with JS but it seems there's a colission between the name of the funcion and the variable name. As if it gets overwritten or so. I did a workaround by renaming the 'show' variable to 'showControl' and it works.
(Probably is far better to set the variable value within the show() and hide() methods) 
Suggestions? Thanks!

**Comment by perliedman** [comment]
When you do

```
routeControl.show = true;
```

you're actually overwriting the `show()` function with a boolean. Next time `show()` is called, you're trying to call a boolean, which results in the error message you're referring to.

`show` isn't a variable, it's an option given to the control, that is why it's never assigned, it's just used in `onAdd` to determine if the control should be visible when it's added to the map.

The option is just used to control the initial state of the control. An HTML class (`leaflet-routing-container-hide`) is used to actually hide or show it once it has been added to the map.

**Comment by rossanag** [comment]
Oh, my bad, thanks to clarify this issue. As you told me in another comment I am doing a wrapper over LRM, in order to keep the original one - which I need to understand it better- and to have my own adaptation too.
