### ISSUE TITLE
 L.Icon.Label not working with this LRM example

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#75]
Hi I want to put a label using Icon.Label plugin, but it doesn't display it. I don't know what I'm doing  wrong here. It works perfectly with the example. Thanks for any tip!

    routeControl = L.Routing.control({     
        plan: L.Routing.plan([], {          
        
            waypointIcon: function(i) {                            
                return new L.Icon.Label.Default({ labelText: String.fromCharCode(65 + i) });                                
            },
            geocoder: L.Control.Geocoder.nominatim({
                geocodingQueryParams: { countrycodes: 'ar'}                
            }),         
        }),
    lineOptions: {    
        styles: 
            [
                {color: 'black', opacity: 0.15, weight: 9}, //sombra
                {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                {color: 'red', opacity: 1, weight: 4}] // Centro
       }, 
  
    summaryTemplate:  '<h2>{name}</h2><h3>Distancia: {distance}</h3>',   
   
    language: 'sp',   
    routeWhileDragging: true
    }).addTo(map);

**Comment by perliedman** [comment]
Hi,
in master, `waypointIcon` has been replaced by the more general `createMarker` option. This way, you have full control over how the marker is created, including setting its icon.

I should of course update the example to reflect this. Thanks for reporting.

**Comment by rossanag** [comment]
Thanks! I was going to post that I realized about the change.
