### ISSUE TITLE
infobox result wrong position if the map is not full screen

### ISSUE THREAD

**Issue by 2803media** [perliedman/leaflet-routing-machine#81]
Do you know how to keep the position under the input text box for map which are not full screen? See the screenshot below

Thanks

![capture d ecran 2015-01-29 a 17 23 47](https://cloud.githubusercontent.com/assets/642545/5961278/c3f6a702-a7db-11e4-981b-4b08fcb072b8.png)

**Comment by perliedman** [comment]
Interesting, that's definitely not what's intended to happen. Will look in to it.

**Comment by perliedman** [comment]
I've tried to create a fiddle that reproduces this issue, but I can't get it to work so far.

Could you check this fiddle and see if you can modify it to reproduce the problem you're seeing?

http://jsfiddle.net/3mxd6bvw/

**Comment by 2803media** [comment]
Thanks for the jsfiddle

here is mine, I think the problem is related to #map {position: relative;} 

http://jsfiddle.net/3mxd6bvw/2/

**Comment by perliedman** [comment]
Great, thanks. I'll try to look into it.

The logic to place the results container is pretty simple, and should probably take some other factor into account. Here are the lines involved: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Autocomplete.js#L42-48

**Comment by perliedman** [comment]
Thanks for notifying me of this! The positioning didn't take the scroll position into account, which I never realized since I've just used fullscreen maps.

**Comment by 2803media** [comment]
You're welcome!
