### ISSUE TITLE
Missing L.Routing.Plan._layerAdd?

### ISSUE THREAD

**Issue by robballou** [perliedman/leaflet-routing-machine#84]
With leaflet `0.8-dev`, adding a layer calls the `_layerAdd()` method of the layer being added, which doesn't exist for L.Routing.Plan. I have added an empty `_layerAdd()` method but wasn't sure if that necessitated a pull request.

* This method is called in [`L.Map.addLayer`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L65)
* Looks like [`L.Layer` has a `_layerAdd` method](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L28)

Without this method, Leaflet will encounter an error when the layer is added. Let me know if any more info would be helpful.

**Comment by perliedman** [comment]
Check out the `leaflet-master` branch, which should be compatible with Leaflet's master branch: https://github.com/perliedman/leaflet-routing-machine/tree/leaflet-master

It should contain the changes you need!

I will merge it into LRM's master once Leaflet 1.0 is released.
