### ISSUE TITLE
Bug in L.Routing.OSRM

### ISSUE THREAD

**Issue by cmberlin** [perliedman/leaflet-routing-machine#88]
Line 157

if (waypoints[i].options.allowUTurn)

Should be 

if (options.allowUTurn)

waypoint has no options right?

**Comment by perliedman** [comment]
Actully it has options!

https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Waypoint.js

I think the OSRM `allowUTurn` flag is the only thing it's actually used for.

**Comment by cmberlin** [comment]
Used an old fashioned way to create waypoints.
My mistake sorry for that.

**Comment by perliedman** [comment]
Yes, that is also fine. Or it should be fine. Although not documented in the API (yet), methods dealing with waypoints should accept anything that looks like a waypoint. This means it should be fine as long as you pass something that at least has a `latLng` property, and optionally `name` and `options`.

The class `L.Routing.Waypoint` should be for convenience.

**Comment by cmberlin** [comment]
I was passing an array containing objects with a latLng property but 
that leads me to an error. Now i am using the L.Routing.Waypoints class 
and it works.

Anyway thanks for your piece of work.

Cheers Carsten


Am 25.02.2015 um 16:13 schrieb Per Liedman:
>
> Yes, that is also fine. Or it should be fine. Although not documented 
> in the API (yet), methods dealing with waypoints should accept 
> anything that looks like a waypoint. This means it should be fine as 
> long as you pass something that at least has a |latLng| property, and 
> optionally |name| and |options|.
>
> The class |L.Routing.Waypoint| should be for convenience.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perliedman/leaflet-routing-machine/issues/88#issuecomment-75977008>.
>

-- 


--


Mit freundlichen Gruessen/ Kind regards

Carsten Mueller
Technical Partner
--
Extrajetzt® Interactive GmbH
Zehdenicker Str. 8

D-10119 Berlin

fon +49 (0) 30 / 27 58 20 80
fax +49 (0) 30 / 27 58 20 84

cm@extrajetzt.de
http://www.extrajetzt.de

Geschaeftsfuehrer: Carsten Mueller, David R. Rowald, Kaspar Truestedt
AG Charlottenburg HRA 107877 B

**Comment by perliedman** [comment]
Ok, then this is actually a valid bug! Thanks for taking the time to report.

Also, great to hear that you find LRM useful!
