### ISSUE TITLE
Browserify require problem.

### ISSUE THREAD

**Issue by sharkinsspatial** [perliedman/leaflet-routing-machine#89]
I'm unable to require leaflet-routing-machine with browserify.  Running a grunt browserify task gives the following error
````
Error: ENOTDIR, stat '/project/node_modules/leaflet-routing-machine/src/L.Routing.Control.js/node_modules/browserify-shim'
````
My Gruntfile.js is
````javascript
module.exports = function(grunt) {
    grunt.initConfig({
        watch: {
            react: {
                files: ['src/*.jsx','src/**/*.jsx','src/**/*.js'],
                tasks: ['browserify']
            }
        },
        browserify: {
            dist: {
                options: {
                    transform: [require('grunt-react').browserify]
                },
                files: {
                    'build/main.js':['src/*.jsx','src/**/*.jsx','src/**/*.js']
                }
            }
        }
    });
    grunt.loadNpmTasks('grunt-browserify');     
    grunt.loadNpmTasks('grunt-contrib-watch');
};
````
And the require block in my code is
````javascript
var React = require('react');
var L = require('leaflet');
require('leaflet-routing-machine');
````
This seems like it could be related to the recent browserify issue substack/node-browserify#1133

**Comment by perliedman** [comment]
Hm, I think this is related to the fact that the current setup tries to serve two purposes: build a standalone version of LRM using Browserify, but also to be able to include the module in a browserify-based app, like you do.

The quick workaround is to add `browserify-shim` to your `devDependencies`, but I'll try to fix this in a better way.

**Comment by sharkinsspatial** [comment]
Thanks for the assistance.  Testing was sidelined yesterday as OSRM was down, but all looks good now.

**Comment by perliedman** [comment]
Nice. I'll keep this issue open though, so that I remember to actually do something about it at some point!
