### ISSUE TITLE
Problems to change the .leaflet-routing-container position

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-routing-machine#96]
Hi!, I need to change/cutomize its position to make it fitable within a menu layaout. I have a menu icon and I want the  .leaflet-routing-container position appears below it.
My first attemp was to do:

    leaflet-routing-container {
       width: 320px;
       background-color: white;
      padding-top: 4px; 
      top: 40px;   /*added by me */
       
      transition: margin-right 0.2s ease;
    }

It seems the top value is increased every time the control is called, thus the control box get closer and closer to the bottom in each call. Any ideas on how I could it? Thanks!

**Comment by perliedman** [comment]
What do you mean by "every time the control is called"? What are you doing when you call the control?

It sounds like you might want to use the `show` and `hide` methods of the control (see http://www.liedman.net/leaflet-routing-machine/api/#l-routing-itinerary), but that shouldn't move the control.

**Comment by rossanag** [comment]
Sorry for my poor explanation. I meant every time the procedure which `show/hide` the control is called.
I need the control a few pixes under where is set by default, not at the top because there's a menu icon. 
I did what I wrote in my first post (set a value to the top property), but for an unknown reason the control scrolls downs every time a `show` is called.
I hope the captures below help to clarify. Thanks!



     
![control1](https://cloud.githubusercontent.com/assets/1948071/6910677/baea930a-d72c-11e4-96ed-b30ba3c34c47.png)

![control1](https://cloud.githubusercontent.com/assets/1948071/6910688/d5b1b010-d72c-11e4-86f2-10282ef8fe00.png)

**Comment by rossanag** [comment]
Problem solved. It was removeControl that was missed. Setting the top property changed the default position. I decided to add/remove the control on demand since there are a lot of options in the menu. I don't want to have rendered elements if they're no longer needed. I don't know if it is a good strategy, I come from C++ so..my js and css backround is pretty recent.
I close the thread but I am open to your suggestions. Thanks a lot.

**Comment by perliedman** [comment]
I wouldn't worry too much about performance, modern browsers handle hidden elements very well, in my experience.

By just hiding, you might also have the advantage that the control's state isn't lost (inputs contain the same values as when they were hidden, etc.). It depends on how your app works.

Anyway, just to be clear: you didn't encounter any issue in Leaflet Routing Machine when removing the control properly? I probably haven't tested that as much as I should, given that most routing apps just have the control added from the start and never remove it.

**Comment by rossanag** [comment]
Thanks for your suggestion, maybe I'll give a try with the hide/show option. 
I haven't had any issue when removing and adding the control on demand yet. The only modifications I've made was in the plugin .css file, I added top = n to give space to the icon menu as you see in the images.

**Comment by perliedman** [comment]
Notice that you can add such additional rules in your own CSS, if you load it after the plugin's CSS. That way, it will be easier to upgrade LRM without overwriting your CSS additions.

**Comment by rossanag** [comment]
Yes, it's what I am doing actually.  The examples I put above where rather written in a hard coded way to clarify my issues better.

**Comment by jithinag91** [comment]
the controls move when new routeControl= L.Routing.control({});<---method is called
or like this
L.Routing.control({
       waypoints: [
         leaflet.latLng(57.74, 11.94),
       leaflet.latLng(57.6792, 11.949)
      ]
    }).addTo(this.map);
just use setWaypoints () method to avoid movement i think 
routeControl.setWaypoints([
            L.latLng(this.myLatLng),
            L.latLng(hospitalLatLng)
          ]).addTo(this.map);
