### ISSUE TITLE
question about routing

### ISSUE THREAD

**Issue by MannusEtten** [perliedman/leaflet-routing-machine#98]
I really like the routing-tool :-)

I am wondering if I can do routing with only putting two pins on the map and no user interface which tells me how to drive from A to B.

can I also restrict the routing to highways or to a certain kind of road?

**Comment by perliedman** [comment]
Good to hear that you like Leaflet Routing Machine!

If you look at the tutorials for basics, it shows you how to set up routing between two locations without user interaction: http://www.liedman.net/leaflet-routing-machine/tutorials/basic-usage/

If you also want to prevent the user from altering the route, you can also add the options: `draggableWaypoints: false` and `addWaypoints: false`.

The actual routing calculation is, by default, done by OSRM. To control which roads it uses, you need to setup your own OSRM server. This makes it possible to control which ways are used, alter speed and so on. It's fairly easy to set up.

**Comment by MannusEtten** [comment]
thanks for your reply. I use the itenary.Hide()-method and now i see in the upper right corner of my screen a white box. Is this intentionally or can I also remove this white box?
![aaa](https://cloud.githubusercontent.com/assets/3999790/7023649/14eb4b82-dd37-11e4-92e6-d6e197d75cb4.png)

**Comment by perliedman** [comment]
It looks like you're missing the routing icon, for some reason - it should appear in the white box.

As implemented now, `hide` is really "minimize", and the control can be opened again by clicking the "white box".

You can override this behaviour, hiding it completely, by adding this style rule to your CSS:

```css
.leaflet-left .leaflet-routing-container.leaflet-routing-container-hide {
   display: none;
}
```

**Comment by ahmad-muzakkir** [comment]
is there any ways to hide the route and waypoints while i collapse the container ??
